package br.com.av1.prova10;

public class Questao4 {
	public static void main(String[] args) {
		int a = 8;
		int b = 8;
		int c = 4;
		int d = 9;
		int e = 10;
		int x = 2;
		int y = 1;
		int z = 9;

		String resultado1 = "";
		resultado1 = resultado1 + ((y / b) + (e / z) + (a * d) + (b / d));
		resultado1 = resultado1 + ((c / x) + (e * x) + (d + y));
		resultado1 = resultado1 + ((b - e) + (y * b) + (z + x) + (b + b));
		String resultado2 = "";
		resultado2 = resultado2 + ((c / x) + (z / b) + (b / c) + (y / e));
		resultado2 = resultado2 + ((d - b) + (d / e) + (c / z) + (e + y));
		resultado2 = resultado2 + ((e - c) + (x - a) + (b - c) + (y - x) + (b - c));
		resultado2 = resultado2 + ((y / b) + (z - a) + (d / e));
		resultado2 = resultado2 + ((x - c) + (z - a) + (e * d));
		String resultado3 = "";
		resultado3 = resultado3 + ((b * z) + (e * c) + (x / x) + (d + y) + (x / a));
		resultado3 = resultado3 + ((a - e) + (b / z) + (z / z) + (c * a) + (x + e));
		resultado3 = resultado3 + ((x * x) + (d * c) + (b - z));
		resultado3 = resultado3 + ((z * a) + (x + z) + (c / a));
		resultado3 = resultado3 + ((a - d) + (z / z) + (x * e));
		String resultado4 = "";
		resultado4 = resultado4 + ((d * y) + (c * z) + (y / d) + (d * c) + (b + x));
		resultado4 = resultado4 + ((z - z) + (b - c) + (z / d) + (y / e) + (e - y));
		resultado4 = resultado4 + ((x * y) + (c - y) + (z - y) + (d / c));
		resultado4 = resultado4 + ((a * d) + (c * y) + (e - z) + (z + z) + (y + b));
		String resultado5 = "";
		resultado5 = resultado5 + ((b * c) + (e * b) + (z - a) + (b / d));
		resultado5 = resultado5 + ((d * z) + (c * b) + (c / b));
		resultado5 = resultado5 + ((b * x) + (e * z) + (z * a));
		resultado5 = resultado5 + ((d + x) + (y - z) + (d - d));
		resultado5 = resultado5 + ((b + c) + (x - z) + (e - z) + (x * e) + (z - x));
		String resultado6 = "";
		resultado6 = resultado6 + ((b - c) + (b / d) + (e + x) + (c + y));
		resultado6 = resultado6 + ((e + y) + (x + y) + (a + c) + (c / e));
		resultado6 = resultado6 + ((a - a) + (y / b) + (b - z));
		String resultado7 = "";
		resultado7 = resultado7 + ((y - z) + (x + y) + (c + d) + (y - d) + (z / x));
		resultado7 = resultado7 + ((b + e) + (c - a) + (z / e) + (a * e));
		resultado7 = resultado7 + ((e * z) + (e - b) + (a / y) + (e + a));
		resultado7 = resultado7 + ((d + y) + (x / d) + (c + d));
		resultado7 = resultado7 + ((b / a) + (x - c) + (z / x) + (a * b) + (b + z));
		String resultado8 = "";
		resultado8 = resultado8 + ((a * c) + (y - z) + (a * e));
		resultado8 = resultado8 + ((e * a) + (c + e) + (a * e));
		resultado8 = resultado8 + ((z + d) + (z - x) + (z * z) + (b + c) + (b * a));
		String resultado9 = "";
		resultado9 = resultado9 + ((a * d) + (b + b) + (e / c));
		resultado9 = resultado9 + ((c - z) + (b + y) + (e + c) + (y * b) + (y - b));
		resultado9 = resultado9 + ((b + e) + (c - x) + (c + b) + (a * e) + (y * c));
		String resultado10 = "";
		resultado10 = resultado10 + ((b * b) + (c / b) + (x / e) + (a / a) + (b + d));
		resultado10 = resultado10 + ((c + x) + (b / z) + (x / a) + (b - b));
		resultado10 = resultado10 + ((e - x) + (y / b) + (d - a) + (x * z));
		resultado10 = resultado10 + ((y * y) + (z - z) + (a / a) + (e / b));
		String resultado11 = "";
		resultado11 = resultado11 + ((e / x) + (y / d) + (c + d) + (y + d));
		resultado11 = resultado11 + ((b * a) + (e - e) + (x - a) + (a / e));
		resultado11 = resultado11 + ((e + a) + (c / d) + (c + y));
		String resultado12 = "";
		resultado12 = resultado12 + ((a + d) + (y + z) + (z - a) + (e - b) + (z * d));
		resultado12 = resultado12 + ((x - z) + (e + c) + (y / d));
		resultado12 = resultado12 + ((y * e) + (d * a) + (z + b) + (z + x) + (b - z));
		resultado12 = resultado12 + ((y - x) + (z + d) + (z * a) + (c / b) + (c * e));
		resultado12 = resultado12 + ((c * x) + (e - e) + (d / b) + (z - y));
		String resultado13 = "";
		resultado13 = resultado13 + ((c - c) + (d - z) + (e - z) + (a / z) + (b - a));
		resultado13 = resultado13 + ((b - e) + (a + c) + (y / e) + (y / a));
		resultado13 = resultado13 + ((y * a) + (e * z) + (z + a) + (e + d));
		resultado13 = resultado13 + ((z * b) + (a - z) + (z / b) + (e * b));
		String resultado14 = "";
		resultado14 = resultado14 + ((z * z) + (c * z) + (b * e) + (z / a) + (b + c));
		resultado14 = resultado14 + ((y * z) + (e / b) + (b / a) + (z / e));
		resultado14 = resultado14 + ((x / y) + (b * y) + (y * y));
		resultado14 = resultado14 + ((a + b) + (y * x) + (x - x) + (b / z));
		resultado14 = resultado14 + ((x * c) + (x + z) + (c * e) + (d - a) + (x * d));
		String resultado15 = "";
		resultado15 = resultado15 + ((z + y) + (e - b) + (y * d));
		resultado15 = resultado15 + ((y - b) + (a / y) + (y / b) + (x * z));
		resultado15 = resultado15 + ((x + a) + (c - x) + (z + a));
		resultado15 = resultado15 + ((c * d) + (y / y) + (a * b) + (b * b));
		resultado15 = resultado15 + ((d / y) + (b - a) + (z * z) + (d + x));
		String resultado16 = "";
		resultado16 = resultado16 + ((b / d) + (b * x) + (e / a) + (d + d));
		resultado16 = resultado16 + ((x * a) + (b + e) + (e + c) + (a - e));
		resultado16 = resultado16 + ((a * e) + (y + d) + (a * b));
		String resultado17 = "";
		resultado17 = resultado17 + ((x / y) + (d - y) + (e * z) + (z / d) + (a * y));
		resultado17 = resultado17 + ((y + d) + (z - b) + (x + z) + (d / x) + (b - d));
		resultado17 = resultado17 + ((e / x) + (e / x) + (e / z));
		String resultado18 = "";
		resultado18 = resultado18 + ((b / x) + (d / y) + (d / e) + (x / a));
		resultado18 = resultado18 + ((x * e) + (d / c) + (a * b) + (a * b) + (d / b));
		resultado18 = resultado18 + ((a * x) + (b - e) + (d / z) + (a + e));
		resultado18 = resultado18 + ((e + c) + (x / d) + (d - d) + (c - e) + (b * z));
		String resultado19 = "";
		resultado19 = resultado19 + ((e - c) + (y * d) + (a - c));
		resultado19 = resultado19 + ((a - x) + (a / c) + (b - a) + (d + a));
		resultado19 = resultado19 + ((c * e) + (a * e) + (z - a));
		resultado19 = resultado19 + ((c + c) + (b - e) + (c - b));
		String resultado20 = "";
		resultado20 = resultado20 + ((x * b) + (x - b) + (b + x));
		resultado20 = resultado20 + ((a + z) + (a / z) + (e / b) + (d / a) + (e / c));
		resultado20 = resultado20 + ((x / e) + (y - e) + (a + d));
		resultado20 = resultado20 + ((e / e) + (z - z) + (b - y) + (c + a) + (c * c));
		String resultado21 = "";
		resultado21 = resultado21 + ((d - e) + (a - b) + (d / z) + (z + c) + (c - c));
		resultado21 = resultado21 + ((d + c) + (a * d) + (z * a) + (y / z) + (x - d));
		resultado21 = resultado21 + ((d - d) + (e / d) + (a / b));
		String resultado22 = "";
		resultado22 = resultado22 + ((e - x) + (y + c) + (c / x) + (c - x));
		resultado22 = resultado22 + ((e * e) + (z / d) + (d - a));
		resultado22 = resultado22 + ((x + a) + (z - x) + (e + b));
		String resultado23 = "";
		resultado23 = resultado23 + ((x / d) + (e / b) + (d + d) + (x - x));
		resultado23 = resultado23 + ((c / e) + (y / e) + (z + x));
		resultado23 = resultado23 + ((x - z) + (y / z) + (z * e));
		resultado23 = resultado23 + ((z - a) + (c / d) + (x * d) + (y / x) + (z + d));
		resultado23 = resultado23 + ((c * d) + (z * z) + (a / c) + (y * d) + (a + x));
		String resultado24 = "";
		resultado24 = resultado24 + ((z * a) + (c - y) + (e * c) + (c + a) + (a + x));
		resultado24 = resultado24 + ((b / d) + (a * z) + (c - a) + (b * y));
		resultado24 = resultado24 + ((c / e) + (z - a) + (b + b));
		resultado24 = resultado24 + ((a - d) + (a / b) + (e - a));
		resultado24 = resultado24 + ((a / a) + (b - d) + (b + d) + (b * c));
		String resultado25 = "";
		resultado25 = resultado25 + ((y - e) + (y - a) + (c / b) + (e - d) + (z / z));
		resultado25 = resultado25 + ((e + y) + (e / e) + (b - z) + (c + z));
		resultado25 = resultado25 + ((e / a) + (x - z) + (a / d) + (x * a) + (e * c));
		resultado25 = resultado25 + ((x / a) + (y / d) + (d - x) + (c * x) + (x * x));
		resultado25 = resultado25 + ((e - a) + (x - e) + (e - e) + (x / y) + (c / e));
		String resultado26 = "";
		resultado26 = resultado26 + ((c - a) + (c - x) + (z * d) + (d - y) + (c + d));
		resultado26 = resultado26 + ((a + e) + (x / e) + (c * b));
		resultado26 = resultado26 + ((b / a) + (e - y) + (b / b) + (z * x) + (y + e));
		resultado26 = resultado26 + ((c / c) + (z * a) + (y + c) + (y + y));
		String resultado27 = "";
		resultado27 = resultado27 + ((d - e) + (b - a) + (d * d));
		resultado27 = resultado27 + ((d + y) + (a + a) + (y - x));
		resultado27 = resultado27 + ((x / a) + (e * z) + (b * d) + (d / a));
		resultado27 = resultado27 + ((y * e) + (c * a) + (e + b) + (z / a));
		String resultado28 = "";
		resultado28 = resultado28 + ((y - d) + (y + b) + (d / a) + (y - d) + (y * x));
		resultado28 = resultado28 + ((y * a) + (z - x) + (y * c) + (b - y) + (d - b));
		resultado28 = resultado28 + ((a * x) + (e - d) + (z + x) + (e + y));
		resultado28 = resultado28 + ((e * e) + (x / c) + (x - c) + (e * z) + (y + x));
		String resultado29 = "";
		resultado29 = resultado29 + ((e + c) + (y + y) + (c * d) + (y + d) + (c * e));
		resultado29 = resultado29 + ((d - a) + (b * d) + (a - y));
		resultado29 = resultado29 + ((a / b) + (z + y) + (d / y) + (d - z));
		String resultado30 = "";
		resultado30 = resultado30 + ((e / c) + (e * z) + (y * a) + (z * d) + (d * a));
		resultado30 = resultado30 + ((x / y) + (y / y) + (d - a));
		resultado30 = resultado30 + ((b / x) + (e - x) + (x + c) + (z + y));
		String resultado31 = "";
		resultado31 = resultado31 + ((y - a) + (c + z) + (z - c) + (x * b));
		resultado31 = resultado31 + ((y - e) + (e * a) + (y - z) + (b + a));
		resultado31 = resultado31 + ((d - b) + (d - y) + (b - y) + (x / y));
		resultado31 = resultado31 + ((e / e) + (e + b) + (c * z) + (y - a) + (b + y));
		resultado31 = resultado31 + ((z + b) + (z + d) + (e * b) + (b / y) + (y - z));
		String resultado32 = "";
		resultado32 = resultado32 + ((c * z) + (y / b) + (d + x) + (x + z));
		resultado32 = resultado32 + ((d * b) + (y * e) + (x + c) + (z * a) + (x / x));
		resultado32 = resultado32 + ((d / d) + (x - b) + (d - c) + (z / d) + (e * y));
		resultado32 = resultado32 + ((d - e) + (d + z) + (y * a) + (e / d) + (a / d));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}