package br.com.simulado1;

public class Questao17 {
	public static void main(String[] args) {
		StringBuilder sb = new StringBuilder();
		sb.append("17. Dado o trecho de código abaixo, liste a saída exibida no console.\n"
				+ "public class PegadinhaJava {\n"
				+ "	public static void main(String[] args) {\n"
				+ "    	int a;\n"
				+ "    	int b;\n"
				+ "    	int c;\n"
				+ "    	int d;\n"
				+ "    	int e;\n"
				+ "\n"
				+ "    	a = 2;\n"
				+ "    	b = 3;\n"
				+ "    	c = 5;\n"
				+ "    	d = 7;\n"
				+ "    	e = 10;\n"
				+ "\n"
				+ "    	String resultado1;\n"
				+ "    	resultado1 = a + b + \"\";\n"
				+ "    	resultado1 = resultado1 + (c - d);\n"
				+ "    	resultado1 = resultado1 + d;\n"
				+ "\n"
				+ "    	String resultado2;\n"
				+ "    	resultado2 = \"\";\n"
				+ "    	resultado2 = resultado2 + (a * b);\n"
				+ "    	resultado2 = resultado2 + c;\n"
				+ "    	resultado2 = resultado2 + (d / e);\n"
				+ "\n"
				+ "    	String resultado3;\n"
				+ "    	resultado3 = (a + b) + \"\";\n"
				+ "    	resultado3 = resultado3 + (c + d - e);\n"
				+ "    	resultado3 = resultado3 + (b * d);\n"
				+ "\n"
				+ "    	a = a * b;\n"
				+ "    	b = b - c;\n"
				+ "    	c = c + d;\n"
				+ "    	d = d + 2;\n"
				+ "    	e = e / 2;\n"
				+ "\n"
				+ "    	String resultado4;\n"
				+ "    	resultado4 = \"\";\n"
				+ "    	resultado4 = resultado4 + a;\n"
				+ "    	resultado4 = resultado4 + b;\n"
				+ "    	resultado4 = resultado4 + c;\n"
				+ "    	resultado4 = resultado4 + d;\n"
				+ "    	resultado4 = resultado4 + e;\n"
				+ "\n"
				+ "    	String resultado5;\n"
				+ "    	resultado5 = \"Total: \";\n"
				+ "    	resultado5 = resultado5 + (a + b);\n"
				+ "    	resultado5 = resultado5 + c;\n"
				+ "    	resultado5 = resultado5 + (d * e);\n"
				+ "\n"
				+ "    	String resultado6;\n"
				+ "    	resultado6 = \"Final: \";\n"
				+ "    	resultado6 = resultado6 + (a - b);\n"
				+ "    	resultado6 = resultado6 + (b * c);\n"
				+ "    	resultado6 = resultado6 + (d + e);\n"
				+ "\n"
				+ "    	int x;\n"
				+ "    	int y;\n"
				+ "    	int z;\n"
				+ "\n"
				+ "    	x = 8;\n"
				+ "    	y = 4;\n"
				+ "    	z = 12;\n"
				+ "\n"
				+ "    	x = x + y * 2;\n"
				+ "    	y = y - z / 3;\n"
				+ "    	z = z - x;\n"
				+ "\n"
				+ "    	String resultado7;\n"
				+ "    	resultado7 = \"\";\n"
				+ "    	resultado7 = resultado7 + x;\n"
				+ "    	resultado7 = resultado7 + y;\n"
				+ "    	resultado7 = resultado7 + z;\n"
				+ "\n"
				+ "    	String resultado8;\n"
				+ "    	resultado8 = \"X: \";\n"
				+ "    	resultado8 = resultado8 + x;\n"
				+ "    	resultado8 = resultado8 + \", Y: \";\n"
				+ "    	resultado8 = resultado8 + y;\n"
				+ "    	resultado8 = resultado8 + \", Z: \";\n"
				+ "    	resultado8 = resultado8 + z;\n"
				+ "\n"
				+ "    	String resultado9;\n"
				+ "    	resultado9 = \"Soma: \";\n"
				+ "    	resultado9 = resultado9 + (x + y);\n"
				+ "    	resultado9 = resultado9 + (y * z);\n"
				+ "    	resultado9 = resultado9 + (x - z);\n"
				+ "\n"
				+ "    	double valor1;\n"
				+ "    	double valor2;\n"
				+ "    	double soma;\n"
				+ "    	double diferenca;\n"
				+ "    	double produto;\n"
				+ "\n"
				+ "    	valor1 = 6.5;\n"
				+ "    	valor2 = 3.5;\n"
				+ "\n"
				+ "    	soma = valor1 + valor2;\n"
				+ "    	diferenca = valor1 - valor2;\n"
				+ "    	produto = valor1 * valor2;\n"
				+ "\n"
				+ "    	String resultado10;\n"
				+ "    	resultado10 = \"\";\n"
				+ "    	resultado10 = resultado10 + soma;\n"
				+ "\n"
				+ "    	String resultado11;\n"
				+ "    	resultado11 = soma + \"\";\n"
				+ "\n"
				+ "    	String resultado12;\n"
				+ "    	resultado12 = \"\";\n"
				+ "    	resultado12 = resultado12 + valor1;\n"
				+ "    	resultado12 = resultado12 + valor2;\n"
				+ "\n"
				+ "    	String resultado13;\n"
				+ "    	resultado13 = \"Operações: \";\n"
				+ "    	resultado13 = resultado13 + \"Soma = \";\n"
				+ "    	resultado13 = resultado13 + soma;\n"
				+ "    	resultado13 = resultado13 + \", Diferença = \";\n"
				+ "    	resultado13 = resultado13 + diferenca;\n"
				+ "    	resultado13 = resultado13 + \", Produto = \";\n"
				+ "    	resultado13 = resultado13 + produto;\n"
				+ "\n"
				+ "    	System.out.println(\"Resultado 1: \" + resultado1);\n"
				+ "    	System.out.println(\"Resultado 2: \" + resultado2);\n"
				+ "    	System.out.println(\"Resultado 3: \" + resultado3);\n"
				+ "    	System.out.println(\"Resultado 4: \" + resultado4);\n"
				+ "    	System.out.println(\"Resultado 5: \" + resultado5);\n"
				+ "    	System.out.println(\"Resultado 6: \" + resultado6);\n"
				+ "    	System.out.println(\"Resultado 7: \" + resultado7);\n"
				+ "    	System.out.println(\"Resultado 8: \" + resultado8);\n"
				+ "    	System.out.println(\"Resultado 9: \" + resultado9);\n"
				+ "    	System.out.println(\"Resultado 10: \" + resultado10);\n"
				+ "    	System.out.println(\"Resultado 11: \" + resultado11);\n"
				+ "    	System.out.println(\"Resultado 12: \" + resultado12);\n"
				+ "    	System.out.println(\"Resultado 13: \" + resultado13);\n"
				+ "	}\n"
				+ "}\n"
				+ "");

		System.out.println(sb.toString());


		System.err.println("Listagem do que vai aparecer no console: ");
		
		PegadinhaJava.corrigePegadinha();
	}
}
