package br.com.av1.prova31;

public class Questao4 {
	public static void main(String[] args) {
		int a = 5;
		int b = 10;
		int c = 4;
		int d = 7;
		int e = 5;
		int x = 2;
		int y = 3;
		int z = 1;

		String resultado1 = "";
		resultado1 = resultado1 + ((z / b) + (x - e) + (c * c) + (e + z));
		resultado1 = resultado1 + ((x * x) + (b * e) + (c * e) + (z / x) + (x * d));
		resultado1 = resultado1 + ((x - x) + (b * x) + (e * b) + (z - c));
		String resultado2 = "";
		resultado2 = resultado2 + ((z + d) + (e * z) + (c + b) + (b - c));
		resultado2 = resultado2 + ((a + c) + (c + y) + (z + d) + (d * c) + (a - d));
		resultado2 = resultado2 + ((d / x) + (d - y) + (b - y) + (e * z));
		resultado2 = resultado2 + ((e * e) + (e + d) + (z / b) + (c * a));
		String resultado3 = "";
		resultado3 = resultado3 + ((e - x) + (a / e) + (x + c) + (c + x) + (d + b));
		resultado3 = resultado3 + ((e * e) + (b - d) + (y * e) + (x / a));
		resultado3 = resultado3 + ((y * c) + (x / a) + (a / z) + (d * z));
		String resultado4 = "";
		resultado4 = resultado4 + ((e + z) + (d / z) + (d - z) + (x / e));
		resultado4 = resultado4 + ((c / c) + (y + b) + (y - b) + (d + b) + (d / z));
		resultado4 = resultado4 + ((b + z) + (b / b) + (z / c) + (d / x));
		String resultado5 = "";
		resultado5 = resultado5 + ((e + a) + (c / x) + (a / d));
		resultado5 = resultado5 + ((z + y) + (z / a) + (e - y));
		resultado5 = resultado5 + ((a * b) + (x / c) + (e - c) + (z * x));
		resultado5 = resultado5 + ((y - e) + (a - c) + (x + d) + (z / z));
		String resultado6 = "";
		resultado6 = resultado6 + ((a / z) + (x / d) + (z - b));
		resultado6 = resultado6 + ((b / x) + (d + y) + (y * e));
		resultado6 = resultado6 + ((b + c) + (a + a) + (z * z));
		String resultado7 = "";
		resultado7 = resultado7 + ((c / a) + (e * y) + (a / c));
		resultado7 = resultado7 + ((d * y) + (c * x) + (e * x));
		resultado7 = resultado7 + ((b - z) + (a + a) + (y / b) + (z * y) + (b - a));
		resultado7 = resultado7 + ((y / e) + (y + x) + (z - c));
		String resultado8 = "";
		resultado8 = resultado8 + ((a / x) + (z * z) + (c * z) + (x + z));
		resultado8 = resultado8 + ((a / c) + (c * y) + (d * e) + (x * z) + (d + z));
		resultado8 = resultado8 + ((b + e) + (e + z) + (z - z) + (x + z));
		String resultado9 = "";
		resultado9 = resultado9 + ((y - b) + (a + e) + (z + x) + (a - b) + (z * d));
		resultado9 = resultado9 + ((z / y) + (d - x) + (b - b));
		resultado9 = resultado9 + ((a / c) + (d / e) + (b * a) + (y * d));
		resultado9 = resultado9 + ((d * b) + (a * d) + (a + a) + (c + a) + (a * a));
		resultado9 = resultado9 + ((a * d) + (d / x) + (a / y) + (b / z) + (z + z));
		String resultado10 = "";
		resultado10 = resultado10 + ((e + d) + (x - e) + (b * d) + (b * x));
		resultado10 = resultado10 + ((y * a) + (b - y) + (y - c) + (y + d) + (b + c));
		resultado10 = resultado10 + ((c + c) + (e - e) + (a - b) + (a - z));
		resultado10 = resultado10 + ((a * b) + (x + y) + (e + y) + (c * c));
		resultado10 = resultado10 + ((x - d) + (x * a) + (e + x) + (z - x) + (d - e));
		String resultado11 = "";
		resultado11 = resultado11 + ((c / x) + (b + x) + (x / a));
		resultado11 = resultado11 + ((b + x) + (x + e) + (b * z));
		resultado11 = resultado11 + ((y * c) + (x + b) + (e - c));
		resultado11 = resultado11 + ((b + e) + (b * x) + (c / c) + (a / d) + (a - y));
		resultado11 = resultado11 + ((x / x) + (z / x) + (e - z) + (b / c));
		String resultado12 = "";
		resultado12 = resultado12 + ((x + d) + (d + b) + (c - e));
		resultado12 = resultado12 + ((b - b) + (e / a) + (e / a) + (c + d));
		resultado12 = resultado12 + ((y / x) + (e / x) + (e - e) + (e / e));
		resultado12 = resultado12 + ((x / b) + (d * y) + (c + e));
		resultado12 = resultado12 + ((x * d) + (x * a) + (a + a) + (d + d));
		String resultado13 = "";
		resultado13 = resultado13 + ((z / x) + (x - d) + (y / y));
		resultado13 = resultado13 + ((c + c) + (e + b) + (e + c));
		resultado13 = resultado13 + ((y + b) + (c * y) + (b * a));
		resultado13 = resultado13 + ((x / b) + (z + c) + (b / e));
		resultado13 = resultado13 + ((y - b) + (x + y) + (y - a));
		String resultado14 = "";
		resultado14 = resultado14 + ((b * c) + (x + c) + (a / a) + (e + d) + (a / x));
		resultado14 = resultado14 + ((z - z) + (e * c) + (e - e) + (b / e) + (b - b));
		resultado14 = resultado14 + ((a * d) + (z + a) + (b + y) + (a / x) + (a + a));
		resultado14 = resultado14 + ((d / x) + (d + b) + (d + d));
		String resultado15 = "";
		resultado15 = resultado15 + ((d / a) + (d * y) + (b * b));
		resultado15 = resultado15 + ((y / z) + (x + b) + (c / z) + (b + y));
		resultado15 = resultado15 + ((e / x) + (d * c) + (c * x) + (y + e) + (d / x));
		resultado15 = resultado15 + ((e + c) + (d * d) + (z + z));
		String resultado16 = "";
		resultado16 = resultado16 + ((y - c) + (c / a) + (d * a));
		resultado16 = resultado16 + ((c / y) + (x + a) + (c / x) + (x * z) + (c * c));
		resultado16 = resultado16 + ((z * x) + (e - x) + (x / e) + (d - e));
		String resultado17 = "";
		resultado17 = resultado17 + ((c * a) + (a * x) + (z - e));
		resultado17 = resultado17 + ((z / y) + (c * a) + (a * x));
		resultado17 = resultado17 + ((a * e) + (y * a) + (c - e));
		resultado17 = resultado17 + ((x - e) + (a * e) + (d - y) + (a + c) + (e - a));
		resultado17 = resultado17 + ((e * a) + (a + x) + (y * x) + (z * c));
		String resultado18 = "";
		resultado18 = resultado18 + ((x / x) + (y / y) + (b / b) + (y + d) + (c + d));
		resultado18 = resultado18 + ((e + c) + (z / b) + (d - z) + (d + z));
		resultado18 = resultado18 + ((c + b) + (z + y) + (a * d) + (b - y));
		resultado18 = resultado18 + ((y / z) + (b + e) + (y * b) + (z / c) + (d + z));
		resultado18 = resultado18 + ((e / b) + (a * b) + (e * b));
		String resultado19 = "";
		resultado19 = resultado19 + ((d / c) + (c + c) + (y + x));
		resultado19 = resultado19 + ((y / y) + (y / b) + (z + x));
		resultado19 = resultado19 + ((c * b) + (d * b) + (d * x) + (z + d) + (x + c));
		resultado19 = resultado19 + ((e - c) + (e * c) + (e * e) + (c + e) + (y - z));
		String resultado20 = "";
		resultado20 = resultado20 + ((c / b) + (z - b) + (d * e) + (y / c) + (y * a));
		resultado20 = resultado20 + ((x * z) + (b - x) + (y - z) + (x / a) + (d + y));
		resultado20 = resultado20 + ((z + e) + (e + a) + (c - a));
		resultado20 = resultado20 + ((b * y) + (e - y) + (x * c) + (y * b) + (b * b));
		String resultado21 = "";
		resultado21 = resultado21 + ((c * x) + (y / a) + (a * a));
		resultado21 = resultado21 + ((d - z) + (x * d) + (a + e) + (c + b) + (a - c));
		resultado21 = resultado21 + ((a / c) + (c * d) + (x + d) + (b + d));
		String resultado22 = "";
		resultado22 = resultado22 + ((c + b) + (a - e) + (y + y));
		resultado22 = resultado22 + ((y - d) + (b / c) + (a + c) + (a - y));
		resultado22 = resultado22 + ((c * x) + (d / z) + (b / x) + (b * e) + (b / e));
		resultado22 = resultado22 + ((a + b) + (a / d) + (y - y) + (c * x));
		String resultado23 = "";
		resultado23 = resultado23 + ((c * b) + (x * a) + (b / c));
		resultado23 = resultado23 + ((y * y) + (a / z) + (e * c) + (d * a) + (y - a));
		resultado23 = resultado23 + ((e - z) + (y * e) + (b - y) + (c * a) + (x + c));
		resultado23 = resultado23 + ((z + y) + (z + b) + (y / c) + (a * e) + (e - a));
		resultado23 = resultado23 + ((y / a) + (z / e) + (x + b) + (a - e) + (z + y));
		String resultado24 = "";
		resultado24 = resultado24 + ((y * z) + (a / c) + (a - b) + (x * a) + (b / y));
		resultado24 = resultado24 + ((a * y) + (e - a) + (d + x) + (a + y));
		resultado24 = resultado24 + ((a * d) + (y / a) + (y / b));
		String resultado25 = "";
		resultado25 = resultado25 + ((c / b) + (e - x) + (a + b));
		resultado25 = resultado25 + ((a + y) + (b + e) + (x / a) + (b * d) + (c / a));
		resultado25 = resultado25 + ((x / c) + (b * y) + (x + d) + (z * d) + (c + z));
		resultado25 = resultado25 + ((b * a) + (z / c) + (y + d) + (y + b) + (z - a));
		String resultado26 = "";
		resultado26 = resultado26 + ((d / d) + (e * z) + (b * a));
		resultado26 = resultado26 + ((b - z) + (y - a) + (a / d) + (e / b));
		resultado26 = resultado26 + ((c * d) + (e + d) + (d / z));
		resultado26 = resultado26 + ((b - e) + (y - e) + (e + x) + (z * e) + (y - a));
		String resultado27 = "";
		resultado27 = resultado27 + ((c - x) + (b - z) + (x / e) + (a + d));
		resultado27 = resultado27 + ((a - x) + (d + x) + (d - b) + (y * b) + (e / y));
		resultado27 = resultado27 + ((z + x) + (y - d) + (c * b));
		String resultado28 = "";
		resultado28 = resultado28 + ((z / a) + (z / a) + (a / a) + (a * d));
		resultado28 = resultado28 + ((x - b) + (c / y) + (y - b) + (d + e) + (d / x));
		resultado28 = resultado28 + ((d + a) + (d / b) + (a / x) + (a * e) + (c / c));
		String resultado29 = "";
		resultado29 = resultado29 + ((e - d) + (y / e) + (z + c) + (c * d));
		resultado29 = resultado29 + ((d * b) + (z * d) + (y + a) + (b * a));
		resultado29 = resultado29 + ((y * y) + (z + d) + (b - d));
		resultado29 = resultado29 + ((z * x) + (b / z) + (z * a) + (a - d) + (z * y));
		resultado29 = resultado29 + ((d - x) + (z - e) + (e * c));
		String resultado30 = "";
		resultado30 = resultado30 + ((a - e) + (c + d) + (b * z) + (y * a) + (z - y));
		resultado30 = resultado30 + ((e - a) + (x - a) + (c - c));
		resultado30 = resultado30 + ((z + b) + (b - e) + (e + d) + (d / a));
		resultado30 = resultado30 + ((c - b) + (z / c) + (x / z) + (x / y) + (c + y));
		String resultado31 = "";
		resultado31 = resultado31 + ((x - z) + (b - b) + (a + c) + (x * z) + (d + e));
		resultado31 = resultado31 + ((y * y) + (d * c) + (e - a) + (x / z) + (d + d));
		resultado31 = resultado31 + ((d * c) + (b - y) + (d + x));
		String resultado32 = "";
		resultado32 = resultado32 + ((x / y) + (y / z) + (z / x) + (b - b) + (z / b));
		resultado32 = resultado32 + ((a - a) + (z + b) + (z * z) + (d / d));
		resultado32 = resultado32 + ((c * c) + (e - a) + (z / x) + (a + z));
		resultado32 = resultado32 + ((a + z) + (x * x) + (d / b) + (d * b) + (z - y));
		resultado32 = resultado32 + ((b - a) + (c - e) + (d + a) + (e + z));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}