package br.com.av1.genZ01;

public class Questao4 
	public static void main(String[] args) {
		int a = 9;
		int b = 8;
		int c = 8;
		int d = 3;
		int e = 7;
		int x = 2;
		int y = 9;
		int z = 1;

		String resultado1 = "";
		resultado1 = resultado1 + ((b + d) + (d * a) + (d + a));
		resultado1 = resultado1 + ((b / e) + (x + y) + (z * a) + (d - a));
		resultado1 = resultado1 + ((c * z) + (b * e) + (e / z) + (z + b));
		resultado1 = resultado1 + ((b - y) + (a + b) + (z + c) + (c * b) + (b + x));
		resultado1 = resultado1 + ((c + d) + (x + d) + (c * z) + (e / x));
		String resultado2 = "";
		resultado2 = resultado2 + ((z * x) + (b - y) + (z / b) + (c / b));
		resultado2 = resultado2 + ((y + d) + (x * c) + (x / d) + (y / c) + (b * d));
		resultado2 = resultado2 + ((d / d) + (d + y) + (c - d) + (e + x) + (a / d));
		resultado2 = resultado2 + ((c + x) + (b / y) + (z + c));
		resultado2 = resultado2 + ((y * c) + (c - z) + (e - y));
		String resultado3 = "";
		resultado3 = resultado3 + ((a - a) + (x - d) + (a + b) + (e * z) + (d - b));
		resultado3 = resultado3 + ((e / a) + (c + a) + (x + e) + (d - d) + (x / d));
		resultado3 = resultado3 + ((x / z) + (e * x) + (x * z));
		resultado3 = resultado3 + ((d / x) + (x + d) + (c / d) + (x / y) + (b - y));
		String resultado4 = "";
		resultado4 = resultado4 + ((x - d) + (z - z) + (y / c));
		resultado4 = resultado4 + ((a * e) + (z + y) + (c - b));
		resultado4 = resultado4 + ((a + y) + (y + e) + (e / a) + (e + z));
		String resultado5 = "";
		resultado5 = resultado5 + ((a / a) + (b / b) + (d - x) + (b * z));
		resultado5 = resultado5 + ((e + b) + (z * e) + (d - b));
		resultado5 = resultado5 + ((b + z) + (b * b) + (z - c) + (a - b) + (x + d));
		String resultado6 = "";
		resultado6 = resultado6 + ((b * z) + (y - x) + (z + x));
		resultado6 = resultado6 + ((c + b) + (x - y) + (y - a) + (e * e) + (x + z));
		resultado6 = resultado6 + ((c / b) + (d - e) + (c / z) + (e * z) + (z / c));
		String resultado7 = "";
		resultado7 = resultado7 + ((y - c) + (y + c) + (d + c));
		resultado7 = resultado7 + ((e * c) + (e * b) + (x - c) + (e / b) + (z + b));
		resultado7 = resultado7 + ((e * b) + (e + a) + (a + e) + (x * b));
		String resultado8 = "";
		resultado8 = resultado8 + ((a - x) + (b - z) + (a - c));
		resultado8 = resultado8 + ((a * z) + (z - a) + (y / a) + (x + c));
		resultado8 = resultado8 + ((c / d) + (b - z) + (a + c) + (x + b));
		resultado8 = resultado8 + ((y + z) + (e * b) + (z / c));
		resultado8 = resultado8 + ((e - b) + (y * d) + (c * a));
		String resultado9 = "";
		resultado9 = resultado9 + ((d / z) + (c - x) + (e + d) + (c / b));
		resultado9 = resultado9 + ((x * d) + (y + e) + (d + y) + (d / z));
		resultado9 = resultado9 + ((b * b) + (z + b) + (d / b) + (z - x) + (y + e));
		resultado9 = resultado9 + ((x * x) + (e - d) + (z * e) + (e + x) + (x + e));
		String resultado10 = "";
		resultado10 = resultado10 + ((c + x) + (d - z) + (d + c) + (c * z));
		resultado10 = resultado10 + ((b / c) + (b / c) + (b * z));
		resultado10 = resultado10 + ((d / e) + (z + z) + (e + c) + (z - c));
		String resultado11 = "";
		resultado11 = resultado11 + ((c * a) + (a / b) + (d + b) + (z / z));
		resultado11 = resultado11 + ((x - c) + (d * d) + (x / z) + (a * e));
		resultado11 = resultado11 + ((b - c) + (e * d) + (d + d) + (e / b) + (z - y));
		String resultado12 = "";
		resultado12 = resultado12 + ((y + c) + (y - a) + (x + y) + (x - x));
		resultado12 = resultado12 + ((c - z) + (d * y) + (x + e));
		resultado12 = resultado12 + ((x / z) + (y - e) + (c / e) + (z / d));
		resultado12 = resultado12 + ((y / z) + (c + z) + (e + d) + (a / d) + (e / a));
		resultado12 = resultado12 + ((x - e) + (d + e) + (y / x));
		String resultado13 = "";
		resultado13 = resultado13 + ((b - x) + (z * y) + (e + z) + (e - b) + (z + a));
		resultado13 = resultado13 + ((d / x) + (a / b) + (y / e));
		resultado13 = resultado13 + ((a + b) + (d - b) + (c - a) + (b + c) + (b + x));
		resultado13 = resultado13 + ((y / x) + (c - z) + (d - y) + (x + a) + (z - a));
		String resultado14 = "";
		resultado14 = resultado14 + ((c - y) + (z - z) + (y + c) + (a + c) + (c / x));
		resultado14 = resultado14 + ((b / y) + (x / y) + (a - x));
		resultado14 = resultado14 + ((a * e) + (x + d) + (y + b) + (x + y) + (d + b));
		resultado14 = resultado14 + ((z - z) + (d * c) + (c / b));
		resultado14 = resultado14 + ((a + d) + (y - b) + (c + d));
		String resultado15 = "";
		resultado15 = resultado15 + ((b + d) + (e + c) + (d + a) + (a + a) + (b - e));
		resultado15 = resultado15 + ((z / x) + (a * d) + (e * y));
		resultado15 = resultado15 + ((z - a) + (x + d) + (z - z));
		resultado15 = resultado15 + ((a + x) + (b * x) + (z + b) + (c - c));
		resultado15 = resultado15 + ((z - y) + (y + x) + (b + y) + (d * c));
		String resultado16 = "";
		resultado16 = resultado16 + ((d - d) + (z * d) + (b / d) + (b - e));
		resultado16 = resultado16 + ((b + y) + (a / x) + (a + b));
		resultado16 = resultado16 + ((z / a) + (z / z) + (e + a));
		resultado16 = resultado16 + ((x / b) + (d + b) + (a / z) + (x - e) + (e * x));
		resultado16 = resultado16 + ((z / z) + (z * y) + (x + z) + (z - d));
		String resultado17 = "";
		resultado17 = resultado17 + ((e - y) + (a / z) + (e - z));
		resultado17 = resultado17 + ((b + d) + (b / c) + (c / d) + (e / e) + (e - b));
		resultado17 = resultado17 + ((y * c) + (a - b) + (b / b));
		resultado17 = resultado17 + ((c / z) + (x - e) + (z * z) + (d / e) + (e - d));
		String resultado18 = "";
		resultado18 = resultado18 + ((e + a) + (x - z) + (y * z) + (e * x));
		resultado18 = resultado18 + ((b * d) + (z - d) + (y / c) + (c - y));
		resultado18 = resultado18 + ((c - b) + (d * z) + (a + z));
		resultado18 = resultado18 + ((e + z) + (x / c) + (e / a) + (e * e) + (x + z));
		String resultado19 = "";
		resultado19 = resultado19 + ((z + c) + (d * y) + (z + b) + (y - a) + (x * y));
		resultado19 = resultado19 + ((x * c) + (x * y) + (d + y));
		resultado19 = resultado19 + ((z * a) + (e / d) + (d + c) + (a - y) + (c / x));
		String resultado20 = "";
		resultado20 = resultado20 + ((y + b) + (d - e) + (c * c));
		resultado20 = resultado20 + ((d + d) + (c + d) + (c / d) + (a + z));
		resultado20 = resultado20 + ((b / d) + (b + d) + (x - b) + (a * x) + (x - d));
		String resultado21 = "";
		resultado21 = resultado21 + ((d - e) + (x + e) + (d + y) + (b + d));
		resultado21 = resultado21 + ((z / d) + (a + e) + (b * a));
		resultado21 = resultado21 + ((d - y) + (b - b) + (y * a));
		resultado21 = resultado21 + ((z - d) + (z - x) + (a + a) + (b + x) + (a / e));
		String resultado22 = "";
		resultado22 = resultado22 + ((c - y) + (z + x) + (z - z) + (a - d) + (c * z));
		resultado22 = resultado22 + ((c + d) + (y / x) + (d / e) + (e / e));
		resultado22 = resultado22 + ((c * x) + (b - c) + (d / b) + (d - a) + (x - c));
		resultado22 = resultado22 + ((a - c) + (c + c) + (y * x));
		String resultado23 = "";
		resultado23 = resultado23 + ((d + e) + (b * b) + (a + z));
		resultado23 = resultado23 + ((d / z) + (e - e) + (b + z));
		resultado23 = resultado23 + ((a / d) + (d - c) + (e * b) + (b / c));
		String resultado24 = "";
		resultado24 = resultado24 + ((d + d) + (a + y) + (y + z) + (c * z));
		resultado24 = resultado24 + ((a - b) + (e * b) + (b + d));
		resultado24 = resultado24 + ((b + c) + (x - d) + (z - x) + (b / a) + (a + c));
		resultado24 = resultado24 + ((e - e) + (e * c) + (d / x));
		String resultado25 = "";
		resultado25 = resultado25 + ((x - e) + (x - d) + (e - e));
		resultado25 = resultado25 + ((z + d) + (d * c) + (d - y) + (e / d));
		resultado25 = resultado25 + ((e + e) + (d - d) + (e / e) + (a / d) + (z / b));
		resultado25 = resultado25 + ((b * z) + (y + e) + (e - a) + (a * x));
		resultado25 = resultado25 + ((d / d) + (d + c) + (x / z));
		String resultado26 = "";
		resultado26 = resultado26 + ((d * b) + (b * e) + (d / y));
		resultado26 = resultado26 + ((x + d) + (d + a) + (b + y));
		resultado26 = resultado26 + ((z + c) + (b + z) + (a / y) + (z * c));
		resultado26 = resultado26 + ((e * b) + (a * x) + (z + b) + (b / e));
		String resultado27 = "";
		resultado27 = resultado27 + ((y / z) + (z * c) + (c / e) + (y + e));
		resultado27 = resultado27 + ((x / b) + (a + c) + (y * b) + (d * e));
		resultado27 = resultado27 + ((e + b) + (y / d) + (y + b) + (z - b) + (e * b));
		resultado27 = resultado27 + ((z * a) + (e / z) + (b + c) + (c / c));
		resultado27 = resultado27 + ((e + b) + (x * c) + (z / a) + (z + e) + (z + y));
		String resultado28 = "";
		resultado28 = resultado28 + ((z * z) + (c / c) + (b * z) + (b / c));
		resultado28 = resultado28 + ((z * c) + (a / e) + (y - x) + (e * e));
		resultado28 = resultado28 + ((e - z) + (y + z) + (e * e) + (z + z));
		String resultado29 = "";
		resultado29 = resultado29 + ((b / a) + (z * z) + (y - a) + (y - b) + (c * y));
		resultado29 = resultado29 + ((z - a) + (d - a) + (x + e));
		resultado29 = resultado29 + ((e + c) + (y + d) + (b - d) + (c / e) + (a - d));
		resultado29 = resultado29 + ((z + a) + (y * y) + (a + c));
		resultado29 = resultado29 + ((y + e) + (y - b) + (d + b) + (d / a));
		String resultado30 = "";
		resultado30 = resultado30 + ((x - y) + (d / b) + (b / e) + (d * c) + (e / b));
		resultado30 = resultado30 + ((a + e) + (z + z) + (x - d) + (z / d) + (b * y));
		resultado30 = resultado30 + ((y * x) + (d + y) + (a + e));
		resultado30 = resultado30 + ((e + c) + (e / a) + (b - y));
		String resultado31 = "";
		resultado31 = resultado31 + ((x * e) + (z + y) + (y / b) + (x - b));
		resultado31 = resultado31 + ((b * x) + (c * z) + (b * c) + (x / b) + (b * a));
		resultado31 = resultado31 + ((b - a) + (a - c) + (a + b) + (a + d) + (y / y));
		resultado31 = resultado31 + ((y * d) + (y / z) + (z / c));
		String resultado32 = "";
		resultado32 = resultado32 + ((d / y) + (a - x) + (x / x) + (y + y));
		resultado32 = resultado32 + ((a * e) + (d * b) + (c * a) + (d * z));
		resultado32 = resultado32 + ((z + z) + (c + y) + (b + d) + (b * x));
		resultado32 = resultado32 + ((a * b) + (d / x) + (z + z) + (e - a));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}