package br.com.av1.prova05;

public class Questao4 {
	public static void main(String[] args) {
		int a = 2;
		int b = 10;
		int c = 1;
		int d = 7;
		int e = 9;
		int x = 2;
		int y = 4;
		int z = 7;

		String resultado1 = "";
		resultado1 = resultado1 + ((b + z) + (e / a) + (c + b) + (b + c) + (z + a));
		resultado1 = resultado1 + ((c / z) + (x * x) + (a * e) + (d + z) + (y + b));
		resultado1 = resultado1 + ((c - c) + (d - y) + (y - b) + (z + d));
		resultado1 = resultado1 + ((y / b) + (x / a) + (z - y));
		String resultado2 = "";
		resultado2 = resultado2 + ((z + c) + (e + e) + (e - b));
		resultado2 = resultado2 + ((a - d) + (a * x) + (y - x));
		resultado2 = resultado2 + ((a * y) + (y * b) + (a - e) + (b + b));
		resultado2 = resultado2 + ((z * c) + (e / a) + (z / x) + (y / b) + (a - b));
		resultado2 = resultado2 + ((z - y) + (e / b) + (y - d) + (c / a) + (d / x));
		String resultado3 = "";
		resultado3 = resultado3 + ((e / d) + (y * y) + (a + x) + (a + z) + (x / d));
		resultado3 = resultado3 + ((y / a) + (d * d) + (d - e));
		resultado3 = resultado3 + ((x - d) + (d / x) + (x * z) + (b / e));
		resultado3 = resultado3 + ((z + y) + (e + x) + (x / x) + (a / z));
		resultado3 = resultado3 + ((z / c) + (x / b) + (d / x) + (c * e));
		String resultado4 = "";
		resultado4 = resultado4 + ((z - z) + (c / a) + (x + b) + (c + c));
		resultado4 = resultado4 + ((c + c) + (x + e) + (z - y));
		resultado4 = resultado4 + ((b + z) + (d - e) + (e / z) + (b - c) + (c / z));
		String resultado5 = "";
		resultado5 = resultado5 + ((y * y) + (b - x) + (z / b));
		resultado5 = resultado5 + ((c - z) + (d / y) + (z - b));
		resultado5 = resultado5 + ((e + e) + (z * y) + (b + d) + (y / e) + (d * x));
		resultado5 = resultado5 + ((d / e) + (e - e) + (x / c) + (z + e));
		resultado5 = resultado5 + ((x - b) + (x * z) + (d + b) + (d * b) + (y * z));
		String resultado6 = "";
		resultado6 = resultado6 + ((z + a) + (z * z) + (b / x));
		resultado6 = resultado6 + ((y * b) + (d - e) + (e + c) + (b + b));
		resultado6 = resultado6 + ((b - x) + (e - x) + (a - c) + (a - y));
		String resultado7 = "";
		resultado7 = resultado7 + ((e + e) + (x / c) + (e - x) + (b - d) + (b * x));
		resultado7 = resultado7 + ((d * d) + (z + d) + (y - e) + (c / e));
		resultado7 = resultado7 + ((a - d) + (a - e) + (z + y) + (z * x) + (y * e));
		resultado7 = resultado7 + ((y * c) + (d - x) + (b - x));
		String resultado8 = "";
		resultado8 = resultado8 + ((x + a) + (x * d) + (b / d));
		resultado8 = resultado8 + ((d / d) + (e + b) + (e + z) + (y + z) + (z + b));
		resultado8 = resultado8 + ((b * e) + (e * e) + (a + b) + (a * c));
		resultado8 = resultado8 + ((y / x) + (z - y) + (e / a));
		resultado8 = resultado8 + ((d / a) + (a * x) + (z + b) + (y - e));
		String resultado9 = "";
		resultado9 = resultado9 + ((b - x) + (z + e) + (x + d));
		resultado9 = resultado9 + ((e + e) + (b - c) + (d + z) + (e - z));
		resultado9 = resultado9 + ((c + b) + (z * y) + (y + a) + (c * c));
		String resultado10 = "";
		resultado10 = resultado10 + ((a * x) + (e - c) + (a - x) + (d / z));
		resultado10 = resultado10 + ((z + a) + (x * b) + (c / d) + (z * d));
		resultado10 = resultado10 + ((b + x) + (e + y) + (x - e));
		resultado10 = resultado10 + ((c / b) + (x * a) + (x - y));
		String resultado11 = "";
		resultado11 = resultado11 + ((b / b) + (z - b) + (b - e));
		resultado11 = resultado11 + ((e + z) + (z * x) + (x * b));
		resultado11 = resultado11 + ((a + y) + (a - y) + (c * a) + (x / c) + (y * y));
		resultado11 = resultado11 + ((c - b) + (z + b) + (x + a));
		String resultado12 = "";
		resultado12 = resultado12 + ((e - d) + (b + x) + (z - z));
		resultado12 = resultado12 + ((e - d) + (z + a) + (d + y));
		resultado12 = resultado12 + ((x + z) + (d + x) + (b + z) + (c / a));
		resultado12 = resultado12 + ((d / d) + (a * c) + (b * a) + (y + c));
		resultado12 = resultado12 + ((c - y) + (z / e) + (d - z) + (x * e));
		String resultado13 = "";
		resultado13 = resultado13 + ((b / b) + (x - x) + (c + b) + (e - b) + (b * y));
		resultado13 = resultado13 + ((a - a) + (z + z) + (y - z) + (z / c) + (z / a));
		resultado13 = resultado13 + ((d * y) + (z * z) + (b - z));
		resultado13 = resultado13 + ((c - z) + (x * c) + (a - x));
		String resultado14 = "";
		resultado14 = resultado14 + ((c + z) + (b - b) + (z * b) + (x * c) + (e / b));
		resultado14 = resultado14 + ((y + c) + (y - x) + (z * a));
		resultado14 = resultado14 + ((y - z) + (b * c) + (d + a) + (y + x));
		String resultado15 = "";
		resultado15 = resultado15 + ((c / a) + (a * e) + (c - b) + (d - a) + (a - b));
		resultado15 = resultado15 + ((e / x) + (e * c) + (d - y) + (x / y) + (e + c));
		resultado15 = resultado15 + ((e - b) + (b * c) + (z + e));
		resultado15 = resultado15 + ((c / a) + (c - z) + (d - b) + (y + a) + (y * b));
		resultado15 = resultado15 + ((e + y) + (y - d) + (x / y));
		String resultado16 = "";
		resultado16 = resultado16 + ((a - b) + (z - e) + (y - y) + (e / y) + (c - e));
		resultado16 = resultado16 + ((y / x) + (x / b) + (y / c) + (y * y));
		resultado16 = resultado16 + ((x / a) + (z * a) + (a + a) + (c + c) + (c + x));
		resultado16 = resultado16 + ((d / e) + (x - z) + (a * b) + (a / c) + (x - y));
		String resultado17 = "";
		resultado17 = resultado17 + ((c + b) + (z * e) + (a / y));
		resultado17 = resultado17 + ((z - y) + (d / x) + (z / d));
		resultado17 = resultado17 + ((x - c) + (y * d) + (x - c) + (y / b) + (e - b));
		String resultado18 = "";
		resultado18 = resultado18 + ((e / a) + (y / e) + (b - c) + (a - e));
		resultado18 = resultado18 + ((x + d) + (a + c) + (c / x) + (c / y));
		resultado18 = resultado18 + ((d - c) + (d * c) + (b + c));
		resultado18 = resultado18 + ((e + x) + (b * b) + (d + x));
		String resultado19 = "";
		resultado19 = resultado19 + ((b + c) + (x - y) + (a - y) + (d / x) + (a * x));
		resultado19 = resultado19 + ((c - a) + (y + b) + (y * d));
		resultado19 = resultado19 + ((b * y) + (y / d) + (y * a) + (z + c));
		resultado19 = resultado19 + ((e / a) + (e * a) + (c - b) + (c - y));
		resultado19 = resultado19 + ((e + x) + (d - c) + (z * e) + (a * a) + (z * e));
		String resultado20 = "";
		resultado20 = resultado20 + ((e * y) + (a + x) + (x * y) + (x - y));
		resultado20 = resultado20 + ((a - c) + (d + b) + (z / y) + (y - d) + (e * e));
		resultado20 = resultado20 + ((a + a) + (c + a) + (x - z) + (a + a) + (y * b));
		resultado20 = resultado20 + ((z + y) + (y / c) + (c + x));
		resultado20 = resultado20 + ((y - b) + (e + d) + (c * e) + (x + a));
		String resultado21 = "";
		resultado21 = resultado21 + ((b / c) + (x + b) + (z + z) + (d - b));
		resultado21 = resultado21 + ((y * z) + (z * a) + (x * a) + (z + z));
		resultado21 = resultado21 + ((d - x) + (d - c) + (a * x) + (y - a) + (x * z));
		String resultado22 = "";
		resultado22 = resultado22 + ((a + d) + (e - y) + (z + z));
		resultado22 = resultado22 + ((a + e) + (y - z) + (c / b));
		resultado22 = resultado22 + ((a + d) + (z - e) + (x + a) + (y * c) + (d / z));
		resultado22 = resultado22 + ((x + y) + (b * c) + (a / b));
		resultado22 = resultado22 + ((e / e) + (b / b) + (b / x));
		String resultado23 = "";
		resultado23 = resultado23 + ((d - z) + (a * a) + (z / a) + (e * d) + (y - e));
		resultado23 = resultado23 + ((x / e) + (a * c) + (a * b) + (e / y) + (c / a));
		resultado23 = resultado23 + ((a / b) + (z * c) + (z + c) + (a + y) + (b * e));
		String resultado24 = "";
		resultado24 = resultado24 + ((c / c) + (y * d) + (d - y) + (d / e) + (y * c));
		resultado24 = resultado24 + ((e + x) + (y + b) + (z + x) + (d * z) + (c / e));
		resultado24 = resultado24 + ((y + e) + (b - b) + (a - c) + (x / x) + (y - y));
		String resultado25 = "";
		resultado25 = resultado25 + ((b * c) + (d - e) + (y / e) + (z + x));
		resultado25 = resultado25 + ((x - a) + (z + c) + (y / d) + (e / a) + (b - d));
		resultado25 = resultado25 + ((e + d) + (z * x) + (x + b));
		resultado25 = resultado25 + ((y - c) + (b * z) + (b / y) + (d + z));
		resultado25 = resultado25 + ((c * c) + (d * z) + (a / z) + (y + d));
		String resultado26 = "";
		resultado26 = resultado26 + ((z + e) + (a - y) + (d + b));
		resultado26 = resultado26 + ((a * z) + (b + x) + (z - d) + (x * y) + (y / z));
		resultado26 = resultado26 + ((b * b) + (a - b) + (a + d) + (d * e));
		resultado26 = resultado26 + ((x / e) + (a - z) + (z - a));
		resultado26 = resultado26 + ((d - d) + (a / e) + (z - e));
		String resultado27 = "";
		resultado27 = resultado27 + ((e + x) + (a + c) + (c + y) + (a + y));
		resultado27 = resultado27 + ((z - y) + (a / a) + (c * d));
		resultado27 = resultado27 + ((c * x) + (z + c) + (x + e));
		resultado27 = resultado27 + ((e - z) + (z + d) + (y / c) + (a - z));
		String resultado28 = "";
		resultado28 = resultado28 + ((z - a) + (y * d) + (c - y) + (y / e) + (e * y));
		resultado28 = resultado28 + ((e / a) + (c + x) + (e + a));
		resultado28 = resultado28 + ((c / a) + (z * d) + (e + b) + (x * c) + (x / b));
		String resultado29 = "";
		resultado29 = resultado29 + ((x / x) + (y * c) + (a + b));
		resultado29 = resultado29 + ((y * e) + (a * b) + (c * d));
		resultado29 = resultado29 + ((d * a) + (a + e) + (y + z) + (x + e));
		String resultado30 = "";
		resultado30 = resultado30 + ((e + y) + (e - a) + (x * c));
		resultado30 = resultado30 + ((c - c) + (z * e) + (c + x) + (z + e));
		resultado30 = resultado30 + ((d / b) + (e + x) + (x / b) + (y - b) + (y * z));
		resultado30 = resultado30 + ((e / d) + (d - z) + (y * z));
		String resultado31 = "";
		resultado31 = resultado31 + ((a + d) + (d * d) + (z / a) + (c + c));
		resultado31 = resultado31 + ((x / y) + (a / z) + (a / e) + (x + x) + (z + a));
		resultado31 = resultado31 + ((x - z) + (a * b) + (z / c));
		resultado31 = resultado31 + ((x + b) + (d / e) + (c + x));
		String resultado32 = "";
		resultado32 = resultado32 + ((c - c) + (y / d) + (b + e) + (z + y));
		resultado32 = resultado32 + ((e * d) + (b - b) + (a + c));
		resultado32 = resultado32 + ((y - y) + (z - y) + (c / z) + (a / e));
		resultado32 = resultado32 + ((b * y) + (b + x) + (z - a) + (e * z) + (c / a));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}