package br.com.av1.genZ02;

public class Questao4 {
	public static void main(String[] args) {
		int a = 9;
		int b = 3;
		int c = 5;
		int d = 8;
		int e = 7;
		int x = 6;
		int y = 5;
		int z = 7;

		String resultado1 = "";
		resultado1 = resultado1 + ((x * c) + (a / e) + (y * y) + (d + z));
		resultado1 = resultado1 + ((a * a) + (y * c) + (a - d) + (z - b) + (x / e));
		resultado1 = resultado1 + ((y / e) + (e - x) + (b * e) + (a - c) + (b + d));
		String resultado2 = "";
		resultado2 = resultado2 + ((x / b) + (x + d) + (x + e));
		resultado2 = resultado2 + ((b * z) + (c + b) + (b - d));
		resultado2 = resultado2 + ((a * b) + (b * e) + (c / b) + (c / x));
		String resultado3 = "";
		resultado3 = resultado3 + ((x + y) + (z + d) + (c * c) + (x / y) + (z + c));
		resultado3 = resultado3 + ((c + b) + (e / z) + (y * c));
		resultado3 = resultado3 + ((a * b) + (d / x) + (c + y) + (x + b));
		String resultado4 = "";
		resultado4 = resultado4 + ((c * e) + (e + e) + (d * z) + (y / d) + (b + d));
		resultado4 = resultado4 + ((e / x) + (d + b) + (x - y));
		resultado4 = resultado4 + ((a / d) + (a - z) + (y + y) + (y + z) + (x - a));
		resultado4 = resultado4 + ((c + a) + (y + z) + (e - d));
		String resultado5 = "";
		resultado5 = resultado5 + ((e * z) + (y * c) + (d - c) + (d / b));
		resultado5 = resultado5 + ((a - y) + (x + b) + (c + z) + (y + a));
		resultado5 = resultado5 + ((x - b) + (b * a) + (d * c));
		resultado5 = resultado5 + ((x * a) + (d - y) + (d / c) + (y - b));
		resultado5 = resultado5 + ((d / z) + (e + a) + (e * b) + (e * x));
		String resultado6 = "";
		resultado6 = resultado6 + ((z / e) + (d * c) + (z + y) + (y - x));
		resultado6 = resultado6 + ((z + d) + (x * x) + (d * e) + (b / e));
		resultado6 = resultado6 + ((c * y) + (e * z) + (x / b) + (c - y));
		String resultado7 = "";
		resultado7 = resultado7 + ((c / d) + (d / z) + (z * b) + (c - e) + (a + d));
		resultado7 = resultado7 + ((e - x) + (x * c) + (c / b) + (a * c));
		resultado7 = resultado7 + ((d * a) + (c * a) + (y - d) + (b - z) + (a - c));
		String resultado8 = "";
		resultado8 = resultado8 + ((x - e) + (b + b) + (d - a));
		resultado8 = resultado8 + ((e / e) + (z * y) + (c + z) + (e - c) + (x + b));
		resultado8 = resultado8 + ((c * x) + (x - x) + (z / d) + (b + z));
		String resultado9 = "";
		resultado9 = resultado9 + ((y / c) + (a + e) + (b - b) + (d * e) + (e + c));
		resultado9 = resultado9 + ((c + b) + (x * e) + (z - a) + (e + b));
		resultado9 = resultado9 + ((e - d) + (y + y) + (a / b) + (d * d));
		resultado9 = resultado9 + ((z + y) + (a - z) + (y + e) + (y - a) + (z - a));
		resultado9 = resultado9 + ((x * c) + (d / d) + (e + c) + (a + z) + (x + z));
		String resultado10 = "";
		resultado10 = resultado10 + ((e - d) + (d * x) + (e - e));
		resultado10 = resultado10 + ((d / a) + (d * b) + (z + d) + (y * d) + (d / c));
		resultado10 = resultado10 + ((c * x) + (c - d) + (e - d));
		resultado10 = resultado10 + ((x + d) + (e - x) + (d - x));
		String resultado11 = "";
		resultado11 = resultado11 + ((a - z) + (d / b) + (c - a) + (e / c));
		resultado11 = resultado11 + ((c / y) + (x - b) + (y / z) + (d * x));
		resultado11 = resultado11 + ((b / y) + (a / a) + (b - b) + (b * y));
		String resultado12 = "";
		resultado12 = resultado12 + ((a - x) + (b + d) + (y - x));
		resultado12 = resultado12 + ((c / x) + (a / b) + (z * z) + (d + z));
		resultado12 = resultado12 + ((d * e) + (e - x) + (a * y));
		String resultado13 = "";
		resultado13 = resultado13 + ((d * x) + (x + z) + (c / e) + (e / c));
		resultado13 = resultado13 + ((x / a) + (y - z) + (y / a));
		resultado13 = resultado13 + ((e + a) + (b * x) + (c / a) + (b - a));
		resultado13 = resultado13 + ((x * d) + (z * c) + (z * x) + (z + y) + (c / x));
		resultado13 = resultado13 + ((a + z) + (c - y) + (c - x) + (e * y));
		String resultado14 = "";
		resultado14 = resultado14 + ((z - e) + (z * x) + (c - c) + (c / a));
		resultado14 = resultado14 + ((z - d) + (e / c) + (d - a) + (e * x));
		resultado14 = resultado14 + ((a * b) + (a - a) + (x / a) + (e * z));
		resultado14 = resultado14 + ((z * d) + (c * e) + (x / b) + (e * x));
		resultado14 = resultado14 + ((a * z) + (y / y) + (d - c) + (d * e));
		String resultado15 = "";
		resultado15 = resultado15 + ((b * b) + (c + x) + (z - d) + (x + c));
		resultado15 = resultado15 + ((z * d) + (d - b) + (a - d) + (d + d) + (y + d));
		resultado15 = resultado15 + ((c * e) + (b + e) + (b * z));
		String resultado16 = "";
		resultado16 = resultado16 + ((a - a) + (b / c) + (d / y));
		resultado16 = resultado16 + ((c - x) + (y + c) + (e - c) + (c - y));
		resultado16 = resultado16 + ((d - c) + (d + d) + (b + b));
		resultado16 = resultado16 + ((c * a) + (a + z) + (d * a) + (y - a));
		String resultado17 = "";
		resultado17 = resultado17 + ((z / x) + (d - e) + (z + z) + (e + c) + (b / x));
		resultado17 = resultado17 + ((d - b) + (y - e) + (a + z) + (d / z) + (d * x));
		resultado17 = resultado17 + ((a - b) + (d + x) + (d - d) + (a / y));
		resultado17 = resultado17 + ((e + z) + (e + b) + (z - x) + (z + e));
		String resultado18 = "";
		resultado18 = resultado18 + ((z - b) + (b * a) + (b / a) + (y / y) + (a + e));
		resultado18 = resultado18 + ((c - y) + (c / a) + (a + a) + (b * x));
		resultado18 = resultado18 + ((d - c) + (z - d) + (y / c));
		resultado18 = resultado18 + ((a + b) + (b - z) + (c * b) + (b / c) + (d * z));
		resultado18 = resultado18 + ((a / e) + (y / z) + (a + z) + (x * c) + (d / c));
		String resultado19 = "";
		resultado19 = resultado19 + ((d / e) + (c / d) + (c * x) + (z / b) + (x * a));
		resultado19 = resultado19 + ((b + b) + (y - b) + (e * c));
		resultado19 = resultado19 + ((x / x) + (e / a) + (z / y) + (a + x));
		resultado19 = resultado19 + ((z + b) + (x + x) + (y - b) + (b + z) + (y - y));
		String resultado20 = "";
		resultado20 = resultado20 + ((d + y) + (a + x) + (b + y) + (y + d) + (c / b));
		resultado20 = resultado20 + ((x + x) + (z + e) + (z * x));
		resultado20 = resultado20 + ((c - a) + (a - z) + (c * z));
		resultado20 = resultado20 + ((b - y) + (c - z) + (c - e));
		String resultado21 = "";
		resultado21 = resultado21 + ((a * b) + (d / y) + (c / x) + (z - a) + (b - x));
		resultado21 = resultado21 + ((z - e) + (y - b) + (c * y));
		resultado21 = resultado21 + ((c * d) + (c + b) + (a - a) + (c - b) + (c / a));
		resultado21 = resultado21 + ((d - b) + (e * e) + (z * a) + (x / b));
		String resultado22 = "";
		resultado22 = resultado22 + ((z * c) + (c - e) + (e / e) + (d + b) + (b - y));
		resultado22 = resultado22 + ((d * e) + (d - c) + (y * z));
		resultado22 = resultado22 + ((a + d) + (c / b) + (d + y));
		String resultado23 = "";
		resultado23 = resultado23 + ((y - b) + (y * z) + (c / x) + (c - c) + (c * y));
		resultado23 = resultado23 + ((d * c) + (e / c) + (c + c) + (y + d) + (a - c));
		resultado23 = resultado23 + ((c * a) + (b * x) + (c * x) + (y / e) + (z - a));
		String resultado24 = "";
		resultado24 = resultado24 + ((c - y) + (c - a) + (d / y));
		resultado24 = resultado24 + ((y - y) + (a * y) + (z / e));
		resultado24 = resultado24 + ((y * a) + (x * y) + (y * c) + (e * x));
		resultado24 = resultado24 + ((b / d) + (z + e) + (z * a) + (e + e) + (y * b));
		resultado24 = resultado24 + ((b - y) + (d * e) + (c * e));
		String resultado25 = "";
		resultado25 = resultado25 + ((d / e) + (z - e) + (b * d) + (d - z));
		resultado25 = resultado25 + ((z - d) + (e - c) + (e / a) + (c / d));
		resultado25 = resultado25 + ((z * d) + (e + z) + (e + d));
		resultado25 = resultado25 + ((y * y) + (z - y) + (z * e) + (y / b) + (x / y));
		String resultado26 = "";
		resultado26 = resultado26 + ((a * d) + (d * y) + (b + a));
		resultado26 = resultado26 + ((z / c) + (a * a) + (e / e) + (z + a) + (a / e));
		resultado26 = resultado26 + ((y * b) + (z / b) + (e / a) + (x / x));
		String resultado27 = "";
		resultado27 = resultado27 + ((d / a) + (d * a) + (x - y) + (y * c) + (c - b));
		resultado27 = resultado27 + ((y - e) + (c - z) + (d + d) + (z / e));
		resultado27 = resultado27 + ((x + c) + (z * c) + (b / c) + (d * y) + (c / z));
		resultado27 = resultado27 + ((x / z) + (x * x) + (d * d) + (e / d) + (a / z));
		String resultado28 = "";
		resultado28 = resultado28 + ((e / y) + (a - z) + (a / z) + (a / b) + (c - e));
		resultado28 = resultado28 + ((x * y) + (y - d) + (b - e) + (z * e));
		resultado28 = resultado28 + ((b * b) + (z - x) + (e - y));
		resultado28 = resultado28 + ((x - a) + (c + x) + (c / a) + (y + b) + (x * e));
		String resultado29 = "";
		resultado29 = resultado29 + ((x / c) + (e - a) + (a / e) + (z - a) + (y * c));
		resultado29 = resultado29 + ((z - a) + (y + z) + (e / b) + (x / e));
		resultado29 = resultado29 + ((y + y) + (z * d) + (e * e) + (d * a));
		resultado29 = resultado29 + ((x * b) + (y - b) + (a - x));
		String resultado30 = "";
		resultado30 = resultado30 + ((b / c) + (x - x) + (z * e));
		resultado30 = resultado30 + ((b + e) + (x - d) + (d - b));
		resultado30 = resultado30 + ((a / z) + (b - x) + (d / e) + (a * c) + (a - z));
		resultado30 = resultado30 + ((e * d) + (d + b) + (y + y));
		String resultado31 = "";
		resultado31 = resultado31 + ((b * x) + (x + d) + (y - y) + (z - e));
		resultado31 = resultado31 + ((z * y) + (x - c) + (b * z));
		resultado31 = resultado31 + ((b + y) + (x / a) + (d + b) + (x * b));
		resultado31 = resultado31 + ((c - z) + (c + c) + (d * a) + (a + b) + (y + z));
		String resultado32 = "";
		resultado32 = resultado32 + ((x + d) + (d - b) + (y + x));
		resultado32 = resultado32 + ((e * y) + (b / c) + (x + c) + (y / z));
		resultado32 = resultado32 + ((d / b) + (b + y) + (c - c) + (a / z) + (a / a));
		resultado32 = resultado32 + ((c * d) + (c * e) + (d + z) + (z + b));
		resultado32 = resultado32 + ((y / z) + (y * a) + (b - a) + (d / e));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}