package br.com.av1.prova11;

public class Questao4 {
	public static void main(String[] args) {
		int a = 3;
		int b = 9;
		int c = 3;
		int d = 6;
		int e = 7;
		int x = 7;
		int y = 9;
		int z = 4;

		String resultado1 = "";
		resultado1 = resultado1 + ((x + c) + (d * d) + (z + y));
		resultado1 = resultado1 + ((c * x) + (a / z) + (b - y) + (d + b) + (e - x));
		resultado1 = resultado1 + ((e / z) + (x * d) + (b / y) + (y + z) + (y / b));
		String resultado2 = "";
		resultado2 = resultado2 + ((d - c) + (e * c) + (b + z));
		resultado2 = resultado2 + ((x / c) + (e - z) + (a + a) + (z / x) + (e + z));
		resultado2 = resultado2 + ((x + b) + (a / e) + (d - a));
		String resultado3 = "";
		resultado3 = resultado3 + ((y + d) + (e / d) + (c + d) + (z - x) + (d * a));
		resultado3 = resultado3 + ((y - y) + (b - e) + (z * c));
		resultado3 = resultado3 + ((e / z) + (a - c) + (x + y) + (y * e));
		resultado3 = resultado3 + ((e + z) + (a * e) + (z - z));
		resultado3 = resultado3 + ((a * e) + (c / x) + (y - y) + (d * b));
		String resultado4 = "";
		resultado4 = resultado4 + ((y - e) + (e * a) + (x / c) + (z / z) + (x + c));
		resultado4 = resultado4 + ((d / e) + (x * y) + (e + e) + (z + z));
		resultado4 = resultado4 + ((c - y) + (e * c) + (a / z) + (e * e) + (c * d));
		resultado4 = resultado4 + ((c + d) + (y + c) + (d + x));
		resultado4 = resultado4 + ((c - a) + (d / a) + (e - e) + (z - x));
		String resultado5 = "";
		resultado5 = resultado5 + ((y - z) + (e * z) + (a / d) + (z + d));
		resultado5 = resultado5 + ((z / d) + (d + y) + (c * d) + (b - x));
		resultado5 = resultado5 + ((x * z) + (y * z) + (y * b));
		resultado5 = resultado5 + ((c * c) + (a * b) + (y * x) + (b - c) + (a / z));
		String resultado6 = "";
		resultado6 = resultado6 + ((c / e) + (e + y) + (d / d));
		resultado6 = resultado6 + ((a / a) + (e - y) + (a * d) + (x / d) + (y + z));
		resultado6 = resultado6 + ((x / a) + (y / z) + (e * z));
		resultado6 = resultado6 + ((c / z) + (e + z) + (b + b));
		String resultado7 = "";
		resultado7 = resultado7 + ((a / c) + (b / d) + (z + e));
		resultado7 = resultado7 + ((a / d) + (e - y) + (c * c) + (b - a));
		resultado7 = resultado7 + ((b * b) + (y + a) + (c * e));
		String resultado8 = "";
		resultado8 = resultado8 + ((e - y) + (a / z) + (y - b));
		resultado8 = resultado8 + ((b * x) + (a / z) + (y * d) + (e - d) + (z * c));
		resultado8 = resultado8 + ((d + c) + (c - y) + (e + c));
		String resultado9 = "";
		resultado9 = resultado9 + ((y / a) + (e + z) + (z + y));
		resultado9 = resultado9 + ((z + b) + (b / z) + (a + b) + (c + e) + (a / c));
		resultado9 = resultado9 + ((d / a) + (b * a) + (y / d));
		resultado9 = resultado9 + ((y - e) + (z + c) + (b / a) + (z * b) + (x + y));
		resultado9 = resultado9 + ((y * d) + (e - b) + (b / e));
		String resultado10 = "";
		resultado10 = resultado10 + ((d / x) + (c - z) + (z * c));
		resultado10 = resultado10 + ((e / e) + (b * d) + (b * b) + (z / d));
		resultado10 = resultado10 + ((b + d) + (d + d) + (y / a) + (e - d) + (e * b));
		resultado10 = resultado10 + ((x / b) + (c / x) + (e - a) + (x - c));
		String resultado11 = "";
		resultado11 = resultado11 + ((z - x) + (y / b) + (e - z));
		resultado11 = resultado11 + ((x + d) + (x - b) + (x / z));
		resultado11 = resultado11 + ((d + a) + (a / x) + (b / x) + (x - x));
		String resultado12 = "";
		resultado12 = resultado12 + ((y + e) + (z / a) + (y - c) + (d / y) + (a - z));
		resultado12 = resultado12 + ((b / y) + (z - z) + (x + b) + (d + y) + (a * b));
		resultado12 = resultado12 + ((y * a) + (y * z) + (y / z));
		resultado12 = resultado12 + ((y - e) + (a * b) + (x - a));
		String resultado13 = "";
		resultado13 = resultado13 + ((c / y) + (a + d) + (c + y) + (y / a) + (d * z));
		resultado13 = resultado13 + ((a / y) + (a * y) + (y - z));
		resultado13 = resultado13 + ((z * d) + (z + y) + (b - x) + (e * y) + (z - a));
		String resultado14 = "";
		resultado14 = resultado14 + ((b - x) + (z / z) + (z / x) + (e / d));
		resultado14 = resultado14 + ((a * z) + (x * c) + (y - x));
		resultado14 = resultado14 + ((b / x) + (x - z) + (z * d) + (z * y));
		String resultado15 = "";
		resultado15 = resultado15 + ((y * b) + (y + y) + (y / a));
		resultado15 = resultado15 + ((b + y) + (c * x) + (a / b) + (d / c) + (z / e));
		resultado15 = resultado15 + ((z + y) + (b * b) + (x * c) + (y - z));
		resultado15 = resultado15 + ((a / b) + (b - a) + (e / y) + (x + a));
		resultado15 = resultado15 + ((z * b) + (b / a) + (x - c) + (b + b) + (e + b));
		String resultado16 = "";
		resultado16 = resultado16 + ((y + a) + (b + a) + (a + x));
		resultado16 = resultado16 + ((x - a) + (b * b) + (y * b) + (d + y));
		resultado16 = resultado16 + ((z + x) + (x - c) + (y * e) + (c - a));
		String resultado17 = "";
		resultado17 = resultado17 + ((x * d) + (e + x) + (c / a) + (e / a) + (c - a));
		resultado17 = resultado17 + ((z + e) + (z + c) + (b + b));
		resultado17 = resultado17 + ((d / x) + (a / d) + (y + y));
		String resultado18 = "";
		resultado18 = resultado18 + ((x + z) + (e * e) + (x * x) + (z - y) + (c - a));
		resultado18 = resultado18 + ((c * d) + (x * d) + (y - d) + (d - z));
		resultado18 = resultado18 + ((c - a) + (c + c) + (z * c) + (b / e));
		resultado18 = resultado18 + ((c / c) + (y / b) + (d / a));
		String resultado19 = "";
		resultado19 = resultado19 + ((z + z) + (d / z) + (z - x) + (x * a) + (y - b));
		resultado19 = resultado19 + ((y * a) + (x + x) + (a - z) + (c * a) + (d * d));
		resultado19 = resultado19 + ((x * d) + (c * z) + (d + b) + (e * y) + (b / b));
		resultado19 = resultado19 + ((a - c) + (y / z) + (d / y) + (c * x) + (x * a));
		resultado19 = resultado19 + ((z + x) + (d - z) + (c + b));
		String resultado20 = "";
		resultado20 = resultado20 + ((d * b) + (b / e) + (z - x) + (c + c));
		resultado20 = resultado20 + ((x + z) + (y / e) + (d + a) + (b / e) + (c * d));
		resultado20 = resultado20 + ((d + a) + (e - c) + (z / b) + (d * d) + (z - b));
		resultado20 = resultado20 + ((c / x) + (b - e) + (c + z) + (z / a));
		resultado20 = resultado20 + ((b * d) + (c + z) + (d * d));
		String resultado21 = "";
		resultado21 = resultado21 + ((z - b) + (d - y) + (y * x) + (b - y) + (e * z));
		resultado21 = resultado21 + ((a * a) + (b - d) + (y / z) + (e * c));
		resultado21 = resultado21 + ((a * z) + (b + a) + (d * c));
		String resultado22 = "";
		resultado22 = resultado22 + ((z * e) + (a * z) + (c / x));
		resultado22 = resultado22 + ((x / c) + (z - c) + (e + x) + (x / c) + (y / z));
		resultado22 = resultado22 + ((a / d) + (c + x) + (x * b) + (y + c));
		String resultado23 = "";
		resultado23 = resultado23 + ((x * x) + (a * x) + (b + d));
		resultado23 = resultado23 + ((a - a) + (y - b) + (d * e));
		resultado23 = resultado23 + ((y + c) + (e * z) + (y - z));
		String resultado24 = "";
		resultado24 = resultado24 + ((y + z) + (b - b) + (b + c));
		resultado24 = resultado24 + ((c * z) + (x - x) + (d - x) + (y * b));
		resultado24 = resultado24 + ((c - e) + (y + b) + (b * d) + (y * e));
		resultado24 = resultado24 + ((c * e) + (y + b) + (c + e) + (a * y));
		resultado24 = resultado24 + ((z / a) + (y - x) + (d / e));
		String resultado25 = "";
		resultado25 = resultado25 + ((c + c) + (y * z) + (z + a) + (e - b));
		resultado25 = resultado25 + ((z + b) + (c / e) + (a * c) + (b * c) + (d - e));
		resultado25 = resultado25 + ((z * y) + (y * z) + (d / z));
		String resultado26 = "";
		resultado26 = resultado26 + ((b - b) + (x - z) + (b * c) + (e / z) + (x * e));
		resultado26 = resultado26 + ((z * x) + (a + d) + (x / a) + (b - y));
		resultado26 = resultado26 + ((e / z) + (z * d) + (y * y));
		resultado26 = resultado26 + ((y / z) + (a - y) + (c * x) + (e - x));
		resultado26 = resultado26 + ((b / b) + (a / y) + (c / y) + (d - d));
		String resultado27 = "";
		resultado27 = resultado27 + ((b + e) + (b / z) + (e / c) + (b * x) + (z / z));
		resultado27 = resultado27 + ((a + y) + (x + b) + (z + e) + (c + a) + (e + c));
		resultado27 = resultado27 + ((d + z) + (z * e) + (y + c));
		resultado27 = resultado27 + ((d - y) + (d * c) + (a / d));
		resultado27 = resultado27 + ((y / x) + (a + d) + (x * z));
		String resultado28 = "";
		resultado28 = resultado28 + ((b - z) + (e / d) + (e - x));
		resultado28 = resultado28 + ((a * a) + (y / d) + (b * z) + (b - b) + (c - c));
		resultado28 = resultado28 + ((x * y) + (c + b) + (z - b) + (c - y) + (a / b));
		String resultado29 = "";
		resultado29 = resultado29 + ((d * z) + (c - z) + (a / y));
		resultado29 = resultado29 + ((c + y) + (e - y) + (a + e));
		resultado29 = resultado29 + ((a / d) + (e * e) + (y + x));
		resultado29 = resultado29 + ((e * x) + (d + y) + (d * e));
		resultado29 = resultado29 + ((x - e) + (c - x) + (d * y) + (y + a) + (e + d));
		String resultado30 = "";
		resultado30 = resultado30 + ((c + e) + (d / e) + (c + e) + (a * b));
		resultado30 = resultado30 + ((z - d) + (d / y) + (y / a));
		resultado30 = resultado30 + ((y * e) + (e * e) + (c + c) + (z / x));
		resultado30 = resultado30 + ((d - a) + (d - x) + (e / b) + (d / y) + (e + x));
		resultado30 = resultado30 + ((y + x) + (z - d) + (e - y));
		String resultado31 = "";
		resultado31 = resultado31 + ((b / x) + (e - y) + (b * e));
		resultado31 = resultado31 + ((y / x) + (b + c) + (e + x) + (x * y) + (z * d));
		resultado31 = resultado31 + ((z * y) + (a / b) + (e * y) + (b * c) + (y / y));
		resultado31 = resultado31 + ((b / e) + (e + y) + (y + a) + (y + z) + (y / d));
		String resultado32 = "";
		resultado32 = resultado32 + ((a - d) + (c + x) + (a * b) + (d + x));
		resultado32 = resultado32 + ((y + z) + (x + b) + (x * y) + (z - z));
		resultado32 = resultado32 + ((y / a) + (z - a) + (z - a) + (a / z) + (e + c));
		resultado32 = resultado32 + ((c - d) + (e / a) + (z / x) + (a / c));
		resultado32 = resultado32 + ((a - z) + (e / d) + (x * x) + (b / e));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}