package br.com.av1.prova19;

public class Questao4 {
	public static void main(String[] args) {
		int a = 5;
		int b = 5;
		int c = 3;
		int d = 6;
		int e = 6;
		int x = 6;
		int y = 4;
		int z = 9;

		String resultado1 = "";
		resultado1 = resultado1 + ((b / c) + (y * y) + (d / b) + (b - y) + (c / x));
		resultado1 = resultado1 + ((a * b) + (x * a) + (b / c) + (a / c));
		resultado1 = resultado1 + ((c - e) + (z * a) + (y - b) + (a + b));
		resultado1 = resultado1 + ((x - c) + (z * z) + (z + c) + (b * x));
		String resultado2 = "";
		resultado2 = resultado2 + ((c * b) + (a * z) + (b - y) + (z / a) + (a + d));
		resultado2 = resultado2 + ((y + a) + (z + d) + (e - c) + (a + x));
		resultado2 = resultado2 + ((e - b) + (a * a) + (y + b) + (z - x) + (d + z));
		String resultado3 = "";
		resultado3 = resultado3 + ((b - x) + (z / z) + (c * x) + (d / c) + (c * z));
		resultado3 = resultado3 + ((d - e) + (e - e) + (a - b) + (d * z) + (d + c));
		resultado3 = resultado3 + ((y / c) + (c - z) + (e - x) + (x / d));
		String resultado4 = "";
		resultado4 = resultado4 + ((a + x) + (b + e) + (c * x) + (c / d));
		resultado4 = resultado4 + ((a * d) + (e * y) + (x * a));
		resultado4 = resultado4 + ((b * z) + (c + y) + (b - c) + (e - x) + (x / d));
		resultado4 = resultado4 + ((c - d) + (x / b) + (x * y) + (x + b) + (x / e));
		String resultado5 = "";
		resultado5 = resultado5 + ((z / e) + (a - a) + (y / c));
		resultado5 = resultado5 + ((y - d) + (x - b) + (z / c) + (x / x) + (c - a));
		resultado5 = resultado5 + ((a - a) + (a / x) + (z * d) + (a / d));
		resultado5 = resultado5 + ((d / a) + (z + a) + (e * a) + (x + z) + (y - a));
		String resultado6 = "";
		resultado6 = resultado6 + ((e - e) + (b + y) + (b * z) + (b - z) + (z - c));
		resultado6 = resultado6 + ((b - x) + (y * e) + (y + a) + (a * e) + (a + d));
		resultado6 = resultado6 + ((c - c) + (b * b) + (z / b) + (a / z));
		resultado6 = resultado6 + ((c / z) + (z - y) + (d / b) + (z + z));
		String resultado7 = "";
		resultado7 = resultado7 + ((b + c) + (z / e) + (x + z));
		resultado7 = resultado7 + ((e + b) + (b / y) + (z + d) + (z * d) + (e / y));
		resultado7 = resultado7 + ((x - b) + (y - y) + (x + a) + (a / d) + (b - d));
		String resultado8 = "";
		resultado8 = resultado8 + ((b / d) + (c * y) + (e / y) + (x / b));
		resultado8 = resultado8 + ((z * b) + (a - z) + (a - e) + (b / c) + (z - y));
		resultado8 = resultado8 + ((a / a) + (d / y) + (c * b) + (y + d) + (a + a));
		resultado8 = resultado8 + ((d - e) + (y + z) + (c * z));
		resultado8 = resultado8 + ((y + y) + (b + e) + (z - d) + (b * b) + (b * z));
		String resultado9 = "";
		resultado9 = resultado9 + ((x * b) + (e + a) + (b + y) + (e * y));
		resultado9 = resultado9 + ((y - e) + (x * e) + (b - e));
		resultado9 = resultado9 + ((a + b) + (a / c) + (b / b) + (y - d));
		String resultado10 = "";
		resultado10 = resultado10 + ((d * a) + (z * c) + (z / x));
		resultado10 = resultado10 + ((e + z) + (c - a) + (c + c) + (e * b) + (a / z));
		resultado10 = resultado10 + ((d - y) + (a / a) + (x / x) + (x - e));
		resultado10 = resultado10 + ((y - b) + (d / b) + (c / z) + (c / e));
		String resultado11 = "";
		resultado11 = resultado11 + ((c + d) + (x * e) + (y + d) + (e + c));
		resultado11 = resultado11 + ((b + b) + (c - e) + (c + c) + (y + d));
		resultado11 = resultado11 + ((a + y) + (c - x) + (e - y) + (y - d));
		resultado11 = resultado11 + ((d + c) + (c - e) + (x - a) + (d * d));
		resultado11 = resultado11 + ((y / y) + (x / b) + (x * x));
		String resultado12 = "";
		resultado12 = resultado12 + ((e - z) + (b / d) + (x * b) + (x / x));
		resultado12 = resultado12 + ((e * c) + (z - x) + (x / a) + (y * b));
		resultado12 = resultado12 + ((c / a) + (e / a) + (a - d));
		resultado12 = resultado12 + ((d + c) + (e + e) + (y + a) + (y + b) + (d * y));
		resultado12 = resultado12 + ((y * z) + (e * c) + (e / a));
		String resultado13 = "";
		resultado13 = resultado13 + ((x - y) + (y - d) + (y * y) + (b + b));
		resultado13 = resultado13 + ((y + b) + (e + d) + (b / c) + (a / a) + (x / z));
		resultado13 = resultado13 + ((b / y) + (a * e) + (y / y));
		resultado13 = resultado13 + ((e + b) + (b - a) + (b / z) + (a / d));
		resultado13 = resultado13 + ((d * e) + (e / b) + (c - z) + (z / b) + (a * c));
		String resultado14 = "";
		resultado14 = resultado14 + ((e + y) + (c * z) + (b + e));
		resultado14 = resultado14 + ((a + y) + (c * b) + (y + b));
		resultado14 = resultado14 + ((e / d) + (b - c) + (z / x) + (e - a));
		resultado14 = resultado14 + ((x / c) + (e - c) + (x * c) + (c + y) + (d - z));
		String resultado15 = "";
		resultado15 = resultado15 + ((d / b) + (e / b) + (b * a) + (d + d) + (x * e));
		resultado15 = resultado15 + ((b - d) + (a / b) + (e + c) + (b + z));
		resultado15 = resultado15 + ((c + e) + (c * x) + (b / a) + (c * a) + (a / a));
		resultado15 = resultado15 + ((c / a) + (y * c) + (e * d) + (z / z));
		resultado15 = resultado15 + ((b + x) + (x + z) + (a * y) + (y + c));
		String resultado16 = "";
		resultado16 = resultado16 + ((y * c) + (d - c) + (d / x));
		resultado16 = resultado16 + ((a - x) + (c + b) + (b / c) + (e / e));
		resultado16 = resultado16 + ((x * a) + (c * e) + (x + y));
		resultado16 = resultado16 + ((z * x) + (y + a) + (e - e));
		resultado16 = resultado16 + ((x + a) + (e / b) + (y * z));
		String resultado17 = "";
		resultado17 = resultado17 + ((c * d) + (a / y) + (y * e));
		resultado17 = resultado17 + ((e + a) + (y * d) + (z / b));
		resultado17 = resultado17 + ((d * d) + (z - y) + (z + e));
		resultado17 = resultado17 + ((b + z) + (d * d) + (a + b));
		resultado17 = resultado17 + ((z * c) + (b * y) + (c * b) + (d - y) + (d / y));
		String resultado18 = "";
		resultado18 = resultado18 + ((a / d) + (y / a) + (a - a) + (b / a) + (e - b));
		resultado18 = resultado18 + ((x - y) + (d + d) + (d / e) + (a + e));
		resultado18 = resultado18 + ((b + x) + (y - x) + (e + e));
		resultado18 = resultado18 + ((x + a) + (z * a) + (c + c) + (x * x));
		String resultado19 = "";
		resultado19 = resultado19 + ((y + a) + (y * c) + (z + b) + (c + y) + (b + c));
		resultado19 = resultado19 + ((x / a) + (c / x) + (d + a));
		resultado19 = resultado19 + ((x * y) + (y + x) + (c / z) + (c + x) + (c + x));
		resultado19 = resultado19 + ((y - a) + (y / b) + (d - b));
		String resultado20 = "";
		resultado20 = resultado20 + ((d + y) + (a - z) + (b - y));
		resultado20 = resultado20 + ((y - e) + (z - d) + (e - b) + (c - a) + (z - e));
		resultado20 = resultado20 + ((b - x) + (x / z) + (b * y) + (c / y));
		String resultado21 = "";
		resultado21 = resultado21 + ((e - b) + (d + y) + (x - d) + (z + c) + (z * x));
		resultado21 = resultado21 + ((y - y) + (x - e) + (a + d));
		resultado21 = resultado21 + ((e - d) + (c / z) + (c * e) + (z + z));
		String resultado22 = "";
		resultado22 = resultado22 + ((z / d) + (d * a) + (c / b) + (z + e));
		resultado22 = resultado22 + ((x / y) + (x - a) + (e / y));
		resultado22 = resultado22 + ((b + d) + (x + x) + (z * x));
		resultado22 = resultado22 + ((x / x) + (e + a) + (a + c) + (x * c) + (e * e));
		String resultado23 = "";
		resultado23 = resultado23 + ((x / e) + (c * b) + (y / e));
		resultado23 = resultado23 + ((x + x) + (a + z) + (b * e) + (d - x) + (b * x));
		resultado23 = resultado23 + ((d + e) + (a / c) + (x / z) + (b + y));
		resultado23 = resultado23 + ((z + z) + (a + c) + (d - a));
		String resultado24 = "";
		resultado24 = resultado24 + ((d * a) + (e / a) + (a + y));
		resultado24 = resultado24 + ((b / z) + (d - c) + (x - x) + (y + x) + (b / b));
		resultado24 = resultado24 + ((c / z) + (x / c) + (c / b) + (b / b));
		String resultado25 = "";
		resultado25 = resultado25 + ((c * d) + (e / b) + (d / e) + (c * e));
		resultado25 = resultado25 + ((b + a) + (a * a) + (e * e));
		resultado25 = resultado25 + ((y - c) + (d + y) + (x + z));
		String resultado26 = "";
		resultado26 = resultado26 + ((y / a) + (x - b) + (a / a));
		resultado26 = resultado26 + ((z * z) + (b / c) + (d / x) + (x + y) + (d - a));
		resultado26 = resultado26 + ((c * y) + (z + c) + (e - c) + (x * x) + (a + c));
		resultado26 = resultado26 + ((a * d) + (e - a) + (a / y) + (e * z) + (y + x));
		String resultado27 = "";
		resultado27 = resultado27 + ((y + b) + (y / y) + (b * z) + (c - b));
		resultado27 = resultado27 + ((e * c) + (z - e) + (a - z));
		resultado27 = resultado27 + ((e + x) + (e - x) + (z / e));
		resultado27 = resultado27 + ((d + a) + (a / x) + (e + e) + (b - y) + (e - b));
		String resultado28 = "";
		resultado28 = resultado28 + ((a * c) + (y + d) + (z * a) + (a + a) + (e + y));
		resultado28 = resultado28 + ((x - e) + (a / d) + (c + a) + (c - x));
		resultado28 = resultado28 + ((d / a) + (c + e) + (z * z));
		resultado28 = resultado28 + ((x + d) + (d - b) + (x - d));
		resultado28 = resultado28 + ((d * d) + (a + d) + (x / y) + (d - z));
		String resultado29 = "";
		resultado29 = resultado29 + ((e + d) + (e / a) + (d + z));
		resultado29 = resultado29 + ((y - b) + (z - y) + (a + c) + (x * e) + (z - c));
		resultado29 = resultado29 + ((z - y) + (e + e) + (a / y) + (d - y));
		resultado29 = resultado29 + ((x / b) + (b * d) + (e - x));
		String resultado30 = "";
		resultado30 = resultado30 + ((c / e) + (e * e) + (c * e));
		resultado30 = resultado30 + ((b + d) + (x - z) + (a + a) + (z + c));
		resultado30 = resultado30 + ((a - c) + (e / z) + (y * e) + (a + d) + (c + x));
		resultado30 = resultado30 + ((a - c) + (a - c) + (y * c));
		String resultado31 = "";
		resultado31 = resultado31 + ((x * a) + (c * x) + (y / y) + (e * c));
		resultado31 = resultado31 + ((b - z) + (e + x) + (e / y));
		resultado31 = resultado31 + ((c * c) + (y * y) + (z + d));
		resultado31 = resultado31 + ((a / c) + (z + x) + (e + z) + (d / b) + (d / e));
		String resultado32 = "";
		resultado32 = resultado32 + ((y - d) + (z / z) + (d / y) + (x + d));
		resultado32 = resultado32 + ((x / e) + (e - z) + (c * y) + (y * b) + (a / a));
		resultado32 = resultado32 + ((y / b) + (x / z) + (c + e));
		resultado32 = resultado32 + ((b - z) + (d - y) + (d + b));
		resultado32 = resultado32 + ((a + e) + (x * a) + (z / a) + (e / b) + (c + d));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}