package br.com.av1.prova20;

public class Questao4 {
	public static void main(String[] args) {
		int a = 7;
		int b = 1;
		int c = 5;
		int d = 2;
		int e = 2;
		int x = 10;
		int y = 1;
		int z = 6;

		String resultado1 = "";
		resultado1 = resultado1 + ((e / e) + (b * a) + (x * c));
		resultado1 = resultado1 + ((e / c) + (z + b) + (d - e) + (x * d));
		resultado1 = resultado1 + ((z + a) + (d + c) + (c - c));
		String resultado2 = "";
		resultado2 = resultado2 + ((z * b) + (x - y) + (c / y));
		resultado2 = resultado2 + ((d / z) + (c - d) + (d - y) + (x / a) + (b / e));
		resultado2 = resultado2 + ((y - x) + (a * y) + (x / b) + (y * a));
		String resultado3 = "";
		resultado3 = resultado3 + ((b - b) + (e + z) + (z * z) + (x / c) + (c - x));
		resultado3 = resultado3 + ((x + a) + (e - a) + (b - x));
		resultado3 = resultado3 + ((z + y) + (x / z) + (y + y) + (c - c));
		String resultado4 = "";
		resultado4 = resultado4 + ((x + b) + (z * c) + (a - b) + (e + c) + (d - y));
		resultado4 = resultado4 + ((c / d) + (d * y) + (c / d));
		resultado4 = resultado4 + ((b + z) + (a - b) + (b * b) + (e * a) + (a * b));
		resultado4 = resultado4 + ((e - y) + (y / y) + (c - e));
		String resultado5 = "";
		resultado5 = resultado5 + ((a - c) + (y - e) + (a - b) + (x * z));
		resultado5 = resultado5 + ((x + b) + (e + x) + (z * a) + (z - c));
		resultado5 = resultado5 + ((b * x) + (e / b) + (d * y) + (y * z));
		resultado5 = resultado5 + ((y + d) + (b - z) + (b + z) + (e * z));
		String resultado6 = "";
		resultado6 = resultado6 + ((b + d) + (y / z) + (x + e));
		resultado6 = resultado6 + ((b / y) + (y / c) + (e * d) + (a + x));
		resultado6 = resultado6 + ((y + b) + (b * a) + (c * z) + (z / c));
		resultado6 = resultado6 + ((b / y) + (y * d) + (a * b));
		resultado6 = resultado6 + ((d / x) + (c / d) + (z * y) + (b / e));
		String resultado7 = "";
		resultado7 = resultado7 + ((e / x) + (x / c) + (c - y) + (b * c));
		resultado7 = resultado7 + ((x * e) + (b * x) + (z * e));
		resultado7 = resultado7 + ((d / z) + (b / y) + (b * z));
		resultado7 = resultado7 + ((e * b) + (a - e) + (e / y) + (y - z));
		resultado7 = resultado7 + ((a - e) + (y + x) + (b + d) + (e / z));
		String resultado8 = "";
		resultado8 = resultado8 + ((z * d) + (b + a) + (y + y) + (b - x));
		resultado8 = resultado8 + ((z * x) + (x - c) + (z + e));
		resultado8 = resultado8 + ((b + d) + (b + x) + (e * y) + (a / a));
		resultado8 = resultado8 + ((x * x) + (e + e) + (a - d) + (x * z));
		resultado8 = resultado8 + ((z / e) + (e + a) + (z + b));
		String resultado9 = "";
		resultado9 = resultado9 + ((b / x) + (b - c) + (z - y));
		resultado9 = resultado9 + ((c - z) + (d - c) + (e + y));
		resultado9 = resultado9 + ((c + z) + (c + z) + (y / c) + (e / c));
		resultado9 = resultado9 + ((e - z) + (e / c) + (c - e) + (b * z) + (z + d));
		String resultado10 = "";
		resultado10 = resultado10 + ((b + y) + (b + x) + (z * a) + (b / c));
		resultado10 = resultado10 + ((z - c) + (x + d) + (d + z));
		resultado10 = resultado10 + ((d + b) + (c * b) + (e + x) + (x / e) + (c / e));
		resultado10 = resultado10 + ((d / z) + (d - z) + (d + z) + (y - e) + (d / e));
		resultado10 = resultado10 + ((d - e) + (y + e) + (c - e) + (x / x));
		String resultado11 = "";
		resultado11 = resultado11 + ((y - c) + (e * d) + (c * b) + (x + y) + (a * z));
		resultado11 = resultado11 + ((a * a) + (a / x) + (b - x) + (z + e) + (c / c));
		resultado11 = resultado11 + ((c - x) + (e - y) + (c + c) + (c / e) + (b * y));
		String resultado12 = "";
		resultado12 = resultado12 + ((d - e) + (a - y) + (z + e));
		resultado12 = resultado12 + ((y + a) + (d - x) + (c * z));
		resultado12 = resultado12 + ((x - d) + (z + y) + (c * a) + (z * a));
		String resultado13 = "";
		resultado13 = resultado13 + ((y - z) + (z * y) + (e / y) + (y / e));
		resultado13 = resultado13 + ((d / x) + (x + b) + (x * x));
		resultado13 = resultado13 + ((x - b) + (x + d) + (b + b) + (a * z));
		resultado13 = resultado13 + ((d * x) + (y * a) + (c / x));
		resultado13 = resultado13 + ((a + d) + (z + x) + (z * c) + (x / a) + (b / y));
		String resultado14 = "";
		resultado14 = resultado14 + ((c / e) + (a * a) + (a - a) + (e + z) + (z * c));
		resultado14 = resultado14 + ((z * z) + (b / c) + (d + b));
		resultado14 = resultado14 + ((y / y) + (c * c) + (y + b));
		resultado14 = resultado14 + ((b + y) + (x / z) + (y - d) + (c / y));
		resultado14 = resultado14 + ((x - x) + (z * y) + (z * z) + (y + z));
		String resultado15 = "";
		resultado15 = resultado15 + ((d + x) + (e + b) + (e * a) + (c * c) + (c + z));
		resultado15 = resultado15 + ((z / c) + (e - x) + (d * z) + (d / y) + (y + c));
		resultado15 = resultado15 + ((x * d) + (e - y) + (b - e) + (e * a) + (z * e));
		resultado15 = resultado15 + ((y + e) + (e * z) + (z - b) + (b + e));
		String resultado16 = "";
		resultado16 = resultado16 + ((d * c) + (x / x) + (c - z) + (e - a));
		resultado16 = resultado16 + ((x - b) + (y - e) + (y - e) + (y / y) + (d / a));
		resultado16 = resultado16 + ((x * b) + (a + c) + (b / b) + (x - c));
		resultado16 = resultado16 + ((c - b) + (b + x) + (e / z));
		String resultado17 = "";
		resultado17 = resultado17 + ((a + e) + (y + y) + (x * x));
		resultado17 = resultado17 + ((z / c) + (d - b) + (e - b));
		resultado17 = resultado17 + ((c * e) + (b + e) + (e + e) + (z * d) + (d + b));
		String resultado18 = "";
		resultado18 = resultado18 + ((c * z) + (c + d) + (d / e) + (z - z));
		resultado18 = resultado18 + ((x - e) + (d - b) + (z * d));
		resultado18 = resultado18 + ((z / a) + (z * e) + (d / c));
		resultado18 = resultado18 + ((x / x) + (x * d) + (d + b) + (c - x));
		String resultado19 = "";
		resultado19 = resultado19 + ((y + x) + (b * b) + (b * c));
		resultado19 = resultado19 + ((c * c) + (z / a) + (d / c) + (e + y));
		resultado19 = resultado19 + ((z - x) + (x - d) + (z * z));
		resultado19 = resultado19 + ((c * c) + (b / a) + (a - e) + (y / c));
		resultado19 = resultado19 + ((e - y) + (a + b) + (y - y) + (d - c));
		String resultado20 = "";
		resultado20 = resultado20 + ((a - d) + (a * b) + (b - d) + (y + b));
		resultado20 = resultado20 + ((a - c) + (x * z) + (y + z) + (e * b) + (b * c));
		resultado20 = resultado20 + ((a / z) + (c + b) + (x + z) + (y + y));
		resultado20 = resultado20 + ((a / y) + (d - a) + (e - a) + (z * x) + (b - e));
		String resultado21 = "";
		resultado21 = resultado21 + ((b / b) + (z / d) + (y - x) + (e + e) + (e / b));
		resultado21 = resultado21 + ((d / x) + (a + e) + (y + d));
		resultado21 = resultado21 + ((d - y) + (c * a) + (b - b) + (e + x) + (x / z));
		resultado21 = resultado21 + ((b - x) + (c + e) + (x - b));
		resultado21 = resultado21 + ((b + b) + (x * z) + (y * a));
		String resultado22 = "";
		resultado22 = resultado22 + ((x / x) + (b + b) + (a * b) + (e * b) + (d - c));
		resultado22 = resultado22 + ((z / d) + (e * z) + (a - e) + (x / y) + (x + z));
		resultado22 = resultado22 + ((a - z) + (z * b) + (c / e) + (a * x));
		resultado22 = resultado22 + ((e + z) + (a / c) + (x - d) + (a + z));
		resultado22 = resultado22 + ((c / y) + (c + x) + (c * c) + (e / d) + (y + c));
		String resultado23 = "";
		resultado23 = resultado23 + ((d - d) + (z * y) + (d / e) + (b / b) + (x / y));
		resultado23 = resultado23 + ((c + y) + (a * e) + (a - c) + (z * b) + (a * e));
		resultado23 = resultado23 + ((b * a) + (e / c) + (d - x) + (d + c) + (c - y));
		resultado23 = resultado23 + ((a + y) + (b / x) + (b + a) + (y - y));
		resultado23 = resultado23 + ((x + c) + (a + z) + (y - d));
		String resultado24 = "";
		resultado24 = resultado24 + ((a * d) + (e / e) + (e * y) + (e / b) + (e + e));
		resultado24 = resultado24 + ((a / x) + (x / y) + (e - d) + (x - y) + (c - d));
		resultado24 = resultado24 + ((x + y) + (e * x) + (a * b) + (z * y));
		resultado24 = resultado24 + ((b + c) + (d / b) + (b - y));
		resultado24 = resultado24 + ((x + x) + (c / e) + (e - y));
		String resultado25 = "";
		resultado25 = resultado25 + ((a - c) + (a * c) + (z * y) + (z / b) + (c - y));
		resultado25 = resultado25 + ((e + b) + (e - y) + (d / a) + (x * e) + (e / c));
		resultado25 = resultado25 + ((y - y) + (d + d) + (z + a));
		String resultado26 = "";
		resultado26 = resultado26 + ((x * d) + (e - y) + (c / e) + (c / d) + (a / e));
		resultado26 = resultado26 + ((c + e) + (a / z) + (z + d));
		resultado26 = resultado26 + ((b / d) + (b - y) + (d - x) + (b + b));
		resultado26 = resultado26 + ((y - c) + (b / d) + (c + x) + (c - e));
		String resultado27 = "";
		resultado27 = resultado27 + ((d / b) + (b / e) + (x + z));
		resultado27 = resultado27 + ((c - b) + (y / c) + (z - d) + (x + c));
		resultado27 = resultado27 + ((y / c) + (d - e) + (x - e) + (b / b) + (y + d));
		String resultado28 = "";
		resultado28 = resultado28 + ((e - c) + (c * y) + (y * e) + (y + x));
		resultado28 = resultado28 + ((d * c) + (c / b) + (d + d) + (e + x) + (x + z));
		resultado28 = resultado28 + ((e - y) + (z * d) + (z + d) + (x / z) + (d * x));
		resultado28 = resultado28 + ((c / d) + (z - c) + (b / y) + (b / x));
		String resultado29 = "";
		resultado29 = resultado29 + ((a / b) + (x / a) + (c + a) + (c - x) + (e * z));
		resultado29 = resultado29 + ((c - b) + (e / e) + (z * e));
		resultado29 = resultado29 + ((d + y) + (c * x) + (e - x) + (y + z) + (x - y));
		String resultado30 = "";
		resultado30 = resultado30 + ((x - e) + (d - d) + (c - y) + (c + z) + (z - d));
		resultado30 = resultado30 + ((a + x) + (c * e) + (a / e) + (d * y));
		resultado30 = resultado30 + ((c + x) + (y + b) + (d - e) + (d - z));
		resultado30 = resultado30 + ((d / y) + (b / a) + (x + b) + (y + d) + (b * b));
		resultado30 = resultado30 + ((a - b) + (d - b) + (d - e) + (d + y));
		String resultado31 = "";
		resultado31 = resultado31 + ((z - y) + (e + x) + (y - a) + (c - e) + (a + b));
		resultado31 = resultado31 + ((b / d) + (z * c) + (b * y) + (a + y) + (x / x));
		resultado31 = resultado31 + ((x * b) + (d / a) + (z + d));
		resultado31 = resultado31 + ((x / e) + (y - c) + (b / a) + (z - z) + (b - a));
		resultado31 = resultado31 + ((z * c) + (b - y) + (x / b));
		String resultado32 = "";
		resultado32 = resultado32 + ((x - x) + (z * z) + (a - d) + (e - c) + (d / e));
		resultado32 = resultado32 + ((d + d) + (e * a) + (b + b) + (a - a));
		resultado32 = resultado32 + ((z - e) + (d * a) + (d * b) + (c / x) + (c + x));
		resultado32 = resultado32 + ((d - z) + (d * c) + (y / c));
		resultado32 = resultado32 + ((a - e) + (d - b) + (y / y));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}