package br.com.av1.prova08;

public class Questao4 {
	public static void main(String[] args) {
		int a = 4;
		int b = 9;
		int c = 2;
		int d = 6;
		int e = 7;
		int x = 1;
		int y = 6;
		int z = 7;

		String resultado1 = "";
		resultado1 = resultado1 + ((z * b) + (a * z) + (z + e) + (z * z));
		resultado1 = resultado1 + ((y * b) + (e * e) + (y + e) + (y - z) + (d * b));
		resultado1 = resultado1 + ((c / b) + (b - b) + (c - b));
		resultado1 = resultado1 + ((b * d) + (y / x) + (x + c) + (a + z));
		String resultado2 = "";
		resultado2 = resultado2 + ((a - y) + (e * z) + (d - y) + (x - y));
		resultado2 = resultado2 + ((y - e) + (x + e) + (d / x) + (a / b));
		resultado2 = resultado2 + ((b / z) + (d - z) + (e / y) + (b / a));
		resultado2 = resultado2 + ((x / z) + (e + y) + (y + y) + (e / b));
		resultado2 = resultado2 + ((c + a) + (e + y) + (y * c) + (c - x));
		String resultado3 = "";
		resultado3 = resultado3 + ((y - e) + (e + z) + (a + z) + (c - z) + (x + c));
		resultado3 = resultado3 + ((x * y) + (a - z) + (z + e) + (c / e));
		resultado3 = resultado3 + ((x - y) + (z + x) + (x - b) + (e + d));
		resultado3 = resultado3 + ((d / y) + (d + z) + (c * y));
		String resultado4 = "";
		resultado4 = resultado4 + ((b - c) + (x / y) + (x - a));
		resultado4 = resultado4 + ((d + z) + (e - a) + (e / a));
		resultado4 = resultado4 + ((x - c) + (c - d) + (e + z) + (e * b));
		resultado4 = resultado4 + ((x - b) + (z / y) + (b - e) + (a * c) + (x - c));
		String resultado5 = "";
		resultado5 = resultado5 + ((a - x) + (b / x) + (c / x) + (e / a));
		resultado5 = resultado5 + ((x * y) + (a - b) + (a + e));
		resultado5 = resultado5 + ((x + a) + (z - e) + (b + c) + (x / c));
		resultado5 = resultado5 + ((e * x) + (b - e) + (z + c) + (a + a));
		resultado5 = resultado5 + ((y + y) + (c / d) + (c + e) + (x * b) + (d - d));
		String resultado6 = "";
		resultado6 = resultado6 + ((a + z) + (x + b) + (x * y) + (x + x));
		resultado6 = resultado6 + ((b + e) + (c + d) + (x * e));
		resultado6 = resultado6 + ((x / x) + (x - c) + (d + b));
		resultado6 = resultado6 + ((x - d) + (c * d) + (b / a) + (d * e));
		String resultado7 = "";
		resultado7 = resultado7 + ((x + e) + (d * x) + (x * c) + (b + y));
		resultado7 = resultado7 + ((z / d) + (b + y) + (b - c));
		resultado7 = resultado7 + ((e * a) + (d * b) + (c - x));
		String resultado8 = "";
		resultado8 = resultado8 + ((x + a) + (a * b) + (x + b) + (c / z) + (c + x));
		resultado8 = resultado8 + ((x - a) + (c - a) + (z / x) + (b / c));
		resultado8 = resultado8 + ((d / a) + (z - e) + (z + c));
		resultado8 = resultado8 + ((b / c) + (y * z) + (c + y) + (e - b) + (c + y));
		resultado8 = resultado8 + ((z + c) + (y - a) + (a + y) + (z - y));
		String resultado9 = "";
		resultado9 = resultado9 + ((y * b) + (x / x) + (e + z) + (c / d) + (e + d));
		resultado9 = resultado9 + ((y - c) + (b - b) + (e + c));
		resultado9 = resultado9 + ((c - b) + (a + z) + (d + c));
		String resultado10 = "";
		resultado10 = resultado10 + ((d - d) + (a + z) + (x * z));
		resultado10 = resultado10 + ((c - x) + (d / d) + (y * d) + (b - d));
		resultado10 = resultado10 + ((e - a) + (c + z) + (x - d) + (z - z));
		String resultado11 = "";
		resultado11 = resultado11 + ((d * x) + (a * d) + (a / b));
		resultado11 = resultado11 + ((x - e) + (b / y) + (b / c));
		resultado11 = resultado11 + ((c / a) + (a * z) + (z + b) + (b / y));
		resultado11 = resultado11 + ((x / c) + (e * e) + (y * z));
		resultado11 = resultado11 + ((x + c) + (a + b) + (a * c) + (y - x));
		String resultado12 = "";
		resultado12 = resultado12 + ((d / a) + (e - b) + (x - z) + (a / d) + (z * c));
		resultado12 = resultado12 + ((y / x) + (a * y) + (a + b));
		resultado12 = resultado12 + ((x / b) + (d - z) + (e - b) + (c - c) + (z * y));
		resultado12 = resultado12 + ((y / c) + (b + y) + (d - c));
		resultado12 = resultado12 + ((x / x) + (d / d) + (y + y) + (d / y));
		String resultado13 = "";
		resultado13 = resultado13 + ((d / d) + (a / x) + (d * a) + (e / d) + (d + c));
		resultado13 = resultado13 + ((y / x) + (a + e) + (y * z) + (c * z) + (z + b));
		resultado13 = resultado13 + ((c - b) + (y - y) + (z / z) + (x + z) + (e - z));
		resultado13 = resultado13 + ((z / d) + (d - x) + (x * e) + (c * x) + (e / c));
		String resultado14 = "";
		resultado14 = resultado14 + ((d + d) + (d * z) + (b / c) + (x * b));
		resultado14 = resultado14 + ((z * b) + (a - x) + (y * x) + (z - y));
		resultado14 = resultado14 + ((d / e) + (y / x) + (z * b) + (b / y) + (z / b));
		resultado14 = resultado14 + ((b / e) + (d * y) + (y + e));
		String resultado15 = "";
		resultado15 = resultado15 + ((b * d) + (z * a) + (a * a));
		resultado15 = resultado15 + ((e * a) + (e * a) + (y / b) + (a + d));
		resultado15 = resultado15 + ((d / b) + (x + e) + (b - y) + (e - c) + (z + a));
		resultado15 = resultado15 + ((x / y) + (a + y) + (x - y));
		String resultado16 = "";
		resultado16 = resultado16 + ((z + z) + (x * e) + (c / d) + (y / e));
		resultado16 = resultado16 + ((y + z) + (b / b) + (x + z));
		resultado16 = resultado16 + ((x + e) + (a * b) + (b * a) + (b / y) + (x * c));
		String resultado17 = "";
		resultado17 = resultado17 + ((x - e) + (d - y) + (y * c) + (d / d) + (d * c));
		resultado17 = resultado17 + ((x - c) + (y - z) + (d + x));
		resultado17 = resultado17 + ((e * x) + (e + e) + (d - e));
		String resultado18 = "";
		resultado18 = resultado18 + ((a * c) + (z + b) + (c * e));
		resultado18 = resultado18 + ((e / y) + (x * y) + (y + b));
		resultado18 = resultado18 + ((d / a) + (b * b) + (a * y) + (a - x) + (z + z));
		String resultado19 = "";
		resultado19 = resultado19 + ((d * b) + (z * b) + (c * c) + (c + x) + (x - c));
		resultado19 = resultado19 + ((c / y) + (y * a) + (d / y) + (c - z) + (y + e));
		resultado19 = resultado19 + ((c + b) + (c * b) + (c / b) + (d / b) + (z - b));
		String resultado20 = "";
		resultado20 = resultado20 + ((d - y) + (e - b) + (d - x));
		resultado20 = resultado20 + ((a / a) + (a - a) + (d + e) + (c / e) + (z * x));
		resultado20 = resultado20 + ((a / e) + (y * c) + (c - c) + (e - a) + (z + a));
		resultado20 = resultado20 + ((d + x) + (z - x) + (c - b) + (x + y) + (d + d));
		String resultado21 = "";
		resultado21 = resultado21 + ((b - d) + (z - e) + (x / d) + (b * e) + (z + c));
		resultado21 = resultado21 + ((x * z) + (x + e) + (z + d) + (a / y) + (e - y));
		resultado21 = resultado21 + ((d * x) + (b / y) + (b + b) + (e + z));
		String resultado22 = "";
		resultado22 = resultado22 + ((a * a) + (b / d) + (c - b));
		resultado22 = resultado22 + ((c * a) + (d / y) + (b * z));
		resultado22 = resultado22 + ((b / b) + (y + d) + (b * a) + (b + a));
		resultado22 = resultado22 + ((y - y) + (a - y) + (e - e) + (y * e));
		resultado22 = resultado22 + ((b + e) + (e * a) + (e + a) + (y * a));
		String resultado23 = "";
		resultado23 = resultado23 + ((d / x) + (x + e) + (x / y));
		resultado23 = resultado23 + ((e / y) + (z * z) + (c + c) + (a / b));
		resultado23 = resultado23 + ((y / b) + (c * z) + (e + y) + (x + c));
		resultado23 = resultado23 + ((z - c) + (x + b) + (x - x));
		resultado23 = resultado23 + ((d - z) + (x * b) + (e * a) + (y * z));
		String resultado24 = "";
		resultado24 = resultado24 + ((a - a) + (x / x) + (z + z));
		resultado24 = resultado24 + ((b * z) + (x / d) + (c * a));
		resultado24 = resultado24 + ((b * d) + (d / y) + (x - c) + (b - b) + (c * e));
		resultado24 = resultado24 + ((x - y) + (a + a) + (d - y) + (x * z));
		resultado24 = resultado24 + ((z / b) + (z / d) + (y / e) + (c + y));
		String resultado25 = "";
		resultado25 = resultado25 + ((x / y) + (e + d) + (b + a) + (a + y) + (y + e));
		resultado25 = resultado25 + ((b + e) + (c - x) + (a - x) + (z + e) + (x / e));
		resultado25 = resultado25 + ((d + x) + (e - y) + (x * z) + (b - e) + (c - a));
		resultado25 = resultado25 + ((c * d) + (a * a) + (b * b) + (d / y) + (d * b));
		resultado25 = resultado25 + ((y - e) + (b / c) + (e * c) + (z - c));
		String resultado26 = "";
		resultado26 = resultado26 + ((e - z) + (e * e) + (z + a));
		resultado26 = resultado26 + ((d + e) + (b - b) + (x / d) + (y * c));
		resultado26 = resultado26 + ((e - a) + (c / x) + (c + d));
		resultado26 = resultado26 + ((z / z) + (d / z) + (x + c) + (c - d) + (e + c));
		String resultado27 = "";
		resultado27 = resultado27 + ((x + x) + (a * b) + (b - d) + (y / z));
		resultado27 = resultado27 + ((e + d) + (e * z) + (a * y));
		resultado27 = resultado27 + ((d - x) + (c + y) + (a - b) + (a + z) + (z / d));
		resultado27 = resultado27 + ((x / z) + (y + e) + (z * x));
		String resultado28 = "";
		resultado28 = resultado28 + ((b / a) + (b * c) + (b - c) + (a - c) + (a * c));
		resultado28 = resultado28 + ((x + x) + (x / a) + (z - a));
		resultado28 = resultado28 + ((y * x) + (a + e) + (c + e) + (d + d));
		String resultado29 = "";
		resultado29 = resultado29 + ((z * y) + (d * d) + (z + z));
		resultado29 = resultado29 + ((e + a) + (a + b) + (c / x) + (z * e) + (d * y));
		resultado29 = resultado29 + ((d / x) + (a + b) + (y + x) + (e - z));
		resultado29 = resultado29 + ((d + b) + (z + e) + (y / y) + (c * y) + (a + z));
		resultado29 = resultado29 + ((c - b) + (e / y) + (z + a) + (c - e));
		String resultado30 = "";
		resultado30 = resultado30 + ((d + z) + (b / d) + (a + d) + (a + z));
		resultado30 = resultado30 + ((y * y) + (e - x) + (y + e) + (x - e));
		resultado30 = resultado30 + ((e * c) + (y * d) + (c / y));
		resultado30 = resultado30 + ((x / y) + (a - y) + (x - a) + (x * d));
		String resultado31 = "";
		resultado31 = resultado31 + ((e + d) + (a / a) + (x * z) + (x / a) + (d + b));
		resultado31 = resultado31 + ((z - x) + (b - d) + (c + d) + (x / z) + (c * x));
		resultado31 = resultado31 + ((e + b) + (c / b) + (a * e));
		resultado31 = resultado31 + ((b + x) + (y / a) + (e + a) + (y - c) + (c + e));
		resultado31 = resultado31 + ((a - c) + (d * y) + (d + a));
		String resultado32 = "";
		resultado32 = resultado32 + ((c * c) + (a + e) + (x - c) + (b + y) + (z + b));
		resultado32 = resultado32 + ((e / d) + (a - z) + (c * c));
		resultado32 = resultado32 + ((a + x) + (a * y) + (z - c) + (a / e) + (a * d));
		resultado32 = resultado32 + ((d / z) + (e / c) + (z + b));
		resultado32 = resultado32 + ((z / x) + (a + x) + (y + d));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}