package br.com.av1.prova23;

public class Questao4 {
	public static void main(String[] args) {
		int a = 3;
		int b = 4;
		int c = 3;
		int d = 9;
		int e = 3;
		int x = 8;
		int y = 10;
		int z = 7;

		String resultado1 = "";
		resultado1 = resultado1 + ((x / c) + (c / c) + (e / e));
		resultado1 = resultado1 + ((d / d) + (x / e) + (e + e) + (x * d));
		resultado1 = resultado1 + ((z / c) + (c / x) + (a / x));
		resultado1 = resultado1 + ((a + b) + (c + c) + (d - d) + (a + x));
		resultado1 = resultado1 + ((z * e) + (b / c) + (a - c) + (z * z));
		String resultado2 = "";
		resultado2 = resultado2 + ((x * d) + (x + a) + (x / e) + (d * z));
		resultado2 = resultado2 + ((d + x) + (x * b) + (x / d) + (d * c) + (b * c));
		resultado2 = resultado2 + ((c * d) + (c * e) + (y + x));
		resultado2 = resultado2 + ((z / d) + (c * x) + (a / a) + (z - c) + (d * x));
		resultado2 = resultado2 + ((b - d) + (z - a) + (x - a) + (y / c) + (x * y));
		String resultado3 = "";
		resultado3 = resultado3 + ((e + y) + (d * d) + (c * y) + (d * e) + (d / e));
		resultado3 = resultado3 + ((y * c) + (z / y) + (y - c));
		resultado3 = resultado3 + ((b + a) + (c * y) + (a - c) + (x * x) + (e - c));
		String resultado4 = "";
		resultado4 = resultado4 + ((c + e) + (x + a) + (a + x) + (z / b) + (d / z));
		resultado4 = resultado4 + ((b / e) + (a + b) + (d / d));
		resultado4 = resultado4 + ((a / z) + (z + y) + (a * c) + (e * x));
		resultado4 = resultado4 + ((c / e) + (d * e) + (c - e) + (b - z));
		String resultado5 = "";
		resultado5 = resultado5 + ((x + y) + (d * x) + (c - z) + (c * x));
		resultado5 = resultado5 + ((a * z) + (y / d) + (b + z));
		resultado5 = resultado5 + ((e - x) + (x * x) + (z - x));
		resultado5 = resultado5 + ((z * b) + (b / x) + (b / c));
		String resultado6 = "";
		resultado6 = resultado6 + ((a - z) + (a - x) + (c - e) + (e + y));
		resultado6 = resultado6 + ((z * e) + (e * z) + (a + x) + (a * b));
		resultado6 = resultado6 + ((y / z) + (e + e) + (a - y));
		resultado6 = resultado6 + ((b / y) + (y / e) + (z * d) + (e - y));
		String resultado7 = "";
		resultado7 = resultado7 + ((a * c) + (b - e) + (z - x) + (z + c) + (a / a));
		resultado7 = resultado7 + ((b + d) + (d / z) + (e + d) + (e * y) + (x - b));
		resultado7 = resultado7 + ((e * a) + (y + b) + (z - b));
		resultado7 = resultado7 + ((x * c) + (a / z) + (y - d) + (c - e) + (b + a));
		resultado7 = resultado7 + ((z - x) + (d / z) + (a * e) + (x + z));
		String resultado8 = "";
		resultado8 = resultado8 + ((c / b) + (x + e) + (b + c) + (c - b) + (e + x));
		resultado8 = resultado8 + ((x / c) + (x * d) + (e * x) + (z / b));
		resultado8 = resultado8 + ((c + d) + (c * a) + (b - a) + (a - b));
		resultado8 = resultado8 + ((x / c) + (y / x) + (x * x) + (d * d));
		resultado8 = resultado8 + ((c / x) + (c - b) + (d / b) + (x + b) + (x * a));
		String resultado9 = "";
		resultado9 = resultado9 + ((x + z) + (e + z) + (d * x) + (c + y));
		resultado9 = resultado9 + ((x - x) + (z - y) + (d + d) + (d * z) + (y + z));
		resultado9 = resultado9 + ((y * z) + (c + c) + (c - d));
		String resultado10 = "";
		resultado10 = resultado10 + ((z - z) + (c - c) + (b - y));
		resultado10 = resultado10 + ((d * z) + (x + d) + (b * x));
		resultado10 = resultado10 + ((d / e) + (b - z) + (y / a) + (e * a) + (y * e));
		resultado10 = resultado10 + ((z - a) + (c + d) + (z - x));
		resultado10 = resultado10 + ((a * d) + (x * b) + (a * y));
		String resultado11 = "";
		resultado11 = resultado11 + ((b / x) + (y - d) + (d - y) + (d - z));
		resultado11 = resultado11 + ((b * x) + (y / c) + (a - b) + (a + x));
		resultado11 = resultado11 + ((b * x) + (d / y) + (a * a) + (y * x));
		resultado11 = resultado11 + ((e * a) + (z * z) + (d / y) + (y + e));
		String resultado12 = "";
		resultado12 = resultado12 + ((d - b) + (x * e) + (z + e) + (x * e));
		resultado12 = resultado12 + ((z - x) + (e / e) + (z / x) + (e * d) + (x + d));
		resultado12 = resultado12 + ((d / d) + (b * z) + (d - z));
		String resultado13 = "";
		resultado13 = resultado13 + ((z / c) + (e - a) + (d - c) + (d / y) + (y + z));
		resultado13 = resultado13 + ((b * b) + (b * x) + (e - x));
		resultado13 = resultado13 + ((y + y) + (b / z) + (e / b) + (a - c));
		resultado13 = resultado13 + ((d * x) + (x + b) + (e / c));
		String resultado14 = "";
		resultado14 = resultado14 + ((x - a) + (c / a) + (z - x) + (a * c));
		resultado14 = resultado14 + ((z * a) + (b * x) + (e / e) + (x - b));
		resultado14 = resultado14 + ((c * a) + (b + z) + (z * a) + (e - c));
		resultado14 = resultado14 + ((x * e) + (e / x) + (e * a) + (x * c));
		resultado14 = resultado14 + ((e + c) + (a - b) + (d / z) + (a - d));
		String resultado15 = "";
		resultado15 = resultado15 + ((d - c) + (a - c) + (e / y) + (c * c));
		resultado15 = resultado15 + ((a + d) + (a + x) + (c + d) + (e / e));
		resultado15 = resultado15 + ((x / d) + (x / a) + (x / a));
		resultado15 = resultado15 + ((c / d) + (x / z) + (c - c) + (x + e));
		resultado15 = resultado15 + ((a - y) + (x - d) + (d - z));
		String resultado16 = "";
		resultado16 = resultado16 + ((d - b) + (x + b) + (y - c) + (b + x));
		resultado16 = resultado16 + ((y - e) + (x * y) + (y * e));
		resultado16 = resultado16 + ((y * c) + (z * e) + (c - b));
		resultado16 = resultado16 + ((z - z) + (b * z) + (e + z) + (x + c) + (e / x));
		resultado16 = resultado16 + ((d + y) + (e + x) + (e / c) + (d * d) + (d + d));
		String resultado17 = "";
		resultado17 = resultado17 + ((c + z) + (d / a) + (z / y) + (a * y) + (b / y));
		resultado17 = resultado17 + ((z * y) + (y - e) + (a + z) + (y * z));
		resultado17 = resultado17 + ((b * b) + (c + z) + (b / a) + (c / b));
		resultado17 = resultado17 + ((a / a) + (z + d) + (b * x));
		String resultado18 = "";
		resultado18 = resultado18 + ((y * y) + (c * e) + (c * c) + (b - a) + (b * x));
		resultado18 = resultado18 + ((b * x) + (a * y) + (d + c) + (b - e));
		resultado18 = resultado18 + ((d + x) + (x * b) + (y + z) + (b * z));
		resultado18 = resultado18 + ((c * x) + (b * y) + (z - x) + (y - e));
		String resultado19 = "";
		resultado19 = resultado19 + ((b / c) + (b * a) + (b + d) + (y * e) + (e / y));
		resultado19 = resultado19 + ((d * d) + (e / e) + (z / b) + (e - c));
		resultado19 = resultado19 + ((y + b) + (d / x) + (z * d) + (b + d) + (d + z));
		resultado19 = resultado19 + ((b + a) + (b + x) + (b / d) + (y / e) + (b * y));
		resultado19 = resultado19 + ((a / z) + (x / e) + (a * a));
		String resultado20 = "";
		resultado20 = resultado20 + ((x / y) + (a + d) + (z + c) + (c + z));
		resultado20 = resultado20 + ((y - a) + (b / z) + (b / y));
		resultado20 = resultado20 + ((e - e) + (y / z) + (e - x));
		String resultado21 = "";
		resultado21 = resultado21 + ((x * e) + (e * d) + (c / y) + (y + b));
		resultado21 = resultado21 + ((a / e) + (c + d) + (e - a) + (a - z));
		resultado21 = resultado21 + ((b - e) + (b + x) + (x + y) + (x + z));
		resultado21 = resultado21 + ((c + d) + (b / e) + (a * c) + (e * z));
		String resultado22 = "";
		resultado22 = resultado22 + ((b / d) + (z - a) + (d + e) + (b + e));
		resultado22 = resultado22 + ((a + d) + (x + d) + (x * z));
		resultado22 = resultado22 + ((y * z) + (b / y) + (c * x) + (e / a));
		resultado22 = resultado22 + ((b * a) + (x / e) + (z / x));
		String resultado23 = "";
		resultado23 = resultado23 + ((e / d) + (x - y) + (y * d));
		resultado23 = resultado23 + ((a + x) + (c * z) + (c / e) + (y * z) + (x * b));
		resultado23 = resultado23 + ((d - a) + (y / d) + (d / y));
		resultado23 = resultado23 + ((b * d) + (b - a) + (c / a));
		resultado23 = resultado23 + ((a + y) + (b / c) + (x - x) + (x * b));
		String resultado24 = "";
		resultado24 = resultado24 + ((z - z) + (y * z) + (y * x) + (c - z));
		resultado24 = resultado24 + ((c + x) + (e + e) + (a / z));
		resultado24 = resultado24 + ((d + c) + (d / y) + (y / c));
		resultado24 = resultado24 + ((x - b) + (e * x) + (e / d));
		String resultado25 = "";
		resultado25 = resultado25 + ((e * c) + (d + z) + (b * z) + (z / b));
		resultado25 = resultado25 + ((c - y) + (d + z) + (c + e) + (b + b) + (d + b));
		resultado25 = resultado25 + ((c - y) + (z + x) + (d - x) + (c - d));
		String resultado26 = "";
		resultado26 = resultado26 + ((e - x) + (c - x) + (a - a) + (x * b));
		resultado26 = resultado26 + ((b + c) + (a / a) + (a / c) + (y + c));
		resultado26 = resultado26 + ((e * e) + (a * x) + (a - x) + (z - y));
		String resultado27 = "";
		resultado27 = resultado27 + ((d * z) + (x / c) + (b - a) + (a - a) + (e - y));
		resultado27 = resultado27 + ((a * x) + (z / c) + (d - b) + (c / a));
		resultado27 = resultado27 + ((e - x) + (z * a) + (b - x) + (b - b));
		resultado27 = resultado27 + ((b + d) + (z / e) + (e + z));
		String resultado28 = "";
		resultado28 = resultado28 + ((b * b) + (e - y) + (e / e));
		resultado28 = resultado28 + ((e * c) + (z - b) + (x + d) + (x * z) + (y / x));
		resultado28 = resultado28 + ((x * e) + (b * x) + (e / b) + (b - z));
		resultado28 = resultado28 + ((e - x) + (y - y) + (x * x) + (d * e));
		resultado28 = resultado28 + ((c * y) + (z + a) + (b - e));
		String resultado29 = "";
		resultado29 = resultado29 + ((d / x) + (c - d) + (y - x) + (x / e));
		resultado29 = resultado29 + ((z * y) + (c * z) + (e + x) + (b / a) + (c + z));
		resultado29 = resultado29 + ((z / d) + (x / y) + (z - e) + (a + b));
		resultado29 = resultado29 + ((c + z) + (y * e) + (x * z) + (d * y) + (b - e));
		resultado29 = resultado29 + ((x / x) + (d - a) + (z + a) + (c + b));
		String resultado30 = "";
		resultado30 = resultado30 + ((e / z) + (e - x) + (z / b));
		resultado30 = resultado30 + ((c - z) + (c + z) + (d + e) + (e - z) + (x / d));
		resultado30 = resultado30 + ((y / b) + (c * e) + (b + e) + (e * d));
		String resultado31 = "";
		resultado31 = resultado31 + ((c / b) + (x / b) + (c / a) + (b / z) + (c - b));
		resultado31 = resultado31 + ((y / x) + (c + c) + (b / d) + (a / a) + (x + x));
		resultado31 = resultado31 + ((d * x) + (c * y) + (d * a) + (x + d) + (a * c));
		String resultado32 = "";
		resultado32 = resultado32 + ((a * b) + (x + y) + (z * c) + (z / c) + (e / b));
		resultado32 = resultado32 + ((c + a) + (c - d) + (c / x) + (x + c) + (z / x));
		resultado32 = resultado32 + ((x + a) + (e + a) + (b / b) + (b - y) + (z - d));
		resultado32 = resultado32 + ((y / b) + (z + c) + (a / d) + (a / b) + (y * c));
		resultado32 = resultado32 + ((x + x) + (y + x) + (b * e));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}
