package br.com.av1.prova27;

public class Questao4 {
	public static void main(String[] args) {
		int a = 1;
		int b = 1;
		int c = 1;
		int d = 7;
		int e = 7;
		int x = 6;
		int y = 9;
		int z = 6;

		String resultado1 = "";
		resultado1 = resultado1 + ((x + x) + (c * e) + (c / d));
		resultado1 = resultado1 + ((x / z) + (c - c) + (a * b));
		resultado1 = resultado1 + ((c + y) + (b + z) + (b / b));
		resultado1 = resultado1 + ((a / d) + (c - a) + (x - z) + (x * a) + (b / y));
		String resultado2 = "";
		resultado2 = resultado2 + ((d - e) + (x * e) + (d / y) + (x + a) + (d - y));
		resultado2 = resultado2 + ((y + b) + (d - b) + (c * d));
		resultado2 = resultado2 + ((c * a) + (y - d) + (x - e) + (e - c));
		resultado2 = resultado2 + ((e - c) + (e + a) + (y - d));
		String resultado3 = "";
		resultado3 = resultado3 + ((y + z) + (e * z) + (b / c));
		resultado3 = resultado3 + ((d * d) + (a - c) + (d * y));
		resultado3 = resultado3 + ((a - c) + (d * c) + (x / c) + (c - y) + (z + z));
		String resultado4 = "";
		resultado4 = resultado4 + ((a + b) + (y + z) + (e + a));
		resultado4 = resultado4 + ((c - z) + (x + a) + (c / e) + (x + e));
		resultado4 = resultado4 + ((a + a) + (y - c) + (z + c) + (y * z));
		resultado4 = resultado4 + ((b / c) + (x + b) + (y + d) + (e / e) + (a - b));
		String resultado5 = "";
		resultado5 = resultado5 + ((y + x) + (z - a) + (a - e));
		resultado5 = resultado5 + ((z + b) + (a + b) + (c * y) + (c - e));
		resultado5 = resultado5 + ((z / x) + (x + z) + (x / c) + (x - b));
		String resultado6 = "";
		resultado6 = resultado6 + ((z + z) + (a - d) + (b - b));
		resultado6 = resultado6 + ((x * d) + (y * e) + (y + y));
		resultado6 = resultado6 + ((y + b) + (a / d) + (b + a));
		String resultado7 = "";
		resultado7 = resultado7 + ((b * c) + (z * a) + (e + b) + (d * z) + (a + x));
		resultado7 = resultado7 + ((c - y) + (c * e) + (a - z) + (y + y));
		resultado7 = resultado7 + ((z - e) + (a / a) + (e - c));
		resultado7 = resultado7 + ((y / b) + (z + y) + (z / z) + (y + c) + (y * x));
		String resultado8 = "";
		resultado8 = resultado8 + ((e * z) + (a - e) + (x * x) + (y + z) + (d / d));
		resultado8 = resultado8 + ((c * b) + (b - z) + (d / z) + (y + y));
		resultado8 = resultado8 + ((d / a) + (z + x) + (b - d) + (e / b) + (x / x));
		String resultado9 = "";
		resultado9 = resultado9 + ((d - d) + (d - z) + (b * z));
		resultado9 = resultado9 + ((y * b) + (b + e) + (y + x) + (c - z) + (a + a));
		resultado9 = resultado9 + ((z - x) + (y - c) + (c * a) + (e + y));
		resultado9 = resultado9 + ((e / d) + (c + e) + (x + c) + (x * z));
		resultado9 = resultado9 + ((b + y) + (y + b) + (d + d) + (e + x));
		String resultado10 = "";
		resultado10 = resultado10 + ((a + b) + (c + b) + (z - e) + (b * z) + (d / d));
		resultado10 = resultado10 + ((y / c) + (e - x) + (c * d) + (d / x) + (d - x));
		resultado10 = resultado10 + ((b * d) + (x * c) + (y + c));
		String resultado11 = "";
		resultado11 = resultado11 + ((a * e) + (x / c) + (x + x));
		resultado11 = resultado11 + ((x - d) + (b - d) + (x * c) + (a + a) + (y - c));
		resultado11 = resultado11 + ((y / e) + (c / c) + (b * x) + (c + c));
		String resultado12 = "";
		resultado12 = resultado12 + ((e / d) + (d + a) + (y + a) + (a - d));
		resultado12 = resultado12 + ((d / x) + (d + z) + (x * y));
		resultado12 = resultado12 + ((d + z) + (a - x) + (d - a) + (z / d) + (x - e));
		resultado12 = resultado12 + ((e + a) + (b * x) + (a * e));
		resultado12 = resultado12 + ((y + z) + (z / d) + (a - z) + (y * b));
		String resultado13 = "";
		resultado13 = resultado13 + ((c - e) + (d + y) + (b / x) + (a / b));
		resultado13 = resultado13 + ((b + e) + (x + c) + (x / z));
		resultado13 = resultado13 + ((e * c) + (z - z) + (z + e));
		resultado13 = resultado13 + ((e - b) + (e * a) + (e * c));
		String resultado14 = "";
		resultado14 = resultado14 + ((c - x) + (x - y) + (d - d) + (y + z) + (a * y));
		resultado14 = resultado14 + ((e + c) + (d / z) + (d / a));
		resultado14 = resultado14 + ((y / d) + (e * a) + (e - y));
		resultado14 = resultado14 + ((x / e) + (a - c) + (d - z));
		resultado14 = resultado14 + ((y * y) + (d - d) + (a + x) + (d + b));
		String resultado15 = "";
		resultado15 = resultado15 + ((z + y) + (d - z) + (y - x));
		resultado15 = resultado15 + ((e + e) + (c + d) + (b - y) + (d - z));
		resultado15 = resultado15 + ((d * d) + (z + x) + (d + d) + (z - a) + (c - a));
		resultado15 = resultado15 + ((c + b) + (z - x) + (d / a) + (b * z));
		resultado15 = resultado15 + ((a + a) + (e / d) + (c / c) + (e - z) + (e - c));
		String resultado16 = "";
		resultado16 = resultado16 + ((y * x) + (d * x) + (e - z) + (z - e) + (a - z));
		resultado16 = resultado16 + ((b + x) + (x * a) + (x + y) + (z / z) + (b * c));
		resultado16 = resultado16 + ((z + d) + (z * a) + (d - a));
		resultado16 = resultado16 + ((b - e) + (a / a) + (y / c) + (y * z));
		resultado16 = resultado16 + ((b * a) + (z + x) + (z - x) + (b * z) + (e * e));
		String resultado17 = "";
		resultado17 = resultado17 + ((d + z) + (z / y) + (z / d) + (b / e));
		resultado17 = resultado17 + ((x * a) + (a * z) + (c / d) + (d * e) + (c + e));
		resultado17 = resultado17 + ((a * x) + (b + x) + (d / d) + (z - y));
		resultado17 = resultado17 + ((a * x) + (b + z) + (y / y) + (x + b));
		resultado17 = resultado17 + ((c + b) + (z + z) + (e / e));
		String resultado18 = "";
		resultado18 = resultado18 + ((c + y) + (z - x) + (c / b));
		resultado18 = resultado18 + ((z * c) + (z / e) + (b / d) + (a / z) + (y + e));
		resultado18 = resultado18 + ((z / z) + (a * b) + (c * y) + (a * y) + (a - a));
		String resultado19 = "";
		resultado19 = resultado19 + ((y + a) + (y / x) + (d + d) + (z - a) + (e + z));
		resultado19 = resultado19 + ((e / x) + (a + z) + (b + c) + (y / e) + (y / x));
		resultado19 = resultado19 + ((e / c) + (c / b) + (c / z));
		resultado19 = resultado19 + ((a * e) + (z - z) + (b * d) + (e / z) + (x + b));
		resultado19 = resultado19 + ((e - d) + (b - d) + (b - d) + (b - c));
		String resultado20 = "";
		resultado20 = resultado20 + ((c + y) + (d / d) + (d * b));
		resultado20 = resultado20 + ((a / e) + (z * y) + (z / c) + (b - a));
		resultado20 = resultado20 + ((c * e) + (x * c) + (e / d) + (e + a) + (b + y));
		String resultado21 = "";
		resultado21 = resultado21 + ((b + z) + (d / d) + (a - b));
		resultado21 = resultado21 + ((e + x) + (y / y) + (e - a));
		resultado21 = resultado21 + ((y - z) + (y * a) + (y * e) + (x / x));
		resultado21 = resultado21 + ((b - a) + (d + c) + (z / y) + (d / c));
		String resultado22 = "";
		resultado22 = resultado22 + ((z * e) + (z / d) + (x / b) + (z - z) + (b - c));
		resultado22 = resultado22 + ((b / c) + (e - x) + (y * d) + (b * e));
		resultado22 = resultado22 + ((d / c) + (y - a) + (e - a) + (b * a));
		String resultado23 = "";
		resultado23 = resultado23 + ((x - b) + (b * z) + (y - x) + (e * x));
		resultado23 = resultado23 + ((y * z) + (c * x) + (a * z) + (x - b) + (b * a));
		resultado23 = resultado23 + ((z * a) + (d * x) + (d / y) + (c - a) + (b * y));
		resultado23 = resultado23 + ((b + b) + (a * y) + (e - z) + (x / d));
		String resultado24 = "";
		resultado24 = resultado24 + ((d / c) + (a - a) + (x - b) + (x - d));
		resultado24 = resultado24 + ((x * c) + (a - y) + (b - e) + (a + z) + (d - y));
		resultado24 = resultado24 + ((b * c) + (c * a) + (y * d) + (b - a));
		resultado24 = resultado24 + ((x * x) + (c - z) + (y + a) + (c * d));
		String resultado25 = "";
		resultado25 = resultado25 + ((x * c) + (d / y) + (y / a) + (y - b) + (x + a));
		resultado25 = resultado25 + ((e * e) + (y * c) + (x * b) + (a / d) + (y * e));
		resultado25 = resultado25 + ((y + e) + (b * x) + (c / e));
		String resultado26 = "";
		resultado26 = resultado26 + ((c * z) + (a + d) + (x + a) + (y - e));
		resultado26 = resultado26 + ((b / c) + (x - b) + (a - b));
		resultado26 = resultado26 + ((d - x) + (c - a) + (d - d) + (y - c) + (x / y));
		resultado26 = resultado26 + ((c * z) + (e * d) + (b - a) + (y - a));
		String resultado27 = "";
		resultado27 = resultado27 + ((b / a) + (c / a) + (x / z) + (y - x) + (y - y));
		resultado27 = resultado27 + ((x - b) + (a * y) + (z / d) + (a + b));
		resultado27 = resultado27 + ((x / d) + (z - x) + (c - b) + (d - z) + (b / d));
		resultado27 = resultado27 + ((e / b) + (d - z) + (a - x));
		String resultado28 = "";
		resultado28 = resultado28 + ((x + d) + (b - z) + (e / d) + (c * x));
		resultado28 = resultado28 + ((z * e) + (d * e) + (a - x));
		resultado28 = resultado28 + ((y / a) + (y / d) + (c + d) + (e + x));
		String resultado29 = "";
		resultado29 = resultado29 + ((a * y) + (c - y) + (x / a) + (b * e) + (d + y));
		resultado29 = resultado29 + ((x + y) + (b - a) + (x - x) + (c - b) + (d + b));
		resultado29 = resultado29 + ((x * e) + (x / z) + (c / d) + (c - e) + (b - a));
		resultado29 = resultado29 + ((e - d) + (a * x) + (e + b) + (b * a) + (a / z));
		resultado29 = resultado29 + ((y / b) + (e * d) + (z + d) + (d / y));
		String resultado30 = "";
		resultado30 = resultado30 + ((x / x) + (z / y) + (y - b) + (c / d));
		resultado30 = resultado30 + ((c - z) + (e - d) + (c * d));
		resultado30 = resultado30 + ((d - d) + (x + e) + (c * c));
		String resultado31 = "";
		resultado31 = resultado31 + ((z * y) + (z * b) + (c - d) + (e - c));
		resultado31 = resultado31 + ((x + e) + (c - e) + (y * d));
		resultado31 = resultado31 + ((d - e) + (d * d) + (a * c) + (x / b));
		resultado31 = resultado31 + ((b * b) + (d / c) + (e * y) + (b * e));
		String resultado32 = "";
		resultado32 = resultado32 + ((y - b) + (d * z) + (z + x));
		resultado32 = resultado32 + ((z - c) + (b * b) + (z - d));
		resultado32 = resultado32 + ((a * c) + (a - y) + (d + z) + (x + c));
		resultado32 = resultado32 + ((z * x) + (y - d) + (b - z) + (e - a) + (c * z));
		resultado32 = resultado32 + ((c * b) + (y / e) + (e / b) + (y - y));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}