package br.com.av1.prova24;

public class Questao4 {
	public static void main(String[] args) {
		int a = 4;
		int b = 5;
		int c = 2;
		int d = 2;
		int e = 3;
		int x = 1;
		int y = 2;
		int z = 3;

		String resultado1 = "";
		resultado1 = resultado1 + ((a * z) + (c + z) + (y - d));
		resultado1 = resultado1 + ((d * d) + (d - e) + (b * a) + (y / y) + (c / b));
		resultado1 = resultado1 + ((b * e) + (d * d) + (z - d) + (d * y));
		resultado1 = resultado1 + ((a + e) + (b - y) + (d * c) + (z + e) + (x + e));
		resultado1 = resultado1 + ((y * z) + (y * z) + (c + e) + (z * x) + (y * y));
		String resultado2 = "";
		resultado2 = resultado2 + ((x + z) + (c * c) + (e + a) + (y + e) + (b + a));
		resultado2 = resultado2 + ((y * x) + (x * z) + (b + x) + (z * y));
		resultado2 = resultado2 + ((y - c) + (e + b) + (z - e) + (c + a) + (z - x));
		resultado2 = resultado2 + ((c + x) + (y - c) + (d - z) + (b - a) + (z * x));
		resultado2 = resultado2 + ((c / x) + (x / d) + (b * z));
		String resultado3 = "";
		resultado3 = resultado3 + ((z + b) + (a / z) + (d / z));
		resultado3 = resultado3 + ((x / e) + (y / y) + (e * c) + (d + z) + (e / y));
		resultado3 = resultado3 + ((x - e) + (z / b) + (c + b) + (b * y) + (b + a));
		String resultado4 = "";
		resultado4 = resultado4 + ((a * a) + (z + z) + (b + x));
		resultado4 = resultado4 + ((d + c) + (a - d) + (d / z) + (d + x) + (a - c));
		resultado4 = resultado4 + ((x + z) + (e / b) + (c - c) + (x - d) + (b * c));
		resultado4 = resultado4 + ((c / c) + (d + y) + (c + b) + (b * b));
		String resultado5 = "";
		resultado5 = resultado5 + ((b + c) + (c * e) + (a / c) + (a * z));
		resultado5 = resultado5 + ((d + x) + (x - a) + (z / a) + (z - a) + (y / d));
		resultado5 = resultado5 + ((d / c) + (y + a) + (z - y));
		String resultado6 = "";
		resultado6 = resultado6 + ((x * x) + (e - z) + (e - c));
		resultado6 = resultado6 + ((x - e) + (y + x) + (y + b));
		resultado6 = resultado6 + ((z / z) + (c * d) + (y * c) + (a * y));
		resultado6 = resultado6 + ((d / x) + (d - a) + (y - d) + (d + a) + (c * b));
		resultado6 = resultado6 + ((z / y) + (e - x) + (a / c) + (b + a) + (c * e));
		String resultado7 = "";
		resultado7 = resultado7 + ((b + z) + (c / c) + (y * d) + (e / z) + (c * z));
		resultado7 = resultado7 + ((z / y) + (a / d) + (b / y) + (a / a) + (y + e));
		resultado7 = resultado7 + ((e - y) + (z / b) + (a * x) + (a * b));
		String resultado8 = "";
		resultado8 = resultado8 + ((d - d) + (x * z) + (b * b) + (x - z));
		resultado8 = resultado8 + ((y * y) + (a - b) + (b * z) + (y * z) + (x - b));
		resultado8 = resultado8 + ((y + x) + (x + e) + (x / c) + (d * b) + (a + x));
		resultado8 = resultado8 + ((c - x) + (y / x) + (e / b) + (e + a) + (z * y));
		resultado8 = resultado8 + ((e * y) + (a / c) + (c / x) + (x / d));
		String resultado9 = "";
		resultado9 = resultado9 + ((c + z) + (a + b) + (x * y) + (d - z) + (a + e));
		resultado9 = resultado9 + ((b / z) + (d - e) + (d + e) + (e / a) + (b - x));
		resultado9 = resultado9 + ((b * x) + (x + y) + (d + d) + (e * z));
		resultado9 = resultado9 + ((e * y) + (d / e) + (b / a) + (y - c));
		resultado9 = resultado9 + ((x / x) + (y + e) + (b * d) + (a / x) + (a * a));
		String resultado10 = "";
		resultado10 = resultado10 + ((e + x) + (y * y) + (c * e) + (e - z) + (d + c));
		resultado10 = resultado10 + ((b * b) + (d / c) + (e * c));
		resultado10 = resultado10 + ((d * a) + (d + d) + (c * y) + (x + d));
		resultado10 = resultado10 + ((y - e) + (e + a) + (e + c) + (y - c));
		resultado10 = resultado10 + ((y + a) + (x / d) + (b / e) + (c * a));
		String resultado11 = "";
		resultado11 = resultado11 + ((z + y) + (x + a) + (x / b));
		resultado11 = resultado11 + ((z * c) + (c / x) + (c * y));
		resultado11 = resultado11 + ((x * a) + (y / e) + (e + x));
		resultado11 = resultado11 + ((d / z) + (d + x) + (e + x) + (z - e) + (c - c));
		resultado11 = resultado11 + ((d + c) + (x - z) + (z / e));
		String resultado12 = "";
		resultado12 = resultado12 + ((z * b) + (c / c) + (z - c) + (c - z));
		resultado12 = resultado12 + ((e * y) + (a / c) + (y + b) + (z + a) + (z - y));
		resultado12 = resultado12 + ((e - a) + (c * z) + (d + b) + (z + y) + (d + b));
		resultado12 = resultado12 + ((a - a) + (b / c) + (b * b) + (c + b) + (a + x));
		String resultado13 = "";
		resultado13 = resultado13 + ((z * b) + (x + c) + (d + a));
		resultado13 = resultado13 + ((d / e) + (d + y) + (a / d));
		resultado13 = resultado13 + ((a + c) + (b + e) + (e * d) + (y * x));
		resultado13 = resultado13 + ((b - x) + (x + e) + (b + z) + (d + x));
		String resultado14 = "";
		resultado14 = resultado14 + ((z - a) + (y + d) + (x + a) + (d * x) + (z / d));
		resultado14 = resultado14 + ((e - b) + (e * e) + (a / c) + (b / e));
		resultado14 = resultado14 + ((c * x) + (b * d) + (y / e) + (x + b) + (y / a));
		resultado14 = resultado14 + ((z - e) + (y + d) + (e / y));
		String resultado15 = "";
		resultado15 = resultado15 + ((e + x) + (a + d) + (x / b) + (c - x));
		resultado15 = resultado15 + ((c * c) + (e - z) + (c / d) + (b + e) + (d + z));
		resultado15 = resultado15 + ((a * c) + (z + d) + (z * d));
		resultado15 = resultado15 + ((b + x) + (e + d) + (x / y));
		String resultado16 = "";
		resultado16 = resultado16 + ((z * e) + (y / z) + (d + a) + (x + b));
		resultado16 = resultado16 + ((d / c) + (z * d) + (d / b) + (z + d) + (x / x));
		resultado16 = resultado16 + ((y + c) + (c / x) + (e + z));
		resultado16 = resultado16 + ((x * a) + (d / z) + (e - e) + (y - e) + (y * e));
		String resultado17 = "";
		resultado17 = resultado17 + ((a + e) + (d + d) + (z + d) + (e + b));
		resultado17 = resultado17 + ((a / e) + (c + d) + (x / d) + (c + c) + (z * b));
		resultado17 = resultado17 + ((x - b) + (x - c) + (d * e) + (y - y) + (e - a));
		resultado17 = resultado17 + ((e * c) + (c - z) + (e + e) + (a - a) + (y / e));
		resultado17 = resultado17 + ((c / c) + (y / z) + (z / z) + (b * e));
		String resultado18 = "";
		resultado18 = resultado18 + ((d - y) + (b - b) + (d * e) + (x + e) + (y + y));
		resultado18 = resultado18 + ((b - z) + (x / a) + (b - y) + (z * e));
		resultado18 = resultado18 + ((a * z) + (x * c) + (b - z) + (b / x) + (e / c));
		resultado18 = resultado18 + ((b * y) + (b - d) + (x / z) + (c - z) + (b - x));
		String resultado19 = "";
		resultado19 = resultado19 + ((y / a) + (x * c) + (b - b));
		resultado19 = resultado19 + ((y / z) + (z + d) + (x + x) + (z * c) + (x / c));
		resultado19 = resultado19 + ((z + y) + (a + c) + (e - c));
		resultado19 = resultado19 + ((e / z) + (y + b) + (x - d) + (a + e) + (b / c));
		String resultado20 = "";
		resultado20 = resultado20 + ((d + a) + (c * c) + (b * d));
		resultado20 = resultado20 + ((c + b) + (y - z) + (e * e));
		resultado20 = resultado20 + ((y / y) + (y / x) + (a * d) + (c / b));
		resultado20 = resultado20 + ((a / c) + (c / a) + (a * e) + (a * b) + (y + d));
		String resultado21 = "";
		resultado21 = resultado21 + ((a - a) + (z * b) + (z * z) + (y / e));
		resultado21 = resultado21 + ((a - x) + (x + d) + (x - a));
		resultado21 = resultado21 + ((x + a) + (a * x) + (d + a) + (b + b) + (c + e));
		String resultado22 = "";
		resultado22 = resultado22 + ((b * b) + (d / y) + (e * c) + (y + e));
		resultado22 = resultado22 + ((e + c) + (a / x) + (y / z) + (z - a) + (e + z));
		resultado22 = resultado22 + ((c - b) + (z / z) + (d + e) + (c - a) + (a / c));
		resultado22 = resultado22 + ((x - a) + (e / z) + (c + y) + (z * c) + (x * a));
		String resultado23 = "";
		resultado23 = resultado23 + ((e - a) + (b / a) + (y * e) + (e * z) + (b - e));
		resultado23 = resultado23 + ((c - d) + (e - d) + (c * b) + (e / e));
		resultado23 = resultado23 + ((e * e) + (b / z) + (x * c) + (b / z) + (x - a));
		resultado23 = resultado23 + ((d + c) + (z - y) + (y + a));
		resultado23 = resultado23 + ((c + b) + (c * c) + (d / b) + (z - a));
		String resultado24 = "";
		resultado24 = resultado24 + ((z / b) + (z * x) + (b / c) + (z + a) + (a / d));
		resultado24 = resultado24 + ((c - c) + (x + y) + (a + e) + (y - e));
		resultado24 = resultado24 + ((d / y) + (b * z) + (a + d) + (z / c) + (z - c));
		resultado24 = resultado24 + ((z * b) + (z + x) + (b - b) + (d - y));
		String resultado25 = "";
		resultado25 = resultado25 + ((b / d) + (a / b) + (d - y) + (d / a) + (a - c));
		resultado25 = resultado25 + ((z - e) + (e + c) + (c / c) + (c / z) + (b + y));
		resultado25 = resultado25 + ((b + y) + (c / z) + (b * c) + (z / b) + (x + c));
		String resultado26 = "";
		resultado26 = resultado26 + ((c + y) + (y * a) + (y + x));
		resultado26 = resultado26 + ((d - b) + (y * x) + (a / a) + (e / d));
		resultado26 = resultado26 + ((c * b) + (e / c) + (z * d) + (e + a));
		String resultado27 = "";
		resultado27 = resultado27 + ((c / c) + (e * d) + (z / a));
		resultado27 = resultado27 + ((b * x) + (x - z) + (z + x) + (a + c) + (e * d));
		resultado27 = resultado27 + ((y - b) + (z / z) + (x * x) + (y - c));
		resultado27 = resultado27 + ((x + x) + (a + c) + (e / y) + (x + y));
		String resultado28 = "";
		resultado28 = resultado28 + ((z - c) + (x * d) + (y - a));
		resultado28 = resultado28 + ((d - c) + (d + z) + (b + c) + (a / y) + (z / c));
		resultado28 = resultado28 + ((c * e) + (d / e) + (x - x));
		String resultado29 = "";
		resultado29 = resultado29 + ((d * b) + (b * z) + (a / x) + (c + y) + (b - e));
		resultado29 = resultado29 + ((b + y) + (e / x) + (e / a));
		resultado29 = resultado29 + ((b + x) + (e - b) + (x / z) + (d - a));
		String resultado30 = "";
		resultado30 = resultado30 + ((b * e) + (a + z) + (c * c) + (a / c) + (y + d));
		resultado30 = resultado30 + ((a * c) + (z + z) + (x * b));
		resultado30 = resultado30 + ((z + a) + (z * e) + (b / a));
		resultado30 = resultado30 + ((e * a) + (c * a) + (a + e));
		String resultado31 = "";
		resultado31 = resultado31 + ((y * e) + (z * z) + (b + c) + (d / b));
		resultado31 = resultado31 + ((b / c) + (z / a) + (b / e));
		resultado31 = resultado31 + ((z * c) + (b + a) + (x / c) + (a + e) + (d / x));
		resultado31 = resultado31 + ((y - z) + (b - e) + (a + a));
		String resultado32 = "";
		resultado32 = resultado32 + ((b - a) + (x - z) + (b * y) + (e + x));
		resultado32 = resultado32 + ((x * d) + (b * c) + (z + a) + (e - z));
		resultado32 = resultado32 + ((a - x) + (x / e) + (a * x) + (x - e));
		resultado32 = resultado32 + ((e + y) + (a - x) + (d + y));
		resultado32 = resultado32 + ((c + y) + (b - z) + (d - e) + (y * c) + (x + e));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}