package br.com.av1.prova02;

public class Questao4 {
	public static void main(String[] args) {
		int a = 6;
		int b = 8;
		int c = 10;
		int d = 6;
		int e = 1;
		int x = 9;
		int y = 2;
		int z = 6;

		String resultado1 = "";
		resultado1 = resultado1 + ((z / d) + (x - b) + (d - b));
		resultado1 = resultado1 + ((d - b) + (c / d) + (b + z) + (z - c) + (b / e));
		resultado1 = resultado1 + ((x + y) + (e / x) + (y - d) + (d / c));
		resultado1 = resultado1 + ((z + b) + (c - z) + (d / a));
		resultado1 = resultado1 + ((e * y) + (e * b) + (b * b) + (c * x));
		String resultado2 = "";
		resultado2 = resultado2 + ((a / d) + (y / y) + (b / z) + (d + x) + (d + y));
		resultado2 = resultado2 + ((z + a) + (c * c) + (x / a) + (z - a) + (a - y));
		resultado2 = resultado2 + ((e / b) + (z + d) + (c + x) + (x + d));
		resultado2 = resultado2 + ((z * y) + (b / d) + (z / z) + (b / e) + (a - z));
		resultado2 = resultado2 + ((b - c) + (e * e) + (b * d));
		String resultado3 = "";
		resultado3 = resultado3 + ((a * x) + (c / x) + (b / y) + (b * x));
		resultado3 = resultado3 + ((a + b) + (e - c) + (c + b) + (b - c));
		resultado3 = resultado3 + ((x + e) + (y / b) + (x - a));
		resultado3 = resultado3 + ((z + c) + (x * x) + (z - c) + (e / b) + (b + d));
		resultado3 = resultado3 + ((b - z) + (a + x) + (b / y) + (x / y));
		String resultado4 = "";
		resultado4 = resultado4 + ((e / b) + (e * c) + (a + c) + (e + x) + (c * d));
		resultado4 = resultado4 + ((c * a) + (e / b) + (b / x) + (d + z) + (e / a));
		resultado4 = resultado4 + ((y - x) + (d - d) + (x / c));
		resultado4 = resultado4 + ((a - a) + (z - e) + (x - b) + (c - e));
		resultado4 = resultado4 + ((d / a) + (z + x) + (x / e) + (b * d) + (y - c));
		String resultado5 = "";
		resultado5 = resultado5 + ((d - e) + (y - b) + (y + c) + (e / b) + (b / z));
		resultado5 = resultado5 + ((d * d) + (z - d) + (c / e) + (a - b) + (x * y));
		resultado5 = resultado5 + ((d * z) + (d - y) + (e / e) + (y - e));
		resultado5 = resultado5 + ((b - e) + (b * c) + (b / d) + (x * d));
		resultado5 = resultado5 + ((b * a) + (a / y) + (b + y) + (c + z));
		String resultado6 = "";
		resultado6 = resultado6 + ((d - y) + (a + y) + (z - d));
		resultado6 = resultado6 + ((b / d) + (d * b) + (b - d) + (c * a));
		resultado6 = resultado6 + ((x / x) + (c / y) + (d - y) + (b + d));
		resultado6 = resultado6 + ((c / y) + (e / c) + (a - z) + (z / d) + (y * a));
		String resultado7 = "";
		resultado7 = resultado7 + ((d * x) + (y / e) + (e * y));
		resultado7 = resultado7 + ((y + x) + (a - y) + (b + d));
		resultado7 = resultado7 + ((a + e) + (z + x) + (a * y) + (x / b));
		String resultado8 = "";
		resultado8 = resultado8 + ((e - y) + (e * x) + (d + d) + (d / a) + (a + d));
		resultado8 = resultado8 + ((b + b) + (y * z) + (x + e) + (y / e) + (z / c));
		resultado8 = resultado8 + ((y + x) + (c * b) + (d - b) + (d * y) + (d + c));
		resultado8 = resultado8 + ((x / a) + (a / x) + (x + z));
		String resultado9 = "";
		resultado9 = resultado9 + ((z - c) + (b / b) + (e * c) + (y + d) + (a + d));
		resultado9 = resultado9 + ((b + y) + (a / z) + (x * z) + (a + e));
		resultado9 = resultado9 + ((e - x) + (c - e) + (b * d));
		resultado9 = resultado9 + ((x - z) + (a * y) + (y - d) + (x * d));
		resultado9 = resultado9 + ((a * c) + (a + c) + (z / z));
		String resultado10 = "";
		resultado10 = resultado10 + ((a + y) + (y / b) + (e + x) + (c / z) + (e - e));
		resultado10 = resultado10 + ((d - c) + (x - d) + (c + c) + (z - e));
		resultado10 = resultado10 + ((c * c) + (c + b) + (y / a) + (b + a));
		resultado10 = resultado10 + ((d + b) + (a * e) + (y / c) + (x + z));
		String resultado11 = "";
		resultado11 = resultado11 + ((d - z) + (b / e) + (e + e) + (y * y));
		resultado11 = resultado11 + ((d + d) + (y - z) + (c * z) + (e / y) + (a * y));
		resultado11 = resultado11 + ((b * a) + (d / x) + (d * z) + (z + y) + (a + y));
		resultado11 = resultado11 + ((z / e) + (a + x) + (y / y) + (d * e));
		resultado11 = resultado11 + ((y + b) + (b - d) + (c + c) + (d - b) + (b - y));
		String resultado12 = "";
		resultado12 = resultado12 + ((b / b) + (c / x) + (e + b) + (x * x));
		resultado12 = resultado12 + ((d + b) + (b - d) + (x - x));
		resultado12 = resultado12 + ((b + x) + (b * z) + (d - b));
		resultado12 = resultado12 + ((c / b) + (e - b) + (a + d) + (x / e) + (b / a));
		String resultado13 = "";
		resultado13 = resultado13 + ((y / e) + (x + e) + (e + c));
		resultado13 = resultado13 + ((e - c) + (e + e) + (a / x) + (a / y) + (a * c));
		resultado13 = resultado13 + ((e * y) + (a * c) + (c - b));
		String resultado14 = "";
		resultado14 = resultado14 + ((d - c) + (c - c) + (c / b) + (x + y));
		resultado14 = resultado14 + ((z + x) + (b / b) + (b * e));
		resultado14 = resultado14 + ((z / a) + (a - b) + (c / y) + (x * d));
		resultado14 = resultado14 + ((d / z) + (z * e) + (d + c));
		resultado14 = resultado14 + ((a * c) + (y / d) + (x * c));
		String resultado15 = "";
		resultado15 = resultado15 + ((a * z) + (d + y) + (c * e));
		resultado15 = resultado15 + ((b + a) + (a + a) + (b + d) + (c * e));
		resultado15 = resultado15 + ((a + d) + (y * d) + (z / a) + (a * b));
		String resultado16 = "";
		resultado16 = resultado16 + ((d / c) + (e + z) + (a / a));
		resultado16 = resultado16 + ((c * y) + (x / b) + (b / z) + (e / x) + (b * c));
		resultado16 = resultado16 + ((e + z) + (x * z) + (b - y) + (d / z));
		resultado16 = resultado16 + ((c - a) + (b - x) + (a / y) + (b * y) + (e - a));
		String resultado17 = "";
		resultado17 = resultado17 + ((a + a) + (y * x) + (c * c) + (b / e) + (y + c));
		resultado17 = resultado17 + ((b - d) + (c / e) + (b - d) + (y / c));
		resultado17 = resultado17 + ((c * c) + (d * a) + (z + a));
		resultado17 = resultado17 + ((c + b) + (d / d) + (e - d));
		String resultado18 = "";
		resultado18 = resultado18 + ((d - x) + (c / x) + (c * c) + (c - a));
		resultado18 = resultado18 + ((c / d) + (b + z) + (y + a) + (e / z) + (y + d));
		resultado18 = resultado18 + ((c / a) + (a - x) + (x * c));
		resultado18 = resultado18 + ((x - d) + (y + e) + (a / a));
		String resultado19 = "";
		resultado19 = resultado19 + ((a * e) + (a - d) + (c + x) + (a + x));
		resultado19 = resultado19 + ((d / x) + (b * e) + (a * b) + (b / a) + (e - b));
		resultado19 = resultado19 + ((c * d) + (e + b) + (y / c));
		resultado19 = resultado19 + ((e - d) + (y / e) + (c + c));
		String resultado20 = "";
		resultado20 = resultado20 + ((b / c) + (x * x) + (b * x));
		resultado20 = resultado20 + ((x * a) + (b * y) + (e / y) + (b - b) + (x * a));
		resultado20 = resultado20 + ((e / y) + (a / y) + (z + y) + (x + z) + (e - z));
		resultado20 = resultado20 + ((a - b) + (y / x) + (y * e));
		resultado20 = resultado20 + ((x * e) + (z + e) + (a + e) + (a / c) + (c / b));
		String resultado21 = "";
		resultado21 = resultado21 + ((z - c) + (c - e) + (a / x) + (e / d) + (y + a));
		resultado21 = resultado21 + ((y - y) + (c * z) + (d - z) + (b / e) + (e / x));
		resultado21 = resultado21 + ((e * c) + (b + z) + (e + d) + (a / z));
		String resultado22 = "";
		resultado22 = resultado22 + ((y + a) + (x / e) + (y * b) + (c / e) + (z - b));
		resultado22 = resultado22 + ((x + d) + (a - y) + (c * c) + (e + b));
		resultado22 = resultado22 + ((e * b) + (y / e) + (x / c) + (c / e) + (b * a));
		resultado22 = resultado22 + ((z - a) + (x - a) + (e + d));
		String resultado23 = "";
		resultado23 = resultado23 + ((b / d) + (y - b) + (d + z));
		resultado23 = resultado23 + ((d / a) + (e / d) + (a - a) + (y - e));
		resultado23 = resultado23 + ((b - a) + (z / b) + (y / d) + (x * x) + (b * x));
		resultado23 = resultado23 + ((a / x) + (y + c) + (x - b));
		resultado23 = resultado23 + ((e + b) + (x + e) + (a - z) + (y * c));
		String resultado24 = "";
		resultado24 = resultado24 + ((z * e) + (z / x) + (x - x));
		resultado24 = resultado24 + ((e - a) + (b - z) + (x + e) + (e + x));
		resultado24 = resultado24 + ((y + a) + (y * x) + (b / x) + (z / b) + (y + e));
		resultado24 = resultado24 + ((e - b) + (e / z) + (y * d) + (e / b));
		resultado24 = resultado24 + ((e / a) + (d - b) + (z + x) + (z * x) + (d * x));
		String resultado25 = "";
		resultado25 = resultado25 + ((e / c) + (y * y) + (z + a));
		resultado25 = resultado25 + ((e - b) + (z / y) + (e * d) + (b / b) + (x + z));
		resultado25 = resultado25 + ((b * z) + (x * z) + (b - z) + (y + a) + (y * a));
		resultado25 = resultado25 + ((c / b) + (e * e) + (b + x) + (x - c));
		String resultado26 = "";
		resultado26 = resultado26 + ((d / c) + (x * b) + (x + x));
		resultado26 = resultado26 + ((x - y) + (y - a) + (d - b) + (c / b));
		resultado26 = resultado26 + ((z * b) + (y * z) + (c * e) + (y / z) + (e + a));
		resultado26 = resultado26 + ((a + c) + (x - d) + (a + c));
		resultado26 = resultado26 + ((a * c) + (b + y) + (x / x));
		String resultado27 = "";
		resultado27 = resultado27 + ((x / a) + (b + c) + (x - a) + (b + c));
		resultado27 = resultado27 + ((e - c) + (a - x) + (z + d) + (a * y) + (x + c));
		resultado27 = resultado27 + ((z * z) + (b + d) + (c - a) + (x * d));
		resultado27 = resultado27 + ((x + c) + (d / b) + (a - c));
		String resultado28 = "";
		resultado28 = resultado28 + ((a - z) + (y / c) + (a / c));
		resultado28 = resultado28 + ((a / b) + (c + a) + (c * a) + (b + d) + (x / b));
		resultado28 = resultado28 + ((e - y) + (e * z) + (c + y));
		resultado28 = resultado28 + ((y + y) + (e * b) + (b - c));
		String resultado29 = "";
		resultado29 = resultado29 + ((e * d) + (c * c) + (z / d) + (a / b));
		resultado29 = resultado29 + ((d + y) + (a / x) + (x + c) + (a + d));
		resultado29 = resultado29 + ((a - b) + (a / z) + (b - d) + (d + d) + (d / y));
		resultado29 = resultado29 + ((y / e) + (x * y) + (y * e) + (a / z));
		resultado29 = resultado29 + ((e * e) + (x - z) + (b * c) + (y - b) + (x - d));
		String resultado30 = "";
		resultado30 = resultado30 + ((c - a) + (y - b) + (a - e));
		resultado30 = resultado30 + ((z - y) + (a - z) + (y * y));
		resultado30 = resultado30 + ((d - b) + (d - d) + (c - y) + (e * a));
		resultado30 = resultado30 + ((y - d) + (z / z) + (y - b) + (b + z) + (d - y));
		resultado30 = resultado30 + ((d - c) + (a * y) + (y * y) + (a + x) + (a / y));
		String resultado31 = "";
		resultado31 = resultado31 + ((c + b) + (d + b) + (e + x) + (d - x));
		resultado31 = resultado31 + ((d + x) + (a + y) + (b / b) + (c * a) + (e + b));
		resultado31 = resultado31 + ((c - e) + (y * a) + (x / y) + (b / b));
		String resultado32 = "";
		resultado32 = resultado32 + ((z / a) + (x * c) + (y * x) + (c / x));
		resultado32 = resultado32 + ((b / e) + (e * x) + (e * b) + (x + a) + (y / b));
		resultado32 = resultado32 + ((d * b) + (b * x) + (b * z) + (b + x));
		resultado32 = resultado32 + ((x - z) + (c * d) + (a - x));
		resultado32 = resultado32 + ((y - e) + (b + c) + (d * e) + (a + e) + (e + d));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}