package br.com.av1.prova25;

public class Questao4 {
	public static void main(String[] args) {
		int a = 9;
		int b = 10;
		int c = 5;
		int d = 3;
		int e = 3;
		int x = 10;
		int y = 4;
		int z = 5;

		String resultado1 = "";
		resultado1 = resultado1 + ((a * b) + (y - a) + (y / y) + (d + c) + (e * y));
		resultado1 = resultado1 + ((e - e) + (b + e) + (b + z) + (z / x) + (d / c));
		resultado1 = resultado1 + ((y / d) + (c * d) + (e * e) + (c / b));
		String resultado2 = "";
		resultado2 = resultado2 + ((d + x) + (z * c) + (y * e) + (x + z));
		resultado2 = resultado2 + ((c - d) + (d - y) + (b - d) + (d / c) + (e * x));
		resultado2 = resultado2 + ((a - y) + (d / c) + (x * x) + (x + b) + (b * z));
		String resultado3 = "";
		resultado3 = resultado3 + ((b + d) + (a - c) + (c - b) + (b + c));
		resultado3 = resultado3 + ((x + z) + (b - z) + (b - d));
		resultado3 = resultado3 + ((e + b) + (d / d) + (x + c) + (z / z) + (x - x));
		String resultado4 = "";
		resultado4 = resultado4 + ((z - c) + (b / x) + (y * x));
		resultado4 = resultado4 + ((z * d) + (b / z) + (d + c) + (d - x) + (x / e));
		resultado4 = resultado4 + ((e / c) + (z * y) + (z / b) + (z * d));
		resultado4 = resultado4 + ((x * x) + (z / b) + (x - c));
		String resultado5 = "";
		resultado5 = resultado5 + ((a - y) + (x - b) + (z * c) + (a * d));
		resultado5 = resultado5 + ((e * b) + (y - b) + (d - x) + (b - x));
		resultado5 = resultado5 + ((e * d) + (a + b) + (d / d) + (y + b) + (y - e));
		resultado5 = resultado5 + ((c * x) + (e * e) + (x - d) + (a - x) + (y + d));
		resultado5 = resultado5 + ((z + d) + (y - d) + (x + x));
		String resultado6 = "";
		resultado6 = resultado6 + ((x * e) + (b - e) + (c - x));
		resultado6 = resultado6 + ((a / z) + (a - y) + (y * c) + (d / e));
		resultado6 = resultado6 + ((e * e) + (c - c) + (b / y) + (a / y));
		resultado6 = resultado6 + ((e - x) + (y + e) + (b - y));
		String resultado7 = "";
		resultado7 = resultado7 + ((c + a) + (b * c) + (z * e));
		resultado7 = resultado7 + ((z / x) + (x - e) + (y + x) + (x / d) + (a / b));
		resultado7 = resultado7 + ((x - x) + (b + x) + (b * z) + (z * y));
		resultado7 = resultado7 + ((b + c) + (y - y) + (e / e) + (a / b) + (d + b));
		resultado7 = resultado7 + ((d / x) + (y / b) + (y * b));
		String resultado8 = "";
		resultado8 = resultado8 + ((e * e) + (a / b) + (c / y) + (e - a) + (b * e));
		resultado8 = resultado8 + ((y - y) + (b * d) + (z + x) + (d + c) + (y / y));
		resultado8 = resultado8 + ((d + z) + (y * x) + (e / c) + (c + d));
		resultado8 = resultado8 + ((x * d) + (e + e) + (a + x) + (a - y));
		String resultado9 = "";
		resultado9 = resultado9 + ((b / x) + (e / c) + (d / c));
		resultado9 = resultado9 + ((b * c) + (d + x) + (b / x));
		resultado9 = resultado9 + ((a / b) + (b + z) + (y - d));
		resultado9 = resultado9 + ((z - y) + (y - x) + (e + b) + (d * a) + (c + y));
		resultado9 = resultado9 + ((x - y) + (a / y) + (y * c));
		String resultado10 = "";
		resultado10 = resultado10 + ((x + b) + (e - e) + (d + z) + (c - e) + (d - e));
		resultado10 = resultado10 + ((y + e) + (a - d) + (y / e) + (c * d));
		resultado10 = resultado10 + ((d / y) + (e * a) + (a - e) + (e * x) + (a / c));
		String resultado11 = "";
		resultado11 = resultado11 + ((e * b) + (e + b) + (y + x) + (b - c) + (d * e));
		resultado11 = resultado11 + ((y * c) + (d / a) + (y + c) + (x - d));
		resultado11 = resultado11 + ((d - z) + (z + y) + (b - d) + (d / c));
		resultado11 = resultado11 + ((e * c) + (z - e) + (z + b) + (y * x));
		resultado11 = resultado11 + ((e - e) + (c / b) + (c * c) + (a / x));
		String resultado12 = "";
		resultado12 = resultado12 + ((z / e) + (x / e) + (z + y));
		resultado12 = resultado12 + ((a / x) + (x + c) + (a + d));
		resultado12 = resultado12 + ((z * e) + (y + z) + (y - b));
		String resultado13 = "";
		resultado13 = resultado13 + ((x / e) + (a * z) + (c / d) + (e * c));
		resultado13 = resultado13 + ((c / c) + (b / z) + (b / c) + (e / z) + (d - c));
		resultado13 = resultado13 + ((b + a) + (x / z) + (c + b) + (e * x) + (e + d));
		String resultado14 = "";
		resultado14 = resultado14 + ((b - e) + (a / e) + (y * d) + (x - e));
		resultado14 = resultado14 + ((z * a) + (c / y) + (d * x) + (x * a) + (x / e));
		resultado14 = resultado14 + ((d * y) + (d - e) + (c * a));
		resultado14 = resultado14 + ((b - b) + (e - x) + (d + a) + (y / e));
		resultado14 = resultado14 + ((c * b) + (y + y) + (e * z) + (d - b) + (b * c));
		String resultado15 = "";
		resultado15 = resultado15 + ((x * c) + (a - z) + (b + e));
		resultado15 = resultado15 + ((x / b) + (d * b) + (c - z) + (d - e) + (d - x));
		resultado15 = resultado15 + ((a / d) + (c / z) + (y * e) + (b - z) + (y / y));
		String resultado16 = "";
		resultado16 = resultado16 + ((e - y) + (z + y) + (b - e) + (e * d));
		resultado16 = resultado16 + ((z / z) + (x / c) + (y - c) + (y - a));
		resultado16 = resultado16 + ((x / a) + (x * d) + (d * z) + (x + x) + (a - b));
		String resultado17 = "";
		resultado17 = resultado17 + ((e + b) + (d * z) + (z + y));
		resultado17 = resultado17 + ((a * b) + (e + z) + (e - e));
		resultado17 = resultado17 + ((e - z) + (b + z) + (d / a) + (z - x) + (z - x));
		resultado17 = resultado17 + ((a + b) + (x + e) + (z / c) + (y / b) + (a + z));
		String resultado18 = "";
		resultado18 = resultado18 + ((c + a) + (b + x) + (b + x) + (x - x));
		resultado18 = resultado18 + ((b - z) + (x / z) + (c / d) + (d * a) + (y * e));
		resultado18 = resultado18 + ((e - a) + (c - y) + (a / d) + (b - z) + (z + b));
		resultado18 = resultado18 + ((c + e) + (e * d) + (y * y));
		String resultado19 = "";
		resultado19 = resultado19 + ((a / y) + (z + z) + (z * x));
		resultado19 = resultado19 + ((z * y) + (y * d) + (c / b) + (z / b));
		resultado19 = resultado19 + ((x - c) + (a + a) + (y + a));
		String resultado20 = "";
		resultado20 = resultado20 + ((c + b) + (z - d) + (x - x) + (c - d) + (c + a));
		resultado20 = resultado20 + ((e * d) + (x + e) + (e + a));
		resultado20 = resultado20 + ((a / a) + (a * a) + (c + d) + (c + c) + (x + d));
		resultado20 = resultado20 + ((z * e) + (b + b) + (a - b) + (b / y) + (a * c));
		resultado20 = resultado20 + ((a + d) + (c + x) + (a - d));
		String resultado21 = "";
		resultado21 = resultado21 + ((a + a) + (z / e) + (e * b) + (b + c));
		resultado21 = resultado21 + ((y / b) + (e * c) + (x - y));
		resultado21 = resultado21 + ((e + y) + (b - b) + (a + c) + (c - y) + (c - e));
		resultado21 = resultado21 + ((y * z) + (e + e) + (y - z) + (x * d));
		resultado21 = resultado21 + ((x + y) + (c + a) + (x - b));
		String resultado22 = "";
		resultado22 = resultado22 + ((y * e) + (c / y) + (b + c));
		resultado22 = resultado22 + ((a / z) + (x + b) + (a * a) + (c * y));
		resultado22 = resultado22 + ((x - y) + (z / a) + (e * y) + (b * y) + (a + d));
		resultado22 = resultado22 + ((c / e) + (z + a) + (c * x));
		resultado22 = resultado22 + ((c - d) + (e * b) + (c - e) + (b * d));
		String resultado23 = "";
		resultado23 = resultado23 + ((x / z) + (z + y) + (y - x));
		resultado23 = resultado23 + ((a * x) + (y / y) + (x / x) + (a / y));
		resultado23 = resultado23 + ((b * y) + (a * b) + (c + c));
		resultado23 = resultado23 + ((c - b) + (e - e) + (a + z) + (y / e));
		resultado23 = resultado23 + ((c / d) + (y - c) + (a / z) + (x * c) + (e * z));
		String resultado24 = "";
		resultado24 = resultado24 + ((z * x) + (c * y) + (z / z) + (b / y));
		resultado24 = resultado24 + ((y - x) + (b + y) + (a * b) + (e / z));
		resultado24 = resultado24 + ((x - x) + (c + y) + (x * z));
		resultado24 = resultado24 + ((y / x) + (y - z) + (x - b));
		resultado24 = resultado24 + ((e + y) + (c + a) + (e - d) + (z / y));
		String resultado25 = "";
		resultado25 = resultado25 + ((c * c) + (b * d) + (e * e));
		resultado25 = resultado25 + ((x * e) + (x * b) + (z * c));
		resultado25 = resultado25 + ((a / e) + (x * c) + (a + b));
		resultado25 = resultado25 + ((b + b) + (y * d) + (d + y) + (a + z) + (e * c));
		resultado25 = resultado25 + ((x - y) + (b / x) + (c / x));
		String resultado26 = "";
		resultado26 = resultado26 + ((z - a) + (c + z) + (y / d) + (c + z) + (z + a));
		resultado26 = resultado26 + ((c + x) + (d * c) + (c * c));
		resultado26 = resultado26 + ((y * c) + (d - c) + (b * x) + (d - e) + (a * e));
		String resultado27 = "";
		resultado27 = resultado27 + ((e + e) + (a / z) + (y + x) + (d + b));
		resultado27 = resultado27 + ((z + c) + (d * c) + (x / z) + (c - a) + (x * y));
		resultado27 = resultado27 + ((d - e) + (z * x) + (z / y) + (y - z));
		resultado27 = resultado27 + ((a - c) + (y * b) + (d + c));
		String resultado28 = "";
		resultado28 = resultado28 + ((e / b) + (c - y) + (y * c) + (y - c));
		resultado28 = resultado28 + ((d - y) + (c + e) + (b + a) + (y - b) + (x / x));
		resultado28 = resultado28 + ((d - c) + (x * b) + (d * z));
		String resultado29 = "";
		resultado29 = resultado29 + ((c / a) + (c - a) + (z * e) + (z - y));
		resultado29 = resultado29 + ((x * b) + (e * d) + (e - x));
		resultado29 = resultado29 + ((a + a) + (c / y) + (b * e) + (d / c) + (x * d));
		resultado29 = resultado29 + ((e + c) + (d + e) + (y / a) + (d / b) + (x - y));
		resultado29 = resultado29 + ((y - e) + (y + y) + (b + e) + (y + a) + (c - d));
		String resultado30 = "";
		resultado30 = resultado30 + ((c / e) + (c * e) + (a * c));
		resultado30 = resultado30 + ((b - y) + (z / x) + (y - y) + (y / c));
		resultado30 = resultado30 + ((a - x) + (a + b) + (e - y) + (x - b) + (e - z));
		resultado30 = resultado30 + ((e * d) + (x - z) + (e - c));
		String resultado31 = "";
		resultado31 = resultado31 + ((z / c) + (b - e) + (d + y));
		resultado31 = resultado31 + ((e - c) + (c / e) + (x - d));
		resultado31 = resultado31 + ((a * d) + (d + a) + (a / y) + (z * y));
		resultado31 = resultado31 + ((d - d) + (y / a) + (z / c) + (d + d));
		String resultado32 = "";
		resultado32 = resultado32 + ((e + y) + (x * e) + (a - c));
		resultado32 = resultado32 + ((y - z) + (b - b) + (b / c) + (e / e) + (a * y));
		resultado32 = resultado32 + ((z - y) + (e * e) + (z * z));
		resultado32 = resultado32 + ((b + b) + (b + y) + (a / b) + (e * y) + (y - c));
		resultado32 = resultado32 + ((b / a) + (b - e) + (a - z) + (e / x) + (x + y));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}