package br.com.av1.prova14;

public class Questao4 {
	public static void main(String[] args) {
		int a = 7;
		int b = 10;
		int c = 10;
		int d = 8;
		int e = 7;
		int x = 2;
		int y = 2;
		int z = 1;

		String resultado1 = "";
		resultado1 = resultado1 + ((b + a) + (z * z) + (z / e) + (b - z));
		resultado1 = resultado1 + ((d + y) + (x - b) + (e + z) + (y / b) + (d - c));
		resultado1 = resultado1 + ((z + x) + (a * x) + (b + e) + (e + a) + (y + b));
		resultado1 = resultado1 + ((y + z) + (c / a) + (e + e) + (b * b) + (a + y));
		String resultado2 = "";
		resultado2 = resultado2 + ((c - z) + (x + a) + (d / z) + (y / x) + (e - x));
		resultado2 = resultado2 + ((b + c) + (z * a) + (b / b) + (a - a) + (c / a));
		resultado2 = resultado2 + ((x + e) + (c * y) + (x * x) + (a - c) + (b * x));
		String resultado3 = "";
		resultado3 = resultado3 + ((y - d) + (a + b) + (x - d));
		resultado3 = resultado3 + ((y / a) + (y - c) + (y + z) + (x * z));
		resultado3 = resultado3 + ((z / x) + (z - a) + (a / b));
		resultado3 = resultado3 + ((z * c) + (z * a) + (d + z) + (b / a));
		resultado3 = resultado3 + ((c / d) + (b + a) + (z + z) + (e + e) + (z + c));
		String resultado4 = "";
		resultado4 = resultado4 + ((x - c) + (c / a) + (b + e));
		resultado4 = resultado4 + ((c * y) + (c + x) + (c / e));
		resultado4 = resultado4 + ((a / d) + (z * d) + (c * z) + (b / c));
		resultado4 = resultado4 + ((b * a) + (b * b) + (d + b) + (e + y));
		String resultado5 = "";
		resultado5 = resultado5 + ((x / z) + (c - e) + (e * e) + (y / c));
		resultado5 = resultado5 + ((y + b) + (e / c) + (e / y));
		resultado5 = resultado5 + ((y / z) + (e + a) + (z / c) + (x - b));
		resultado5 = resultado5 + ((d - y) + (z * a) + (b - z) + (c / z));
		String resultado6 = "";
		resultado6 = resultado6 + ((a - e) + (b + a) + (y / y) + (d * c) + (y + x));
		resultado6 = resultado6 + ((d - e) + (z / c) + (z * d));
		resultado6 = resultado6 + ((e * e) + (d - c) + (z / e) + (e - e) + (b - a));
		resultado6 = resultado6 + ((b / b) + (e + d) + (x / a));
		String resultado7 = "";
		resultado7 = resultado7 + ((a / d) + (b - c) + (z * x) + (y * c) + (d - d));
		resultado7 = resultado7 + ((e / b) + (e * x) + (e - a));
		resultado7 = resultado7 + ((d / c) + (x - a) + (y / b) + (b - e) + (e + a));
		String resultado8 = "";
		resultado8 = resultado8 + ((d * a) + (b - y) + (x - x) + (e + d));
		resultado8 = resultado8 + ((a - e) + (e / x) + (c + e));
		resultado8 = resultado8 + ((c - x) + (d + c) + (a / b) + (a * z));
		String resultado9 = "";
		resultado9 = resultado9 + ((x + c) + (z / x) + (x / z) + (b + y) + (z + e));
		resultado9 = resultado9 + ((a / x) + (c * x) + (z - e));
		resultado9 = resultado9 + ((x - a) + (b - e) + (z / a) + (x / y));
		resultado9 = resultado9 + ((x * c) + (a + e) + (z + e) + (d - d));
		String resultado10 = "";
		resultado10 = resultado10 + ((x - d) + (y * e) + (a * b) + (b - y));
		resultado10 = resultado10 + ((b - c) + (c / b) + (e * z) + (y + x));
		resultado10 = resultado10 + ((y + y) + (e * d) + (b + d) + (c - a) + (y - z));
		resultado10 = resultado10 + ((d * d) + (y + b) + (x / b));
		resultado10 = resultado10 + ((b / y) + (e + b) + (y + x));
		String resultado11 = "";
		resultado11 = resultado11 + ((b / x) + (y / z) + (d + y) + (d / y) + (z * a));
		resultado11 = resultado11 + ((z + c) + (x * b) + (x - e));
		resultado11 = resultado11 + ((d + a) + (d - x) + (x - y) + (x - a));
		resultado11 = resultado11 + ((b + z) + (b + c) + (z * c));
		resultado11 = resultado11 + ((y / z) + (y - y) + (b * e));
		String resultado12 = "";
		resultado12 = resultado12 + ((x * z) + (b * b) + (z * b));
		resultado12 = resultado12 + ((b - e) + (b / d) + (b * e) + (c + d) + (y - b));
		resultado12 = resultado12 + ((a / x) + (a + b) + (z / c));
		String resultado13 = "";
		resultado13 = resultado13 + ((d * y) + (c - z) + (a - y));
		resultado13 = resultado13 + ((a + a) + (y / e) + (z - c));
		resultado13 = resultado13 + ((c / x) + (x - c) + (x - y) + (z * b));
		String resultado14 = "";
		resultado14 = resultado14 + ((d * d) + (e + c) + (e - a) + (e - c) + (a * z));
		resultado14 = resultado14 + ((c / b) + (y / x) + (e / d) + (a - a));
		resultado14 = resultado14 + ((a - a) + (a / d) + (z * a) + (d * b) + (e - a));
		resultado14 = resultado14 + ((z * c) + (y / x) + (a * e));
		String resultado15 = "";
		resultado15 = resultado15 + ((x - y) + (c - b) + (x + x) + (e * y) + (c + x));
		resultado15 = resultado15 + ((y + d) + (c - e) + (c / y) + (c * z) + (x / z));
		resultado15 = resultado15 + ((d - c) + (a - z) + (e * e));
		String resultado16 = "";
		resultado16 = resultado16 + ((b / x) + (d * c) + (x / d));
		resultado16 = resultado16 + ((x * z) + (b + e) + (a * d));
		resultado16 = resultado16 + ((d * z) + (x / b) + (c - y));
		resultado16 = resultado16 + ((d * c) + (y * y) + (e / d));
		resultado16 = resultado16 + ((y + y) + (d - a) + (x - z) + (e * y) + (z - b));
		String resultado17 = "";
		resultado17 = resultado17 + ((y + z) + (e / c) + (c + z) + (b - e));
		resultado17 = resultado17 + ((z + c) + (a / x) + (y + a));
		resultado17 = resultado17 + ((e + a) + (z - z) + (e * y) + (e + d));
		resultado17 = resultado17 + ((c / d) + (a * b) + (d - a));
		resultado17 = resultado17 + ((y / z) + (d + c) + (c / e));
		String resultado18 = "";
		resultado18 = resultado18 + ((b - e) + (a / y) + (z + e) + (x * b));
		resultado18 = resultado18 + ((d + e) + (y - b) + (z * c));
		resultado18 = resultado18 + ((d - y) + (y + e) + (x - c) + (a / b));
		resultado18 = resultado18 + ((a - x) + (z * a) + (e / e));
		resultado18 = resultado18 + ((b - z) + (a + d) + (a - a) + (c + e) + (y + b));
		String resultado19 = "";
		resultado19 = resultado19 + ((b - d) + (y / a) + (c + d) + (a - e));
		resultado19 = resultado19 + ((e - b) + (c / a) + (a / e) + (c * d));
		resultado19 = resultado19 + ((a + b) + (y + z) + (b - y) + (e / y));
		String resultado20 = "";
		resultado20 = resultado20 + ((c / z) + (x + a) + (d / b));
		resultado20 = resultado20 + ((x - y) + (y - b) + (d / y) + (d * d) + (c * e));
		resultado20 = resultado20 + ((b / e) + (d * d) + (e - x) + (d + y));
		resultado20 = resultado20 + ((e - c) + (e / z) + (z * y));
		resultado20 = resultado20 + ((z / z) + (d - y) + (a / b) + (y + b) + (x + x));
		String resultado21 = "";
		resultado21 = resultado21 + ((x / c) + (e * a) + (e / z));
		resultado21 = resultado21 + ((e - x) + (c + e) + (a / b) + (b / b) + (y / c));
		resultado21 = resultado21 + ((d - d) + (d * b) + (a - d) + (y - d) + (x - z));
		resultado21 = resultado21 + ((x / z) + (x + b) + (c + b) + (y / b) + (a * x));
		String resultado22 = "";
		resultado22 = resultado22 + ((d / y) + (e - z) + (b + y) + (z * b));
		resultado22 = resultado22 + ((y + c) + (b * c) + (a - b));
		resultado22 = resultado22 + ((c + c) + (z - e) + (d + y));
		resultado22 = resultado22 + ((y * c) + (a + a) + (a - b));
		String resultado23 = "";
		resultado23 = resultado23 + ((a - a) + (y / a) + (b - b) + (a + b));
		resultado23 = resultado23 + ((a + c) + (e + c) + (y + d));
		resultado23 = resultado23 + ((x - c) + (d * z) + (b / a) + (c - e));
		String resultado24 = "";
		resultado24 = resultado24 + ((e / a) + (a - z) + (z * z) + (b + c) + (y * e));
		resultado24 = resultado24 + ((c + e) + (z + d) + (z * x));
		resultado24 = resultado24 + ((x - z) + (c - x) + (d * z) + (e + c));
		resultado24 = resultado24 + ((c + e) + (a + a) + (z + z) + (e / b));
		String resultado25 = "";
		resultado25 = resultado25 + ((a * y) + (y * a) + (x / d) + (c - z) + (x * e));
		resultado25 = resultado25 + ((x / b) + (e + x) + (y + z) + (c - z) + (a - b));
		resultado25 = resultado25 + ((z + x) + (c / x) + (x + e) + (c - d));
		String resultado26 = "";
		resultado26 = resultado26 + ((e + b) + (d * b) + (x - c) + (y + d));
		resultado26 = resultado26 + ((b / x) + (d * d) + (c - d) + (c * c));
		resultado26 = resultado26 + ((z / x) + (e / a) + (z - y) + (d * x));
		resultado26 = resultado26 + ((e * b) + (b / b) + (x + y) + (x / d));
		resultado26 = resultado26 + ((e / x) + (e / a) + (e / c) + (a * y));
		String resultado27 = "";
		resultado27 = resultado27 + ((d + b) + (d - z) + (b * d));
		resultado27 = resultado27 + ((e / z) + (x - z) + (x - b));
		resultado27 = resultado27 + ((e - a) + (y / a) + (y / a) + (x + e));
		String resultado28 = "";
		resultado28 = resultado28 + ((b * e) + (c + x) + (a + e) + (e * c) + (z - a));
		resultado28 = resultado28 + ((a / e) + (e * x) + (e - b) + (c / b) + (e / d));
		resultado28 = resultado28 + ((z * d) + (b - a) + (b - y) + (x + b));
		resultado28 = resultado28 + ((z * d) + (e + c) + (c / a) + (b * a));
		resultado28 = resultado28 + ((z - y) + (z - c) + (x - e) + (y + z) + (c / x));
		String resultado29 = "";
		resultado29 = resultado29 + ((e - a) + (x - z) + (e / x));
		resultado29 = resultado29 + ((b * b) + (d * x) + (y - a) + (x + y));
		resultado29 = resultado29 + ((z / d) + (z - x) + (c * a));
		resultado29 = resultado29 + ((z + x) + (y / y) + (c * a) + (e + x) + (e / z));
		String resultado30 = "";
		resultado30 = resultado30 + ((y + c) + (a * a) + (z - b));
		resultado30 = resultado30 + ((e / a) + (z / z) + (z - x) + (c / d) + (d + e));
		resultado30 = resultado30 + ((y - e) + (e + c) + (b + d) + (e / x));
		resultado30 = resultado30 + ((y / y) + (d / c) + (x * c));
		String resultado31 = "";
		resultado31 = resultado31 + ((b * y) + (c + z) + (c + b));
		resultado31 = resultado31 + ((d * y) + (e + z) + (a / x));
		resultado31 = resultado31 + ((b / a) + (b + a) + (x / y) + (y - y) + (y - y));
		String resultado32 = "";
		resultado32 = resultado32 + ((c * x) + (b * y) + (d + e) + (e - d) + (c * x));
		resultado32 = resultado32 + ((e + a) + (z / y) + (b - z) + (b + b) + (b / x));
		resultado32 = resultado32 + ((d / d) + (x + e) + (a + a) + (a + y) + (b / z));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}