package br.com.av1.prova22;

public class Questao4 {
	public static void main(String[] args) {
		int a = 9;
		int b = 10;
		int c = 2;
		int d = 4;
		int e = 3;
		int x = 6;
		int y = 4;
		int z = 1;

		String resultado1 = "";
		resultado1 = resultado1 + ((e - a) + (y / c) + (a * e) + (c * d));
		resultado1 = resultado1 + ((c - a) + (x / a) + (y * e) + (e * z) + (x + y));
		resultado1 = resultado1 + ((d + c) + (b / b) + (a * c) + (z / b));
		String resultado2 = "";
		resultado2 = resultado2 + ((x - d) + (d - z) + (a - y) + (c * e));
		resultado2 = resultado2 + ((d - a) + (z * x) + (d * c));
		resultado2 = resultado2 + ((x + z) + (b + y) + (e * x) + (x / x) + (b / x));
		String resultado3 = "";
		resultado3 = resultado3 + ((y / b) + (x / a) + (z * z));
		resultado3 = resultado3 + ((d * x) + (b * x) + (e + y));
		resultado3 = resultado3 + ((e + z) + (d + d) + (y / c) + (z - e) + (x / c));
		resultado3 = resultado3 + ((b / d) + (d / z) + (z + c) + (x - z));
		resultado3 = resultado3 + ((x - x) + (x + e) + (a / e));
		String resultado4 = "";
		resultado4 = resultado4 + ((b / d) + (e + a) + (a - x) + (d * e));
		resultado4 = resultado4 + ((e - d) + (y * x) + (d / z) + (d + y) + (c - z));
		resultado4 = resultado4 + ((y / x) + (a + y) + (c + z) + (x * d));
		resultado4 = resultado4 + ((a + z) + (e - a) + (d * d) + (z * x));
		String resultado5 = "";
		resultado5 = resultado5 + ((e - b) + (e / y) + (b - y));
		resultado5 = resultado5 + ((c * y) + (b - c) + (d / a) + (z / z) + (x / z));
		resultado5 = resultado5 + ((b + y) + (c / y) + (x + y));
		resultado5 = resultado5 + ((c / a) + (c * b) + (x / d) + (c + y) + (a - b));
		String resultado6 = "";
		resultado6 = resultado6 + ((d * x) + (y - c) + (x / e));
		resultado6 = resultado6 + ((x + z) + (b * z) + (c + z) + (z * a));
		resultado6 = resultado6 + ((d / e) + (b + d) + (z * d) + (e * z) + (y * a));
		resultado6 = resultado6 + ((z * d) + (d + x) + (e / y) + (c / a) + (y - c));
		String resultado7 = "";
		resultado7 = resultado7 + ((c + a) + (z / a) + (x + x));
		resultado7 = resultado7 + ((d * y) + (z + c) + (d / d));
		resultado7 = resultado7 + ((b - z) + (d - z) + (c * z) + (e - e) + (d - d));
		resultado7 = resultado7 + ((a + c) + (z - d) + (b / d) + (c / b) + (d / y));
		resultado7 = resultado7 + ((e * b) + (y - y) + (e / c));
		String resultado8 = "";
		resultado8 = resultado8 + ((b - d) + (c - e) + (a / b) + (c - x));
		resultado8 = resultado8 + ((x / e) + (a - a) + (c + a));
		resultado8 = resultado8 + ((b / b) + (d + y) + (c / z));
		String resultado9 = "";
		resultado9 = resultado9 + ((d / b) + (c * d) + (a * b) + (z * x));
		resultado9 = resultado9 + ((d * a) + (z + y) + (d - x) + (a - b) + (b + c));
		resultado9 = resultado9 + ((d + d) + (a - x) + (a * a));
		resultado9 = resultado9 + ((d / b) + (e * e) + (z * c) + (a + e));
		resultado9 = resultado9 + ((e - b) + (x + d) + (d * y));
		String resultado10 = "";
		resultado10 = resultado10 + ((z - x) + (x * x) + (x / y));
		resultado10 = resultado10 + ((e - d) + (d - c) + (b / z) + (a + c) + (b - d));
		resultado10 = resultado10 + ((z * e) + (y / z) + (y - a) + (c / c) + (d * e));
		String resultado11 = "";
		resultado11 = resultado11 + ((y * e) + (x + d) + (a + x));
		resultado11 = resultado11 + ((d - b) + (e * e) + (e + e));
		resultado11 = resultado11 + ((b + y) + (y / x) + (y / a));
		resultado11 = resultado11 + ((b - y) + (y / d) + (b + z));
		resultado11 = resultado11 + ((c - z) + (x - c) + (e / e));
		String resultado12 = "";
		resultado12 = resultado12 + ((a + y) + (a + y) + (a * z) + (c / a) + (d - y));
		resultado12 = resultado12 + ((d / b) + (e + e) + (z / x) + (e / z) + (y / y));
		resultado12 = resultado12 + ((b - e) + (y - a) + (b + y) + (e * c));
		String resultado13 = "";
		resultado13 = resultado13 + ((b - z) + (e + y) + (x - d));
		resultado13 = resultado13 + ((x + y) + (a / y) + (z * c) + (b - d) + (x + c));
		resultado13 = resultado13 + ((y - x) + (e / d) + (e * x) + (d * a) + (y / x));
		resultado13 = resultado13 + ((d + e) + (a - c) + (y - b) + (d + d) + (y * y));
		String resultado14 = "";
		resultado14 = resultado14 + ((x - b) + (z / e) + (x - a) + (x + x) + (x + b));
		resultado14 = resultado14 + ((b * b) + (e + z) + (a + c) + (e - c));
		resultado14 = resultado14 + ((c + d) + (e / y) + (d - c) + (y / c));
		String resultado15 = "";
		resultado15 = resultado15 + ((a - x) + (z - x) + (a * e));
		resultado15 = resultado15 + ((a + y) + (y * y) + (a * e) + (c - e));
		resultado15 = resultado15 + ((a / a) + (e * c) + (e - c));
		resultado15 = resultado15 + ((e * d) + (x - a) + (a * z));
		String resultado16 = "";
		resultado16 = resultado16 + ((y / e) + (y / x) + (c - b) + (e - z) + (c * a));
		resultado16 = resultado16 + ((a - b) + (y * z) + (a - d) + (y * b));
		resultado16 = resultado16 + ((b + e) + (c - b) + (a / d) + (d - d));
		resultado16 = resultado16 + ((d / x) + (y / b) + (x * x) + (z / y));
		resultado16 = resultado16 + ((b / b) + (x / e) + (c * z) + (x + b) + (d + a));
		String resultado17 = "";
		resultado17 = resultado17 + ((z + y) + (z * b) + (e - y) + (a - e) + (z / b));
		resultado17 = resultado17 + ((d * c) + (b / c) + (x * b) + (c / x));
		resultado17 = resultado17 + ((b - a) + (e * x) + (y / a));
		String resultado18 = "";
		resultado18 = resultado18 + ((a / e) + (a - c) + (x / e));
		resultado18 = resultado18 + ((x * d) + (z * y) + (x - d));
		resultado18 = resultado18 + ((e + x) + (e + x) + (d / b));
		resultado18 = resultado18 + ((c * c) + (x + b) + (c - y) + (z - y));
		String resultado19 = "";
		resultado19 = resultado19 + ((d + z) + (e + a) + (z + z) + (e - c));
		resultado19 = resultado19 + ((d / e) + (d + c) + (e / z));
		resultado19 = resultado19 + ((z + d) + (y - z) + (x - z) + (d * a));
		resultado19 = resultado19 + ((y / z) + (z + z) + (d * c) + (y / x) + (y - x));
		String resultado20 = "";
		resultado20 = resultado20 + ((x / e) + (c + e) + (b + x) + (c / b));
		resultado20 = resultado20 + ((e - c) + (e * b) + (z + d) + (c - c) + (x * x));
		resultado20 = resultado20 + ((b / d) + (e * y) + (x - y));
		resultado20 = resultado20 + ((c + e) + (x + a) + (z * x) + (z / x));
		resultado20 = resultado20 + ((z / c) + (y / y) + (b * x) + (x + z) + (d * x));
		String resultado21 = "";
		resultado21 = resultado21 + ((b + z) + (d * e) + (x + z) + (c / a) + (d - b));
		resultado21 = resultado21 + ((z / a) + (y - b) + (x / z) + (c * e));
		resultado21 = resultado21 + ((x + d) + (z * a) + (e + b) + (c / c));
		resultado21 = resultado21 + ((e / c) + (d * z) + (b + y));
		String resultado22 = "";
		resultado22 = resultado22 + ((e * d) + (y - b) + (c * b));
		resultado22 = resultado22 + ((c + b) + (c / y) + (a + y) + (a - c) + (x - e));
		resultado22 = resultado22 + ((y / d) + (d * e) + (b / c) + (b * x) + (y + e));
		resultado22 = resultado22 + ((c / x) + (b + d) + (e * z));
		resultado22 = resultado22 + ((b - c) + (x + z) + (z * d));
		String resultado23 = "";
		resultado23 = resultado23 + ((e + b) + (e / e) + (z + c) + (x + z) + (a / z));
		resultado23 = resultado23 + ((e * b) + (d / z) + (d - y) + (x + y) + (e * c));
		resultado23 = resultado23 + ((c - d) + (a - z) + (y - d) + (e * e));
		resultado23 = resultado23 + ((c * z) + (c / x) + (z / b) + (d - b) + (z - x));
		resultado23 = resultado23 + ((z / e) + (x / y) + (e - a) + (b / b) + (y * e));
		String resultado24 = "";
		resultado24 = resultado24 + ((c - b) + (c / b) + (d + y) + (y + b));
		resultado24 = resultado24 + ((a - e) + (x - x) + (a + y));
		resultado24 = resultado24 + ((e / z) + (z - b) + (y / c));
		resultado24 = resultado24 + ((z + x) + (a / b) + (a - b) + (d + e));
		resultado24 = resultado24 + ((a - d) + (y * y) + (d * z) + (x - c));
		String resultado25 = "";
		resultado25 = resultado25 + ((z / y) + (d / d) + (a * x));
		resultado25 = resultado25 + ((c / c) + (e - x) + (y + x) + (e - x));
		resultado25 = resultado25 + ((a / b) + (c * e) + (e / z) + (b - b) + (d - x));
		String resultado26 = "";
		resultado26 = resultado26 + ((y * e) + (a / b) + (e - d));
		resultado26 = resultado26 + ((y / x) + (a - x) + (c + y));
		resultado26 = resultado26 + ((e + a) + (e + c) + (b * b) + (a / e));
		String resultado27 = "";
		resultado27 = resultado27 + ((z * d) + (e / y) + (e + x) + (e / y) + (c / z));
		resultado27 = resultado27 + ((e - a) + (b * y) + (e * c) + (e + a) + (x / e));
		resultado27 = resultado27 + ((e / d) + (b - x) + (z * y) + (z + z) + (d - x));
		resultado27 = resultado27 + ((d / a) + (a / y) + (a - d) + (c / c) + (d + d));
		resultado27 = resultado27 + ((b - a) + (z + z) + (z / z) + (a - c));
		String resultado28 = "";
		resultado28 = resultado28 + ((a * a) + (x / c) + (z - e) + (c / x) + (d - c));
		resultado28 = resultado28 + ((e / d) + (x + c) + (x / z) + (z * b) + (x - d));
		resultado28 = resultado28 + ((y - c) + (a + y) + (a / a) + (a - x));
		resultado28 = resultado28 + ((y - z) + (e - b) + (a / a) + (d + b));
		resultado28 = resultado28 + ((z * d) + (x * c) + (x * z) + (c + x));
		String resultado29 = "";
		resultado29 = resultado29 + ((b - e) + (x + b) + (d - a) + (c - y) + (x + d));
		resultado29 = resultado29 + ((b + y) + (z * c) + (z - y) + (d * e));
		resultado29 = resultado29 + ((x + z) + (d - a) + (x / a) + (y + x));
		resultado29 = resultado29 + ((e * c) + (b - b) + (x + e));
		String resultado30 = "";
		resultado30 = resultado30 + ((d + e) + (a * d) + (a / c) + (z / c) + (e / z));
		resultado30 = resultado30 + ((d + b) + (a + c) + (a / c));
		resultado30 = resultado30 + ((b * c) + (d + y) + (b * c) + (e * b) + (x - c));
		resultado30 = resultado30 + ((y + x) + (a + b) + (d - x));
		resultado30 = resultado30 + ((c - y) + (d + c) + (a / x) + (x - y) + (y * z));
		String resultado31 = "";
		resultado31 = resultado31 + ((y - c) + (a / a) + (c / c));
		resultado31 = resultado31 + ((a + a) + (x / x) + (z * z) + (e / b));
		resultado31 = resultado31 + ((x / a) + (y * a) + (y * z) + (e * x) + (c / a));
		resultado31 = resultado31 + ((c * z) + (c - y) + (y - y));
		String resultado32 = "";
		resultado32 = resultado32 + ((a * y) + (z - e) + (a + z) + (y - x));
		resultado32 = resultado32 + ((c + z) + (a - y) + (a - d) + (c / z));
		resultado32 = resultado32 + ((x + c) + (y / b) + (x / a) + (z * x));
		resultado32 = resultado32 + ((c + b) + (b + x) + (b - e));
		resultado32 = resultado32 + ((a * c) + (z + a) + (b - a));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}
