package br.com.av1.prova06;

public class Questao4 {
	public static void main(String[] args) {
		int a = 1;
		int b = 7;
		int c = 5;
		int d = 1;
		int e = 9;
		int x = 3;
		int y = 7;
		int z = 10;

		String resultado1 = "";
		resultado1 = resultado1 + ((d - b) + (c / y) + (e * b) + (a * a));
		resultado1 = resultado1 + ((a + e) + (z / a) + (z - d) + (a + a) + (a * a));
		resultado1 = resultado1 + ((a - e) + (b * c) + (e - x) + (y * z));
		String resultado2 = "";
		resultado2 = resultado2 + ((x / y) + (c * b) + (c - d) + (a - y));
		resultado2 = resultado2 + ((d + z) + (b + x) + (x / x) + (c * e));
		resultado2 = resultado2 + ((d / a) + (d + d) + (a - c));
		resultado2 = resultado2 + ((a * e) + (e * x) + (c + z));
		resultado2 = resultado2 + ((z * z) + (e / y) + (e / d) + (z + y) + (c - a));
		String resultado3 = "";
		resultado3 = resultado3 + ((z + x) + (d + d) + (d + d) + (a / c));
		resultado3 = resultado3 + ((c + y) + (x + y) + (z - z) + (e + x) + (y * b));
		resultado3 = resultado3 + ((z / b) + (y - z) + (b / x) + (b / c) + (e + z));
		resultado3 = resultado3 + ((y / z) + (b + d) + (a * e));
		resultado3 = resultado3 + ((b - a) + (z + d) + (c + c) + (c - y) + (d + e));
		String resultado4 = "";
		resultado4 = resultado4 + ((y + e) + (z - e) + (a * x) + (a * e));
		resultado4 = resultado4 + ((d - b) + (a / e) + (b - e));
		resultado4 = resultado4 + ((x / d) + (y + c) + (b + a));
		resultado4 = resultado4 + ((z / a) + (b - e) + (e * x));
		resultado4 = resultado4 + ((x / x) + (x + e) + (e - z));
		String resultado5 = "";
		resultado5 = resultado5 + ((e / e) + (d / b) + (y - d) + (b - z));
		resultado5 = resultado5 + ((x * y) + (x * z) + (a / a) + (z + b) + (a + a));
		resultado5 = resultado5 + ((b * d) + (a / b) + (a * x) + (x * x) + (x * c));
		resultado5 = resultado5 + ((y + c) + (y * z) + (z / a));
		String resultado6 = "";
		resultado6 = resultado6 + ((y - c) + (z / c) + (d + d));
		resultado6 = resultado6 + ((e - a) + (y * y) + (z / d));
		resultado6 = resultado6 + ((b / b) + (z + e) + (e - y) + (b / b) + (z / d));
		String resultado7 = "";
		resultado7 = resultado7 + ((z + z) + (x - y) + (e * y));
		resultado7 = resultado7 + ((z / e) + (d / a) + (x * c));
		resultado7 = resultado7 + ((e / e) + (x - z) + (b - a));
		String resultado8 = "";
		resultado8 = resultado8 + ((x - z) + (z - a) + (x * x) + (c + y));
		resultado8 = resultado8 + ((b - d) + (b - c) + (c - y) + (e - d));
		resultado8 = resultado8 + ((x / b) + (e / z) + (e / x) + (e / a));
		resultado8 = resultado8 + ((y * c) + (d - z) + (a / d) + (a - x));
		String resultado9 = "";
		resultado9 = resultado9 + ((b + y) + (b / x) + (a * d));
		resultado9 = resultado9 + ((x + b) + (x + a) + (b + y) + (e / a));
		resultado9 = resultado9 + ((x - y) + (z / a) + (b - c) + (y * z) + (x + c));
		String resultado10 = "";
		resultado10 = resultado10 + ((a * d) + (x + b) + (x + x) + (x + x) + (b * a));
		resultado10 = resultado10 + ((d + c) + (x / x) + (e + b) + (a * x));
		resultado10 = resultado10 + ((a - y) + (x + d) + (b / d) + (e - b));
		resultado10 = resultado10 + ((y + d) + (b * y) + (x / d) + (z - e));
		String resultado11 = "";
		resultado11 = resultado11 + ((e / b) + (a - c) + (z + y) + (d - z));
		resultado11 = resultado11 + ((e + y) + (e + a) + (x + b));
		resultado11 = resultado11 + ((c * x) + (b / y) + (x + x) + (d - z));
		String resultado12 = "";
		resultado12 = resultado12 + ((e - y) + (x - x) + (a * e));
		resultado12 = resultado12 + ((e - c) + (z * x) + (z * y));
		resultado12 = resultado12 + ((e - e) + (a + y) + (y * d) + (b * y));
		resultado12 = resultado12 + ((x - d) + (z + c) + (e / x));
		resultado12 = resultado12 + ((e * x) + (x - z) + (c + b));
		String resultado13 = "";
		resultado13 = resultado13 + ((y * e) + (x + c) + (d * a) + (y / e));
		resultado13 = resultado13 + ((a / z) + (a * z) + (e - e));
		resultado13 = resultado13 + ((y - x) + (y + b) + (d + d) + (x - z) + (z * x));
		String resultado14 = "";
		resultado14 = resultado14 + ((a - c) + (b / z) + (x + d));
		resultado14 = resultado14 + ((c - x) + (y * y) + (e - x));
		resultado14 = resultado14 + ((z - z) + (a - e) + (x + y) + (z * z));
		resultado14 = resultado14 + ((z * a) + (e - y) + (a / c));
		String resultado15 = "";
		resultado15 = resultado15 + ((x + z) + (d - e) + (e * x));
		resultado15 = resultado15 + ((e * b) + (y * b) + (d / e));
		resultado15 = resultado15 + ((y - b) + (y + b) + (e * b) + (x - c) + (x + c));
		resultado15 = resultado15 + ((y * y) + (a * d) + (z * d) + (c - d) + (e / a));
		String resultado16 = "";
		resultado16 = resultado16 + ((x / x) + (b / d) + (z - d) + (z / d));
		resultado16 = resultado16 + ((x + d) + (d / a) + (c - d) + (x - a));
		resultado16 = resultado16 + ((c / a) + (y * z) + (d - z));
		String resultado17 = "";
		resultado17 = resultado17 + ((a * d) + (z + c) + (x * c) + (x / b));
		resultado17 = resultado17 + ((x * c) + (z * y) + (c / y) + (y * a) + (c / z));
		resultado17 = resultado17 + ((y / z) + (d + b) + (y / c) + (x - b));
		String resultado18 = "";
		resultado18 = resultado18 + ((a / y) + (d - c) + (c - y) + (x + x));
		resultado18 = resultado18 + ((x - y) + (y - z) + (d - z) + (x + y) + (c + d));
		resultado18 = resultado18 + ((e * a) + (y / x) + (d * e));
		resultado18 = resultado18 + ((y / d) + (d - e) + (b - y));
		resultado18 = resultado18 + ((b + e) + (a * b) + (d / x) + (x - x) + (c + x));
		String resultado19 = "";
		resultado19 = resultado19 + ((z + c) + (a - x) + (z + x) + (d - d));
		resultado19 = resultado19 + ((d + b) + (c + y) + (e + c) + (d * z) + (z - z));
		resultado19 = resultado19 + ((y + c) + (x - c) + (e + b) + (x * y));
		resultado19 = resultado19 + ((e + x) + (e / d) + (y + y) + (e + y));
		resultado19 = resultado19 + ((d / z) + (a - y) + (d / y));
		String resultado20 = "";
		resultado20 = resultado20 + ((z / e) + (c + d) + (e / c) + (a * y) + (c / c));
		resultado20 = resultado20 + ((e * y) + (d + e) + (b * a) + (z / z));
		resultado20 = resultado20 + ((x - b) + (b + x) + (z - c) + (d * e));
		resultado20 = resultado20 + ((x + e) + (x * b) + (x - a) + (y + b));
		String resultado21 = "";
		resultado21 = resultado21 + ((z * e) + (d / b) + (a / y));
		resultado21 = resultado21 + ((x - z) + (e * c) + (d - d) + (z * x));
		resultado21 = resultado21 + ((x + d) + (z * y) + (b + y));
		String resultado22 = "";
		resultado22 = resultado22 + ((a * e) + (a * c) + (c + b) + (d / z));
		resultado22 = resultado22 + ((z * c) + (z * d) + (c - d) + (c / e));
		resultado22 = resultado22 + ((y - c) + (z * a) + (b * z) + (d / c));
		resultado22 = resultado22 + ((y * c) + (d - a) + (z + d) + (b / e));
		String resultado23 = "";
		resultado23 = resultado23 + ((d * z) + (c + d) + (e * a));
		resultado23 = resultado23 + ((x - c) + (e * c) + (a - y) + (c + z) + (b + d));
		resultado23 = resultado23 + ((c + b) + (b / z) + (d - y));
		resultado23 = resultado23 + ((z / x) + (z - x) + (x * c) + (a / x));
		resultado23 = resultado23 + ((z - x) + (d / y) + (a - e) + (y / x) + (y + e));
		String resultado24 = "";
		resultado24 = resultado24 + ((c / b) + (e + y) + (d / y));
		resultado24 = resultado24 + ((a + x) + (c * e) + (y * z) + (c + x) + (x * x));
		resultado24 = resultado24 + ((c + b) + (d - y) + (y / b) + (a / b));
		String resultado25 = "";
		resultado25 = resultado25 + ((b * d) + (b / x) + (e - z) + (y - y) + (y - z));
		resultado25 = resultado25 + ((z / b) + (d + e) + (c - a) + (z + z) + (d / c));
		resultado25 = resultado25 + ((a + a) + (b / e) + (a - e) + (c / c) + (d / a));
		String resultado26 = "";
		resultado26 = resultado26 + ((e / b) + (y + a) + (a / e) + (z / c) + (y * c));
		resultado26 = resultado26 + ((e * e) + (b * y) + (y - y) + (d + c));
		resultado26 = resultado26 + ((x + e) + (x - y) + (e + y) + (z - b));
		resultado26 = resultado26 + ((e / e) + (e + z) + (a / b) + (d * e) + (y + c));
		resultado26 = resultado26 + ((b / x) + (d + z) + (z * a) + (d * e));
		String resultado27 = "";
		resultado27 = resultado27 + ((y + x) + (x - c) + (c + x));
		resultado27 = resultado27 + ((y + c) + (e + d) + (x + a));
		resultado27 = resultado27 + ((c * x) + (a * d) + (y * b));
		resultado27 = resultado27 + ((e * c) + (y / d) + (d / y) + (x * b));
		resultado27 = resultado27 + ((c + a) + (x - x) + (b * y) + (e / b));
		String resultado28 = "";
		resultado28 = resultado28 + ((y + y) + (x - d) + (d - a) + (d - y));
		resultado28 = resultado28 + ((d - c) + (b - z) + (b * z));
		resultado28 = resultado28 + ((a - d) + (c - x) + (d - z));
		resultado28 = resultado28 + ((b / z) + (y + e) + (c * b) + (d + e) + (z * c));
		resultado28 = resultado28 + ((a / z) + (z / y) + (x * c) + (x / c));
		String resultado29 = "";
		resultado29 = resultado29 + ((d - c) + (y / c) + (x / d) + (a * x));
		resultado29 = resultado29 + ((e - b) + (a - a) + (d * z) + (z * y));
		resultado29 = resultado29 + ((x + c) + (y * b) + (z + c));
		resultado29 = resultado29 + ((y + y) + (x / x) + (z * e) + (e + z));
		resultado29 = resultado29 + ((a / a) + (e + c) + (d / y));
		String resultado30 = "";
		resultado30 = resultado30 + ((c + x) + (z / d) + (a * a) + (z / d));
		resultado30 = resultado30 + ((b * c) + (z - d) + (y - a));
		resultado30 = resultado30 + ((y - z) + (d * e) + (c / a));
		String resultado31 = "";
		resultado31 = resultado31 + ((y * e) + (z / e) + (a + x));
		resultado31 = resultado31 + ((z - d) + (y * x) + (e * e));
		resultado31 = resultado31 + ((b / z) + (b / y) + (y - z));
		resultado31 = resultado31 + ((y + d) + (d - x) + (d * c));
		String resultado32 = "";
		resultado32 = resultado32 + ((z / y) + (a + x) + (b + z) + (x + y) + (z + e));
		resultado32 = resultado32 + ((e + z) + (b / c) + (c + d));
		resultado32 = resultado32 + ((z * y) + (e / y) + (a - x) + (e + a) + (y + b));
		resultado32 = resultado32 + ((a / x) + (a - d) + (c / e) + (b - c) + (c / b));
		resultado32 = resultado32 + ((b - a) + (b * c) + (a + a) + (a + d));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}