package br.com.av1.prova07;

public class Questao4 {
	public static void main(String[] args) {
		int a = 8;
		int b = 4;
		int c = 3;
		int d = 2;
		int e = 7;
		int x = 5;
		int y = 1;
		int z = 10;

		String resultado1 = "";
		resultado1 = resultado1 + ((z + e) + (z / z) + (x * a) + (y + b) + (z - a));
		resultado1 = resultado1 + ((a * b) + (a + e) + (e / c) + (x * c) + (x - d));
		resultado1 = resultado1 + ((e + b) + (x + x) + (c + y) + (b + d));
		String resultado2 = "";
		resultado2 = resultado2 + ((a + a) + (b + c) + (c / a));
		resultado2 = resultado2 + ((d / z) + (b + d) + (y - z) + (y * z) + (c - x));
		resultado2 = resultado2 + ((y / b) + (b / z) + (b / z) + (y - z));
		resultado2 = resultado2 + ((c - c) + (a + x) + (d + c));
		resultado2 = resultado2 + ((y * z) + (b - b) + (e + c));
		String resultado3 = "";
		resultado3 = resultado3 + ((a * b) + (e * e) + (x - c));
		resultado3 = resultado3 + ((a - b) + (x / b) + (z - c) + (e * a));
		resultado3 = resultado3 + ((x + b) + (b * z) + (y + e) + (y + b) + (c + e));
		String resultado4 = "";
		resultado4 = resultado4 + ((x + d) + (x / d) + (c * z) + (y * b) + (e - a));
		resultado4 = resultado4 + ((e - y) + (b * b) + (z * e));
		resultado4 = resultado4 + ((x + b) + (y * a) + (b - c) + (b - b) + (y * y));
		resultado4 = resultado4 + ((x - e) + (a + z) + (b / z) + (x * b) + (y / c));
		resultado4 = resultado4 + ((a * d) + (b / a) + (e - a) + (d - x));
		String resultado5 = "";
		resultado5 = resultado5 + ((z * b) + (z + b) + (z + x) + (e - b));
		resultado5 = resultado5 + ((e - d) + (x - d) + (c - z) + (d + z));
		resultado5 = resultado5 + ((y / x) + (e - a) + (b * y) + (c + y));
		String resultado6 = "";
		resultado6 = resultado6 + ((a * y) + (a - e) + (b - b));
		resultado6 = resultado6 + ((c - b) + (c * d) + (y - d) + (e * c));
		resultado6 = resultado6 + ((b + d) + (a * z) + (z * y) + (a + y) + (z + z));
		resultado6 = resultado6 + ((x * b) + (a + x) + (z / y) + (a / e));
		resultado6 = resultado6 + ((b + a) + (x * z) + (d * b) + (z - b));
		String resultado7 = "";
		resultado7 = resultado7 + ((d / d) + (a - d) + (e / y) + (b / z));
		resultado7 = resultado7 + ((a / c) + (d * x) + (y - e));
		resultado7 = resultado7 + ((c - y) + (b / c) + (x + e) + (b - z) + (x - y));
		resultado7 = resultado7 + ((z / x) + (x - c) + (b * b) + (b - y) + (x * z));
		String resultado8 = "";
		resultado8 = resultado8 + ((x + x) + (e / b) + (d + x) + (c * d));
		resultado8 = resultado8 + ((e / x) + (a + x) + (z / c));
		resultado8 = resultado8 + ((c / a) + (y - y) + (b - y));
		resultado8 = resultado8 + ((e - a) + (a / y) + (b - b) + (c - d));
		resultado8 = resultado8 + ((a * d) + (d + d) + (d * y) + (e * z));
		String resultado9 = "";
		resultado9 = resultado9 + ((a / d) + (d * d) + (b * y));
		resultado9 = resultado9 + ((y + y) + (z / a) + (d * z) + (a * e));
		resultado9 = resultado9 + ((d * y) + (b * b) + (c + b));
		resultado9 = resultado9 + ((y + e) + (d * z) + (c - d));
		resultado9 = resultado9 + ((d + x) + (x / e) + (c / x) + (a + a));
		String resultado10 = "";
		resultado10 = resultado10 + ((c + a) + (z - y) + (y / z));
		resultado10 = resultado10 + ((e - e) + (y - a) + (c - z) + (x + c));
		resultado10 = resultado10 + ((b - c) + (d * a) + (e * b));
		resultado10 = resultado10 + ((c / x) + (y / z) + (a * b) + (c - b));
		resultado10 = resultado10 + ((z / b) + (c * z) + (z * c) + (z - a));
		String resultado11 = "";
		resultado11 = resultado11 + ((e * e) + (a / x) + (z - d));
		resultado11 = resultado11 + ((e / z) + (z - z) + (x * c) + (b * d));
		resultado11 = resultado11 + ((d - e) + (d / c) + (a - a) + (y * a) + (d / a));
		resultado11 = resultado11 + ((b * d) + (y + d) + (x * x));
		resultado11 = resultado11 + ((z + e) + (x / x) + (c - a));
		String resultado12 = "";
		resultado12 = resultado12 + ((e / y) + (c - d) + (c + y));
		resultado12 = resultado12 + ((c - c) + (y * z) + (b - z) + (e + a) + (b * y));
		resultado12 = resultado12 + ((c / a) + (a - d) + (y - z) + (d - y));
		resultado12 = resultado12 + ((b + y) + (x + b) + (b / y) + (z * x));
		String resultado13 = "";
		resultado13 = resultado13 + ((a + b) + (y - x) + (a / e));
		resultado13 = resultado13 + ((d * b) + (x - a) + (c - e) + (b / e) + (x * e));
		resultado13 = resultado13 + ((a - d) + (d * c) + (a / c) + (c - c) + (d * a));
		String resultado14 = "";
		resultado14 = resultado14 + ((e * b) + (c - d) + (x - x) + (z / x));
		resultado14 = resultado14 + ((x * b) + (a + d) + (y - x) + (d * y) + (y + c));
		resultado14 = resultado14 + ((b - e) + (c / c) + (c / d) + (d + z));
		resultado14 = resultado14 + ((d * z) + (e - e) + (b - c) + (z + a) + (d / a));
		resultado14 = resultado14 + ((e + y) + (c + c) + (x + b));
		String resultado15 = "";
		resultado15 = resultado15 + ((y + d) + (e / x) + (a + y) + (c + z));
		resultado15 = resultado15 + ((c / e) + (a - y) + (y - e) + (x - z));
		resultado15 = resultado15 + ((c * z) + (c / b) + (c - e));
		resultado15 = resultado15 + ((a / z) + (d / z) + (x + e) + (y - x) + (a * b));
		String resultado16 = "";
		resultado16 = resultado16 + ((c - c) + (d / c) + (c / a));
		resultado16 = resultado16 + ((z / x) + (b * c) + (z / z) + (y - x));
		resultado16 = resultado16 + ((b / e) + (y * x) + (a * d));
		resultado16 = resultado16 + ((e * e) + (b * c) + (c - a) + (z / b));
		String resultado17 = "";
		resultado17 = resultado17 + ((b / e) + (e - a) + (x - d) + (d - e) + (c * x));
		resultado17 = resultado17 + ((x * a) + (x / d) + (z / e) + (x + e));
		resultado17 = resultado17 + ((e / y) + (b + e) + (y * y));
		resultado17 = resultado17 + ((e / z) + (e / e) + (b - d));
		resultado17 = resultado17 + ((b - c) + (e - b) + (d * x) + (x * y) + (y * a));
		String resultado18 = "";
		resultado18 = resultado18 + ((a / a) + (y / z) + (b + x) + (a / z));
		resultado18 = resultado18 + ((a - y) + (y - y) + (x + c) + (d + c) + (a + y));
		resultado18 = resultado18 + ((z * c) + (c + x) + (b + d) + (e * b));
		String resultado19 = "";
		resultado19 = resultado19 + ((y + y) + (a / y) + (y * c));
		resultado19 = resultado19 + ((e - z) + (d - y) + (a - d) + (x + y) + (e * y));
		resultado19 = resultado19 + ((e + z) + (d * b) + (x + z) + (z + c));
		resultado19 = resultado19 + ((x - y) + (a * y) + (e - z));
		resultado19 = resultado19 + ((d / d) + (c / e) + (d * d) + (e + y));
		String resultado20 = "";
		resultado20 = resultado20 + ((a - a) + (b - a) + (e * c) + (y - b));
		resultado20 = resultado20 + ((e * d) + (y * x) + (c - b) + (c / d));
		resultado20 = resultado20 + ((x + x) + (a * d) + (z / x));
		resultado20 = resultado20 + ((b / d) + (y / b) + (c * a) + (b + b));
		resultado20 = resultado20 + ((a / e) + (b * d) + (y + z) + (c - d) + (z / b));
		String resultado21 = "";
		resultado21 = resultado21 + ((z * z) + (x * e) + (z + d) + (d / c) + (y - e));
		resultado21 = resultado21 + ((e + b) + (z / z) + (c * a) + (y * y) + (a - c));
		resultado21 = resultado21 + ((b / b) + (d - b) + (a - b) + (c + z));
		resultado21 = resultado21 + ((d + c) + (b * e) + (d * a));
		String resultado22 = "";
		resultado22 = resultado22 + ((a / d) + (y + c) + (c * e) + (a + b));
		resultado22 = resultado22 + ((c - z) + (d - d) + (z + c) + (x + z));
		resultado22 = resultado22 + ((b - e) + (y - a) + (c * b) + (b + c));
		String resultado23 = "";
		resultado23 = resultado23 + ((d / a) + (e * e) + (c / a) + (a + y));
		resultado23 = resultado23 + ((z * z) + (y + d) + (e - y) + (x / a) + (b * e));
		resultado23 = resultado23 + ((c - a) + (y - d) + (d * e));
		resultado23 = resultado23 + ((x / x) + (c / x) + (x * x) + (z - e));
		String resultado24 = "";
		resultado24 = resultado24 + ((z - d) + (e + x) + (y / c) + (z * x));
		resultado24 = resultado24 + ((d + y) + (a - e) + (e - z));
		resultado24 = resultado24 + ((x * z) + (c - y) + (e * z) + (b * d) + (e / b));
		String resultado25 = "";
		resultado25 = resultado25 + ((c - z) + (y / d) + (y + b) + (z / e));
		resultado25 = resultado25 + ((c / d) + (y / z) + (e + x));
		resultado25 = resultado25 + ((a / y) + (e + y) + (e / b) + (b * z) + (b - b));
		String resultado26 = "";
		resultado26 = resultado26 + ((d + e) + (y * c) + (y - a) + (a + x));
		resultado26 = resultado26 + ((y / y) + (c * z) + (c / a) + (a / x));
		resultado26 = resultado26 + ((c / c) + (b / y) + (d + a) + (a / a));
		resultado26 = resultado26 + ((a / d) + (y + d) + (z - e) + (z - z));
		resultado26 = resultado26 + ((y / c) + (z + c) + (y + a));
		String resultado27 = "";
		resultado27 = resultado27 + ((y * d) + (x + d) + (b * b) + (e + x));
		resultado27 = resultado27 + ((z / z) + (x + d) + (e - z));
		resultado27 = resultado27 + ((c / x) + (e + e) + (z - e));
		String resultado28 = "";
		resultado28 = resultado28 + ((b / y) + (a * y) + (c / c) + (y - e) + (b + x));
		resultado28 = resultado28 + ((x / x) + (b * b) + (z / b) + (b - b));
		resultado28 = resultado28 + ((e - a) + (y / d) + (x * e) + (x / d));
		resultado28 = resultado28 + ((d / x) + (b * z) + (c - y) + (a + d) + (b * a));
		String resultado29 = "";
		resultado29 = resultado29 + ((y - b) + (d / z) + (y / c) + (z + y) + (b - e));
		resultado29 = resultado29 + ((c * x) + (y / y) + (a * y));
		resultado29 = resultado29 + ((d * x) + (a / d) + (y + x));
		resultado29 = resultado29 + ((c / b) + (b / e) + (c + x));
		String resultado30 = "";
		resultado30 = resultado30 + ((b - b) + (c * a) + (x * d) + (x - c));
		resultado30 = resultado30 + ((e - d) + (c * a) + (b / y) + (a * d) + (y * x));
		resultado30 = resultado30 + ((x + c) + (a - d) + (x + e) + (z - c));
		resultado30 = resultado30 + ((c + z) + (a / z) + (e - d) + (d / e));
		resultado30 = resultado30 + ((d / a) + (d + a) + (x - x));
		String resultado31 = "";
		resultado31 = resultado31 + ((z - z) + (c - b) + (b / b));
		resultado31 = resultado31 + ((a * c) + (y * e) + (a + y));
		resultado31 = resultado31 + ((c * e) + (c - b) + (a / c) + (z + y) + (e - b));
		String resultado32 = "";
		resultado32 = resultado32 + ((y + z) + (b + a) + (c * y) + (x + y) + (d * b));
		resultado32 = resultado32 + ((d * e) + (c * z) + (d + x) + (z / z) + (a / x));
		resultado32 = resultado32 + ((a - d) + (y - d) + (c * z) + (b - x));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}