package br.com.av1.prova15;

public class Questao4 {
	public static void main(String[] args) {
		int a = 2;
		int b = 3;
		int c = 10;
		int d = 1;
		int e = 1;
		int x = 4;
		int y = 10;
		int z = 3;

		String resultado1 = "";
		resultado1 = resultado1 + ((y * e) + (c + x) + (z * y) + (c - b));
		resultado1 = resultado1 + ((z / b) + (a - e) + (c / d) + (c + d));
		resultado1 = resultado1 + ((a - y) + (e * y) + (a + y) + (d / z) + (y * d));
		resultado1 = resultado1 + ((b + c) + (b / b) + (a - d) + (a - b) + (y - x));
		String resultado2 = "";
		resultado2 = resultado2 + ((c - b) + (a - c) + (y / d) + (c - a));
		resultado2 = resultado2 + ((x * d) + (z + a) + (d + z));
		resultado2 = resultado2 + ((c * a) + (c * a) + (a - x));
		resultado2 = resultado2 + ((d * x) + (z - y) + (z * d) + (z - x));
		String resultado3 = "";
		resultado3 = resultado3 + ((x * c) + (z + d) + (z * e) + (b - e) + (d / c));
		resultado3 = resultado3 + ((d + c) + (z - e) + (d / b));
		resultado3 = resultado3 + ((d / y) + (y / a) + (y - b) + (x * b) + (c + c));
		resultado3 = resultado3 + ((b * z) + (y * y) + (x - x) + (e / a) + (x + x));
		resultado3 = resultado3 + ((e - d) + (c * z) + (c * x) + (d + x));
		String resultado4 = "";
		resultado4 = resultado4 + ((c / y) + (d + x) + (b + c) + (b * d) + (x / e));
		resultado4 = resultado4 + ((e - e) + (e + b) + (d - y) + (a - b));
		resultado4 = resultado4 + ((x + y) + (c - e) + (z / c));
		String resultado5 = "";
		resultado5 = resultado5 + ((c + d) + (b * c) + (d * z) + (y - c));
		resultado5 = resultado5 + ((x / c) + (c / a) + (z * d));
		resultado5 = resultado5 + ((d + e) + (c / y) + (a - c) + (c * c));
		resultado5 = resultado5 + ((e + c) + (a + b) + (d - z) + (d + c));
		resultado5 = resultado5 + ((z - b) + (e + a) + (a * d));
		String resultado6 = "";
		resultado6 = resultado6 + ((d + x) + (b * e) + (x + b) + (y - d) + (b - a));
		resultado6 = resultado6 + ((z * e) + (x * y) + (z + d) + (c - d) + (y / e));
		resultado6 = resultado6 + ((d - a) + (c - z) + (x * z) + (z * e) + (a + z));
		String resultado7 = "";
		resultado7 = resultado7 + ((c / z) + (b - d) + (c + b) + (y - y));
		resultado7 = resultado7 + ((c * e) + (x + d) + (x + c));
		resultado7 = resultado7 + ((z * x) + (a * a) + (z * z));
		String resultado8 = "";
		resultado8 = resultado8 + ((b / b) + (z - z) + (c / c) + (d - y));
		resultado8 = resultado8 + ((y / x) + (a * e) + (x * b) + (d / c));
		resultado8 = resultado8 + ((x / b) + (y + z) + (a + b) + (y - z));
		resultado8 = resultado8 + ((a - a) + (a * x) + (c - e));
		String resultado9 = "";
		resultado9 = resultado9 + ((d * z) + (b - c) + (y - a) + (b + a) + (c - b));
		resultado9 = resultado9 + ((d - b) + (a / b) + (z + b));
		resultado9 = resultado9 + ((x / e) + (z * e) + (x - d) + (e / z) + (y / d));
		resultado9 = resultado9 + ((x + y) + (x + d) + (d * a));
		String resultado10 = "";
		resultado10 = resultado10 + ((b + e) + (c - y) + (y - y) + (b / b));
		resultado10 = resultado10 + ((c - z) + (d * d) + (y * x) + (x - z));
		resultado10 = resultado10 + ((z + b) + (b - y) + (x / c) + (e - y));
		resultado10 = resultado10 + ((z * d) + (d + c) + (y / d) + (y - y) + (c / x));
		String resultado11 = "";
		resultado11 = resultado11 + ((e + z) + (d / x) + (e / a));
		resultado11 = resultado11 + ((y * y) + (z / y) + (a + y) + (e / a) + (x * a));
		resultado11 = resultado11 + ((b / e) + (e + b) + (d - d));
		resultado11 = resultado11 + ((x / x) + (d * c) + (y + x) + (a + x));
		String resultado12 = "";
		resultado12 = resultado12 + ((a * d) + (a / d) + (z - z));
		resultado12 = resultado12 + ((y - b) + (c + d) + (e + a));
		resultado12 = resultado12 + ((d - x) + (x + y) + (b / a));
		String resultado13 = "";
		resultado13 = resultado13 + ((d + a) + (e + y) + (e + z) + (y + c) + (b / y));
		resultado13 = resultado13 + ((y + e) + (c / e) + (z / e) + (z + b) + (b - z));
		resultado13 = resultado13 + ((a - y) + (y - x) + (x / d) + (x + d) + (d / d));
		resultado13 = resultado13 + ((y * x) + (e - d) + (e - c));
		String resultado14 = "";
		resultado14 = resultado14 + ((z * x) + (a - x) + (z / x) + (d / x) + (a - a));
		resultado14 = resultado14 + ((b + y) + (d - d) + (c + d) + (a + d) + (z - x));
		resultado14 = resultado14 + ((c * e) + (c + c) + (c + x));
		String resultado15 = "";
		resultado15 = resultado15 + ((y / d) + (d / y) + (y / x) + (y + b));
		resultado15 = resultado15 + ((a + d) + (z * b) + (a + a) + (y * y));
		resultado15 = resultado15 + ((x - a) + (a + z) + (y + b) + (y - c));
		String resultado16 = "";
		resultado16 = resultado16 + ((c - x) + (d * y) + (c * d) + (c - y) + (a / x));
		resultado16 = resultado16 + ((d * e) + (b + b) + (x - z) + (c / d) + (y / a));
		resultado16 = resultado16 + ((b + b) + (d / x) + (b - x) + (z - a));
		resultado16 = resultado16 + ((e - y) + (b * c) + (y / d) + (z - z));
		resultado16 = resultado16 + ((z + y) + (d * d) + (x * x) + (d + d) + (c / a));
		String resultado17 = "";
		resultado17 = resultado17 + ((a * b) + (z - b) + (z - e));
		resultado17 = resultado17 + ((d + a) + (c - x) + (c * a) + (e / b));
		resultado17 = resultado17 + ((b - c) + (e + e) + (z * y) + (y / b));
		resultado17 = resultado17 + ((y - z) + (z + e) + (y * b) + (a * y) + (x * e));
		String resultado18 = "";
		resultado18 = resultado18 + ((a / d) + (a * c) + (e * x) + (y + e));
		resultado18 = resultado18 + ((z + y) + (e / b) + (e + c) + (c / b));
		resultado18 = resultado18 + ((c - a) + (b + c) + (x * e) + (z - c) + (c / e));
		resultado18 = resultado18 + ((z + d) + (y - a) + (c - d) + (c * a) + (a - z));
		String resultado19 = "";
		resultado19 = resultado19 + ((a * b) + (c * y) + (x / c));
		resultado19 = resultado19 + ((y + e) + (c + d) + (a + c));
		resultado19 = resultado19 + ((b * x) + (z * a) + (b - a) + (c - b) + (e / d));
		resultado19 = resultado19 + ((b * z) + (e + x) + (z - b));
		String resultado20 = "";
		resultado20 = resultado20 + ((z / d) + (z + c) + (d + x) + (c / c));
		resultado20 = resultado20 + ((d + z) + (b * y) + (z * z));
		resultado20 = resultado20 + ((b + b) + (z / d) + (x / x) + (b + b));
		String resultado21 = "";
		resultado21 = resultado21 + ((e / y) + (d + c) + (d * d) + (a * y));
		resultado21 = resultado21 + ((b * e) + (b - c) + (x * d));
		resultado21 = resultado21 + ((y + e) + (d - d) + (a + e));
		resultado21 = resultado21 + ((z + c) + (y + d) + (y / z));
		String resultado22 = "";
		resultado22 = resultado22 + ((y + y) + (d / d) + (e / x));
		resultado22 = resultado22 + ((z * a) + (x - x) + (a + c) + (x * x) + (d + a));
		resultado22 = resultado22 + ((y + c) + (z * z) + (c / x));
		resultado22 = resultado22 + ((x / a) + (y + a) + (a + z) + (a / y) + (x - a));
		resultado22 = resultado22 + ((e / c) + (y - y) + (a + x) + (c * x) + (b / a));
		String resultado23 = "";
		resultado23 = resultado23 + ((z / c) + (y + x) + (e + b) + (z * e) + (c + c));
		resultado23 = resultado23 + ((e * e) + (z / a) + (z / a) + (y + c) + (z + e));
		resultado23 = resultado23 + ((b + b) + (b - z) + (e / d));
		resultado23 = resultado23 + ((d / z) + (x + c) + (z / x) + (d + d));
		resultado23 = resultado23 + ((a * e) + (e + d) + (c / d) + (e * z));
		String resultado24 = "";
		resultado24 = resultado24 + ((y * e) + (x / e) + (e + x) + (d * a));
		resultado24 = resultado24 + ((a * b) + (z - d) + (e - b) + (c + x) + (y * d));
		resultado24 = resultado24 + ((b + z) + (x - z) + (z * b));
		resultado24 = resultado24 + ((y + d) + (y / b) + (e + z) + (x * x) + (a / z));
		resultado24 = resultado24 + ((c - c) + (y / e) + (a + d) + (c * z) + (z * e));
		String resultado25 = "";
		resultado25 = resultado25 + ((c * e) + (d * d) + (y / y) + (x + d));
		resultado25 = resultado25 + ((c + a) + (e / x) + (z - y));
		resultado25 = resultado25 + ((y / y) + (z - d) + (e * z));
		resultado25 = resultado25 + ((a / z) + (c / c) + (d + a));
		String resultado26 = "";
		resultado26 = resultado26 + ((x - e) + (x * z) + (y / a) + (b - y) + (y * c));
		resultado26 = resultado26 + ((y + z) + (e / d) + (a / z) + (b - d));
		resultado26 = resultado26 + ((a / d) + (y * c) + (c * b));
		resultado26 = resultado26 + ((a + y) + (y - e) + (a - y) + (a / b) + (z + y));
		resultado26 = resultado26 + ((z / z) + (a + d) + (b - e) + (c * z) + (x + z));
		String resultado27 = "";
		resultado27 = resultado27 + ((y + y) + (x + z) + (d / d) + (z * x));
		resultado27 = resultado27 + ((a / b) + (d - y) + (y - x));
		resultado27 = resultado27 + ((c - z) + (z / y) + (d + c) + (x - y));
		resultado27 = resultado27 + ((c / e) + (a / b) + (c / y));
		resultado27 = resultado27 + ((y - y) + (y - z) + (b * d));
		String resultado28 = "";
		resultado28 = resultado28 + ((y - a) + (b / e) + (d + z) + (d - b));
		resultado28 = resultado28 + ((d + z) + (z * d) + (e * a));
		resultado28 = resultado28 + ((z / b) + (c - x) + (c / a) + (e - d));
		String resultado29 = "";
		resultado29 = resultado29 + ((c - e) + (a / d) + (y + x));
		resultado29 = resultado29 + ((e - e) + (a * a) + (x * e));
		resultado29 = resultado29 + ((d / y) + (e + y) + (e * d) + (x * a) + (y * c));
		String resultado30 = "";
		resultado30 = resultado30 + ((a * e) + (x - a) + (y - b) + (y - a) + (b - e));
		resultado30 = resultado30 + ((b * y) + (z + c) + (b + a) + (a + d));
		resultado30 = resultado30 + ((x * a) + (e - c) + (y - e));
		String resultado31 = "";
		resultado31 = resultado31 + ((b - e) + (y / e) + (x - z));
		resultado31 = resultado31 + ((z + b) + (z - a) + (z - z) + (e * a) + (x * y));
		resultado31 = resultado31 + ((d / c) + (z / x) + (e - b) + (y + b) + (e + x));
		resultado31 = resultado31 + ((b + d) + (c / d) + (y / c) + (e + z));
		resultado31 = resultado31 + ((z / c) + (c - d) + (e + d) + (z - e) + (y - e));
		String resultado32 = "";
		resultado32 = resultado32 + ((y / e) + (x - c) + (a / d) + (x / y));
		resultado32 = resultado32 + ((a / a) + (c * z) + (b - y) + (a + e));
		resultado32 = resultado32 + ((y - e) + (d - c) + (z - x));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}