package br.com.av1.prova09;

public class Questao4 {
	public static void main(String[] args) {
		int a = 4;
		int b = 3;
		int c = 1;
		int d = 7;
		int e = 3;
		int x = 8;
		int y = 8;
		int z = 8;

		String resultado1 = "";
		resultado1 = resultado1 + ((x - z) + (e / x) + (c - z) + (b / c));
		resultado1 = resultado1 + ((y - b) + (d + y) + (b / c) + (y + c));
		resultado1 = resultado1 + ((c * e) + (z - x) + (e - c) + (a + c));
		resultado1 = resultado1 + ((e / x) + (x - x) + (x + a));
		String resultado2 = "";
		resultado2 = resultado2 + ((x * y) + (c - e) + (b / a) + (e * z) + (e * y));
		resultado2 = resultado2 + ((c * b) + (b * e) + (b - b) + (y * y) + (d - c));
		resultado2 = resultado2 + ((z - x) + (e / a) + (y / a) + (d / x) + (b + x));
		String resultado3 = "";
		resultado3 = resultado3 + ((b * e) + (e / e) + (a / z));
		resultado3 = resultado3 + ((z * y) + (d + e) + (z / b) + (z + e));
		resultado3 = resultado3 + ((e * d) + (a - x) + (x - b));
		resultado3 = resultado3 + ((c - d) + (e - d) + (a - x) + (c - b) + (a * a));
		resultado3 = resultado3 + ((y / z) + (e + x) + (y * c) + (y / d) + (x / y));
		String resultado4 = "";
		resultado4 = resultado4 + ((x + a) + (z + c) + (y / b) + (y / c) + (e * b));
		resultado4 = resultado4 + ((e * x) + (y * e) + (d + y));
		resultado4 = resultado4 + ((y * y) + (d / a) + (c + e) + (e + e) + (x + d));
		resultado4 = resultado4 + ((y / z) + (y / b) + (d * b) + (b * x) + (z * c));
		String resultado5 = "";
		resultado5 = resultado5 + ((e / e) + (c / z) + (d - c) + (b * b));
		resultado5 = resultado5 + ((x - c) + (d - e) + (z * y) + (x + z));
		resultado5 = resultado5 + ((b + c) + (z + d) + (d - x) + (z * x));
		resultado5 = resultado5 + ((e / d) + (z - a) + (c * d) + (b / d) + (y * e));
		String resultado6 = "";
		resultado6 = resultado6 + ((c + y) + (c - c) + (x * b) + (e + y) + (e + x));
		resultado6 = resultado6 + ((d / c) + (z * a) + (y - y) + (d - x));
		resultado6 = resultado6 + ((a + b) + (b * b) + (d * z) + (b - y) + (y * e));
		String resultado7 = "";
		resultado7 = resultado7 + ((x * y) + (e - x) + (e + e) + (c - d) + (y - x));
		resultado7 = resultado7 + ((a / a) + (x - a) + (c * y) + (d / e));
		resultado7 = resultado7 + ((x / a) + (z * c) + (b / e) + (z / y) + (x - y));
		String resultado8 = "";
		resultado8 = resultado8 + ((b * c) + (y + y) + (y * b) + (x - a) + (c + b));
		resultado8 = resultado8 + ((b / d) + (z / y) + (z - x) + (c / c) + (z / b));
		resultado8 = resultado8 + ((x - y) + (e / y) + (y - e) + (b / b) + (a / b));
		resultado8 = resultado8 + ((e / a) + (z * b) + (y - b) + (d * b) + (d * e));
		resultado8 = resultado8 + ((a - b) + (c / y) + (z / x));
		String resultado9 = "";
		resultado9 = resultado9 + ((a + b) + (c + z) + (z - y) + (d + y) + (a * d));
		resultado9 = resultado9 + ((e / a) + (d * a) + (b - y));
		resultado9 = resultado9 + ((c / d) + (d + c) + (y / d) + (z - b) + (a + e));
		resultado9 = resultado9 + ((y / d) + (a / a) + (a * a) + (e / y));
		resultado9 = resultado9 + ((a + d) + (b + c) + (b / z));
		String resultado10 = "";
		resultado10 = resultado10 + ((y + x) + (x + x) + (a / x));
		resultado10 = resultado10 + ((z - x) + (a * y) + (x - b) + (a + c));
		resultado10 = resultado10 + ((b - d) + (e + z) + (b + y) + (y + b));
		resultado10 = resultado10 + ((e / b) + (y - c) + (y + y) + (c - d));
		resultado10 = resultado10 + ((x - d) + (b / z) + (d * b));
		String resultado11 = "";
		resultado11 = resultado11 + ((e + d) + (e * x) + (b * d) + (x * e) + (d * x));
		resultado11 = resultado11 + ((c - z) + (e / e) + (d - x));
		resultado11 = resultado11 + ((c + z) + (a - c) + (x / e));
		String resultado12 = "";
		resultado12 = resultado12 + ((d * e) + (z * z) + (b / y) + (e - b) + (e * z));
		resultado12 = resultado12 + ((d * y) + (z + b) + (x + y) + (x - x) + (z - c));
		resultado12 = resultado12 + ((d / a) + (a / b) + (e * e) + (d / x));
		resultado12 = resultado12 + ((x + y) + (z + a) + (x - a) + (y * z) + (y / x));
		String resultado13 = "";
		resultado13 = resultado13 + ((a + c) + (b * z) + (y + d) + (a - z) + (x - c));
		resultado13 = resultado13 + ((d / a) + (z / y) + (d - c));
		resultado13 = resultado13 + ((y - x) + (e - x) + (b / c) + (c + a) + (a / b));
		String resultado14 = "";
		resultado14 = resultado14 + ((d - d) + (z - b) + (x + e));
		resultado14 = resultado14 + ((c - c) + (e * c) + (z + e) + (c - b) + (e * x));
		resultado14 = resultado14 + ((e - a) + (d * a) + (a / y) + (b * e) + (b / z));
		String resultado15 = "";
		resultado15 = resultado15 + ((a * e) + (b - c) + (y - c) + (x - d));
		resultado15 = resultado15 + ((e * x) + (a + c) + (y - a) + (x + z));
		resultado15 = resultado15 + ((c * z) + (a * y) + (x / x));
		resultado15 = resultado15 + ((x - x) + (a * d) + (y - z) + (b / b) + (x + c));
		resultado15 = resultado15 + ((e * z) + (y / x) + (b + a) + (x * e) + (x - y));
		String resultado16 = "";
		resultado16 = resultado16 + ((c * e) + (e / z) + (d - c) + (y * x));
		resultado16 = resultado16 + ((e / z) + (c - d) + (c - b) + (e + d));
		resultado16 = resultado16 + ((e + y) + (e - z) + (b / b) + (e * b));
		resultado16 = resultado16 + ((b + y) + (e / c) + (z / c) + (z - d));
		resultado16 = resultado16 + ((c * e) + (e * c) + (a - c) + (a - z) + (x / c));
		String resultado17 = "";
		resultado17 = resultado17 + ((z * b) + (x + b) + (e * e) + (y / b) + (c - d));
		resultado17 = resultado17 + ((y - e) + (z * z) + (c / a));
		resultado17 = resultado17 + ((x / x) + (b * z) + (y * x) + (b + x));
		resultado17 = resultado17 + ((b / x) + (z * c) + (b - y) + (b - c) + (e - e));
		String resultado18 = "";
		resultado18 = resultado18 + ((a + e) + (b + y) + (c * b));
		resultado18 = resultado18 + ((x + e) + (y / a) + (a - d));
		resultado18 = resultado18 + ((x * z) + (c / d) + (a / c) + (d * e));
		resultado18 = resultado18 + ((a / e) + (a * z) + (y / d) + (x + b) + (e + c));
		resultado18 = resultado18 + ((a + z) + (y * x) + (d * e) + (e + c) + (x - x));
		String resultado19 = "";
		resultado19 = resultado19 + ((d + z) + (c / y) + (c + b) + (z * z));
		resultado19 = resultado19 + ((d - e) + (c * z) + (a / y));
		resultado19 = resultado19 + ((z * z) + (z + b) + (z / c) + (c / z) + (a - z));
		String resultado20 = "";
		resultado20 = resultado20 + ((e * c) + (z + z) + (y * b) + (c / b) + (e * x));
		resultado20 = resultado20 + ((c + c) + (z * y) + (y + a) + (x + x) + (y / c));
		resultado20 = resultado20 + ((x / z) + (x + d) + (a - e) + (e / y));
		resultado20 = resultado20 + ((b * z) + (c - y) + (a * b) + (z - b));
		resultado20 = resultado20 + ((y * d) + (e * e) + (a + b) + (y * d) + (e / z));
		String resultado21 = "";
		resultado21 = resultado21 + ((y + x) + (d * c) + (b - c) + (a + c) + (d * d));
		resultado21 = resultado21 + ((b * e) + (z + a) + (e / d) + (d * x));
		resultado21 = resultado21 + ((a - a) + (d / c) + (z * b) + (c * b) + (x - z));
		String resultado22 = "";
		resultado22 = resultado22 + ((b * y) + (x + y) + (d * e) + (d * b));
		resultado22 = resultado22 + ((c / e) + (z - a) + (a * c) + (y + a) + (e + c));
		resultado22 = resultado22 + ((b - c) + (d - d) + (y - z));
		resultado22 = resultado22 + ((a + a) + (d + b) + (x * x) + (a / a) + (c - z));
		resultado22 = resultado22 + ((b - y) + (a * e) + (e * y) + (y / x) + (a + e));
		String resultado23 = "";
		resultado23 = resultado23 + ((d + a) + (e * y) + (e - e) + (c * a));
		resultado23 = resultado23 + ((a * y) + (c - y) + (e / d) + (y - x) + (b - d));
		resultado23 = resultado23 + ((d / b) + (z * c) + (z + z));
		String resultado24 = "";
		resultado24 = resultado24 + ((a / z) + (a / c) + (a + d));
		resultado24 = resultado24 + ((d / d) + (z * a) + (z + d));
		resultado24 = resultado24 + ((d - x) + (c - a) + (b * x) + (c + z) + (b / b));
		resultado24 = resultado24 + ((z / a) + (d - b) + (b + e));
		String resultado25 = "";
		resultado25 = resultado25 + ((x + z) + (a * z) + (e + y) + (b / e));
		resultado25 = resultado25 + ((z + x) + (z / b) + (c * y));
		resultado25 = resultado25 + ((x / d) + (y + a) + (e * x) + (b / y) + (c / b));
		resultado25 = resultado25 + ((e + d) + (z + e) + (x / c) + (c + d));
		String resultado26 = "";
		resultado26 = resultado26 + ((b * y) + (x - y) + (c - z));
		resultado26 = resultado26 + ((b - y) + (c + e) + (b * b) + (d - e));
		resultado26 = resultado26 + ((c / c) + (b / e) + (x * d) + (b * c) + (c - c));
		String resultado27 = "";
		resultado27 = resultado27 + ((y - z) + (x / e) + (d - e));
		resultado27 = resultado27 + ((c + a) + (e * d) + (y / d));
		resultado27 = resultado27 + ((c - z) + (c / e) + (e - c));
		resultado27 = resultado27 + ((e * b) + (x / c) + (b / y) + (b - c) + (c / b));
		String resultado28 = "";
		resultado28 = resultado28 + ((b + z) + (z - e) + (c + b) + (a + x) + (a * b));
		resultado28 = resultado28 + ((x + y) + (z * d) + (z - c));
		resultado28 = resultado28 + ((b - y) + (y / x) + (e + b) + (a + x));
		resultado28 = resultado28 + ((b + b) + (z / d) + (c - b) + (x - a));
		String resultado29 = "";
		resultado29 = resultado29 + ((e + z) + (b - x) + (z / a));
		resultado29 = resultado29 + ((c / x) + (x * y) + (x + c));
		resultado29 = resultado29 + ((y - y) + (c + z) + (e + e) + (y / c) + (y - d));
		resultado29 = resultado29 + ((b + a) + (d + a) + (e * y) + (c / e));
		String resultado30 = "";
		resultado30 = resultado30 + ((d - b) + (c / e) + (d / a) + (a - b) + (c * a));
		resultado30 = resultado30 + ((x - b) + (c - c) + (z * a) + (c / a));
		resultado30 = resultado30 + ((c - d) + (e + z) + (d + z) + (x / y) + (d + e));
		resultado30 = resultado30 + ((e / a) + (z / e) + (b + y));
		String resultado31 = "";
		resultado31 = resultado31 + ((a * b) + (e / y) + (y - z) + (x / b) + (b - x));
		resultado31 = resultado31 + ((c / z) + (b * z) + (y * e) + (d * e) + (y * z));
		resultado31 = resultado31 + ((b / x) + (y + b) + (c + x) + (c * z) + (e / a));
		String resultado32 = "";
		resultado32 = resultado32 + ((a * c) + (x - a) + (b - c) + (y / e) + (c + c));
		resultado32 = resultado32 + ((e + b) + (e + a) + (z * c) + (x - z));
		resultado32 = resultado32 + ((c + e) + (x * x) + (a / z) + (c * b));
		resultado32 = resultado32 + ((c * z) + (e * x) + (d - a));
		resultado32 = resultado32 + ((d - a) + (a / c) + (z * a) + (z * d));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}