package br.com.av1.prova18;

public class Questao4 {
	public static void main(String[] args) {
		int a = 7;
		int b = 6;
		int c = 7;
		int d = 5;
		int e = 3;
		int x = 7;
		int y = 5;
		int z = 7;

		String resultado1 = "";
		resultado1 = resultado1 + ((e / y) + (e / x) + (d * y) + (c * x));
		resultado1 = resultado1 + ((a * a) + (z * y) + (x - b));
		resultado1 = resultado1 + ((d * b) + (e * c) + (z * y) + (x - x));
		String resultado2 = "";
		resultado2 = resultado2 + ((e - c) + (z + a) + (b * e));
		resultado2 = resultado2 + ((b / b) + (y - x) + (x / e) + (e - d));
		resultado2 = resultado2 + ((d - y) + (b + e) + (y * e) + (x / c) + (y - e));
		String resultado3 = "";
		resultado3 = resultado3 + ((a + d) + (z * b) + (d + z));
		resultado3 = resultado3 + ((c + d) + (d * d) + (y + a) + (e * z) + (y * c));
		resultado3 = resultado3 + ((z + d) + (c * d) + (x / b));
		String resultado4 = "";
		resultado4 = resultado4 + ((a - x) + (b * x) + (z - x) + (e + c));
		resultado4 = resultado4 + ((c + x) + (y + c) + (d - c) + (x / c));
		resultado4 = resultado4 + ((x * c) + (x * y) + (z * x));
		resultado4 = resultado4 + ((x / e) + (c * z) + (e * c));
		resultado4 = resultado4 + ((z * z) + (c * y) + (b - y) + (z - x) + (a / z));
		String resultado5 = "";
		resultado5 = resultado5 + ((e / d) + (d * d) + (b / x));
		resultado5 = resultado5 + ((a * d) + (z / e) + (x - d) + (a / c));
		resultado5 = resultado5 + ((c - a) + (e - a) + (c * y) + (y / z) + (a * d));
		resultado5 = resultado5 + ((b / z) + (c * x) + (d - b) + (x * x));
		resultado5 = resultado5 + ((x * b) + (c * b) + (x + a) + (e - b) + (b * a));
		String resultado6 = "";
		resultado6 = resultado6 + ((a / c) + (c * d) + (a - z) + (c + b) + (z + c));
		resultado6 = resultado6 + ((x * d) + (x + a) + (c / b) + (e - c) + (z - x));
		resultado6 = resultado6 + ((e / a) + (e - a) + (c / a) + (z - z) + (z + z));
		String resultado7 = "";
		resultado7 = resultado7 + ((z - y) + (a * z) + (d / b) + (b + d) + (z - b));
		resultado7 = resultado7 + ((y / e) + (a + e) + (b / c) + (b + a) + (a * x));
		resultado7 = resultado7 + ((y - a) + (y - d) + (x - y) + (c - c));
		resultado7 = resultado7 + ((d - y) + (c / z) + (d - x) + (b * z) + (z + b));
		String resultado8 = "";
		resultado8 = resultado8 + ((b * b) + (e + z) + (a / x) + (b * x) + (e + e));
		resultado8 = resultado8 + ((a * e) + (a / b) + (b - d));
		resultado8 = resultado8 + ((z + x) + (d + a) + (a + e));
		String resultado9 = "";
		resultado9 = resultado9 + ((x / d) + (e / y) + (e / d));
		resultado9 = resultado9 + ((c * z) + (a - b) + (a / a));
		resultado9 = resultado9 + ((e + y) + (d / e) + (z / y));
		resultado9 = resultado9 + ((a - d) + (z * d) + (a - y) + (c * e));
		String resultado10 = "";
		resultado10 = resultado10 + ((y - a) + (d - y) + (x / b) + (x + a) + (d - x));
		resultado10 = resultado10 + ((x / z) + (d * z) + (e + d) + (e / y) + (d * y));
		resultado10 = resultado10 + ((a + x) + (x + y) + (a - d));
		resultado10 = resultado10 + ((e * e) + (b / e) + (y / c) + (b / x) + (e / c));
		String resultado11 = "";
		resultado11 = resultado11 + ((z / y) + (y * z) + (b / e));
		resultado11 = resultado11 + ((a + e) + (c + a) + (c - c));
		resultado11 = resultado11 + ((b + e) + (x / z) + (a * x) + (z * a) + (a / d));
		resultado11 = resultado11 + ((b * x) + (y + y) + (a * b));
		String resultado12 = "";
		resultado12 = resultado12 + ((y * d) + (e * b) + (c + e));
		resultado12 = resultado12 + ((e * y) + (e - a) + (z + b) + (e + c) + (c * y));
		resultado12 = resultado12 + ((a - c) + (a / a) + (b + z) + (z * c));
		resultado12 = resultado12 + ((d + b) + (e - a) + (e + e));
		resultado12 = resultado12 + ((z + z) + (d - d) + (a * b));
		String resultado13 = "";
		resultado13 = resultado13 + ((d / x) + (c * a) + (d / e));
		resultado13 = resultado13 + ((e - z) + (e * d) + (x + a));
		resultado13 = resultado13 + ((c + c) + (a + d) + (a - a) + (d * b) + (a * c));
		String resultado14 = "";
		resultado14 = resultado14 + ((c + b) + (z + b) + (d * d) + (y - a) + (x - z));
		resultado14 = resultado14 + ((b / y) + (y / e) + (e * x));
		resultado14 = resultado14 + ((x / e) + (c * b) + (x - b) + (b / a));
		resultado14 = resultado14 + ((b * x) + (c + x) + (x / d) + (e - a) + (d * z));
		resultado14 = resultado14 + ((z - b) + (c / z) + (b / z));
		String resultado15 = "";
		resultado15 = resultado15 + ((y * x) + (e - d) + (x - x) + (c / d));
		resultado15 = resultado15 + ((y + d) + (b * x) + (z + a));
		resultado15 = resultado15 + ((a + b) + (a + z) + (e + a) + (b - d) + (b / c));
		resultado15 = resultado15 + ((y / c) + (e + b) + (c - z));
		resultado15 = resultado15 + ((y + c) + (z - b) + (e + b) + (d * a));
		String resultado16 = "";
		resultado16 = resultado16 + ((z - z) + (x * d) + (y - y) + (a - c));
		resultado16 = resultado16 + ((d * e) + (c * e) + (b - x) + (x * y) + (c * x));
		resultado16 = resultado16 + ((d / y) + (z - c) + (c + a) + (y - b) + (z - e));
		String resultado17 = "";
		resultado17 = resultado17 + ((d + z) + (d / d) + (x * c) + (z / b));
		resultado17 = resultado17 + ((y + e) + (b + a) + (y - d));
		resultado17 = resultado17 + ((y * c) + (z / d) + (z / x) + (z * a));
		resultado17 = resultado17 + ((z * z) + (a - b) + (e - x));
		resultado17 = resultado17 + ((d * c) + (z + x) + (z * b));
		String resultado18 = "";
		resultado18 = resultado18 + ((e * z) + (d / a) + (d + c) + (a / e) + (z - c));
		resultado18 = resultado18 + ((a * y) + (c + e) + (c / z) + (b + d) + (y + c));
		resultado18 = resultado18 + ((e / a) + (e - b) + (c - z) + (b * b) + (c / b));
		String resultado19 = "";
		resultado19 = resultado19 + ((d - e) + (b - z) + (e / a) + (c - d) + (b * a));
		resultado19 = resultado19 + ((e - y) + (d * a) + (c + b) + (d - z));
		resultado19 = resultado19 + ((c / y) + (c * d) + (e / e));
		resultado19 = resultado19 + ((d / x) + (x * a) + (a / c) + (e + z));
		resultado19 = resultado19 + ((y - b) + (e - x) + (b / e) + (a + z));
		String resultado20 = "";
		resultado20 = resultado20 + ((c + z) + (x - x) + (x * x) + (e + y));
		resultado20 = resultado20 + ((x - y) + (d + z) + (c + z) + (z / c));
		resultado20 = resultado20 + ((c + c) + (z / b) + (d - z));
		resultado20 = resultado20 + ((z / y) + (e - b) + (c / e));
		String resultado21 = "";
		resultado21 = resultado21 + ((d - x) + (b * c) + (d * d));
		resultado21 = resultado21 + ((e - y) + (a - a) + (c / b) + (y / x));
		resultado21 = resultado21 + ((y * a) + (a - x) + (y + a));
		resultado21 = resultado21 + ((c * y) + (c / x) + (x - a) + (b * x));
		String resultado22 = "";
		resultado22 = resultado22 + ((y + y) + (x * b) + (a - e));
		resultado22 = resultado22 + ((a / a) + (b + a) + (d * x) + (y - e) + (z / a));
		resultado22 = resultado22 + ((z - d) + (b + y) + (z - x) + (z - d));
		resultado22 = resultado22 + ((y + c) + (d - y) + (y / z) + (y / x));
		resultado22 = resultado22 + ((b + z) + (x / b) + (c + a) + (z * z));
		String resultado23 = "";
		resultado23 = resultado23 + ((z + e) + (a * c) + (c * c) + (b * e) + (e * a));
		resultado23 = resultado23 + ((d / z) + (y / y) + (b - b));
		resultado23 = resultado23 + ((d + b) + (x - d) + (d * z) + (y + e) + (a / a));
		String resultado24 = "";
		resultado24 = resultado24 + ((d / b) + (z * y) + (b * x) + (b / y) + (a / b));
		resultado24 = resultado24 + ((b - z) + (z * z) + (b - y) + (b * c));
		resultado24 = resultado24 + ((a * a) + (d + c) + (e * b) + (b - d));
		resultado24 = resultado24 + ((b + z) + (a + z) + (z * b) + (x + x) + (b - b));
		resultado24 = resultado24 + ((e + e) + (a + c) + (c * x) + (z * x));
		String resultado25 = "";
		resultado25 = resultado25 + ((d / a) + (e - x) + (z - b));
		resultado25 = resultado25 + ((c - e) + (y / z) + (b - d) + (x + e));
		resultado25 = resultado25 + ((a + d) + (y * z) + (e + e) + (e * x));
		resultado25 = resultado25 + ((x * e) + (z - x) + (c / c) + (a * x));
		String resultado26 = "";
		resultado26 = resultado26 + ((x + c) + (d / d) + (a * z) + (z + a));
		resultado26 = resultado26 + ((z / b) + (d - y) + (x / z) + (d / c));
		resultado26 = resultado26 + ((y / e) + (a + e) + (z / z));
		resultado26 = resultado26 + ((b + b) + (x * d) + (z + d) + (z - b));
		resultado26 = resultado26 + ((a / z) + (e - d) + (e - y));
		String resultado27 = "";
		resultado27 = resultado27 + ((z / e) + (z / d) + (b - z) + (c + e) + (e * y));
		resultado27 = resultado27 + ((x - y) + (a + b) + (a * x) + (a * b));
		resultado27 = resultado27 + ((e / c) + (d * e) + (a / b) + (d - e));
		resultado27 = resultado27 + ((x / z) + (x + x) + (e * d) + (d - a));
		resultado27 = resultado27 + ((x - y) + (c * x) + (y + d) + (e / z) + (d / e));
		String resultado28 = "";
		resultado28 = resultado28 + ((z / x) + (y * a) + (b * d));
		resultado28 = resultado28 + ((x / b) + (a - a) + (e - c));
		resultado28 = resultado28 + ((a + z) + (y / z) + (c / x));
		resultado28 = resultado28 + ((c * b) + (x * d) + (c + z) + (a - d));
		resultado28 = resultado28 + ((b / b) + (a + y) + (a * e) + (e + z));
		String resultado29 = "";
		resultado29 = resultado29 + ((x - y) + (b / c) + (x / e) + (e - b));
		resultado29 = resultado29 + ((d * c) + (c - c) + (c / a));
		resultado29 = resultado29 + ((d / x) + (e - a) + (y * x) + (b / x) + (z - x));
		String resultado30 = "";
		resultado30 = resultado30 + ((b + d) + (d + x) + (z * z) + (x + d) + (y / b));
		resultado30 = resultado30 + ((z / b) + (c - z) + (a + c) + (a - z));
		resultado30 = resultado30 + ((d - b) + (b - y) + (e / a) + (x - d) + (x / c));
		resultado30 = resultado30 + ((c / z) + (c * c) + (z * y) + (z * e));
		resultado30 = resultado30 + ((c + x) + (b + e) + (x / z) + (x / x) + (b * b));
		String resultado31 = "";
		resultado31 = resultado31 + ((x / d) + (b / a) + (y / y) + (z + b) + (d / y));
		resultado31 = resultado31 + ((c + z) + (x - d) + (e * c) + (x / a) + (a / y));
		resultado31 = resultado31 + ((d - x) + (e / z) + (c + c));
		String resultado32 = "";
		resultado32 = resultado32 + ((z / a) + (y + c) + (c / y));
		resultado32 = resultado32 + ((a / c) + (c + a) + (e - y) + (c + c) + (x - d));
		resultado32 = resultado32 + ((b * x) + (d - b) + (c - b) + (e - a) + (d + d));
		resultado32 = resultado32 + ((b - b) + (a + z) + (z * d));
		resultado32 = resultado32 + ((c * a) + (d + y) + (e * z) + (y / z));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}