package br.com.av1.prova21;

public class Questao4 {
	public static void main(String[] args) {
		int a = 9;
		int b = 6;
		int c = 10;
		int d = 1;
		int e = 6;
		int x = 4;
		int y = 9;
		int z = 7;

		String resultado1 = "";
		resultado1 = resultado1 + ((e * y) + (e + b) + (a - a) + (y / b));
		resultado1 = resultado1 + ((z + d) + (e - d) + (x + x) + (a / y) + (d * a));
		resultado1 = resultado1 + ((a / b) + (z + z) + (c - x));
		String resultado2 = "";
		resultado2 = resultado2 + ((c - y) + (e / d) + (d * e) + (c + c));
		resultado2 = resultado2 + ((d / c) + (y / a) + (a - b));
		resultado2 = resultado2 + ((x / b) + (d * z) + (y - x) + (c + x));
		String resultado3 = "";
		resultado3 = resultado3 + ((y + x) + (e - d) + (e + d) + (x * d) + (a + a));
		resultado3 = resultado3 + ((a - x) + (d - z) + (c / d) + (y - e) + (x * d));
		resultado3 = resultado3 + ((x - a) + (a * b) + (e * a) + (d / e));
		String resultado4 = "";
		resultado4 = resultado4 + ((e + x) + (c / y) + (e * z));
		resultado4 = resultado4 + ((e + x) + (b * z) + (z + d) + (e - a) + (e * x));
		resultado4 = resultado4 + ((c * y) + (z * y) + (d / a));
		resultado4 = resultado4 + ((a - z) + (b - e) + (e / y) + (c + z));
		resultado4 = resultado4 + ((x - b) + (d + c) + (z / c) + (z + e) + (c / d));
		String resultado5 = "";
		resultado5 = resultado5 + ((z * c) + (d + b) + (d / z) + (b / z) + (d + z));
		resultado5 = resultado5 + ((x - y) + (x + d) + (b - c) + (b * c) + (e / x));
		resultado5 = resultado5 + ((d - y) + (b - b) + (a + z) + (c - b) + (z / z));
		resultado5 = resultado5 + ((e - a) + (c - c) + (b * y));
		String resultado6 = "";
		resultado6 = resultado6 + ((y / b) + (b * z) + (d - d) + (d * y) + (c - b));
		resultado6 = resultado6 + ((x - d) + (e * a) + (a - x) + (b * z));
		resultado6 = resultado6 + ((y - b) + (d - z) + (d * c) + (b / b));
		String resultado7 = "";
		resultado7 = resultado7 + ((d * d) + (z * y) + (y - y));
		resultado7 = resultado7 + ((a + e) + (c / d) + (y * e));
		resultado7 = resultado7 + ((c / x) + (b / y) + (x - e));
		String resultado8 = "";
		resultado8 = resultado8 + ((c / d) + (z - z) + (c / x) + (z * b));
		resultado8 = resultado8 + ((y - a) + (c / a) + (e - d) + (y * c) + (a - b));
		resultado8 = resultado8 + ((y * b) + (c - b) + (z / z) + (e * d) + (b - c));
		resultado8 = resultado8 + ((a + b) + (e * c) + (e / a) + (d - x));
		String resultado9 = "";
		resultado9 = resultado9 + ((e * x) + (x - e) + (a + z) + (b - c) + (y * z));
		resultado9 = resultado9 + ((b / x) + (b - c) + (z - z) + (e / d));
		resultado9 = resultado9 + ((z - c) + (e / a) + (y / e));
		resultado9 = resultado9 + ((c + a) + (d + z) + (e * z));
		resultado9 = resultado9 + ((y * z) + (e + e) + (x - z) + (x * e) + (a - z));
		String resultado10 = "";
		resultado10 = resultado10 + ((d + x) + (x * e) + (c / a) + (d / a));
		resultado10 = resultado10 + ((x * e) + (z + a) + (d - a));
		resultado10 = resultado10 + ((b + d) + (x + c) + (a - a));
		resultado10 = resultado10 + ((c / d) + (x / c) + (x - z));
		resultado10 = resultado10 + ((e * c) + (b * c) + (e - a));
		String resultado11 = "";
		resultado11 = resultado11 + ((e + b) + (b - x) + (b / b) + (y * c));
		resultado11 = resultado11 + ((a + e) + (c - z) + (c * x) + (b * b) + (y + x));
		resultado11 = resultado11 + ((y * c) + (c * y) + (e + b) + (x + a));
		resultado11 = resultado11 + ((b * b) + (b + c) + (a / z) + (c - y) + (z * c));
		String resultado12 = "";
		resultado12 = resultado12 + ((z * d) + (z - b) + (y * y) + (b + a));
		resultado12 = resultado12 + ((y * x) + (e / b) + (x + z) + (x + d));
		resultado12 = resultado12 + ((d + d) + (a - x) + (y / d));
		resultado12 = resultado12 + ((e * z) + (c * c) + (c * b));
		String resultado13 = "";
		resultado13 = resultado13 + ((a / b) + (x + z) + (c / b) + (x / e) + (z / b));
		resultado13 = resultado13 + ((b + a) + (z - e) + (d * d) + (e + z) + (b - a));
		resultado13 = resultado13 + ((b * d) + (z / b) + (d + y) + (x * z) + (y - x));
		resultado13 = resultado13 + ((b / y) + (b * e) + (y - x));
		String resultado14 = "";
		resultado14 = resultado14 + ((a * a) + (b - c) + (a - d) + (x * z) + (c - x));
		resultado14 = resultado14 + ((a - b) + (c * a) + (c + y) + (x + x) + (x + c));
		resultado14 = resultado14 + ((z + a) + (b * e) + (y + y) + (b - b));
		resultado14 = resultado14 + ((a / e) + (b / d) + (y * z));
		resultado14 = resultado14 + ((y - d) + (a * x) + (c + e) + (y + z));
		String resultado15 = "";
		resultado15 = resultado15 + ((x - d) + (d / b) + (y - e));
		resultado15 = resultado15 + ((e - a) + (x - a) + (e / c) + (d - d) + (d + e));
		resultado15 = resultado15 + ((e + a) + (x + d) + (b + a));
		resultado15 = resultado15 + ((y + c) + (z / x) + (d - e));
		resultado15 = resultado15 + ((a + e) + (z / b) + (c + z));
		String resultado16 = "";
		resultado16 = resultado16 + ((d + e) + (d - z) + (y + e) + (x * x));
		resultado16 = resultado16 + ((e - e) + (y + z) + (b - c) + (e / b));
		resultado16 = resultado16 + ((e * a) + (c - z) + (z / z) + (b / z));
		resultado16 = resultado16 + ((y / b) + (x / d) + (e * d) + (e / a) + (y * a));
		String resultado17 = "";
		resultado17 = resultado17 + ((a + y) + (d / e) + (z + y) + (z / x));
		resultado17 = resultado17 + ((a * a) + (e - y) + (y * d) + (c + y));
		resultado17 = resultado17 + ((z * y) + (a / d) + (a / y) + (x - a) + (a + b));
		String resultado18 = "";
		resultado18 = resultado18 + ((c - a) + (c - a) + (x + a));
		resultado18 = resultado18 + ((b - x) + (y + x) + (c - a) + (z / z));
		resultado18 = resultado18 + ((z + d) + (b + c) + (d + b));
		resultado18 = resultado18 + ((a / x) + (x - c) + (x - d) + (a + a) + (c * b));
		String resultado19 = "";
		resultado19 = resultado19 + ((d * x) + (z * d) + (y - c) + (z + c));
		resultado19 = resultado19 + ((e + a) + (z + e) + (a * a));
		resultado19 = resultado19 + ((x / d) + (d - y) + (z / d));
		resultado19 = resultado19 + ((a / c) + (z / c) + (d + e) + (a + a) + (c + y));
		resultado19 = resultado19 + ((z + b) + (z / d) + (y / e) + (d * x));
		String resultado20 = "";
		resultado20 = resultado20 + ((x / d) + (z / c) + (c * x) + (d + x));
		resultado20 = resultado20 + ((z - z) + (x - e) + (b - b) + (c * d) + (c * d));
		resultado20 = resultado20 + ((e - c) + (x - c) + (z * b) + (y - z) + (e - c));
		String resultado21 = "";
		resultado21 = resultado21 + ((d * b) + (z + b) + (e / a) + (z - z));
		resultado21 = resultado21 + ((c * y) + (y * a) + (d - c) + (z * a) + (x + z));
		resultado21 = resultado21 + ((c / y) + (y + y) + (d - e) + (c / b) + (c - e));
		resultado21 = resultado21 + ((y - b) + (b + c) + (b - x));
		resultado21 = resultado21 + ((x - b) + (a - x) + (y - a));
		String resultado22 = "";
		resultado22 = resultado22 + ((c - e) + (x / y) + (d / c));
		resultado22 = resultado22 + ((y / d) + (b * c) + (e - b) + (x * d) + (a * y));
		resultado22 = resultado22 + ((x - d) + (x / e) + (d * z) + (y * z));
		resultado22 = resultado22 + ((x + c) + (x * y) + (y * a) + (x - x) + (e * c));
		String resultado23 = "";
		resultado23 = resultado23 + ((d * b) + (y + d) + (c * b) + (y - x));
		resultado23 = resultado23 + ((c + d) + (z + c) + (y - x) + (d / x));
		resultado23 = resultado23 + ((e / z) + (c + y) + (a / c));
		resultado23 = resultado23 + ((z * d) + (x - b) + (b * b));
		String resultado24 = "";
		resultado24 = resultado24 + ((c - e) + (e / y) + (x - c) + (y * y) + (a / c));
		resultado24 = resultado24 + ((a + y) + (y / b) + (y * e));
		resultado24 = resultado24 + ((d / y) + (d - e) + (e + d));
		resultado24 = resultado24 + ((x - a) + (y * y) + (x + y) + (y / x));
		resultado24 = resultado24 + ((e - y) + (c * y) + (z - z) + (c - x) + (y / b));
		String resultado25 = "";
		resultado25 = resultado25 + ((z * d) + (d + z) + (d + z));
		resultado25 = resultado25 + ((y / b) + (z - b) + (x / x));
		resultado25 = resultado25 + ((c * y) + (x * d) + (z / d) + (y * x));
		String resultado26 = "";
		resultado26 = resultado26 + ((c + b) + (d + x) + (b / y) + (d / d) + (c / b));
		resultado26 = resultado26 + ((z / z) + (d / z) + (c - x) + (x + e));
		resultado26 = resultado26 + ((z / y) + (c / c) + (a / x) + (a * a) + (c - z));
		String resultado27 = "";
		resultado27 = resultado27 + ((b / d) + (a + b) + (y / y) + (z * d));
		resultado27 = resultado27 + ((y - e) + (d - e) + (c / y));
		resultado27 = resultado27 + ((y - e) + (y * x) + (e / a) + (d * c) + (y - y));
		resultado27 = resultado27 + ((b + x) + (b * a) + (y * z) + (z / x) + (b / e));
		resultado27 = resultado27 + ((z * d) + (a / a) + (a - z) + (d - a));
		String resultado28 = "";
		resultado28 = resultado28 + ((c / y) + (y + a) + (e + e) + (e * c) + (a * d));
		resultado28 = resultado28 + ((z + d) + (c / z) + (a / e) + (e - x) + (x + y));
		resultado28 = resultado28 + ((x / x) + (c - z) + (b + b) + (a / y));
		resultado28 = resultado28 + ((c / e) + (a - x) + (z * b));
		String resultado29 = "";
		resultado29 = resultado29 + ((x - d) + (b + e) + (a - a));
		resultado29 = resultado29 + ((x - y) + (z + b) + (a / a));
		resultado29 = resultado29 + ((a - a) + (d / z) + (x * e));
		resultado29 = resultado29 + ((d / x) + (b - b) + (c - a) + (c * d) + (b - a));
		resultado29 = resultado29 + ((z - c) + (e - e) + (c - d) + (a * e));
		String resultado30 = "";
		resultado30 = resultado30 + ((z / c) + (c + b) + (c * x) + (c / d) + (e * b));
		resultado30 = resultado30 + ((b + y) + (e + x) + (y / z) + (d / e) + (z / z));
		resultado30 = resultado30 + ((a * y) + (b / x) + (c / x) + (e + a));
		resultado30 = resultado30 + ((b / x) + (b + d) + (d - a) + (b - c));
		resultado30 = resultado30 + ((d + b) + (e - x) + (y + x));
		String resultado31 = "";
		resultado31 = resultado31 + ((x / c) + (d + c) + (c + c) + (y / x));
		resultado31 = resultado31 + ((x / y) + (y / d) + (y + d) + (x / a));
		resultado31 = resultado31 + ((x * c) + (d / e) + (c + c));
		resultado31 = resultado31 + ((b + d) + (a * b) + (a + d) + (y / b) + (e + e));
		resultado31 = resultado31 + ((a * x) + (d + y) + (a / b) + (e - a));
		String resultado32 = "";
		resultado32 = resultado32 + ((a - z) + (d / y) + (z * y));
		resultado32 = resultado32 + ((x - a) + (d * b) + (a - x) + (e - d) + (d / x));
		resultado32 = resultado32 + ((c - x) + (d * c) + (z - a) + (e - e) + (x * d));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}