package br.com.av1.prova13;

public class Questao4 {
	public static void main(String[] args) {
		int a = 5;
		int b = 7;
		int c = 9;
		int d = 6;
		int e = 4;
		int x = 5;
		int y = 9;
		int z = 6;

		String resultado1 = "";
		resultado1 = resultado1 + ((z / b) + (y - z) + (x / e) + (z + y));
		resultado1 = resultado1 + ((d - y) + (y * z) + (c + z));
		resultado1 = resultado1 + ((d + e) + (z / b) + (b / y));
		resultado1 = resultado1 + ((z / x) + (e / z) + (y - e));
		String resultado2 = "";
		resultado2 = resultado2 + ((y / y) + (y * y) + (b / a) + (z + b) + (e / y));
		resultado2 = resultado2 + ((c / a) + (b / a) + (b * e) + (b - d));
		resultado2 = resultado2 + ((x + b) + (d / e) + (y - y));
		resultado2 = resultado2 + ((b / y) + (b - b) + (e / c) + (b / c));
		String resultado3 = "";
		resultado3 = resultado3 + ((x * z) + (a + e) + (y - x) + (e - d));
		resultado3 = resultado3 + ((x + b) + (z - c) + (y + z));
		resultado3 = resultado3 + ((b - z) + (b / z) + (c * a) + (d * z) + (c + x));
		resultado3 = resultado3 + ((z / z) + (b / y) + (e * z) + (a + b));
		resultado3 = resultado3 + ((e / a) + (b * b) + (z / c));
		String resultado4 = "";
		resultado4 = resultado4 + ((e + c) + (a - y) + (d - b) + (b + x));
		resultado4 = resultado4 + ((b - e) + (y + b) + (d - e) + (x * c));
		resultado4 = resultado4 + ((y * z) + (z - b) + (z - c) + (e * b));
		resultado4 = resultado4 + ((z + z) + (x * c) + (x - b) + (y / x));
		resultado4 = resultado4 + ((d / e) + (c + z) + (c - x));
		String resultado5 = "";
		resultado5 = resultado5 + ((b * z) + (c / c) + (b / y));
		resultado5 = resultado5 + ((y * x) + (b + e) + (z - y) + (d + d));
		resultado5 = resultado5 + ((c * a) + (b + d) + (d / c) + (y - d));
		resultado5 = resultado5 + ((e + e) + (a / d) + (a - y));
		resultado5 = resultado5 + ((b * d) + (y - c) + (x - x) + (b - z));
		String resultado6 = "";
		resultado6 = resultado6 + ((e + a) + (y + z) + (e * x) + (b + e) + (d + y));
		resultado6 = resultado6 + ((b - b) + (x + b) + (x - a));
		resultado6 = resultado6 + ((z - a) + (e * a) + (a * z) + (y - a) + (e + x));
		String resultado7 = "";
		resultado7 = resultado7 + ((x / z) + (b / a) + (d + d) + (e / z) + (e * c));
		resultado7 = resultado7 + ((b - z) + (d / e) + (a * c));
		resultado7 = resultado7 + ((b * y) + (d + y) + (z / a) + (a - c) + (z * a));
		resultado7 = resultado7 + ((x - z) + (c * b) + (x * y) + (b / y));
		resultado7 = resultado7 + ((c / b) + (e + x) + (z + b) + (a - y));
		String resultado8 = "";
		resultado8 = resultado8 + ((y * a) + (e - b) + (e * y));
		resultado8 = resultado8 + ((a + x) + (b - d) + (b + d) + (e + d) + (d + c));
		resultado8 = resultado8 + ((x + z) + (x + y) + (b - z));
		resultado8 = resultado8 + ((y - z) + (c + a) + (c / e));
		String resultado9 = "";
		resultado9 = resultado9 + ((e * y) + (d + b) + (x + b));
		resultado9 = resultado9 + ((b * y) + (d / y) + (d + c) + (c / e) + (x - z));
		resultado9 = resultado9 + ((c - a) + (c / c) + (y * a) + (a / a));
		resultado9 = resultado9 + ((d / z) + (a - c) + (b * c) + (a / z));
		resultado9 = resultado9 + ((e - c) + (c - z) + (b + y) + (z / e));
		String resultado10 = "";
		resultado10 = resultado10 + ((b - x) + (d + a) + (c * d));
		resultado10 = resultado10 + ((c - d) + (a - c) + (y + d) + (a + y) + (c / a));
		resultado10 = resultado10 + ((z - x) + (x + x) + (a + z) + (d - c) + (c + b));
		String resultado11 = "";
		resultado11 = resultado11 + ((y * z) + (x / x) + (z * z) + (e - e) + (d - b));
		resultado11 = resultado11 + ((x - z) + (c * y) + (x / c));
		resultado11 = resultado11 + ((z + d) + (z + z) + (b / e));
		resultado11 = resultado11 + ((b / c) + (y + b) + (e * x));
		resultado11 = resultado11 + ((a - e) + (a / e) + (c * c) + (c / e) + (z / d));
		String resultado12 = "";
		resultado12 = resultado12 + ((z + z) + (z / y) + (z * a) + (c * z));
		resultado12 = resultado12 + ((d + z) + (y + z) + (b * d));
		resultado12 = resultado12 + ((x - x) + (x + y) + (c * y));
		resultado12 = resultado12 + ((z / e) + (b + d) + (x + z) + (d * a));
		resultado12 = resultado12 + ((b * a) + (e + d) + (c * x) + (e / b));
		String resultado13 = "";
		resultado13 = resultado13 + ((c - x) + (d - x) + (a - e) + (e / c) + (y / d));
		resultado13 = resultado13 + ((z * e) + (x - c) + (c + a) + (e - e) + (z - z));
		resultado13 = resultado13 + ((b / d) + (x * d) + (a / c) + (z - e));
		String resultado14 = "";
		resultado14 = resultado14 + ((e / e) + (x / z) + (z * y) + (x * x) + (b + y));
		resultado14 = resultado14 + ((a - z) + (e / x) + (x * y) + (e - a) + (y * a));
		resultado14 = resultado14 + ((a * d) + (e / a) + (b + z) + (e + e) + (a - d));
		resultado14 = resultado14 + ((z - y) + (x - x) + (a + c) + (d - x));
		String resultado15 = "";
		resultado15 = resultado15 + ((a * y) + (b * b) + (b * d) + (y / b));
		resultado15 = resultado15 + ((a - a) + (z + z) + (z / c) + (e / x) + (b + z));
		resultado15 = resultado15 + ((x + d) + (a * e) + (y + c) + (c + c) + (d / b));
		resultado15 = resultado15 + ((c / a) + (z - e) + (c * b) + (a * e));
		resultado15 = resultado15 + ((z - y) + (x - d) + (e * d) + (a - d));
		String resultado16 = "";
		resultado16 = resultado16 + ((a + d) + (y / x) + (d + z));
		resultado16 = resultado16 + ((z + e) + (e * z) + (x * a) + (y / z));
		resultado16 = resultado16 + ((y / z) + (e - y) + (y - z));
		resultado16 = resultado16 + ((e / c) + (d + x) + (x - c) + (y * x));
		resultado16 = resultado16 + ((d + a) + (x - y) + (d / y));
		String resultado17 = "";
		resultado17 = resultado17 + ((x + c) + (y + c) + (b + y));
		resultado17 = resultado17 + ((c + e) + (d - z) + (a / x));
		resultado17 = resultado17 + ((x / z) + (b / c) + (b + x));
		resultado17 = resultado17 + ((e * a) + (e * b) + (e * e));
		String resultado18 = "";
		resultado18 = resultado18 + ((d * e) + (x - a) + (d / c) + (e + e));
		resultado18 = resultado18 + ((z * c) + (b / e) + (d * a));
		resultado18 = resultado18 + ((z / y) + (a + y) + (x * b) + (x - y) + (d + x));
		String resultado19 = "";
		resultado19 = resultado19 + ((d + e) + (d + d) + (b / y) + (x + a) + (d / x));
		resultado19 = resultado19 + ((e / y) + (b / y) + (b * z) + (c / e));
		resultado19 = resultado19 + ((b * d) + (b - d) + (e * c) + (c / e) + (z / a));
		resultado19 = resultado19 + ((b - b) + (z * b) + (x - e) + (z / z) + (c * d));
		String resultado20 = "";
		resultado20 = resultado20 + ((d / c) + (c + e) + (d - a));
		resultado20 = resultado20 + ((y - z) + (a - x) + (a / c));
		resultado20 = resultado20 + ((b / y) + (c + z) + (a / c));
		resultado20 = resultado20 + ((e - b) + (c * c) + (a - x));
		String resultado21 = "";
		resultado21 = resultado21 + ((e + y) + (e * c) + (d / d));
		resultado21 = resultado21 + ((d * d) + (b - c) + (b + x));
		resultado21 = resultado21 + ((a - d) + (y - c) + (y - c) + (z * e));
		resultado21 = resultado21 + ((x + x) + (e / b) + (z - z) + (c - b) + (d / a));
		resultado21 = resultado21 + ((z + b) + (d / c) + (b * d) + (a - z) + (z - b));
		String resultado22 = "";
		resultado22 = resultado22 + ((c - y) + (d * a) + (e + y));
		resultado22 = resultado22 + ((e / z) + (c + x) + (y - a));
		resultado22 = resultado22 + ((c / c) + (y * d) + (y - x) + (b + e) + (e / x));
		resultado22 = resultado22 + ((e - z) + (c / e) + (d / b) + (c / z) + (b + d));
		resultado22 = resultado22 + ((c + a) + (z + a) + (z - x) + (y * d));
		String resultado23 = "";
		resultado23 = resultado23 + ((a * x) + (y / d) + (z / a) + (c / b) + (c - x));
		resultado23 = resultado23 + ((a + c) + (c / a) + (e + d) + (c * x));
		resultado23 = resultado23 + ((y - b) + (b * z) + (a + y));
		resultado23 = resultado23 + ((a - a) + (z - a) + (a / x));
		String resultado24 = "";
		resultado24 = resultado24 + ((c / c) + (b + e) + (z / d) + (z / x) + (z - b));
		resultado24 = resultado24 + ((b * y) + (d * y) + (y + e) + (d - y) + (y * c));
		resultado24 = resultado24 + ((b - d) + (e + d) + (a - y) + (y / y));
		String resultado25 = "";
		resultado25 = resultado25 + ((b / z) + (y + x) + (d * z) + (d * a) + (d + x));
		resultado25 = resultado25 + ((y - y) + (d * x) + (e * z) + (b - d) + (z - b));
		resultado25 = resultado25 + ((z - b) + (b + y) + (x + c) + (x + a) + (b + x));
		resultado25 = resultado25 + ((z - z) + (c / x) + (a - d));
		resultado25 = resultado25 + ((y - e) + (b * c) + (z * y) + (z - d));
		String resultado26 = "";
		resultado26 = resultado26 + ((e + e) + (b + z) + (x / b) + (y / a) + (c + d));
		resultado26 = resultado26 + ((z + b) + (a + d) + (c * z) + (d / x));
		resultado26 = resultado26 + ((e - y) + (c + z) + (a - b));
		String resultado27 = "";
		resultado27 = resultado27 + ((e * x) + (c + a) + (a * e) + (a + d) + (a + c));
		resultado27 = resultado27 + ((x - c) + (b + d) + (y - b));
		resultado27 = resultado27 + ((b * z) + (d - d) + (e + z) + (y / a) + (z * a));
		String resultado28 = "";
		resultado28 = resultado28 + ((e * d) + (c + z) + (e / y) + (c - x));
		resultado28 = resultado28 + ((d / x) + (b * e) + (e + d));
		resultado28 = resultado28 + ((a * y) + (c * b) + (z - y) + (a + x) + (b + e));
		resultado28 = resultado28 + ((a - d) + (b / a) + (x * z) + (e - b));
		resultado28 = resultado28 + ((e / e) + (a / c) + (z * x));
		String resultado29 = "";
		resultado29 = resultado29 + ((z + a) + (b - d) + (y + z) + (d * b));
		resultado29 = resultado29 + ((d + y) + (d + x) + (e + e) + (y - x) + (b * y));
		resultado29 = resultado29 + ((c - x) + (c - e) + (c + a));
		resultado29 = resultado29 + ((z + e) + (y + a) + (b - b) + (y - z) + (a * e));
		String resultado30 = "";
		resultado30 = resultado30 + ((e / x) + (x * x) + (x / z) + (a * y) + (c - z));
		resultado30 = resultado30 + ((a / a) + (b / z) + (d + e));
		resultado30 = resultado30 + ((d - c) + (a - y) + (z / c) + (a - b));
		resultado30 = resultado30 + ((e - d) + (z / e) + (y + z) + (a / y) + (d * d));
		resultado30 = resultado30 + ((b * d) + (x - y) + (y * y) + (x - z));
		String resultado31 = "";
		resultado31 = resultado31 + ((c + a) + (z / a) + (x + x) + (b + c));
		resultado31 = resultado31 + ((c - z) + (a * x) + (d * a) + (y + a));
		resultado31 = resultado31 + ((c / d) + (z * c) + (d + e));
		resultado31 = resultado31 + ((x - b) + (d + e) + (b - c));
		resultado31 = resultado31 + ((b - y) + (d - z) + (e * d) + (x + z) + (z / z));
		String resultado32 = "";
		resultado32 = resultado32 + ((b - y) + (x + a) + (z / z));
		resultado32 = resultado32 + ((b * z) + (c + c) + (z - z) + (e + c) + (x + a));
		resultado32 = resultado32 + ((e + z) + (b / x) + (a * d) + (z - d) + (c / b));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}