package br.com.av1.prova29;

public class Questao4 {
	public static void main(String[] args) {
		int a = 1;
		int b = 2;
		int c = 1;
		int d = 7;
		int e = 2;
		int x = 10;
		int y = 8;
		int z = 1;

		String resultado1 = "";
		resultado1 = resultado1 + ((b * e) + (e * d) + (b * c) + (c + e) + (a * d));
		resultado1 = resultado1 + ((y * b) + (d / y) + (b * z));
		resultado1 = resultado1 + ((y + c) + (e / x) + (y * e));
		resultado1 = resultado1 + ((e + z) + (z * c) + (y + b));
		resultado1 = resultado1 + ((x - b) + (e + y) + (d + z) + (x * e) + (a - d));
		String resultado2 = "";
		resultado2 = resultado2 + ((a / a) + (a - x) + (y / x) + (y * b));
		resultado2 = resultado2 + ((z + z) + (z - b) + (d * d));
		resultado2 = resultado2 + ((e * x) + (x - y) + (c - d));
		String resultado3 = "";
		resultado3 = resultado3 + ((b + a) + (a * e) + (a - b));
		resultado3 = resultado3 + ((b / c) + (e - z) + (z / e) + (z - a));
		resultado3 = resultado3 + ((c * x) + (d - z) + (d * c) + (a * c));
		String resultado4 = "";
		resultado4 = resultado4 + ((b - x) + (a * y) + (e - y));
		resultado4 = resultado4 + ((c - b) + (c / c) + (z - c));
		resultado4 = resultado4 + ((z - b) + (e * d) + (e / b) + (z * z) + (a / x));
		resultado4 = resultado4 + ((z / d) + (c * b) + (z * e) + (x * a) + (y / z));
		resultado4 = resultado4 + ((c / e) + (z * d) + (x + a) + (c - e));
		String resultado5 = "";
		resultado5 = resultado5 + ((c - a) + (e + b) + (z - z));
		resultado5 = resultado5 + ((x * x) + (e / a) + (d - b));
		resultado5 = resultado5 + ((y - c) + (x + z) + (d / b) + (b - a));
		resultado5 = resultado5 + ((z + b) + (y + d) + (x + b));
		String resultado6 = "";
		resultado6 = resultado6 + ((c / x) + (b - y) + (c + c));
		resultado6 = resultado6 + ((d * c) + (z + c) + (y / z) + (e + a));
		resultado6 = resultado6 + ((y - d) + (z - e) + (b - e));
		resultado6 = resultado6 + ((y + y) + (b - e) + (b - x) + (c + y));
		resultado6 = resultado6 + ((e + e) + (c * x) + (z / d) + (e * a));
		String resultado7 = "";
		resultado7 = resultado7 + ((d * c) + (x / b) + (c - a));
		resultado7 = resultado7 + ((c + e) + (z + b) + (z / e) + (y - y) + (b - z));
		resultado7 = resultado7 + ((x * a) + (b / z) + (a * e) + (b * a));
		resultado7 = resultado7 + ((d - z) + (c * y) + (e - b) + (c - b));
		String resultado8 = "";
		resultado8 = resultado8 + ((e - z) + (y * d) + (x * y));
		resultado8 = resultado8 + ((d * e) + (a + x) + (y - d) + (b / x));
		resultado8 = resultado8 + ((c + b) + (y * e) + (b + c) + (a - e) + (c + b));
		String resultado9 = "";
		resultado9 = resultado9 + ((c / e) + (z - x) + (a - z) + (c + a) + (a * a));
		resultado9 = resultado9 + ((d - z) + (y / e) + (d * a) + (d + z) + (z / y));
		resultado9 = resultado9 + ((c * a) + (c - d) + (y / x) + (e + a));
		resultado9 = resultado9 + ((y + b) + (d - x) + (x * d) + (e / x) + (a / b));
		resultado9 = resultado9 + ((y - y) + (c - y) + (y * a) + (e + d) + (x + b));
		String resultado10 = "";
		resultado10 = resultado10 + ((b - a) + (x * a) + (e * x));
		resultado10 = resultado10 + ((b * a) + (x + d) + (b / d) + (a / y));
		resultado10 = resultado10 + ((a * d) + (z + b) + (e + z) + (c / y) + (d * y));
		String resultado11 = "";
		resultado11 = resultado11 + ((z * z) + (z / x) + (c * x) + (e + e));
		resultado11 = resultado11 + ((c * a) + (z * z) + (c + y) + (y / a));
		resultado11 = resultado11 + ((z + a) + (x * d) + (b / d));
		String resultado12 = "";
		resultado12 = resultado12 + ((d + b) + (b / a) + (x / d));
		resultado12 = resultado12 + ((z * y) + (x * z) + (x - e) + (x / b) + (e - x));
		resultado12 = resultado12 + ((y - d) + (a + b) + (c * z) + (a / d) + (z + d));
		resultado12 = resultado12 + ((a * y) + (a * a) + (x * a));
		resultado12 = resultado12 + ((y / y) + (y / e) + (c / c));
		String resultado13 = "";
		resultado13 = resultado13 + ((d + d) + (e + d) + (a - y) + (z - c) + (e + d));
		resultado13 = resultado13 + ((z - a) + (y - x) + (x * y) + (y * a));
		resultado13 = resultado13 + ((y - b) + (d / x) + (d / c) + (c - z) + (d - z));
		String resultado14 = "";
		resultado14 = resultado14 + ((d + y) + (d * x) + (c * z) + (z * b));
		resultado14 = resultado14 + ((e + e) + (c - y) + (c * b) + (b * e) + (y + b));
		resultado14 = resultado14 + ((a / x) + (c * a) + (x / a) + (x - d) + (c + y));
		resultado14 = resultado14 + ((y + x) + (c * e) + (b * a));
		resultado14 = resultado14 + ((x * e) + (z + z) + (a * d));
		String resultado15 = "";
		resultado15 = resultado15 + ((z - d) + (e + b) + (c - b) + (e * b));
		resultado15 = resultado15 + ((y * a) + (e - a) + (z + x) + (y * e));
		resultado15 = resultado15 + ((c + d) + (d - x) + (d + b) + (z * b));
		String resultado16 = "";
		resultado16 = resultado16 + ((e + d) + (a / y) + (d / z));
		resultado16 = resultado16 + ((c - y) + (d * a) + (y - x));
		resultado16 = resultado16 + ((e * x) + (c + a) + (e - x) + (a - d));
		resultado16 = resultado16 + ((c / d) + (z / e) + (e + a) + (d + d) + (b * a));
		String resultado17 = "";
		resultado17 = resultado17 + ((z + d) + (x * d) + (e * y) + (a / x) + (c * c));
		resultado17 = resultado17 + ((e + x) + (z * d) + (e / b) + (b * a) + (z / z));
		resultado17 = resultado17 + ((a / e) + (y + y) + (b / z));
		String resultado18 = "";
		resultado18 = resultado18 + ((z / c) + (a + a) + (e * x) + (e / x) + (x * y));
		resultado18 = resultado18 + ((d - b) + (d - d) + (d + c));
		resultado18 = resultado18 + ((e + e) + (y + z) + (e - x));
		resultado18 = resultado18 + ((e * x) + (x / a) + (a / y) + (b - a));
		resultado18 = resultado18 + ((z / e) + (e * d) + (z * z));
		String resultado19 = "";
		resultado19 = resultado19 + ((d / b) + (c + a) + (z * x) + (y / c) + (b - y));
		resultado19 = resultado19 + ((a + a) + (c / z) + (a / a) + (x - e));
		resultado19 = resultado19 + ((b - z) + (e - b) + (d - e));
		resultado19 = resultado19 + ((a * c) + (d + x) + (b - c) + (x * e));
		resultado19 = resultado19 + ((a - b) + (x * y) + (c / y) + (e * y));
		String resultado20 = "";
		resultado20 = resultado20 + ((e - y) + (x / e) + (a / c) + (c - z));
		resultado20 = resultado20 + ((z + c) + (a - y) + (b * d) + (e / d) + (b / c));
		resultado20 = resultado20 + ((y - b) + (d / y) + (a - a));
		String resultado21 = "";
		resultado21 = resultado21 + ((x / c) + (x + e) + (e * y) + (e / b));
		resultado21 = resultado21 + ((d - a) + (y * b) + (b * x));
		resultado21 = resultado21 + ((x + z) + (y + z) + (e - x));
		resultado21 = resultado21 + ((d + x) + (e / x) + (z / b) + (c * b));
		resultado21 = resultado21 + ((e * y) + (c + x) + (b * b) + (y * c) + (a * a));
		String resultado22 = "";
		resultado22 = resultado22 + ((a / y) + (e - d) + (y + x) + (e * z) + (x - z));
		resultado22 = resultado22 + ((e - d) + (d - d) + (x - y) + (e / x));
		resultado22 = resultado22 + ((e + z) + (x - e) + (a - z) + (a + e));
		String resultado23 = "";
		resultado23 = resultado23 + ((a / d) + (z * e) + (a * b));
		resultado23 = resultado23 + ((y - e) + (x - c) + (b - e) + (z - a) + (d + x));
		resultado23 = resultado23 + ((e / y) + (y * x) + (d * a) + (c * a));
		resultado23 = resultado23 + ((a - b) + (y * z) + (d * y) + (e + a) + (b - c));
		String resultado24 = "";
		resultado24 = resultado24 + ((x - d) + (y - x) + (x - b));
		resultado24 = resultado24 + ((a * z) + (a / c) + (y + x) + (d * b) + (y - b));
		resultado24 = resultado24 + ((c * d) + (z / a) + (a - y) + (z - y) + (c * y));
		resultado24 = resultado24 + ((a + x) + (b * a) + (y + z) + (c / d) + (z - e));
		resultado24 = resultado24 + ((z - b) + (y - a) + (z / c) + (y * b));
		String resultado25 = "";
		resultado25 = resultado25 + ((e / c) + (z + y) + (e * z) + (a * b) + (b + b));
		resultado25 = resultado25 + ((a / d) + (e + b) + (e - d) + (z + c));
		resultado25 = resultado25 + ((a / b) + (b - y) + (d * x));
		resultado25 = resultado25 + ((b + b) + (b - b) + (c - a) + (e * z) + (y + d));
		String resultado26 = "";
		resultado26 = resultado26 + ((c - d) + (x * d) + (e * e) + (x - x) + (d / z));
		resultado26 = resultado26 + ((x / b) + (e / c) + (x / c) + (e + a) + (e - b));
		resultado26 = resultado26 + ((c / d) + (y + d) + (y / x) + (c / x));
		String resultado27 = "";
		resultado27 = resultado27 + ((z - x) + (y / a) + (x - c) + (d - a));
		resultado27 = resultado27 + ((a - y) + (c / a) + (d * y) + (a - y) + (x / y));
		resultado27 = resultado27 + ((y / z) + (z / x) + (z * b) + (b - d) + (x - x));
		resultado27 = resultado27 + ((c + d) + (a * c) + (y + x));
		resultado27 = resultado27 + ((d + y) + (d + y) + (x - z) + (y / x) + (a / x));
		String resultado28 = "";
		resultado28 = resultado28 + ((x + x) + (z + b) + (x - d));
		resultado28 = resultado28 + ((y / b) + (y / z) + (d + y));
		resultado28 = resultado28 + ((z - e) + (x - y) + (d * a) + (c * c) + (x / d));
		resultado28 = resultado28 + ((a * b) + (b / x) + (x - c));
		String resultado29 = "";
		resultado29 = resultado29 + ((c + a) + (b + e) + (d + c) + (e * b) + (z - y));
		resultado29 = resultado29 + ((a - z) + (c - e) + (a / x) + (x / b) + (d / a));
		resultado29 = resultado29 + ((b - c) + (a * c) + (x / x));
		resultado29 = resultado29 + ((c * c) + (a * d) + (c - z) + (a / a));
		String resultado30 = "";
		resultado30 = resultado30 + ((y / e) + (e * b) + (b * c));
		resultado30 = resultado30 + ((d / z) + (a + d) + (b / z));
		resultado30 = resultado30 + ((d * b) + (a * z) + (x - a));
		resultado30 = resultado30 + ((b / e) + (x / e) + (a - z) + (x - y) + (e + a));
		resultado30 = resultado30 + ((c - y) + (a * c) + (d - e));
		String resultado31 = "";
		resultado31 = resultado31 + ((e + d) + (e + b) + (z - e));
		resultado31 = resultado31 + ((b - z) + (b + a) + (e - b) + (b - b));
		resultado31 = resultado31 + ((b - e) + (b / b) + (y * d));
		String resultado32 = "";
		resultado32 = resultado32 + ((a - c) + (c / y) + (d / d) + (a + e) + (b * b));
		resultado32 = resultado32 + ((y + b) + (d + a) + (b * y) + (z - e));
		resultado32 = resultado32 + ((b + c) + (e + z) + (c / y));
		resultado32 = resultado32 + ((e / e) + (e / a) + (x * z) + (e * e));
		resultado32 = resultado32 + ((a + a) + (e * b) + (b / e));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}