package br.com.av1.prova12;

public class Questao4 {
	public static void main(String[] args) {
		int a = 6;
		int b = 6;
		int c = 6;
		int d = 3;
		int e = 4;
		int x = 1;
		int y = 6;
		int z = 6;

		String resultado1 = "";
		resultado1 = resultado1 + ((b / a) + (x * x) + (z - d) + (x / a) + (b * y));
		resultado1 = resultado1 + ((c * y) + (b * d) + (x / y));
		resultado1 = resultado1 + ((c - d) + (b * y) + (b - x));
		resultado1 = resultado1 + ((a / a) + (d / d) + (x - c));
		resultado1 = resultado1 + ((b + e) + (z / a) + (e / e) + (b + d));
		String resultado2 = "";
		resultado2 = resultado2 + ((z * y) + (a - c) + (a - c) + (d - d) + (z - c));
		resultado2 = resultado2 + ((c - x) + (x / b) + (d * x) + (c / z) + (e + x));
		resultado2 = resultado2 + ((b * b) + (c - e) + (b / a));
		resultado2 = resultado2 + ((a + d) + (b - c) + (b + x) + (x / z) + (x - c));
		String resultado3 = "";
		resultado3 = resultado3 + ((z + a) + (a + a) + (x + b) + (c / z) + (a / y));
		resultado3 = resultado3 + ((z / d) + (b - e) + (a / z) + (e - b) + (x * y));
		resultado3 = resultado3 + ((c * y) + (d + e) + (c + x));
		resultado3 = resultado3 + ((d + x) + (d * b) + (b + y) + (a - x) + (c / e));
		resultado3 = resultado3 + ((y * d) + (z * b) + (z - c));
		String resultado4 = "";
		resultado4 = resultado4 + ((d + y) + (d * y) + (y - c) + (z + c));
		resultado4 = resultado4 + ((d * d) + (x + a) + (c * x));
		resultado4 = resultado4 + ((y + b) + (d - d) + (x * z) + (e / y) + (d / d));
		String resultado5 = "";
		resultado5 = resultado5 + ((z * z) + (x - b) + (e - a) + (d / e));
		resultado5 = resultado5 + ((d - e) + (z - d) + (z + a) + (e * x));
		resultado5 = resultado5 + ((z * d) + (z * c) + (d / z));
		String resultado6 = "";
		resultado6 = resultado6 + ((x - x) + (c * a) + (z * y) + (e * a));
		resultado6 = resultado6 + ((b - c) + (a + z) + (a / d) + (b - y));
		resultado6 = resultado6 + ((e - x) + (b * a) + (d + c));
		String resultado7 = "";
		resultado7 = resultado7 + ((b * y) + (x * d) + (b * b) + (b - x));
		resultado7 = resultado7 + ((a / d) + (z - a) + (e + a) + (x - a) + (a / y));
		resultado7 = resultado7 + ((c - a) + (z - b) + (e * e));
		resultado7 = resultado7 + ((b - c) + (e - d) + (b - c) + (a + e));
		resultado7 = resultado7 + ((a * c) + (e - e) + (c + c) + (a + b));
		String resultado8 = "";
		resultado8 = resultado8 + ((d - y) + (z * a) + (e / c) + (c / z) + (e - b));
		resultado8 = resultado8 + ((d * b) + (d / d) + (x / b));
		resultado8 = resultado8 + ((x - d) + (e / b) + (b + x));
		resultado8 = resultado8 + ((c * x) + (b * z) + (d - b) + (c / d));
		String resultado9 = "";
		resultado9 = resultado9 + ((e * b) + (y - c) + (z + e));
		resultado9 = resultado9 + ((a + z) + (d + a) + (y / e));
		resultado9 = resultado9 + ((c * x) + (d - z) + (z - z) + (b / d) + (c / d));
		resultado9 = resultado9 + ((x / d) + (a * a) + (z - c) + (c * d) + (b - y));
		String resultado10 = "";
		resultado10 = resultado10 + ((d / c) + (a / c) + (e + y) + (y - b));
		resultado10 = resultado10 + ((c / y) + (d - e) + (c + z) + (c - y));
		resultado10 = resultado10 + ((x * y) + (d * z) + (z + b) + (z / x) + (x - e));
		resultado10 = resultado10 + ((x / c) + (x + z) + (c + x) + (c / x) + (b * d));
		resultado10 = resultado10 + ((b * z) + (z * c) + (e - z) + (y + e) + (c / e));
		String resultado11 = "";
		resultado11 = resultado11 + ((y - e) + (a / z) + (c / x));
		resultado11 = resultado11 + ((e - e) + (c / c) + (d + d) + (d + e));
		resultado11 = resultado11 + ((d - c) + (b / a) + (c / x) + (e * e));
		String resultado12 = "";
		resultado12 = resultado12 + ((z * c) + (c + x) + (e - e) + (c - c) + (z + a));
		resultado12 = resultado12 + ((z / e) + (e / a) + (z + z));
		resultado12 = resultado12 + ((e * x) + (a * c) + (d * b));
		resultado12 = resultado12 + ((z / x) + (x - d) + (x - x) + (e + e));
		resultado12 = resultado12 + ((b / b) + (d + z) + (c / y));
		String resultado13 = "";
		resultado13 = resultado13 + ((z + b) + (c * d) + (x + c) + (b + z) + (b + a));
		resultado13 = resultado13 + ((e + y) + (e / b) + (x / z));
		resultado13 = resultado13 + ((c - a) + (d + b) + (z - x));
		resultado13 = resultado13 + ((z + e) + (b + a) + (d + z));
		resultado13 = resultado13 + ((c * d) + (x - b) + (c - c) + (z / c) + (d / d));
		String resultado14 = "";
		resultado14 = resultado14 + ((e / c) + (e * a) + (a - b));
		resultado14 = resultado14 + ((a - c) + (c - d) + (d / y));
		resultado14 = resultado14 + ((z + b) + (z / z) + (a - z) + (e - c));
		String resultado15 = "";
		resultado15 = resultado15 + ((z + a) + (d + b) + (c + y));
		resultado15 = resultado15 + ((d * c) + (y - z) + (a / z) + (e / e));
		resultado15 = resultado15 + ((y * y) + (e / y) + (x * x) + (y + c) + (c + z));
		resultado15 = resultado15 + ((z - y) + (d * a) + (y * d) + (x + c) + (a + b));
		String resultado16 = "";
		resultado16 = resultado16 + ((e - c) + (y * c) + (y + b) + (y + y) + (x / x));
		resultado16 = resultado16 + ((e / a) + (a / c) + (z * z) + (e + d));
		resultado16 = resultado16 + ((b / d) + (x / a) + (z * c) + (d - b) + (x - d));
		String resultado17 = "";
		resultado17 = resultado17 + ((d - e) + (e + x) + (z - z) + (d * d) + (x / d));
		resultado17 = resultado17 + ((e / a) + (z + c) + (a * a) + (b / x) + (x * e));
		resultado17 = resultado17 + ((d + b) + (z * e) + (x - z));
		String resultado18 = "";
		resultado18 = resultado18 + ((y - b) + (x + d) + (e / b) + (z + y) + (z / b));
		resultado18 = resultado18 + ((a / x) + (x - x) + (z - z));
		resultado18 = resultado18 + ((d * x) + (c / z) + (b / b) + (a * z));
		resultado18 = resultado18 + ((x / c) + (z - z) + (c - y));
		String resultado19 = "";
		resultado19 = resultado19 + ((d - c) + (e * x) + (b / d) + (b * y));
		resultado19 = resultado19 + ((c * e) + (b / b) + (z / a) + (d / b));
		resultado19 = resultado19 + ((z * z) + (a * a) + (c * x) + (c - e));
		resultado19 = resultado19 + ((x * b) + (y / z) + (d - d) + (y / z));
		resultado19 = resultado19 + ((c / a) + (a + x) + (c / d) + (b * d));
		String resultado20 = "";
		resultado20 = resultado20 + ((d + e) + (b - b) + (z / d) + (e / a));
		resultado20 = resultado20 + ((z / d) + (a + z) + (d + y) + (e + x) + (c * c));
		resultado20 = resultado20 + ((c * b) + (z + e) + (b / y) + (e * e) + (c + x));
		resultado20 = resultado20 + ((e / y) + (z - z) + (d - a) + (e / x));
		String resultado21 = "";
		resultado21 = resultado21 + ((e + z) + (e - e) + (c - e) + (z * y) + (c + c));
		resultado21 = resultado21 + ((a - x) + (d / y) + (c * z));
		resultado21 = resultado21 + ((x / d) + (e + z) + (y / d) + (x - e) + (e / y));
		resultado21 = resultado21 + ((a - x) + (y - x) + (a + a));
		resultado21 = resultado21 + ((b / c) + (a + c) + (y / b));
		String resultado22 = "";
		resultado22 = resultado22 + ((y / e) + (e * x) + (z + c));
		resultado22 = resultado22 + ((z / a) + (c - e) + (z + b));
		resultado22 = resultado22 + ((b + a) + (x - z) + (z * z));
		resultado22 = resultado22 + ((d * d) + (z / c) + (y - b));
		resultado22 = resultado22 + ((b * b) + (a * a) + (z / e));
		String resultado23 = "";
		resultado23 = resultado23 + ((d / c) + (b + z) + (e + d) + (e * d));
		resultado23 = resultado23 + ((y / x) + (d + a) + (z - z) + (x / z));
		resultado23 = resultado23 + ((e / a) + (x + e) + (x + e) + (e + e) + (a + a));
		resultado23 = resultado23 + ((y * a) + (c / x) + (d * d) + (c / a) + (x + c));
		resultado23 = resultado23 + ((e * y) + (x / y) + (x * x) + (y * b));
		String resultado24 = "";
		resultado24 = resultado24 + ((a / x) + (x / y) + (e - d) + (y - d) + (y * x));
		resultado24 = resultado24 + ((y * b) + (d - y) + (e / d) + (e + d) + (z - c));
		resultado24 = resultado24 + ((c * c) + (y + d) + (d - z) + (c * b));
		resultado24 = resultado24 + ((e + b) + (x * d) + (y / e));
		resultado24 = resultado24 + ((d / a) + (c / x) + (z + x));
		String resultado25 = "";
		resultado25 = resultado25 + ((c + y) + (z / a) + (d - c) + (c / d));
		resultado25 = resultado25 + ((y * e) + (c / c) + (c - a) + (x - c));
		resultado25 = resultado25 + ((a + e) + (y * a) + (c + a));
		resultado25 = resultado25 + ((d + b) + (e - b) + (e - c));
		resultado25 = resultado25 + ((e + b) + (x * e) + (c + e));
		String resultado26 = "";
		resultado26 = resultado26 + ((c / d) + (a / z) + (a * y));
		resultado26 = resultado26 + ((b + x) + (d + z) + (x + y) + (d - b));
		resultado26 = resultado26 + ((a + y) + (x * d) + (c / x) + (x / d) + (c + x));
		resultado26 = resultado26 + ((x - z) + (e * d) + (z / c) + (c * d));
		resultado26 = resultado26 + ((c - z) + (x * y) + (a * d) + (z - y) + (b + z));
		String resultado27 = "";
		resultado27 = resultado27 + ((c * b) + (x * y) + (b - b));
		resultado27 = resultado27 + ((e / c) + (b / b) + (c / b) + (e + e));
		resultado27 = resultado27 + ((z / e) + (e - y) + (e - a));
		resultado27 = resultado27 + ((x / c) + (z / z) + (e + z));
		resultado27 = resultado27 + ((c * d) + (d / z) + (d - d) + (e - e));
		String resultado28 = "";
		resultado28 = resultado28 + ((e / e) + (e + b) + (b - c) + (z + x));
		resultado28 = resultado28 + ((x - z) + (e - c) + (b + a) + (z * y) + (x * c));
		resultado28 = resultado28 + ((c * z) + (a - e) + (d + z) + (y / e) + (z / b));
		resultado28 = resultado28 + ((c * a) + (x / b) + (d / b) + (a * b));
		resultado28 = resultado28 + ((y * c) + (d * c) + (d - c) + (y - y));
		String resultado29 = "";
		resultado29 = resultado29 + ((x + a) + (y - b) + (e / e) + (c / z) + (z / e));
		resultado29 = resultado29 + ((x / z) + (y / b) + (a + d) + (x + z) + (z * d));
		resultado29 = resultado29 + ((c + z) + (e * x) + (e * z) + (z * c));
		resultado29 = resultado29 + ((y * z) + (e + d) + (x + e));
		resultado29 = resultado29 + ((d * a) + (e + y) + (z + y));
		String resultado30 = "";
		resultado30 = resultado30 + ((y * x) + (a * d) + (e + y));
		resultado30 = resultado30 + ((d - a) + (e * c) + (a + a) + (y * d));
		resultado30 = resultado30 + ((e + a) + (c + b) + (a + d) + (a * e));
		resultado30 = resultado30 + ((e - e) + (d + x) + (z / b));
		String resultado31 = "";
		resultado31 = resultado31 + ((e / d) + (a / y) + (y / a) + (e * c) + (d * x));
		resultado31 = resultado31 + ((a + c) + (d * y) + (b * a) + (x + z) + (e + x));
		resultado31 = resultado31 + ((b + z) + (a * a) + (b / c) + (e / y) + (a / e));
		resultado31 = resultado31 + ((b * a) + (e + x) + (z * y) + (a * b));
		String resultado32 = "";
		resultado32 = resultado32 + ((c - y) + (e + y) + (d - a) + (b * e) + (x / c));
		resultado32 = resultado32 + ((z - d) + (a + d) + (y + x) + (c * y) + (c / z));
		resultado32 = resultado32 + ((c / a) + (b / b) + (y + d));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}