package br.com.av1.prova01;

public class Questao4 {
	public static void main(String[] args) {
		int a = 7;
		int b = 2;
		int c = 1;
		int d = 10;
		int e = 1;
		int x = 3;
		int y = 9;
		int z = 7;

		String resultado1 = "";
		resultado1 = resultado1 + ((z + e) + (d + a) + (x * d));
		resultado1 = resultado1 + ((b * d) + (b / e) + (x / a) + (d + y) + (y - d));
		resultado1 = resultado1 + ((d + x) + (z * x) + (c / b) + (b - c));
		resultado1 = resultado1 + ((x - e) + (a / e) + (z - b) + (c - b));
		String resultado2 = "";
		resultado2 = resultado2 + ((a + d) + (b + b) + (e - c) + (a / x));
		resultado2 = resultado2 + ((x / e) + (d - x) + (x * c) + (x - d));
		resultado2 = resultado2 + ((d / y) + (b * z) + (y / z) + (a + z) + (z + e));
		resultado2 = resultado2 + ((d / x) + (a + x) + (z + x));
		resultado2 = resultado2 + ((x + x) + (y * z) + (e - a) + (x - y) + (e * e));
		String resultado3 = "";
		resultado3 = resultado3 + ((d + c) + (c / x) + (c * a));
		resultado3 = resultado3 + ((z * d) + (x - a) + (y / z) + (z - a));
		resultado3 = resultado3 + ((x - x) + (x * c) + (e * b));
		String resultado4 = "";
		resultado4 = resultado4 + ((a / y) + (d * c) + (b - x) + (b - z) + (b + z));
		resultado4 = resultado4 + ((b + y) + (a * d) + (e / c) + (z + c) + (y / z));
		resultado4 = resultado4 + ((b / d) + (a * e) + (e - y) + (a + e));
		resultado4 = resultado4 + ((e * y) + (z * z) + (z + d) + (e + x));
		resultado4 = resultado4 + ((c - d) + (d / e) + (z - e) + (e / y));
		String resultado5 = "";
		resultado5 = resultado5 + ((c * c) + (d * e) + (y - z));
		resultado5 = resultado5 + ((b - x) + (e * c) + (x - z) + (y - e));
		resultado5 = resultado5 + ((b - c) + (x + a) + (y + d) + (c - e));
		resultado5 = resultado5 + ((c - a) + (z - a) + (e * a));
		resultado5 = resultado5 + ((d * e) + (x - e) + (d - e) + (z * e));
		String resultado6 = "";
		resultado6 = resultado6 + ((b * e) + (e - a) + (e + a) + (a + c));
		resultado6 = resultado6 + ((a / a) + (z * d) + (d * z) + (y * b));
		resultado6 = resultado6 + ((a / y) + (d * e) + (y - e) + (y * a));
		resultado6 = resultado6 + ((x * b) + (c - a) + (y / b) + (c / z) + (x + y));
		String resultado7 = "";
		resultado7 = resultado7 + ((z + y) + (z - a) + (b / b));
		resultado7 = resultado7 + ((d / x) + (e / a) + (e + e) + (e / z) + (y + d));
		resultado7 = resultado7 + ((x / e) + (a * b) + (x - z) + (a + b) + (d - e));
		resultado7 = resultado7 + ((d * y) + (y / a) + (d / b) + (e + b) + (z / x));
		resultado7 = resultado7 + ((e + d) + (x * z) + (c + a));
		String resultado8 = "";
		resultado8 = resultado8 + ((a * b) + (z * x) + (y * b) + (y + e) + (y / c));
		resultado8 = resultado8 + ((y * e) + (e + x) + (z / z) + (d * y));
		resultado8 = resultado8 + ((d * b) + (c * d) + (x + a) + (y + e) + (c + a));
		resultado8 = resultado8 + ((z + e) + (d / e) + (b - z) + (c * y));
		resultado8 = resultado8 + ((y + d) + (x / x) + (x - x) + (e + c));
		String resultado9 = "";
		resultado9 = resultado9 + ((d / y) + (x / a) + (z - z));
		resultado9 = resultado9 + ((b + e) + (c + x) + (d / b) + (a / a) + (x + z));
		resultado9 = resultado9 + ((c * x) + (c * d) + (a * a) + (z * d) + (z / d));
		resultado9 = resultado9 + ((b + z) + (d + y) + (b + b) + (e / c));
		resultado9 = resultado9 + ((c + c) + (a * b) + (x * x));
		String resultado10 = "";
		resultado10 = resultado10 + ((d / d) + (c - c) + (c * z));
		resultado10 = resultado10 + ((y / e) + (z * c) + (z + x) + (x / c));
		resultado10 = resultado10 + ((x / x) + (x - e) + (a + c) + (d - y) + (y * z));
		String resultado11 = "";
		resultado11 = resultado11 + ((c * y) + (b + x) + (d / y) + (c * a) + (d * d));
		resultado11 = resultado11 + ((b / b) + (y + y) + (y / y) + (a - x) + (d / e));
		resultado11 = resultado11 + ((a / b) + (x / y) + (z / a));
		String resultado12 = "";
		resultado12 = resultado12 + ((b + c) + (b - z) + (b - z) + (b - a));
		resultado12 = resultado12 + ((y + x) + (d * x) + (d + e));
		resultado12 = resultado12 + ((c / c) + (c * a) + (x / e) + (z + c));
		resultado12 = resultado12 + ((a - z) + (z - b) + (a - a) + (z - x));
		resultado12 = resultado12 + ((c + a) + (b - x) + (b / y));
		String resultado13 = "";
		resultado13 = resultado13 + ((c * z) + (d - y) + (b / x) + (b - y));
		resultado13 = resultado13 + ((a * c) + (e / z) + (b - d) + (b * z));
		resultado13 = resultado13 + ((x / a) + (z / y) + (a + e) + (a / d) + (x * d));
		String resultado14 = "";
		resultado14 = resultado14 + ((y + z) + (e - y) + (y + d) + (y * e) + (a * y));
		resultado14 = resultado14 + ((d + c) + (d - a) + (z + z));
		resultado14 = resultado14 + ((b - y) + (x + d) + (y / a) + (a + b) + (b - z));
		String resultado15 = "";
		resultado15 = resultado15 + ((a - d) + (b * c) + (a - c) + (y / c) + (z * d));
		resultado15 = resultado15 + ((b * e) + (b - b) + (d - z));
		resultado15 = resultado15 + ((d + e) + (e / y) + (z / b) + (y + a));
		resultado15 = resultado15 + ((c + z) + (b + e) + (c / z));
		String resultado16 = "";
		resultado16 = resultado16 + ((e / e) + (d - a) + (z - z) + (z * x) + (e - x));
		resultado16 = resultado16 + ((x - e) + (a - c) + (b - d) + (y / d) + (c - z));
		resultado16 = resultado16 + ((e + c) + (y - y) + (e / d));
		String resultado17 = "";
		resultado17 = resultado17 + ((x / z) + (c - d) + (y - x));
		resultado17 = resultado17 + ((b * y) + (e - c) + (a + a) + (x * d));
		resultado17 = resultado17 + ((b - z) + (z - z) + (z - a) + (e - c));
		resultado17 = resultado17 + ((c / d) + (x / x) + (x + c));
		String resultado18 = "";
		resultado18 = resultado18 + ((b * b) + (e - y) + (b + e) + (d * b) + (a * x));
		resultado18 = resultado18 + ((d * y) + (a / c) + (x * d) + (e + e) + (c * d));
		resultado18 = resultado18 + ((z + y) + (d - x) + (a / b) + (a / x) + (a + x));
		String resultado19 = "";
		resultado19 = resultado19 + ((c / x) + (c - x) + (a + x) + (z * b));
		resultado19 = resultado19 + ((x / a) + (a - y) + (b / e) + (d / z));
		resultado19 = resultado19 + ((c - c) + (e * y) + (c + b) + (d - z) + (e + a));
		resultado19 = resultado19 + ((c * a) + (y / y) + (d + c) + (y - b) + (x + e));
		String resultado20 = "";
		resultado20 = resultado20 + ((z * e) + (y * d) + (d - c) + (z - z));
		resultado20 = resultado20 + ((z / z) + (e * z) + (e * c));
		resultado20 = resultado20 + ((y - y) + (c / d) + (c + e) + (b + x) + (e * e));
		String resultado21 = "";
		resultado21 = resultado21 + ((x + x) + (c + a) + (d - c) + (y - e));
		resultado21 = resultado21 + ((x * b) + (b - d) + (y - a) + (d + e) + (e - y));
		resultado21 = resultado21 + ((e - x) + (x - e) + (d / y) + (y - x));
		String resultado22 = "";
		resultado22 = resultado22 + ((a + x) + (e / b) + (a - x) + (b - e) + (z / z));
		resultado22 = resultado22 + ((c * c) + (d / a) + (d / z));
		resultado22 = resultado22 + ((z + y) + (x - b) + (b - x));
		resultado22 = resultado22 + ((d / x) + (d - y) + (z / x));
		resultado22 = resultado22 + ((z - d) + (z * e) + (c / z));
		String resultado23 = "";
		resultado23 = resultado23 + ((c / d) + (d * c) + (c * c) + (x * a));
		resultado23 = resultado23 + ((x - d) + (b + b) + (x + d) + (c / b));
		resultado23 = resultado23 + ((d - y) + (y / y) + (c + x) + (d * c) + (a / c));
		String resultado24 = "";
		resultado24 = resultado24 + ((z - z) + (b - x) + (z * x) + (z / z) + (d - x));
		resultado24 = resultado24 + ((e / d) + (y / a) + (z - c));
		resultado24 = resultado24 + ((y * c) + (c - d) + (b - b) + (b + c));
		String resultado25 = "";
		resultado25 = resultado25 + ((e / e) + (e / c) + (a + y) + (y / y));
		resultado25 = resultado25 + ((z * e) + (e / a) + (d * c) + (e + c) + (e - e));
		resultado25 = resultado25 + ((y + z) + (z + d) + (x - a));
		resultado25 = resultado25 + ((x / y) + (d / d) + (a + e) + (b - e) + (x * y));
		resultado25 = resultado25 + ((x * c) + (e / y) + (z / y) + (z - x) + (z - c));
		String resultado26 = "";
		resultado26 = resultado26 + ((z - x) + (a / z) + (x + c) + (a + e));
		resultado26 = resultado26 + ((x + x) + (c * e) + (x + z) + (c / c) + (b * c));
		resultado26 = resultado26 + ((x + a) + (c + x) + (c - y) + (e - c));
		resultado26 = resultado26 + ((y - x) + (z * a) + (y + e) + (a + b));
		resultado26 = resultado26 + ((e + e) + (c * z) + (d * e) + (c + b) + (e + y));
		String resultado27 = "";
		resultado27 = resultado27 + ((y - z) + (z * x) + (e + b) + (c + x) + (c + c));
		resultado27 = resultado27 + ((x / y) + (z / x) + (e - y) + (y - e) + (e + x));
		resultado27 = resultado27 + ((c - x) + (y * c) + (z + z) + (x + c) + (a * d));
		String resultado28 = "";
		resultado28 = resultado28 + ((b * b) + (d * z) + (x + e));
		resultado28 = resultado28 + ((z * e) + (c * d) + (x + y));
		resultado28 = resultado28 + ((d + z) + (b / a) + (e - b));
		String resultado29 = "";
		resultado29 = resultado29 + ((e + x) + (d - c) + (b + d) + (c / b));
		resultado29 = resultado29 + ((a - a) + (y + d) + (b * x) + (b - d));
		resultado29 = resultado29 + ((z * z) + (z / e) + (a * b) + (b / c) + (b + e));
		resultado29 = resultado29 + ((x - d) + (z + e) + (y / e));
		String resultado30 = "";
		resultado30 = resultado30 + ((c - z) + (b * z) + (x * b) + (y + y));
		resultado30 = resultado30 + ((e * b) + (d * x) + (b * x));
		resultado30 = resultado30 + ((d * c) + (a + y) + (c + d) + (e * c));
		resultado30 = resultado30 + ((e + e) + (z + a) + (z - x));
		String resultado31 = "";
		resultado31 = resultado31 + ((e - z) + (e / a) + (e + y) + (e / y) + (y - e));
		resultado31 = resultado31 + ((d / b) + (c + z) + (e - d) + (y - x));
		resultado31 = resultado31 + ((b * c) + (x * e) + (d / c) + (x + c) + (x / a));
		resultado31 = resultado31 + ((c - b) + (c - a) + (x - x));
		String resultado32 = "";
		resultado32 = resultado32 + ((d - e) + (e * x) + (a - z) + (z + b) + (z * c));
		resultado32 = resultado32 + ((y - e) + (d + b) + (b / y) + (y + a));
		resultado32 = resultado32 + ((c - a) + (e - e) + (c - a) + (x * e) + (e + z));
		resultado32 = resultado32 + ((a + b) + (y - z) + (z - e) + (e * e));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}