package br.com.av1.prova28;

public class Questao4 {
	public static void main(String[] args) {
		int a = 6;
		int b = 10;
		int c = 4;
		int d = 6;
		int e = 9;
		int x = 1;
		int y = 8;
		int z = 9;

		String resultado1 = "";
		resultado1 = resultado1 + ((b * x) + (x * d) + (d * z));
		resultado1 = resultado1 + ((c - x) + (c - c) + (d + z) + (c / e) + (x - z));
		resultado1 = resultado1 + ((a / y) + (d - x) + (c + e) + (e / a) + (d / b));
		resultado1 = resultado1 + ((z * e) + (e * e) + (z / y) + (c + a));
		resultado1 = resultado1 + ((c + e) + (e * d) + (c * c) + (d - a) + (z + c));
		String resultado2 = "";
		resultado2 = resultado2 + ((e + z) + (x / y) + (z - c));
		resultado2 = resultado2 + ((b + b) + (b * d) + (e * c) + (y / z));
		resultado2 = resultado2 + ((d / z) + (d + a) + (e / d) + (b + d));
		String resultado3 = "";
		resultado3 = resultado3 + ((d / c) + (e / d) + (z / a) + (y + a));
		resultado3 = resultado3 + ((c - x) + (c + a) + (z * y) + (x - a) + (c - x));
		resultado3 = resultado3 + ((e / c) + (y * a) + (a + c) + (x + d));
		resultado3 = resultado3 + ((z + c) + (y - z) + (d + y) + (a * x));
		resultado3 = resultado3 + ((e - z) + (c / a) + (y * z) + (a + y) + (e * y));
		String resultado4 = "";
		resultado4 = resultado4 + ((e * x) + (z - x) + (e * y) + (y - y) + (d / y));
		resultado4 = resultado4 + ((z * c) + (b - z) + (z * c));
		resultado4 = resultado4 + ((x + c) + (a * x) + (a + x) + (c + d));
		String resultado5 = "";
		resultado5 = resultado5 + ((z - c) + (b * e) + (b + b) + (x + a) + (d - e));
		resultado5 = resultado5 + ((x / a) + (x + x) + (d + x));
		resultado5 = resultado5 + ((e / d) + (b - e) + (e / x) + (b / b));
		resultado5 = resultado5 + ((e * y) + (y + d) + (c - z) + (a - c));
		resultado5 = resultado5 + ((y + y) + (a / x) + (a + z) + (x + c) + (c / z));
		String resultado6 = "";
		resultado6 = resultado6 + ((a * x) + (x + a) + (a - z));
		resultado6 = resultado6 + ((e - a) + (z + y) + (a * x));
		resultado6 = resultado6 + ((x / b) + (b * d) + (a * d));
		resultado6 = resultado6 + ((x / y) + (e / c) + (b / b) + (z / e));
		String resultado7 = "";
		resultado7 = resultado7 + ((a * b) + (x * c) + (z / b) + (b - a));
		resultado7 = resultado7 + ((y / d) + (z / y) + (b * x));
		resultado7 = resultado7 + ((x * d) + (b + a) + (x * a) + (a - e) + (z + e));
		String resultado8 = "";
		resultado8 = resultado8 + ((e + b) + (x * d) + (b - a) + (z - y));
		resultado8 = resultado8 + ((y + c) + (c - d) + (c * c) + (x + c));
		resultado8 = resultado8 + ((y + b) + (z / e) + (y + d) + (d / e) + (b + y));
		resultado8 = resultado8 + ((e - a) + (c / c) + (e * z) + (c + z));
		resultado8 = resultado8 + ((a * y) + (x - a) + (x + c) + (x * x));
		String resultado9 = "";
		resultado9 = resultado9 + ((e / z) + (d + d) + (x * d) + (c * b));
		resultado9 = resultado9 + ((c - c) + (e - c) + (c - a));
		resultado9 = resultado9 + ((c / y) + (y * c) + (b / c) + (y * y) + (a / x));
		resultado9 = resultado9 + ((c / d) + (y + a) + (d * x) + (b / a) + (z / z));
		String resultado10 = "";
		resultado10 = resultado10 + ((c * e) + (e + z) + (y * a) + (x - e));
		resultado10 = resultado10 + ((e + b) + (z / y) + (x * x));
		resultado10 = resultado10 + ((z * e) + (e + b) + (a + y));
		resultado10 = resultado10 + ((a - x) + (z - d) + (b / b));
		resultado10 = resultado10 + ((y + a) + (c + d) + (b - y) + (x + d));
		String resultado11 = "";
		resultado11 = resultado11 + ((y - c) + (y / z) + (x / y) + (d - x) + (b / d));
		resultado11 = resultado11 + ((x + y) + (c / z) + (a + z) + (d - y) + (y / e));
		resultado11 = resultado11 + ((a - c) + (z / c) + (c + y) + (a / e) + (z / a));
		resultado11 = resultado11 + ((d * a) + (b * a) + (c * y) + (y + e));
		String resultado12 = "";
		resultado12 = resultado12 + ((c / x) + (a + a) + (a / d));
		resultado12 = resultado12 + ((y - b) + (d - y) + (b - d));
		resultado12 = resultado12 + ((a + d) + (c * b) + (z + y));
		String resultado13 = "";
		resultado13 = resultado13 + ((c - x) + (d / c) + (c / e) + (x / b) + (x - y));
		resultado13 = resultado13 + ((d * x) + (a * c) + (c / c));
		resultado13 = resultado13 + ((b / b) + (e / e) + (c * y) + (e / b) + (b * x));
		resultado13 = resultado13 + ((z - e) + (a - e) + (x * y) + (d * e));
		resultado13 = resultado13 + ((x - d) + (c / x) + (x * b) + (b * x));
		String resultado14 = "";
		resultado14 = resultado14 + ((x + z) + (e - c) + (x * d) + (y * e) + (x / a));
		resultado14 = resultado14 + ((z / y) + (e / e) + (y / x));
		resultado14 = resultado14 + ((x / x) + (x + e) + (d / b) + (z - z) + (e * c));
		resultado14 = resultado14 + ((x / a) + (y / x) + (b - a) + (z * y));
		resultado14 = resultado14 + ((e - a) + (a * b) + (c + a));
		String resultado15 = "";
		resultado15 = resultado15 + ((b + d) + (x + a) + (d + a));
		resultado15 = resultado15 + ((a + a) + (z + d) + (b * e) + (a / y));
		resultado15 = resultado15 + ((a + z) + (e * d) + (a * e));
		resultado15 = resultado15 + ((z / y) + (x / d) + (y - a) + (a / e) + (z * b));
		resultado15 = resultado15 + ((b - d) + (b * b) + (e + y));
		String resultado16 = "";
		resultado16 = resultado16 + ((y * y) + (d - e) + (a - b) + (z + b) + (e * b));
		resultado16 = resultado16 + ((z - y) + (c / y) + (a / x) + (d - z));
		resultado16 = resultado16 + ((b * c) + (z * b) + (e / d));
		resultado16 = resultado16 + ((b * y) + (c + x) + (z - z) + (z + y) + (a / e));
		resultado16 = resultado16 + ((b + a) + (z - y) + (z + e) + (c * a));
		String resultado17 = "";
		resultado17 = resultado17 + ((z - c) + (e / b) + (z * y) + (e - a) + (a / c));
		resultado17 = resultado17 + ((d + a) + (b / x) + (d - c) + (b + e));
		resultado17 = resultado17 + ((x - e) + (c / e) + (b - x) + (c - e));
		resultado17 = resultado17 + ((x + b) + (z - c) + (b / d) + (b * d));
		String resultado18 = "";
		resultado18 = resultado18 + ((y - c) + (c + d) + (x / b));
		resultado18 = resultado18 + ((x * z) + (y / e) + (a - x) + (x / y));
		resultado18 = resultado18 + ((y * x) + (b * b) + (b / x) + (z - y) + (d - x));
		resultado18 = resultado18 + ((c / x) + (b + e) + (b - z));
		resultado18 = resultado18 + ((a - c) + (y * y) + (x - y));
		String resultado19 = "";
		resultado19 = resultado19 + ((a + e) + (a - a) + (y + d) + (d * y));
		resultado19 = resultado19 + ((e + y) + (b + d) + (b + z) + (e * b) + (c - e));
		resultado19 = resultado19 + ((b * b) + (c / e) + (c - e) + (a / z) + (e + b));
		String resultado20 = "";
		resultado20 = resultado20 + ((a * b) + (a / e) + (z * z));
		resultado20 = resultado20 + ((d - x) + (a + d) + (c - d) + (e * z) + (z + b));
		resultado20 = resultado20 + ((a - c) + (a * c) + (y * d));
		resultado20 = resultado20 + ((e - e) + (b - z) + (a / e));
		resultado20 = resultado20 + ((b / y) + (b * e) + (x / d));
		String resultado21 = "";
		resultado21 = resultado21 + ((y / y) + (y / y) + (y + y));
		resultado21 = resultado21 + ((a + e) + (a - d) + (y / c) + (x / c) + (z * a));
		resultado21 = resultado21 + ((d / e) + (y * b) + (z + x) + (d + x) + (c + e));
		resultado21 = resultado21 + ((c - c) + (z * x) + (c / b) + (e + c) + (b * x));
		resultado21 = resultado21 + ((d - x) + (b * e) + (y / b));
		String resultado22 = "";
		resultado22 = resultado22 + ((x / b) + (d + b) + (y / d) + (b / e));
		resultado22 = resultado22 + ((c / b) + (e - x) + (b * y) + (x / c) + (d / z));
		resultado22 = resultado22 + ((a + a) + (y * c) + (a * e));
		resultado22 = resultado22 + ((b - d) + (b * b) + (a / y) + (a / c) + (b + z));
		resultado22 = resultado22 + ((x - x) + (b - a) + (x + z) + (c * d) + (z - e));
		String resultado23 = "";
		resultado23 = resultado23 + ((e - z) + (e + b) + (a - c) + (x - x));
		resultado23 = resultado23 + ((e * d) + (d - d) + (x - x) + (e / x) + (x * z));
		resultado23 = resultado23 + ((b * c) + (y - z) + (c * a));
		resultado23 = resultado23 + ((x + e) + (a * d) + (d * b) + (b / c));
		resultado23 = resultado23 + ((a * b) + (c + x) + (c / c) + (b * c) + (c / x));
		String resultado24 = "";
		resultado24 = resultado24 + ((d / y) + (d - e) + (a * e) + (z - a) + (a / a));
		resultado24 = resultado24 + ((d * e) + (a * z) + (b * a) + (x - e));
		resultado24 = resultado24 + ((b + a) + (c + d) + (c * a) + (c - e) + (e * e));
		resultado24 = resultado24 + ((e + z) + (a + b) + (x * z) + (b - x));
		resultado24 = resultado24 + ((a - c) + (d - d) + (c + e));
		String resultado25 = "";
		resultado25 = resultado25 + ((y / y) + (y / e) + (e * y) + (c / e));
		resultado25 = resultado25 + ((e - y) + (d + c) + (b + e) + (a + b) + (d * d));
		resultado25 = resultado25 + ((x / x) + (c / a) + (y / c) + (x / z));
		resultado25 = resultado25 + ((c + z) + (d / a) + (e * b) + (c + d) + (a - b));
		resultado25 = resultado25 + ((x * x) + (a / x) + (x * x));
		String resultado26 = "";
		resultado26 = resultado26 + ((z / y) + (z / b) + (x + y) + (y - a));
		resultado26 = resultado26 + ((z / b) + (c - e) + (b / c));
		resultado26 = resultado26 + ((d * d) + (z / z) + (e * a) + (e - z) + (d + x));
		resultado26 = resultado26 + ((b + y) + (e * b) + (z - y) + (e + y) + (a * e));
		String resultado27 = "";
		resultado27 = resultado27 + ((z - x) + (c - b) + (b + c) + (x - c) + (c - z));
		resultado27 = resultado27 + ((x - x) + (a / e) + (e / e) + (x - y) + (x - c));
		resultado27 = resultado27 + ((c * c) + (a - a) + (a - e) + (x + c) + (e * b));
		String resultado28 = "";
		resultado28 = resultado28 + ((a + z) + (b - d) + (c / c) + (a - x) + (b * b));
		resultado28 = resultado28 + ((e + b) + (a + x) + (d - c) + (e * e) + (y / d));
		resultado28 = resultado28 + ((y - x) + (a + c) + (y * z) + (c + z));
		resultado28 = resultado28 + ((z - y) + (d / b) + (x + e) + (e / c));
		resultado28 = resultado28 + ((y + b) + (a / y) + (e - a));
		String resultado29 = "";
		resultado29 = resultado29 + ((z + x) + (x + e) + (b / b));
		resultado29 = resultado29 + ((d + e) + (x * e) + (x - c) + (e + c) + (y + c));
		resultado29 = resultado29 + ((y * b) + (c / e) + (a / b) + (a + y));
		resultado29 = resultado29 + ((c + y) + (b + b) + (z + z) + (a * x));
		resultado29 = resultado29 + ((x - c) + (z / z) + (x - a));
		String resultado30 = "";
		resultado30 = resultado30 + ((y / a) + (b + b) + (c + b) + (e - z));
		resultado30 = resultado30 + ((x / a) + (b + b) + (y / a) + (a / z) + (x / z));
		resultado30 = resultado30 + ((y / b) + (z - c) + (b - c));
		String resultado31 = "";
		resultado31 = resultado31 + ((z * e) + (e + d) + (e + y) + (b - e));
		resultado31 = resultado31 + ((x - y) + (z + c) + (a - x) + (e + y) + (x / b));
		resultado31 = resultado31 + ((e * a) + (a - a) + (a + z) + (d + x) + (d - y));
		resultado31 = resultado31 + ((c - y) + (b - y) + (c - y) + (e * z));
		String resultado32 = "";
		resultado32 = resultado32 + ((c * e) + (y - a) + (c - a) + (e * b));
		resultado32 = resultado32 + ((e / c) + (b + a) + (x - y));
		resultado32 = resultado32 + ((c + z) + (c - y) + (y / a) + (y - b) + (e / e));
		resultado32 = resultado32 + ((x - b) + (z - y) + (y * e) + (a + d) + (z * x));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}