package br.com.av1.prova16;

public class Questao4 {
	public static void main(String[] args) {
		int a = 1;
		int b = 3;
		int c = 8;
		int d = 10;
		int e = 2;
		int x = 9;
		int y = 5;
		int z = 2;

		String resultado1 = "";
		resultado1 = resultado1 + ((a * y) + (d - z) + (x * d) + (e + z));
		resultado1 = resultado1 + ((c * a) + (c / e) + (d + d) + (c * b) + (z * d));
		resultado1 = resultado1 + ((e - c) + (d * c) + (y + e));
		resultado1 = resultado1 + ((c / a) + (x * z) + (b * e));
		resultado1 = resultado1 + ((y - z) + (c - b) + (e * b));
		String resultado2 = "";
		resultado2 = resultado2 + ((z / y) + (d + y) + (z / d) + (y + c));
		resultado2 = resultado2 + ((e + a) + (x + e) + (z + d) + (b * a));
		resultado2 = resultado2 + ((x + z) + (c + e) + (b * x) + (c * a) + (z * y));
		resultado2 = resultado2 + ((e - x) + (x - d) + (y + c) + (d + e));
		resultado2 = resultado2 + ((b * e) + (e - d) + (z - a));
		String resultado3 = "";
		resultado3 = resultado3 + ((d + y) + (y / e) + (e / c) + (x / e) + (e + c));
		resultado3 = resultado3 + ((e - z) + (z + b) + (d * a) + (d - y) + (x / y));
		resultado3 = resultado3 + ((b - b) + (d - c) + (c + z) + (a / e) + (a / b));
		resultado3 = resultado3 + ((z / z) + (e + a) + (b + x) + (x * a) + (c + z));
		resultado3 = resultado3 + ((b + x) + (b * a) + (e / a));
		String resultado4 = "";
		resultado4 = resultado4 + ((d - b) + (x - c) + (b / b));
		resultado4 = resultado4 + ((z - d) + (a / z) + (c + e) + (a - a));
		resultado4 = resultado4 + ((y + a) + (e / d) + (a / d) + (d * a) + (c + c));
		String resultado5 = "";
		resultado5 = resultado5 + ((a * d) + (b / b) + (d - d) + (c * c) + (d - b));
		resultado5 = resultado5 + ((a * a) + (b - e) + (e * z) + (a + y));
		resultado5 = resultado5 + ((y * y) + (c / a) + (y / z) + (a * e));
		resultado5 = resultado5 + ((z - z) + (d + b) + (x + x) + (x - d) + (c / x));
		resultado5 = resultado5 + ((c / c) + (a / a) + (d * z) + (z * y) + (x / a));
		String resultado6 = "";
		resultado6 = resultado6 + ((x / x) + (c - e) + (a / c) + (e - b) + (z - x));
		resultado6 = resultado6 + ((c / x) + (b + c) + (a / a) + (d / e));
		resultado6 = resultado6 + ((b + e) + (z / b) + (x / a) + (e + e) + (e - a));
		resultado6 = resultado6 + ((b + b) + (e - b) + (b + d) + (d + e));
		resultado6 = resultado6 + ((y * c) + (z + z) + (e / z) + (a * x));
		String resultado7 = "";
		resultado7 = resultado7 + ((x / a) + (y + d) + (a + a));
		resultado7 = resultado7 + ((d * z) + (b / y) + (y + x));
		resultado7 = resultado7 + ((d / y) + (x / b) + (z * c) + (y / x));
		resultado7 = resultado7 + ((d * e) + (e + x) + (d * y) + (e * x) + (x / e));
		resultado7 = resultado7 + ((y / c) + (e + d) + (e - z) + (a / b));
		String resultado8 = "";
		resultado8 = resultado8 + ((x / b) + (b * y) + (z / e) + (z + c));
		resultado8 = resultado8 + ((a * e) + (b + d) + (c / z) + (b / b));
		resultado8 = resultado8 + ((a / b) + (z + z) + (y - c) + (y * b));
		String resultado9 = "";
		resultado9 = resultado9 + ((y + c) + (b - y) + (z - e) + (x - d) + (a * x));
		resultado9 = resultado9 + ((b + z) + (c + z) + (e - z) + (c * e) + (x * y));
		resultado9 = resultado9 + ((z * x) + (z * y) + (b * z));
		String resultado10 = "";
		resultado10 = resultado10 + ((b / a) + (c + y) + (b - d) + (x + b));
		resultado10 = resultado10 + ((z / y) + (x * z) + (a + e) + (e - e));
		resultado10 = resultado10 + ((b - d) + (b * a) + (b / y));
		resultado10 = resultado10 + ((a + b) + (a * e) + (e * d) + (c - a));
		resultado10 = resultado10 + ((z / b) + (x - a) + (e + y) + (e * y));
		String resultado11 = "";
		resultado11 = resultado11 + ((z - e) + (d / d) + (x - x));
		resultado11 = resultado11 + ((c * y) + (b + d) + (z / d) + (c / c));
		resultado11 = resultado11 + ((x / d) + (z - c) + (c * b) + (y / d) + (d + a));
		String resultado12 = "";
		resultado12 = resultado12 + ((a * d) + (e / a) + (d - b));
		resultado12 = resultado12 + ((a * x) + (x / a) + (c + d));
		resultado12 = resultado12 + ((e - e) + (a * a) + (a * d) + (x - z) + (z / c));
		resultado12 = resultado12 + ((a - z) + (z + d) + (d + x) + (b - d) + (b + c));
		String resultado13 = "";
		resultado13 = resultado13 + ((a - d) + (c - e) + (a * c));
		resultado13 = resultado13 + ((z + x) + (z * a) + (a / a));
		resultado13 = resultado13 + ((z * a) + (y + b) + (c + c));
		String resultado14 = "";
		resultado14 = resultado14 + ((e - x) + (c * a) + (a * e));
		resultado14 = resultado14 + ((d + z) + (x * b) + (b - y) + (e * y) + (c + e));
		resultado14 = resultado14 + ((d / a) + (x + d) + (e * y));
		String resultado15 = "";
		resultado15 = resultado15 + ((y / a) + (d + c) + (y / b));
		resultado15 = resultado15 + ((a * a) + (c * e) + (c - c) + (a + c) + (b + e));
		resultado15 = resultado15 + ((e + z) + (y * b) + (e / e) + (a * e));
		String resultado16 = "";
		resultado16 = resultado16 + ((e * a) + (e / b) + (z + c) + (a * z));
		resultado16 = resultado16 + ((x + x) + (x / y) + (c / e));
		resultado16 = resultado16 + ((b - y) + (z * a) + (b * b));
		resultado16 = resultado16 + ((y * a) + (c * d) + (e * d));
		resultado16 = resultado16 + ((b * y) + (b - c) + (z - y) + (a * y) + (a / c));
		String resultado17 = "";
		resultado17 = resultado17 + ((a * a) + (c * c) + (a + x) + (y - y) + (c - e));
		resultado17 = resultado17 + ((a * y) + (a - b) + (c * c) + (c / z) + (a * c));
		resultado17 = resultado17 + ((z / x) + (x + x) + (x * x));
		resultado17 = resultado17 + ((d / a) + (z + d) + (e * d) + (z + y));
		resultado17 = resultado17 + ((a + y) + (b * y) + (b - b) + (z / b));
		String resultado18 = "";
		resultado18 = resultado18 + ((a / x) + (a / d) + (d - c) + (x / d) + (a - y));
		resultado18 = resultado18 + ((x + y) + (b - y) + (z * y));
		resultado18 = resultado18 + ((b + x) + (b * b) + (x - z));
		String resultado19 = "";
		resultado19 = resultado19 + ((a / z) + (d * d) + (z + x));
		resultado19 = resultado19 + ((a - a) + (a + d) + (z / c) + (x * y) + (x / y));
		resultado19 = resultado19 + ((d / x) + (a + a) + (y + a));
		String resultado20 = "";
		resultado20 = resultado20 + ((c / c) + (e + c) + (b / e) + (b - x) + (x * x));
		resultado20 = resultado20 + ((d - z) + (y * e) + (y - a) + (a / y));
		resultado20 = resultado20 + ((c + z) + (d + z) + (e * z) + (x * e) + (a / b));
		resultado20 = resultado20 + ((a / z) + (a / z) + (c / z) + (z * b) + (y - d));
		resultado20 = resultado20 + ((b + a) + (x + e) + (z + c) + (a * a));
		String resultado21 = "";
		resultado21 = resultado21 + ((x / x) + (e - c) + (d - c) + (a / e));
		resultado21 = resultado21 + ((z * c) + (b + x) + (d * d));
		resultado21 = resultado21 + ((y * y) + (z - a) + (c - a));
		resultado21 = resultado21 + ((y / e) + (a / b) + (z * z));
		String resultado22 = "";
		resultado22 = resultado22 + ((b + y) + (e / b) + (a * c) + (x / d) + (e / x));
		resultado22 = resultado22 + ((a - d) + (y * c) + (e * x) + (b / z));
		resultado22 = resultado22 + ((d / b) + (y / a) + (d - d) + (b * d) + (x + c));
		resultado22 = resultado22 + ((e / e) + (c + z) + (d + b) + (d / d));
		String resultado23 = "";
		resultado23 = resultado23 + ((b - y) + (a + d) + (c + d) + (y * d));
		resultado23 = resultado23 + ((a * b) + (e + c) + (e * a) + (b / x));
		resultado23 = resultado23 + ((d - x) + (e / e) + (y + z) + (a / b));
		String resultado24 = "";
		resultado24 = resultado24 + ((z * c) + (y + a) + (y * e) + (z - z) + (y * d));
		resultado24 = resultado24 + ((z + x) + (y * x) + (a + y));
		resultado24 = resultado24 + ((x + a) + (y + b) + (a - z) + (d + b) + (a + z));
		String resultado25 = "";
		resultado25 = resultado25 + ((x * z) + (d - a) + (b - e) + (z / e) + (c / x));
		resultado25 = resultado25 + ((a + y) + (y / x) + (e * e));
		resultado25 = resultado25 + ((y * z) + (e * b) + (y * c));
		String resultado26 = "";
		resultado26 = resultado26 + ((z - b) + (a + x) + (d + x) + (z / e));
		resultado26 = resultado26 + ((y / d) + (c - z) + (a * y) + (x * y));
		resultado26 = resultado26 + ((c * y) + (z + y) + (d + b) + (a - y));
		resultado26 = resultado26 + ((c / y) + (c / b) + (b * d));
		resultado26 = resultado26 + ((z / x) + (b * x) + (b * c));
		String resultado27 = "";
		resultado27 = resultado27 + ((y * a) + (e - y) + (d - c) + (z - b) + (d / e));
		resultado27 = resultado27 + ((x + x) + (d / z) + (y + x));
		resultado27 = resultado27 + ((z * z) + (a + y) + (d + a) + (c * y));
		resultado27 = resultado27 + ((x - b) + (b - b) + (b * z) + (y - c) + (z + e));
		String resultado28 = "";
		resultado28 = resultado28 + ((y * y) + (c * b) + (c + x));
		resultado28 = resultado28 + ((y * x) + (c - y) + (z / y));
		resultado28 = resultado28 + ((z * x) + (d * e) + (x / a) + (c * d));
		resultado28 = resultado28 + ((y / c) + (a - z) + (x - y));
		resultado28 = resultado28 + ((a + d) + (z / y) + (x - d) + (y * d) + (e - x));
		String resultado29 = "";
		resultado29 = resultado29 + ((e * y) + (x / x) + (y / c));
		resultado29 = resultado29 + ((x * a) + (d - c) + (d / d) + (d / z) + (a + d));
		resultado29 = resultado29 + ((c - z) + (x + e) + (a / x) + (z + e));
		resultado29 = resultado29 + ((y + d) + (a / b) + (e + z));
		String resultado30 = "";
		resultado30 = resultado30 + ((a + b) + (z / c) + (z + c));
		resultado30 = resultado30 + ((a * d) + (z / b) + (y * a) + (b - b));
		resultado30 = resultado30 + ((a - z) + (z + c) + (d / b) + (b - y) + (d + y));
		resultado30 = resultado30 + ((d * b) + (x * b) + (z + c) + (c * b) + (e + c));
		resultado30 = resultado30 + ((d / x) + (d * d) + (x + e) + (c * b) + (y - e));
		String resultado31 = "";
		resultado31 = resultado31 + ((e / e) + (b * x) + (e - b) + (x * e) + (z + a));
		resultado31 = resultado31 + ((x * y) + (a / d) + (d + a) + (e - b) + (y * b));
		resultado31 = resultado31 + ((e / a) + (a - z) + (b / a) + (c + c) + (y * a));
		resultado31 = resultado31 + ((y + b) + (e * x) + (a + a) + (b * a));
		resultado31 = resultado31 + ((a / e) + (d + y) + (d * d) + (e * d));
		String resultado32 = "";
		resultado32 = resultado32 + ((a - e) + (x + d) + (c - z));
		resultado32 = resultado32 + ((a - c) + (d / x) + (x * a) + (y / b) + (e / e));
		resultado32 = resultado32 + ((x / d) + (b - b) + (a + e));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}