package br.com.av1.prova03;

public class Questao4 {
	public static void main(String[] args) {
		int a = 9;
		int b = 1;
		int c = 4;
		int d = 1;
		int e = 3;
		int x = 10;
		int y = 2;
		int z = 2;

		String resultado1 = "";
		resultado1 = resultado1 + ((b * y) + (d + c) + (e - z) + (z * d));
		resultado1 = resultado1 + ((e - d) + (a - a) + (c * b) + (e * c) + (e * c));
		resultado1 = resultado1 + ((d - b) + (x + z) + (d + b));
		resultado1 = resultado1 + ((e * y) + (e - z) + (c + c) + (d - c));
		resultado1 = resultado1 + ((b + x) + (z + c) + (e * c) + (z - x));
		String resultado2 = "";
		resultado2 = resultado2 + ((c / x) + (b / a) + (e + a) + (z + d) + (e - b));
		resultado2 = resultado2 + ((e + e) + (b / z) + (y + d) + (b * b) + (y - a));
		resultado2 = resultado2 + ((e * b) + (d + z) + (b / b) + (d * e) + (z * z));
		resultado2 = resultado2 + ((e / z) + (a * y) + (e * e));
		String resultado3 = "";
		resultado3 = resultado3 + ((c / x) + (b + d) + (d - y) + (a / a) + (z + z));
		resultado3 = resultado3 + ((b - y) + (c * d) + (a * y) + (b - e));
		resultado3 = resultado3 + ((x - e) + (a + d) + (z * z) + (z - e) + (x * b));
		resultado3 = resultado3 + ((d * d) + (x - y) + (c / e) + (z - x));
		resultado3 = resultado3 + ((a + c) + (x - y) + (d * x));
		String resultado4 = "";
		resultado4 = resultado4 + ((y - x) + (e + y) + (z - e) + (c * d) + (x + d));
		resultado4 = resultado4 + ((z + z) + (b * d) + (z - e));
		resultado4 = resultado4 + ((d * z) + (x + z) + (z + y) + (a + y));
		resultado4 = resultado4 + ((e * z) + (b + x) + (c / b));
		resultado4 = resultado4 + ((x - c) + (d / a) + (b * z));
		String resultado5 = "";
		resultado5 = resultado5 + ((c * c) + (d - e) + (z - b));
		resultado5 = resultado5 + ((y / z) + (z + x) + (x * e) + (b + x) + (y * c));
		resultado5 = resultado5 + ((e / b) + (a * y) + (y * a));
		resultado5 = resultado5 + ((e - a) + (b / y) + (x * c) + (a + e) + (z - d));
		String resultado6 = "";
		resultado6 = resultado6 + ((y - y) + (x / b) + (d / x));
		resultado6 = resultado6 + ((x - z) + (x - c) + (c * y) + (c * a) + (a / z));
		resultado6 = resultado6 + ((z / b) + (d - z) + (d + x));
		resultado6 = resultado6 + ((y - a) + (a + y) + (y + b) + (d / y) + (a * d));
		resultado6 = resultado6 + ((a + x) + (y / e) + (z / y) + (a + y) + (c * d));
		String resultado7 = "";
		resultado7 = resultado7 + ((y * d) + (y + y) + (x + e) + (x + d));
		resultado7 = resultado7 + ((e * a) + (y / c) + (a * c));
		resultado7 = resultado7 + ((a * x) + (z * a) + (e - x));
		resultado7 = resultado7 + ((x + c) + (y - z) + (a / a) + (c * c) + (a * y));
		String resultado8 = "";
		resultado8 = resultado8 + ((a - b) + (z / b) + (b / d) + (a - y));
		resultado8 = resultado8 + ((d - c) + (d / a) + (z - e) + (y * c) + (c / x));
		resultado8 = resultado8 + ((a * e) + (c - e) + (b * d) + (x - c) + (z / e));
		String resultado9 = "";
		resultado9 = resultado9 + ((d / c) + (d * a) + (z - d));
		resultado9 = resultado9 + ((e * b) + (z * z) + (z + d) + (e + d));
		resultado9 = resultado9 + ((d / c) + (y - c) + (e / c) + (y + e) + (z * x));
		resultado9 = resultado9 + ((a / a) + (y * z) + (d * d) + (y * e));
		resultado9 = resultado9 + ((x + a) + (a - a) + (z * b));
		String resultado10 = "";
		resultado10 = resultado10 + ((a - e) + (y * a) + (c / z));
		resultado10 = resultado10 + ((a / b) + (z * a) + (e / a) + (e / a) + (b / y));
		resultado10 = resultado10 + ((a + y) + (d + a) + (d / z) + (d / y));
		resultado10 = resultado10 + ((z + e) + (d + y) + (b - y) + (c + c));
		String resultado11 = "";
		resultado11 = resultado11 + ((y * y) + (d * z) + (z / b) + (y / x));
		resultado11 = resultado11 + ((x / b) + (c * y) + (b * x) + (e + x));
		resultado11 = resultado11 + ((e - b) + (z - d) + (z + x) + (b - y) + (y * y));
		resultado11 = resultado11 + ((b + a) + (d - z) + (b + e));
		String resultado12 = "";
		resultado12 = resultado12 + ((a * c) + (z - d) + (e * e));
		resultado12 = resultado12 + ((x / x) + (z - e) + (y / y) + (z * y) + (a / x));
		resultado12 = resultado12 + ((d / z) + (d * e) + (e + a));
		resultado12 = resultado12 + ((c - z) + (x * a) + (b - e));
		resultado12 = resultado12 + ((a + d) + (d - x) + (e + x));
		String resultado13 = "";
		resultado13 = resultado13 + ((a / c) + (c - z) + (z * c));
		resultado13 = resultado13 + ((z * z) + (x + c) + (a * e));
		resultado13 = resultado13 + ((x - a) + (a + a) + (c + z) + (x - x) + (x * a));
		resultado13 = resultado13 + ((c * d) + (z - z) + (a - d) + (c * d));
		String resultado14 = "";
		resultado14 = resultado14 + ((a * e) + (d * z) + (x * x) + (a + z) + (e + y));
		resultado14 = resultado14 + ((a / c) + (d * d) + (d * x) + (y / a) + (z - a));
		resultado14 = resultado14 + ((c / c) + (c * z) + (a - c) + (b + x) + (x + c));
		resultado14 = resultado14 + ((x / y) + (c / z) + (x - y));
		resultado14 = resultado14 + ((c / e) + (c - x) + (x - e) + (z - x) + (b + x));
		String resultado15 = "";
		resultado15 = resultado15 + ((c / d) + (y + b) + (b - b));
		resultado15 = resultado15 + ((d * b) + (d * a) + (z * c));
		resultado15 = resultado15 + ((y * d) + (b + b) + (d - e) + (z - e) + (c / x));
		resultado15 = resultado15 + ((e - y) + (z * z) + (x * a) + (y - e));
		resultado15 = resultado15 + ((z - z) + (a * d) + (z + e) + (y - z) + (c - a));
		String resultado16 = "";
		resultado16 = resultado16 + ((y + x) + (b - e) + (z / a) + (b * x));
		resultado16 = resultado16 + ((a * d) + (x - d) + (x - y) + (z * e) + (c * c));
		resultado16 = resultado16 + ((a + z) + (y * z) + (c * c));
		resultado16 = resultado16 + ((c + b) + (c / a) + (e * a) + (e + x) + (c * z));
		String resultado17 = "";
		resultado17 = resultado17 + ((b - z) + (b * c) + (x - b) + (x - x));
		resultado17 = resultado17 + ((z + c) + (e - x) + (x / y) + (a * y));
		resultado17 = resultado17 + ((e / x) + (z + y) + (c * x) + (e * z));
		resultado17 = resultado17 + ((z / c) + (e - d) + (z / e));
		resultado17 = resultado17 + ((a / e) + (d * d) + (b * e));
		String resultado18 = "";
		resultado18 = resultado18 + ((b - b) + (b + c) + (y * e) + (e + x) + (x * z));
		resultado18 = resultado18 + ((z + z) + (y / x) + (d - e) + (a * a) + (c - a));
		resultado18 = resultado18 + ((y / e) + (d * y) + (z / y));
		resultado18 = resultado18 + ((d / d) + (x / e) + (z / y) + (a / a) + (d + a));
		resultado18 = resultado18 + ((d * e) + (d * d) + (z * x) + (c + x) + (a - b));
		String resultado19 = "";
		resultado19 = resultado19 + ((y * b) + (z + y) + (c * a) + (x / y) + (z * y));
		resultado19 = resultado19 + ((b - a) + (c - a) + (z + a) + (x / e) + (e / b));
		resultado19 = resultado19 + ((a + d) + (b / d) + (d * y));
		resultado19 = resultado19 + ((c - d) + (x / y) + (e + e));
		resultado19 = resultado19 + ((a + d) + (e + d) + (e * a));
		String resultado20 = "";
		resultado20 = resultado20 + ((x / a) + (x / z) + (b / e) + (x * d) + (e / z));
		resultado20 = resultado20 + ((c - y) + (y + x) + (d * e));
		resultado20 = resultado20 + ((c / c) + (x / z) + (e * y) + (z - z) + (a + z));
		resultado20 = resultado20 + ((e - c) + (e - y) + (c * c) + (b + e));
		resultado20 = resultado20 + ((y * d) + (y + d) + (y + b));
		String resultado21 = "";
		resultado21 = resultado21 + ((d - c) + (d * d) + (e - x) + (e * c) + (d - c));
		resultado21 = resultado21 + ((a * b) + (a * z) + (x + b) + (c - b) + (y / b));
		resultado21 = resultado21 + ((e + y) + (b / c) + (b / a) + (c / b));
		resultado21 = resultado21 + ((x * e) + (e * y) + (a + x));
		String resultado22 = "";
		resultado22 = resultado22 + ((y + a) + (x - x) + (x - e) + (d * x));
		resultado22 = resultado22 + ((a + d) + (x * y) + (e + e) + (c + y) + (y - y));
		resultado22 = resultado22 + ((y - c) + (z - d) + (d + d));
		resultado22 = resultado22 + ((c / x) + (y / d) + (z * z) + (y / x));
		resultado22 = resultado22 + ((y - z) + (z / x) + (c / y) + (c / e) + (y / a));
		String resultado23 = "";
		resultado23 = resultado23 + ((x - a) + (d / a) + (d / z) + (z + d));
		resultado23 = resultado23 + ((x / y) + (x + a) + (a + a));
		resultado23 = resultado23 + ((d / y) + (e * c) + (e + b));
		String resultado24 = "";
		resultado24 = resultado24 + ((z / z) + (y / y) + (d - b) + (x * b));
		resultado24 = resultado24 + ((z * y) + (d / y) + (b * d) + (a + b) + (b * y));
		resultado24 = resultado24 + ((b - c) + (e * c) + (z * z) + (e + c) + (c - a));
		resultado24 = resultado24 + ((d - x) + (e / c) + (a / d));
		String resultado25 = "";
		resultado25 = resultado25 + ((y / z) + (c * a) + (z - b) + (x - b));
		resultado25 = resultado25 + ((x + y) + (c - b) + (b - x));
		resultado25 = resultado25 + ((e * x) + (d * c) + (a * e) + (d - z));
		resultado25 = resultado25 + ((e + e) + (e - z) + (b - b) + (x / b) + (e - b));
		resultado25 = resultado25 + ((y / e) + (e - b) + (x / b) + (d + d) + (e - e));
		String resultado26 = "";
		resultado26 = resultado26 + ((c * d) + (d / b) + (d * z) + (d / y));
		resultado26 = resultado26 + ((d + x) + (y + c) + (b + y));
		resultado26 = resultado26 + ((d + z) + (d + y) + (y - x) + (x * z));
		resultado26 = resultado26 + ((c - x) + (e + e) + (b - y) + (x + c));
		String resultado27 = "";
		resultado27 = resultado27 + ((e + z) + (x * a) + (y + x) + (x / d) + (c - c));
		resultado27 = resultado27 + ((b - d) + (y / x) + (x * c) + (c / a));
		resultado27 = resultado27 + ((b - e) + (y / d) + (e / c) + (x / a) + (x / z));
		resultado27 = resultado27 + ((c + d) + (a + b) + (z - a));
		resultado27 = resultado27 + ((e + z) + (d + a) + (y * y) + (z + c) + (y / a));
		String resultado28 = "";
		resultado28 = resultado28 + ((y + y) + (c - y) + (b / a) + (e + d));
		resultado28 = resultado28 + ((z / e) + (x + e) + (e * a));
		resultado28 = resultado28 + ((c - b) + (x / y) + (e / a));
		String resultado29 = "";
		resultado29 = resultado29 + ((d / d) + (d * y) + (c - a) + (e / x) + (e - c));
		resultado29 = resultado29 + ((e * e) + (a / e) + (c + x) + (d - y) + (x + a));
		resultado29 = resultado29 + ((e / c) + (z * d) + (b + x) + (z + b));
		resultado29 = resultado29 + ((c + a) + (d / y) + (z / z) + (x / a));
		String resultado30 = "";
		resultado30 = resultado30 + ((x - c) + (e * z) + (d * b));
		resultado30 = resultado30 + ((y + z) + (a * c) + (e / b) + (a + x));
		resultado30 = resultado30 + ((e / y) + (a - x) + (e / b) + (c - a) + (c / y));
		String resultado31 = "";
		resultado31 = resultado31 + ((y / b) + (e - y) + (c + a) + (d + d) + (b * c));
		resultado31 = resultado31 + ((d / x) + (b + y) + (b - b));
		resultado31 = resultado31 + ((y / c) + (a + z) + (e / c));
		String resultado32 = "";
		resultado32 = resultado32 + ((d + d) + (e + b) + (b * z) + (a - x));
		resultado32 = resultado32 + ((x / e) + (y * a) + (x / b) + (c / d) + (d * a));
		resultado32 = resultado32 + ((z / z) + (y - z) + (e - d) + (d + d));
		resultado32 = resultado32 + ((c / z) + (e - a) + (b * e) + (e * e) + (e / z));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}