package br.com.av1.prova04;

public class Questao4 {
	public static void main(String[] args) {
		int a = 10;
		int b = 3;
		int c = 9;
		int d = 6;
		int e = 8;
		int x = 9;
		int y = 2;
		int z = 6;

		String resultado1 = "";
		resultado1 = resultado1 + ((c + x) + (x / b) + (c * c));
		resultado1 = resultado1 + ((d + b) + (c * y) + (b - a));
		resultado1 = resultado1 + ((d - c) + (e - b) + (e / a));
		String resultado2 = "";
		resultado2 = resultado2 + ((c / c) + (x - e) + (c * y));
		resultado2 = resultado2 + ((x + y) + (e - y) + (y * c));
		resultado2 = resultado2 + ((c * z) + (a + z) + (c + d));
		String resultado3 = "";
		resultado3 = resultado3 + ((a - d) + (a - d) + (e - c));
		resultado3 = resultado3 + ((e / y) + (e + c) + (e / z));
		resultado3 = resultado3 + ((e * x) + (a + y) + (d + e));
		String resultado4 = "";
		resultado4 = resultado4 + ((a + x) + (b * a) + (c / d) + (z * z));
		resultado4 = resultado4 + ((a * y) + (a + c) + (a - y));
		resultado4 = resultado4 + ((d - c) + (d + e) + (z * d));
		String resultado5 = "";
		resultado5 = resultado5 + ((x / e) + (y + c) + (d - d));
		resultado5 = resultado5 + ((x / e) + (a / b) + (y - b) + (c - z));
		resultado5 = resultado5 + ((z * a) + (b + b) + (x * c));
		String resultado6 = "";
		resultado6 = resultado6 + ((z - e) + (x / c) + (e / z));
		resultado6 = resultado6 + ((a + z) + (z + e) + (a / x));
		resultado6 = resultado6 + ((e * x) + (d / d) + (y - z) + (d + x));
		resultado6 = resultado6 + ((e - x) + (c + b) + (e / c) + (z + y));
		String resultado7 = "";
		resultado7 = resultado7 + ((z / d) + (z * c) + (y + b) + (e / d) + (c * x));
		resultado7 = resultado7 + ((c + d) + (e / e) + (e - b) + (z * e) + (a * c));
		resultado7 = resultado7 + ((z / y) + (y + a) + (b + b) + (b * d));
		resultado7 = resultado7 + ((z + d) + (c / a) + (b / c));
		String resultado8 = "";
		resultado8 = resultado8 + ((a * e) + (b / e) + (x + z) + (d + z) + (d * x));
		resultado8 = resultado8 + ((x + c) + (d / z) + (e - c) + (b * c) + (x + a));
		resultado8 = resultado8 + ((c / d) + (c * b) + (z - x));
		String resultado9 = "";
		resultado9 = resultado9 + ((b / x) + (d + x) + (c - d) + (a * e) + (b / y));
		resultado9 = resultado9 + ((b + b) + (x - e) + (d + c) + (e / d));
		resultado9 = resultado9 + ((e - b) + (d * y) + (e + y));
		String resultado10 = "";
		resultado10 = resultado10 + ((z / b) + (b + e) + (d + d) + (a * c));
		resultado10 = resultado10 + ((z + d) + (x + x) + (d - e) + (b / x) + (d * y));
		resultado10 = resultado10 + ((z * c) + (z * e) + (x - z) + (c + y));
		resultado10 = resultado10 + ((d * x) + (b * a) + (z / y) + (b / y) + (c - b));
		resultado10 = resultado10 + ((d - b) + (c / b) + (a / e));
		String resultado11 = "";
		resultado11 = resultado11 + ((z * y) + (a + y) + (b / y) + (a + x) + (y / b));
		resultado11 = resultado11 + ((a - e) + (d - c) + (z + c) + (y * e) + (x - x));
		resultado11 = resultado11 + ((c - c) + (x + c) + (c / b) + (c * y));
		resultado11 = resultado11 + ((y - d) + (e / a) + (b / c) + (e * e));
		resultado11 = resultado11 + ((a / y) + (a - y) + (x + x) + (c + x) + (c + c));
		String resultado12 = "";
		resultado12 = resultado12 + ((d / a) + (z - d) + (y - z) + (x * e) + (x - b));
		resultado12 = resultado12 + ((c / c) + (x - c) + (d + c) + (c - z) + (c / b));
		resultado12 = resultado12 + ((e - b) + (x * e) + (c * x) + (z - z) + (c + a));
		resultado12 = resultado12 + ((d * a) + (d - d) + (e + x));
		resultado12 = resultado12 + ((e - y) + (z * d) + (a / b) + (y + b) + (a * x));
		String resultado13 = "";
		resultado13 = resultado13 + ((z / d) + (y / a) + (z - d) + (d - x));
		resultado13 = resultado13 + ((b + d) + (e - c) + (z + y) + (b * e) + (b + x));
		resultado13 = resultado13 + ((y / c) + (a * c) + (y * y) + (e * c) + (z / e));
		String resultado14 = "";
		resultado14 = resultado14 + ((x - d) + (e - e) + (c * e) + (x / e));
		resultado14 = resultado14 + ((d * a) + (e + b) + (x / b));
		resultado14 = resultado14 + ((d - e) + (e + x) + (y * z));
		resultado14 = resultado14 + ((c + d) + (e + x) + (d * b) + (b * d) + (c + a));
		String resultado15 = "";
		resultado15 = resultado15 + ((e / c) + (c / y) + (e - a));
		resultado15 = resultado15 + ((e - y) + (y + b) + (y - c) + (z / e) + (e - a));
		resultado15 = resultado15 + ((x + b) + (x - c) + (a / a) + (z + x));
		String resultado16 = "";
		resultado16 = resultado16 + ((z / d) + (d - a) + (y * a));
		resultado16 = resultado16 + ((z * a) + (b * a) + (x + y));
		resultado16 = resultado16 + ((z * z) + (x / e) + (x - x));
		String resultado17 = "";
		resultado17 = resultado17 + ((b / e) + (e * d) + (c / z) + (a * c));
		resultado17 = resultado17 + ((e / b) + (e / y) + (a * b) + (d * y));
		resultado17 = resultado17 + ((c - x) + (x + c) + (a - b) + (d + d));
		String resultado18 = "";
		resultado18 = resultado18 + ((x - x) + (a * c) + (e / b) + (y / a) + (b + z));
		resultado18 = resultado18 + ((a + c) + (b / x) + (b + b) + (b - a) + (a + z));
		resultado18 = resultado18 + ((c - e) + (d / d) + (z + b) + (d / x));
		String resultado19 = "";
		resultado19 = resultado19 + ((c - y) + (y + z) + (y - e) + (e + c) + (x * b));
		resultado19 = resultado19 + ((a * a) + (x / a) + (e / z) + (z / x));
		resultado19 = resultado19 + ((x / c) + (a / b) + (d / y) + (b * x) + (z / z));
		String resultado20 = "";
		resultado20 = resultado20 + ((b / d) + (x * z) + (e - d));
		resultado20 = resultado20 + ((e * x) + (d * z) + (z + c));
		resultado20 = resultado20 + ((z / e) + (c - x) + (x / d) + (z / y));
		String resultado21 = "";
		resultado21 = resultado21 + ((d * b) + (x / c) + (z * c));
		resultado21 = resultado21 + ((c - z) + (d - y) + (e / x));
		resultado21 = resultado21 + ((a * c) + (e - d) + (d * e) + (c / b) + (x - x));
		String resultado22 = "";
		resultado22 = resultado22 + ((z - z) + (z * x) + (z * b) + (d + b) + (d + y));
		resultado22 = resultado22 + ((b + b) + (y * b) + (e - c) + (y + c) + (b - e));
		resultado22 = resultado22 + ((e / x) + (b / z) + (a - c) + (x - b) + (c * y));
		resultado22 = resultado22 + ((y * e) + (z - a) + (x * d) + (a / d));
		resultado22 = resultado22 + ((y * d) + (y / a) + (y - b) + (c - y));
		String resultado23 = "";
		resultado23 = resultado23 + ((d / z) + (c / z) + (z * x));
		resultado23 = resultado23 + ((x - x) + (b * y) + (y / c) + (z / d) + (a * x));
		resultado23 = resultado23 + ((z * y) + (b / a) + (b * b) + (c * y) + (a + z));
		String resultado24 = "";
		resultado24 = resultado24 + ((b / x) + (a + z) + (x - y) + (x / y) + (z / x));
		resultado24 = resultado24 + ((b - z) + (y + x) + (d - e) + (b + x) + (e - y));
		resultado24 = resultado24 + ((e + b) + (a - b) + (b * e));
		resultado24 = resultado24 + ((x + c) + (b - y) + (x / d) + (z * x) + (e + b));
		String resultado25 = "";
		resultado25 = resultado25 + ((x - x) + (y + e) + (d - e) + (x * e) + (y - e));
		resultado25 = resultado25 + ((x - b) + (x - c) + (d * y) + (a - c));
		resultado25 = resultado25 + ((x + b) + (e + y) + (b / x) + (b * e));
		String resultado26 = "";
		resultado26 = resultado26 + ((b * e) + (c - b) + (z / b));
		resultado26 = resultado26 + ((b / e) + (a + x) + (z + z));
		resultado26 = resultado26 + ((y - x) + (y - e) + (x * y) + (c * e) + (y - e));
		resultado26 = resultado26 + ((e * y) + (b + c) + (b / z) + (d / a));
		String resultado27 = "";
		resultado27 = resultado27 + ((x - x) + (b - b) + (z * x) + (a + x));
		resultado27 = resultado27 + ((a * x) + (c * y) + (x / c));
		resultado27 = resultado27 + ((e + z) + (e - x) + (z - z));
		resultado27 = resultado27 + ((e - c) + (b / b) + (x - c));
		String resultado28 = "";
		resultado28 = resultado28 + ((d + e) + (e * d) + (d * e));
		resultado28 = resultado28 + ((d / y) + (a / c) + (z - a));
		resultado28 = resultado28 + ((z / c) + (d - d) + (b + b) + (z + b) + (z - b));
		resultado28 = resultado28 + ((b + b) + (z * x) + (c * e) + (x - a) + (c * c));
		String resultado29 = "";
		resultado29 = resultado29 + ((y * d) + (x / c) + (a + z) + (x + y));
		resultado29 = resultado29 + ((z - a) + (c * e) + (b / z) + (e + y));
		resultado29 = resultado29 + ((a / b) + (y / a) + (c / a) + (d + z));
		resultado29 = resultado29 + ((c / z) + (b - b) + (x * e) + (z - x));
		resultado29 = resultado29 + ((x * y) + (z + x) + (z / y) + (e - c) + (e + d));
		String resultado30 = "";
		resultado30 = resultado30 + ((a * a) + (b / c) + (b * z) + (a * y));
		resultado30 = resultado30 + ((x / a) + (c + e) + (x * x) + (a / b) + (d + c));
		resultado30 = resultado30 + ((b + z) + (y + d) + (e * e));
		String resultado31 = "";
		resultado31 = resultado31 + ((c - y) + (x * b) + (z + e) + (e + x) + (b * z));
		resultado31 = resultado31 + ((z - y) + (a * e) + (b / z));
		resultado31 = resultado31 + ((e / z) + (x / a) + (b + b) + (z * e));
		resultado31 = resultado31 + ((d * x) + (y - a) + (x + d) + (y + x) + (x / c));
		resultado31 = resultado31 + ((b + x) + (d - a) + (d * x) + (d * a));
		String resultado32 = "";
		resultado32 = resultado32 + ((x * c) + (y / z) + (a * c));
		resultado32 = resultado32 + ((d - e) + (y * c) + (y + z) + (e / d) + (b - d));
		resultado32 = resultado32 + ((a * e) + (c / e) + (b / y) + (d + b) + (z / b));
		resultado32 = resultado32 + ((b - b) + (z / x) + (e * b) + (c - e));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}