package br.com.av1.prova30;

public class Questao4 {
	public static void main(String[] args) {
		int a = 9;
		int b = 9;
		int c = 10;
		int d = 9;
		int e = 4;
		int x = 3;
		int y = 6;
		int z = 2;

		String resultado1 = "";
		resultado1 = resultado1 + ((a / y) + (e / y) + (c * y) + (a - a));
		resultado1 = resultado1 + ((y - c) + (e - z) + (c + d));
		resultado1 = resultado1 + ((e + y) + (a / y) + (x + x));
		resultado1 = resultado1 + ((c / e) + (x / b) + (e / x) + (e / x));
		resultado1 = resultado1 + ((a * z) + (b * a) + (e + c) + (a + y) + (a - x));
		String resultado2 = "";
		resultado2 = resultado2 + ((a - a) + (b - d) + (z / b) + (z + a) + (b * z));
		resultado2 = resultado2 + ((y / z) + (z * e) + (a + c) + (c / c) + (y + c));
		resultado2 = resultado2 + ((a * y) + (e + e) + (y / z));
		String resultado3 = "";
		resultado3 = resultado3 + ((b - d) + (x - e) + (e - c) + (y + y));
		resultado3 = resultado3 + ((c + a) + (a + d) + (y - e) + (z - b) + (x + d));
		resultado3 = resultado3 + ((z + z) + (y * c) + (a - b) + (y + z));
		String resultado4 = "";
		resultado4 = resultado4 + ((d + d) + (b - d) + (b / b) + (a - y));
		resultado4 = resultado4 + ((z / c) + (y / x) + (d / a) + (z + z));
		resultado4 = resultado4 + ((c * e) + (c / d) + (a - z));
		resultado4 = resultado4 + ((y - e) + (e * x) + (x / c) + (c - d));
		String resultado5 = "";
		resultado5 = resultado5 + ((z * b) + (d + z) + (x * c) + (c * c));
		resultado5 = resultado5 + ((x - d) + (e + x) + (c + d) + (c + y));
		resultado5 = resultado5 + ((e / e) + (e - c) + (y + c) + (d - e) + (b / c));
		resultado5 = resultado5 + ((z + x) + (e / d) + (z * y) + (e + b));
		resultado5 = resultado5 + ((b - c) + (z + c) + (x + d));
		String resultado6 = "";
		resultado6 = resultado6 + ((c + x) + (z * x) + (b + y));
		resultado6 = resultado6 + ((z - z) + (a - e) + (a * d) + (c * z));
		resultado6 = resultado6 + ((a + y) + (a / x) + (e * a) + (y + b));
		String resultado7 = "";
		resultado7 = resultado7 + ((d * a) + (c / y) + (c * d));
		resultado7 = resultado7 + ((z + z) + (y / e) + (a - c) + (c / z));
		resultado7 = resultado7 + ((d * y) + (y - a) + (a * z) + (y - x));
		resultado7 = resultado7 + ((a * c) + (d * e) + (d + b) + (e - c) + (d / c));
		String resultado8 = "";
		resultado8 = resultado8 + ((a * x) + (e / b) + (z + z) + (c + z));
		resultado8 = resultado8 + ((e / b) + (y * a) + (d + c));
		resultado8 = resultado8 + ((z * z) + (d - z) + (d / a) + (d - e) + (d / e));
		String resultado9 = "";
		resultado9 = resultado9 + ((d + z) + (z - e) + (a / x) + (c + a));
		resultado9 = resultado9 + ((y - b) + (y + c) + (x + b) + (a + d) + (y / b));
		resultado9 = resultado9 + ((b - z) + (x - c) + (x / d));
		String resultado10 = "";
		resultado10 = resultado10 + ((c * e) + (a * e) + (y - z) + (d / d));
		resultado10 = resultado10 + ((x + d) + (y - a) + (c / z) + (b - a) + (e + z));
		resultado10 = resultado10 + ((z + c) + (d * a) + (d - c) + (a * e));
		resultado10 = resultado10 + ((b - c) + (y - c) + (b / a) + (b + b) + (x + x));
		String resultado11 = "";
		resultado11 = resultado11 + ((y / a) + (z * x) + (z / y) + (y - c));
		resultado11 = resultado11 + ((e + c) + (a / c) + (b - c));
		resultado11 = resultado11 + ((b + e) + (z + e) + (d * d) + (e + e) + (e - c));
		String resultado12 = "";
		resultado12 = resultado12 + ((z / a) + (e - e) + (d + e) + (d - b) + (a - b));
		resultado12 = resultado12 + ((c / c) + (b - e) + (x - z));
		resultado12 = resultado12 + ((z + e) + (b * b) + (z / d) + (y * d) + (a * z));
		String resultado13 = "";
		resultado13 = resultado13 + ((b / d) + (b - a) + (y - b) + (c / d) + (a - e));
		resultado13 = resultado13 + ((z - x) + (b / e) + (x - y) + (b * x));
		resultado13 = resultado13 + ((b + a) + (x - b) + (y + b) + (x + b));
		resultado13 = resultado13 + ((c - y) + (y / c) + (d * y) + (b + x));
		resultado13 = resultado13 + ((a - x) + (b * b) + (y - z));
		String resultado14 = "";
		resultado14 = resultado14 + ((d + c) + (e - y) + (z + d));
		resultado14 = resultado14 + ((y * d) + (b - z) + (x + e));
		resultado14 = resultado14 + ((c + x) + (e / b) + (c / c) + (c / z));
		String resultado15 = "";
		resultado15 = resultado15 + ((d * b) + (x / a) + (c + d) + (z / d) + (a - d));
		resultado15 = resultado15 + ((y + z) + (a / a) + (z * y) + (x * e));
		resultado15 = resultado15 + ((a - z) + (e - b) + (d + a) + (c / y));
		String resultado16 = "";
		resultado16 = resultado16 + ((e / z) + (d - b) + (b * a) + (d / c) + (b - y));
		resultado16 = resultado16 + ((e + e) + (b * a) + (d + y));
		resultado16 = resultado16 + ((d * a) + (y / z) + (e * x) + (c - e) + (e / d));
		resultado16 = resultado16 + ((e + z) + (y * c) + (d - c) + (z * x));
		resultado16 = resultado16 + ((z + z) + (x + d) + (y - b) + (x - e) + (y / x));
		String resultado17 = "";
		resultado17 = resultado17 + ((a / c) + (d - z) + (b / a));
		resultado17 = resultado17 + ((e + c) + (z / a) + (d / b) + (a / a));
		resultado17 = resultado17 + ((c - x) + (a / y) + (x + x) + (y + y) + (b - e));
		resultado17 = resultado17 + ((y / z) + (d - a) + (c * z) + (d + y));
		String resultado18 = "";
		resultado18 = resultado18 + ((x / b) + (c * b) + (a / z) + (c - x));
		resultado18 = resultado18 + ((c * x) + (c + e) + (a / a) + (x / b) + (x - z));
		resultado18 = resultado18 + ((b * d) + (e / b) + (z + y));
		String resultado19 = "";
		resultado19 = resultado19 + ((b * a) + (y / c) + (b - z) + (x * z) + (a * y));
		resultado19 = resultado19 + ((x * e) + (b * c) + (e / b));
		resultado19 = resultado19 + ((z * x) + (y - b) + (d * y) + (a * d));
		resultado19 = resultado19 + ((y + a) + (y * x) + (e - e) + (d + e));
		String resultado20 = "";
		resultado20 = resultado20 + ((z / a) + (e + a) + (e - e));
		resultado20 = resultado20 + ((b * d) + (b - e) + (z - e) + (b + c) + (a + y));
		resultado20 = resultado20 + ((e / y) + (a + x) + (a * x) + (z - c));
		String resultado21 = "";
		resultado21 = resultado21 + ((y + d) + (b / a) + (c - y) + (c + e));
		resultado21 = resultado21 + ((x / x) + (c / e) + (e - y) + (c / z) + (x / c));
		resultado21 = resultado21 + ((a / d) + (b / b) + (y + d) + (d / d) + (a + d));
		resultado21 = resultado21 + ((c / b) + (x / y) + (e - x) + (b - y));
		String resultado22 = "";
		resultado22 = resultado22 + ((y / e) + (y + x) + (c + y) + (a / e));
		resultado22 = resultado22 + ((c * y) + (z + x) + (y / e) + (b / d));
		resultado22 = resultado22 + ((c + e) + (c / e) + (y * d) + (d - x));
		resultado22 = resultado22 + ((d / a) + (a * y) + (z + d) + (c * x));
		resultado22 = resultado22 + ((x - a) + (a + a) + (b / a) + (y * a));
		String resultado23 = "";
		resultado23 = resultado23 + ((e / a) + (a - b) + (x + x));
		resultado23 = resultado23 + ((a + e) + (d * x) + (d + c) + (y / e));
		resultado23 = resultado23 + ((x / e) + (y / a) + (z - z) + (e / c));
		resultado23 = resultado23 + ((z / d) + (z * y) + (e * z) + (x - d) + (e - d));
		resultado23 = resultado23 + ((d * y) + (y / b) + (y / a) + (x + a));
		String resultado24 = "";
		resultado24 = resultado24 + ((b * b) + (d * c) + (d * d) + (x / c));
		resultado24 = resultado24 + ((b / d) + (d - b) + (d * d));
		resultado24 = resultado24 + ((e - a) + (y - y) + (b + y));
		resultado24 = resultado24 + ((y * d) + (b - e) + (z + d) + (z * b) + (c / d));
		resultado24 = resultado24 + ((y + b) + (a - b) + (e - e) + (y + a));
		String resultado25 = "";
		resultado25 = resultado25 + ((y * x) + (x * z) + (x * e) + (b - c) + (y + b));
		resultado25 = resultado25 + ((a - a) + (a - c) + (e - e));
		resultado25 = resultado25 + ((c / a) + (y * c) + (y - d) + (z + y));
		String resultado26 = "";
		resultado26 = resultado26 + ((d + e) + (y + b) + (c - z));
		resultado26 = resultado26 + ((x - e) + (z + b) + (a - e));
		resultado26 = resultado26 + ((y + c) + (b * a) + (c - b) + (a / x) + (z - e));
		String resultado27 = "";
		resultado27 = resultado27 + ((y + c) + (z - b) + (y - c) + (x / d));
		resultado27 = resultado27 + ((c * a) + (z / d) + (x / x));
		resultado27 = resultado27 + ((x + d) + (x - c) + (z - d) + (a + a));
		resultado27 = resultado27 + ((b - e) + (b + e) + (y * d));
		resultado27 = resultado27 + ((b + y) + (y + x) + (b - z) + (b + b) + (x + a));
		String resultado28 = "";
		resultado28 = resultado28 + ((c + b) + (c * e) + (b / e));
		resultado28 = resultado28 + ((c * y) + (d + d) + (x / c));
		resultado28 = resultado28 + ((x / c) + (a - z) + (y + y) + (e - c));
		resultado28 = resultado28 + ((z * z) + (c - b) + (e + x) + (b * z) + (e * d));
		String resultado29 = "";
		resultado29 = resultado29 + ((y + z) + (b - c) + (b * a));
		resultado29 = resultado29 + ((b + d) + (c * e) + (e - y) + (e * b) + (a - b));
		resultado29 = resultado29 + ((x / c) + (z - e) + (d / y) + (y / e) + (c - b));
		String resultado30 = "";
		resultado30 = resultado30 + ((e * z) + (e + c) + (a - z) + (x / b) + (a / c));
		resultado30 = resultado30 + ((z - y) + (y + x) + (e + d) + (y * e));
		resultado30 = resultado30 + ((z + c) + (e - d) + (z + a) + (a * y));
		String resultado31 = "";
		resultado31 = resultado31 + ((a + d) + (x + b) + (c - x) + (x - y) + (x + x));
		resultado31 = resultado31 + ((e - x) + (c + b) + (x - a));
		resultado31 = resultado31 + ((z * x) + (x * d) + (d + c));
		resultado31 = resultado31 + ((b / b) + (a / y) + (y - c));
		resultado31 = resultado31 + ((c / e) + (y + d) + (x / x) + (e / b) + (a - b));
		String resultado32 = "";
		resultado32 = resultado32 + ((z + a) + (c / a) + (a * c));
		resultado32 = resultado32 + ((y - b) + (a + d) + (y * b) + (a * z));
		resultado32 = resultado32 + ((y / z) + (a + y) + (y - a) + (c / b) + (z * x));
		resultado32 = resultado32 + ((z * d) + (x * x) + (a * d) + (b / a) + (d - d));
		resultado32 = resultado32 + ((c / e) + (c * y) + (x / c) + (a / e) + (e / y));

		System.out.println("resultado1: " + resultado1);
		System.out.println("resultado2: " + resultado2);
		System.out.println("resultado3: " + resultado3);
		System.out.println("resultado4: " + resultado4);
		System.out.println("resultado5: " + resultado5);
		System.out.println("resultado6: " + resultado6);
		System.out.println("resultado7: " + resultado7);
		System.out.println("resultado8: " + resultado8);
		System.out.println("resultado9: " + resultado9);
		System.out.println("resultado10: " + resultado10);
		System.out.println("resultado11: " + resultado11);
		System.out.println("resultado12: " + resultado12);
		System.out.println("resultado13: " + resultado13);
		System.out.println("resultado14: " + resultado14);
		System.out.println("resultado15: " + resultado15);
		System.out.println("resultado16: " + resultado16);
		System.out.println("resultado17: " + resultado17);
		System.out.println("resultado18: " + resultado18);
		System.out.println("resultado19: " + resultado19);
		System.out.println("resultado20: " + resultado20);
		System.out.println("resultado21: " + resultado21);
		System.out.println("resultado22: " + resultado22);
		System.out.println("resultado23: " + resultado23);
		System.out.println("resultado24: " + resultado24);
		System.out.println("resultado25: " + resultado25);
		System.out.println("resultado26: " + resultado26);
		System.out.println("resultado27: " + resultado27);
		System.out.println("resultado28: " + resultado28);
		System.out.println("resultado29: " + resultado29);
		System.out.println("resultado30: " + resultado30);
		System.out.println("resultado31: " + resultado31);
		System.out.println("resultado32: " + resultado32);
	}
}